### ISSUE TITLE
Upgrade to BerkeleyDB JE 7.3.7

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#100]
[Oracle Berkeley DB Java Edition](https://docs.oracle.com/cd/E17277_02/html/), 12c Release 1
Library 12.1.7.3, Version 7.3.7, 2017-02-01 03:44:57 UTC

[Release notes](https://docs.oracle.com/cd/E17277_02/html/relnotes.html)
> As of version 7.3, JE is licensed under the Apache 2.0 license. See the LICENSE file for the complete license.

w00t

[Change log](https://docs.oracle.com/cd/E17277_02/html/changelog.html)
> In JE 7.3 the on-disk file format moved to 14. The file format change is forward compatible in that JE files created with earlier releases can be read when opened with JE 7.3 or later. The change is not backward compatible in that files created with JE 7.3 or later cannot be read by earlier releases. After an existing environment is opened read/write using JE 7.3, the environment can no longer be read by earlier releases.

My initial testing has been successful. Reading in a BerkeleyJE graph with the old version worked fine. Updating the version in [janusgraph-berkeleyje/pom.xml](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-berkeleyje/pom.xml#L38) didn't introduce any new dependencies.

**Comment by jerryjch** [comment]
Fixed in PR #101
