### ISSUE TITLE
does janusgraph have the same operator as NEO4J with "merge"

### ISSUE THREAD

**Issue by githublcq** [JanusGraph/janusgraph#1006]
i need the Vertex in janusgraph is unique,so everytime when i need add a relation i have to query the janusgraph to know whether corresponding vertexs exist or not. if it does,i need not  create the Vertexs but only add the edge.  otherwise create the vertexs. it spends a lot of time if the graph is huge.
Neo4j has offered the operator of "merge".firstly it will make sure if the Vertex exists automaticly, if it does then it will not create the Vertex,or it will create the Vertex automaticly.

**Comment by robertdale** [comment]
Create or update:  g.V().has('primaryKey',
'value').fold().coalesce(unfold(),
__.addV().property('primaryKey','value')).property('updatedProperty','value')

Robert Dale

**Comment by githublcq** [comment]
@robertdale
query by hand is inevitable? if the graph is huge, the operator spends more and more time.
