### ISSUE TITLE
HBaseBinaryInputFormat does not read ext parameters

### ISSUE THREAD

**Issue by twilmes** [JanusGraph/janusgraph#1008]
I don't believe there is a way to pass extra parameters down into the HBase connection factory when running on the GraphComputer. It looks like `ext` parameters should be captured like they are in OLTP mode when under the `storage` namespace and passed through. This causes an issue right now with Bigtable because there isn't a way to pass the Bigtable specific parameters including `google.bigtable.project.id`, `google.bigtable.instance.id`, and `hbase.client.connection.impl`.

**Comment by jerryjch** [comment]
@twilmes  It is probably fixed as part of PR #656.  (Refer to the changes in HBaseBinaryInputFormat). But it was only delivered into master branch.

**Comment by twilmes** [comment]
Nice catch! Thanks @jerryjch. What would you think about me applying that `ext` update you made on 0.2? I'd probably consider it a bug fix since it breaks Google Cloud Bigtable compatibility with OLAP.

**Comment by twilmes** [comment]
Closed by #1021
