### ISSUE TITLE
how to check reindexing progress

### ISSUE THREAD

**Issue by githublcq** [JanusGraph/janusgraph#1013]
There are hundred of million vertexs in janusgraph. it costs few hours to reindex those vertexs,how to check reindexing progress?

**Comment by githublcq** [comment]
rerun this :
gremlin> mgmt.updateIndex(number,SchemaAction.REINDEX)  
it shows: Another job with the same id is already running:number

then i run: g.V().has('number','**')  to query, it find nothing!

**Comment by robertdale** [comment]
This is for tracking issues - bugs, feature requests, etc.  Please use the mailing list for general discussion and questions - https://groups.google.com/forum/#!forum/janusgraph-users
