### ISSUE TITLE
the provide traverser does not map to a value: v[411960897536]->[SelectOneStep(a)]

### ISSUE THREAD

**Issue by githublcq** [JanusGraph/janusgraph#1018]
gremlin> g.V().has('user','number','95595').fold().coalesce(unfold(),__addV('user').property('number','95595')).as('a')
.V().has('user','number','15515').fold().coalesce(unfold(),__addV('user').property('number','15515')).addE('call').from('a')

**Comment by robertdale** [comment]
This is probably better formed as a question on the mailing list. In the future, please use the list first and then open an issue when it's identified as an actual bug. https://groups.google.com/forum/#!forum/janusgraph-users

In any case, `fold()` is described as a map step, but it is also a reducing barrier step.  Reducing barrier steps cause any step labels prior to it to be lost, for example 'a'. Rewrite it like this:

```
g.V().has('user','number','95595').fold()
.coalesce(unfold(),__.addV('user').property('number','95595')).as('a')
.coalesce(__.V().has('user','number','15515'),__.addV('user').property('number','15515'))
.addE('call').from('a')
```
