### ISSUE TITLE
Update the Version Compatibility Matrix

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#102]
http://docs.janusgraph.org/0.1.0-SNAPSHOT/version-compat.html

Update the support matrix after the recent upgrades of the components.
We can wait until the major upgrades are all in before updating this doc for the first release.

**Comment by jerryjch** [comment]
More information can be added there.  For example, hadoop version, Java version.

**Comment by mbrukman** [comment]
Fixed by PR #176.
