### ISSUE TITLE
Remove C* "COMPACT STORAGE" declaration for tables created with CQL storage backend

### ISSUE THREAD

**Issue by jeremysears** [JanusGraph/janusgraph#1023]
C* is deprecating the "COMPACT STORAGE" table option in C* 4.X.  In addition, DataStax DSE 6.0.0 now refuses to create tables with the "COMPACT STORAGE" option enabled.  This causes JanusGraph to fail to create tables in that configuration.  For 0.3.0, we should remove the compactStorage() call from org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.initializeTable() ([line 223](https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java#L223)), so as to avoid future data migration issues.

```
[error] (run-main-0) com.datastax.driver.core.exceptions.SyntaxError: Compact tables are not allowed in Cassandra starting with 4.0 version.
[error] com.datastax.driver.core.exceptions.SyntaxError: Compact tables are not allowed in Cassandra starting with 4.0 version.
[error] 	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
[error] 	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
[error] 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
[error] 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
[error] 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
[error] 	at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.initializeTable(CQLKeyColumnValueStore.java:215)
[error] 	at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.<init>(CQLKeyColumnValueStore.java:155)
[error] 	at org.janusgraph.diskstorage.cql.CQLStoreManager.lambda$openDatabase$10(CQLStoreManager.java:323)
[error] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[error] 	at org.janusgraph.diskstorage.cql.CQLStoreManager.openDatabase(CQLStoreManager.java:323)
[error] 	at org.janusgraph.diskstorage.keycolumnvalue.KeyColumnValueStoreManager.openDatabase(KeyColumnValueStoreManager.java:43)
[error] 	at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:453)
[error] 	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1378)
[error] 	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
[error] 	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
[error] 	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:113)
...
[error] Caused by: com.datastax.driver.core.exceptions.SyntaxError: Compact tables are not allowed in Cassandra starting with 4.0 version.
[error] 	at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
```

**Comment by pluradj** [comment]
From the Apache Cassandra [docs](https://cassandra.apache.org/doc/latest/cql/ddl.html#compact-tables):

> WARNING: Since Cassandra 3.0, compact tables have the exact same layout internally than non compact ones (for the same schema obviously), and declaring a table compact only creates artificial limitations on the table definition and usage. It only exists for historical reason and is preserved for backward compatibility And as COMPACT STORAGE cannot, as of Cassandra 4.0, be removed, it is strongly discouraged to create new table with the COMPACT STORAGE option.

With this change, folks using Cassandra 2 would see a surge in storage consumption. We could perhaps set COMPACT STORAGE only for older versions of Cassandra or consider dropping support for older versions of Cassandra. The [version compatibility matrix](http://docs.janusgraph.org/latest/version-compat.html) still shows support for Cassandra 1.2.z, 2.0.z, 2.1.z, 2.2.z.

**Comment by jeremysears** [comment]
I was assuming this would only increase storage for newly created schemas, and existing schemas on old versions of C* would just continue to work with compact storage.  However, new schemas created on old (and newer) versions of C* would require additional storage, but would retain an upgrade path to modern C* versions.

**Comment by jeremysears** [comment]
We could also drop compact storage by default, but add a config option to enable it, for those who need it for use in legacy scenarios.  Alternatively, to avoid a breaking change, we could leave compact storage enabled by default and provide a config option to disable it.  However, since C* is already making this breaking change in 4.X, it seems reasonable to propagate the breaking change into JanusGraph with a config-based backward compatibility escape-hatch for legacy C* users.

**Comment by pluradj** [comment]
@jeremysears I think it would be fair enough to make the breaking change on master. Are you considering [contributing](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) a patch for this?

For reference, DataStax docs on [migrating from compact storage](https://docs.datastax.com/en/cql/3.3/cql/cql_using/dropCompactStorage.html). It'd be good to include upgrade pointers to that doc with this enhancement.

**Comment by jeremysears** [comment]
I'd be willing to consider submitting a PR for this.  However, I won't be able to work on this until ~July.  What are you release timelines for 0.3.0?

**Comment by jeremysears** [comment]
Is there a process for finalizing the breaking change decision, or should I assume that is the right way to proceed?

**Comment by mbrukman** [comment]
@jeremysears — a [DISCUSS] thread on janusgraph-dev@ mailing list would be a good way to confirm that folks are OK with a breaking change. If at all possible, it may be better to do a non-breaking change (i.e., only do it for C* 2.x, and disable it for later versions, since it is a no-op for C* 3.x and invalid in C* 4.x .

http://docs.janusgraph.org/latest/development-decisions.html outlines the process.

**Comment by pluradj** [comment]
The [0.3.0 release](https://groups.google.com/d/msg/janusgraph-dev/0ng5lHio4TQ/1F_BeHP2AQAJ) is right around the corner. @jeremysears If you're not able to work on in until July, then there's a good chance somebody else might pick up this issue before then.

**Comment by bsorrentino** [comment]
Hi 

I've dealt with this problem. 

I used the [Datastax DSE version 6.01](https://github.com/datastax/docker-images/tree/master/example_compose_yamls) and got error `Compact tables are not allowed in Cassandra starting with 4.0 version` .

To solve database creation simply,  i've commented `.compactStorage()` in [file CQLKeyColumnValueStore.java line 223 project janusgraph-cql](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java#L223) and it worked

**Comment by albertbalada** [comment]
Hi Bartolo,
     this is awesome, maybe that can be optionally activated depending on the client so the legacy Thrift client can continue working if required.
