### ISSUE TITLE
CQLStoreManager doesn't support storage.port property

### ISSUE THREAD

**Issue by rkozmer** [JanusGraph/janusgraph#1034]
On the dev server, I would like to easily switch between different Cassandra and Scylla backends. I just realized the `storage.port` is not supported. Does any store manager support it?
Btw: same problem with ElasticSearch - `index.[X].port`.

**Comment by pluradj** [comment]
I just tested this out, and it works fine for me.

In `cassandra.yaml` I updated `native_transport_port: 9043` (default is 9042), then I connected to a graph with: 
```
graph = JanusGraphFactory.build().
    set('storage.backend', 'cql').
    set('storage.hostname', 'localhost').
    set('storage.port', 9043).
    set('storage.cql.keyspace', 'test').
    open()
```

If you are using `cassandra` or `cassandrathrift`, you need to update the Thrift port in the `cassandra.yaml`. For example, I tried `rpc_port: 9161` (default is 9160), then I connected to a graph with: 
```
graph = JanusGraphFactory.build().
    set('storage.backend', 'cassandra').
    set('storage.hostname', 'localhost').
    set('storage.port', 9161).
    set('storage.cassandra.keyspace', 'test').
    open()
```

**Comment by rkozmer** [comment]
Thank you Jason!!!
Both storage.port and index.search.port is working fine now. I found the issue in my code.
Rado
