### ISSUE TITLE
Mistake in section 9.2 of the documentation

### ISSUE THREAD

**Issue by Prakhar0409** [JanusGraph/janusgraph#1036]
Section 9.2 of the Janusgraph Documentation has the following:

Building a vertex-centric index by time speeds up such traversal queries.

```
graph.tx().rollback()  //Never create new indexes while a transaction is active
mgmt = graph.openManagement()
time = mgmt.getPropertyKey('time')
battled = mgmt.getEdgeLabel('battled')
mgmt.buildEdgeIndex(battled, 'battlesByTime', Direction.BOTH, Order.decr, time)
mgmt.commit()
//Wait for the index to become available
mgmt.awaitGraphIndexStatus(graph, 'battlesByTime').call()
//Reindex the existing data
mgmt = graph.openManagement()
mgmt.updateIndex(mgmt.getGraphIndex("battlesByTime"), SchemaAction.REINDEX).get()
mgmt.commit()
```

The following line might be incorrect. It gives a null pointer exception.
`mgmt.awaitGraphIndexStatus(graph, 'battlesByTime').call()` 

Instead the correct line I suppose is:
`mgmt.awaitRelationIndexStatus(graph, 'battlesByTime', 'battled').call()`

**Comment by chupman** [comment]
fixed in PR #1235
