### ISSUE TITLE
Each property lookup resulting backend call (Vertex Centric Index queries)

### ISSUE THREAD

**Issue by rafatuita** [JanusGraph/janusgraph#104]
As described in this post https://groups.google.com/forum/#!topic/aureliusgraphs/qd71sHiCHYI , we should consider enabling this configuration by default to avoid performance degradation.

Need to investigate why this has been disabled previously.

**Comment by amcp** [comment]
Matthias [turned fast-property off by default for the Titan 1.0.0](https://github.com/JanusGraph/janusgraph/commit/ec088079b2f4b64945b7c11f134987c99e519e47) release, for no particular reason. I suggest we turn it back on, or at least discuss this configuration option in the vertex-centric index bit of the documentation

**Comment by twilmes** [comment]
I think it makes good sense to default this back to true. Perhaps we can start a discussion on janusgraph-dev and assume lazy consensus in 72 hours if no one objects just in case anyone has a good reason to leave it false.

**Comment by samikrc** [comment]
Well - I guess defaulting the value to true would make sense as long as the number of properties on an element is reasonable - which is probably the majority of use cases. The graph that we have (in titan at the moment), has a few nodes containing ~25 properties. Hopefully that number is small enough.

Can the OP of that thread comment on the number of properties that were there on the elements?

**Comment by aphelps** [comment]
I was the OP on that thread.  For our system, we usually have ~5-10 properties on any given vertex, and all property data is short (integers or short strings).  I do think that the majority of use cases would prefer fetch all in one go, given that the new-to-1.0 one-at-a-time default dramatically slowed things down due to all the additional trips to the back end.

**Comment by twilmes** [comment]
Thread started here: https://groups.google.com/forum/#!topic/janusgraph-dev/P94zxhUbubc.  No one piped up so I think we should go ahead and turn fast-property back to true.

**Comment by rafatuita** [comment]
I'm picking it up, make some tests and debugs, if I don't find anything
weird, I'll PR to the project...

Cheers,
Rafa

**Comment by twilmes** [comment]
Excellent, thanks @rafatuita.

**Comment by sjudeng** [comment]
@rafatuita, @twilmes What's the status on this? I could have sworn this was done but I'm not finding the PR.

**Comment by rafatuita** [comment]
I was sure that I had pushed a PR for this as well, I just checked and I've been using it on my production system for a while now... anyways, let me push it up.
