### ISSUE TITLE
JanusGraph vertex cut

### ISSUE THREAD

**Issue by MengsD** [JanusGraph/janusgraph#1049]
"**Cutting a vertex means storing a subset of that vertex’s adjacency list on each partition in the graph**."
What does it mean?  In Cassandra, doesn't a vertex's all adjacency list are considered as a row(edges are cells)?

**Comment by jerryjch** [comment]
Yes. But you can define to 'cut vertext' by splitting the potentially huge adjacency list and spreading them across different rows -- thus different partitions. Of course, in this case, the row id (and the vertex id) need to be implemented in such a way that we know we are talking about the same vertex and its edges even they are spliced into multiple partitions.
