### ISSUE TITLE
Is it possible to use a new branch to fix the issue of not using index with or step?

### ISSUE THREAD

**Issue by RaulGuo** [JanusGraph/janusgraph#1054]
The or query cannot use index is really a big trouble for us. We have to use that in many sceneries. Is it possible to fix it in version 0.2.0 with a new branch of 0.2.0?

**Comment by davidclement90** [comment]
I am sorry but the rule voted by JanusGraph's contributor  @pluradj  is : no new feature in a bug fix branch.
So if you really want this feature : you can test your apps with 0.3.0-SNAPSHOT to use 0.3.0 as soon as its release or try to cheery-pick the commit in your custom 0.2 
For me, the fork is not a good choice.

**Comment by pluradj** [comment]
Just a clarification here. This is a _community-based project_. The policy of having no new features in a bug fix branch is a _community policy_, and it is not dictated by a single person. If we want to discuss this more, please bring it up on the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev) mailing list.

**Comment by RaulGuo** [comment]
Thanks for your reply guys. I have got some other ways to avoid using or step to solve my issue. This seems not a fit place to talk about it, but I am trying to study the source code and I have learned a lot. you are doing really great work. I wish to join you somedays soon.
