### ISSUE TITLE
Gremlin.Net Extension library for JanusGraph

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1059]
Provide a .NET library that extends Gremlin.Net (the TinkerPop C#/.NET GLV and driver) with JanusGraph specific types and predicates. Examples for such types are the various `Geoshapes` and predicates enable usage of mixed indices from .NET, e.g., with `textContains`.

Adding a .NET library to JanusGraph will of course make the build process more complicated, but we can basically the same approach TinkerPop has taken and include the .NET build into the usual Maven build.

This ticket is based on this thread from the developer mailing list:
https://groups.google.com/forum/#!topic/janusgraph-dev/LDh1gKuRR3A

**Comment by hittipatrick** [comment]
Hi Florian,

I am working on a project that requires implementation of Janusgraph from C#. I installed all the prerequisites and ran the gremlin-server.bat on the machine and all is working fine from the console. However, whenever i try to connect and do a traversal from C#, I receive the below errror:

'InvalidRequestArguments: The traversal source [g] for alias [g] is not configured on the server.'

Am i missing any configuration on the server?
Can you support in fixing this?

**Comment by FlorianHockmann** [comment]
Hi @hittipatrick,
first of all, please ask usage questions like this on the [user mailing list](https://groups.google.com/forum/#!forum/janusgraph-users) or on [Gitter](https://gitter.im/janusgraph/janusgraph). More people will see your questions there and can possibly help you.

You're probably not connecting with the Console to the JanusGraph Server but instead directly to your backend (like Cassandra). Your error sounds like your server configuration is simply wrong or it misses a startup script that creates and registered a graph traversal source `g` for a configured graph like shows in [the default `empty-sample.groovy`](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/src/assembly/static/scripts/empty-sample.groovy) which needs to be [specified in your server config](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml#L14).

**Comment by FlorianHockmann** [comment]
We now have a dedicated repo for this library where all progress will be tracked:
https://github.com/JanusGraph/janusgraph-dotnet
