### ISSUE TITLE
0.1.0 post-release activities

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#107]
- [x] [Request listing on TP landing page](
https://lists.apache.org/thread.html/246807a067c2ef05d82c1bf38ac53dea1138f89ed0a76f298df9cd84@%3Cdev.tinkerpop.apache.org%3E)

**Comment by mbrukman** [comment]
@amcp – adding this issue to the 0.1.0 milestone means it's a _blocker_ for the 0.1.0 release, whereas the dependency is exactly the opposite: the ability to be listed in the TinkerPop list is dependent on the release, not the other way around.

However, for tracking purposes, we should keep only the issues blocking the release itself referenced by the milestone, as the % completeness directly relates to the issues fixed _before_ the release itself.

I would propose that we create a single issue with a checklist of things we should do after the first release is made, and this issue should be one of those. Thoughts?

**Comment by amcp** [comment]
@mbrukman I agree, so I changed the name of the issue and we can start a list in the description

**Comment by mbrukman** [comment]
Thanks to @robertdale for committing a [change to TinkerPop](https://github.com/apache/tinkerpop/commit/feae45da67df7140f9d0aec7eddd032e50814961) ([posted on TinkerPop dev list](https://lists.apache.org/thread.html/c5dbd4e84869fe689e41bc3f4e728356d7bfc5d01bd5a57b422efe6a@%3Cdev.tinkerpop.apache.org%3E)) to add JanusGraph to the list; waiting for push to http://tinkerpop.apache.org/ for it to be visible publicly.

**Comment by robertdale** [comment]
Changes are live now.

**Comment by mbrukman** [comment]
Thank you, @robertdale!
