### ISSUE TITLE
CQL tests breaking in Travis

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#1085]
Two CQL test groups are failing consistently in Travis with a NullPointerException. Based on review of Travis build logs (see [#1494.29](https://travis-ci.org/JanusGraph/janusgraph/jobs/373112042) and [#1494.30](https://travis-ci.org/JanusGraph/janusgraph/jobs/373112046)) issue appears to have been introduced in #965.

**Comment by pluradj** [comment]
@TitiHl can you please investigate this?

**Comment by TitiHl** [comment]
hmmm. weird. when I run `insertingGettingAndDeletingSimpleDataWorks@ CQLStoreTest` locally, it is passing from IntelliJ. is there any new changes get in recently? I haven't `git fetch` yet as I think I need to fix up the git ssh key (at the moment it confuses with my internal key)

**Comment by TitiHl** [comment]
Hi, done with PR^
https://github.com/JanusGraph/janusgraph/pull/1090

**Comment by sjudeng** [comment]
Fixed by #1090
