### ISSUE TITLE
what is incident edge of vertex

### ISSUE THREAD

**Issue by fantine16** [JanusGraph/janusgraph#1094]
![image](https://user-images.githubusercontent.com/9497853/40818644-c517ff26-658a-11e8-8513-67c45fa57a7f.png)

what does vertex's incident edge mean ?

It's common, for instance, to talk about "a vertex and an incident edge" meaning any edge that has the given vertex as either the start or end of the edge (or both).

Did I understand right?

**Comment by pluradj** [comment]
It contains all edges in both directions, outgoing and incoming edges.

Please direct questions like this to the [janusgraph-users](https://github.com/JanusGraph/janusgraph/#community) mailing list rather than the issue tracker. Thanks.
