### ISSUE TITLE
Slow request  through gremlin server but not through gremlin local console

### ISSUE THREAD

**Issue by graphdb2** [JanusGraph/janusgraph#1100]
Hello,

I experience a slow request through gremlin server but it has good performance in gremlin local console

Gremlin server : around 13 sec
Gremlin local console : 1 sec

The client is gremlin.net and janus version is 0.2.0 and 0.3.0 snapshot

I tested both graphson v2 and v3 it did not make any difference.
 
`
g.V().has('identifiant', 'rdf/reference.legalentity/public/rdx/VO32SGB').outE('parentof').has('from',lte(1474894850)).and(or(__.has('to',gt(1474894850)),__.hasNot('to'))).inV().outE('state').has('from',lte(1474894850)).and(or(__.has('to',gt(1474894850)),__.hasNot('to'))).inV().as('cState').valueMap('name', 'type','status','country','cityid','keys')`

The request  return 10k row.

The same request on Neo4j using gremlin server as well  run around 1 sec on gremlin.net graphson v3

**Comment by FlorianHockmann** [comment]
How exactly did you connect from the console? Did you use `:remote connect` or did you connect directly to your backend?

**Comment by graphdb2** [comment]
The console is connected directly to the hbase backend.

**Comment by graphdb2** [comment]
![gremlinremoteconsole](https://user-images.githubusercontent.com/38073847/41162729-9caf9f5e-6b2e-11e8-9572-2dca811b0cb2.png)

This is the profile of the slow query on the gremlin remote, I have executed the same request several time, so it looks it take 8 sec to serialize 6000 rows with GraphSONMessageSerializerGremlinV2d0.

**Comment by graphdb2** [comment]
I managed to improve the slow request(3.5 sec) through gremlin server Gson v3 by removing the valueMap and replace by local(properties().group().by(key).by(value)):
`
gremlin> :> g.V().has('identifiant', 'rdf/reference.legalentity/public/rdx/VO32SGB').outE('parentof').has('from',lte(1474894850)).and(or(__.has('to',gt(1474894850)),__.hasNot('to'))).inV().barrier().outE('state').has('from',lte(1474894850)).and(or(__.has('to',gt(1474894850)),__.hasNot('to'))).inV().as('cState').local(properties().group().by(key).by(value))`

It looks it is an old issue : http://mail-archives.apache.org/mod_mbox/tinkerpop-dev/201509.mbox/%3CJIRA.12896315.1443152812000.82346.1443284584098@Atlassian.JIRA%3E

**Comment by pluradj** [comment]
Glad you resolved it. Closing.
