### ISSUE TITLE
Cassandra Privilege "Create on Table"

### ISSUE THREAD

**Issue by BeatSager** [JanusGraph/janusgraph#1103]
The issue [Cassandra Privilege "Create on All Keyspaces"](https://github.com/JanusGraph/janusgraph/issues/933) has already been solved.
Unfortunately using cql the same issue is still preset for create table within a keyspace. 
```
CQLKeyColumnValueStore

    private static void initializeTable(final Session session, final String keyspaceName, final String tableName, final Configuration configuration) {
        session.execute(createTable(keyspaceName, tableName)
                .ifNotExists()
                .addPartitionKey(KEY_COLUMN_NAME, DataType.blob())
                .addClusteringColumn(COLUMN_COLUMN_NAME, DataType.blob())
                .addColumn(VALUE_COLUMN_NAME, DataType.blob())
                .withOptions()
                .compressionOptions(compressionOptions(configuration))
                .compactionOptions(compactionOptions(configuration))
                .compactStorage());
    }
```
We would like to run janusgraph without having to give the cassandra user this privilege.

Possible solution for discussion:
https://github.com/BeatSager/janusgraph/commit/d8e1a5008abab4e4fa22482d5295f73ff25a886e

**Comment by pluradj** [comment]
@BeatSager Thank you for opening up the issue. It would be best if you submit your solution as a pull request. Please file an [individual or corporate CLA](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) first. Thanks.

**Comment by BeatSager** [comment]
https://github.com/JanusGraph/janusgraph/pull/1110
