### ISSUE TITLE
Update Log4j to log4j 2

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1105]
JanusGraph uses log4j version 1.2.16 but version 1 isn't supported anymore since almost 3 years ago:

> On August 5, 2015 the Logging Services Project Management Committee announced that Log4j 1.x had reached end of life.

Source: http://logging.apache.org/log4j/1.2/

So JanusGraph should be updated to a more recent version of Log4j. From a user perspective this brings some nice benefits like new logging layouts for example (one of them is the JSON layout which is very useful to have to collect logs in something like the ELK stack or Graylog).

**Comment by pluradj** [comment]
The idea is solid, but question is how Log4j is utilized in the various upstream dependencies, including [TinkerPop](https://github.com/apache/tinkerpop/blob/master/pom.xml#L147).

**Comment by FlorianHockmann** [comment]
Right, I haven't considered that. I created [TINKERPOP-1983](https://issues.apache.org/jira/browse/TINKERPOP-1983) for TinkerPop. We should probably wait until / if the dependency is updated in TinkerPop and then check whether we can update too or if there are still problems left due to other upstream dependencies.

**Comment by FlorianHockmann** [comment]
Looks like we can't do this any time soon as TinkerPop won't update because it in turn needs Spark and Hadoop to update log4j first: https://issues.apache.org/jira/browse/TINKERPOP-1983

We could however document how users can use and configure Logback instead as suggested by Stephen in the linked TinkerPop ticket but that would be a different issue. So, I'm closing this for now.

**Comment by hilbertglm** [comment]
It is fairly straightforward to write a logging appender for log4j that provides output in JSON or whatever other format you like.  I am in the process of writing them for Log4j, Log4j2, Logback, and Serilog so that everything logs to a common REST service in a common format. I can then push that downstream to an ELK stack or other log stream processing tools.

Not ideal, but it gets the job done.

**Comment by amotzhoshen** [comment]
Hi @FlorianHockmann - I'm also interested in producing JSON logs. Is there a documentation how to configure JG to use Logback? I'm working with a dockerized version of the project. Thanks!

**Comment by FlorianHockmann** [comment]
@amotzhoshen No, it's not documented yet. It should work basically like this:

Create your own log4j config `log4j-server.properties`:

```
log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.Threshold=INFO
log4j.appender.A1.layout=biz.paluch.logging.gelf.log4j.GelfLayout
log4j.appender.A1.layout.ExtractStackTrace=true

# Set loggers
log4j.rootLogger=INFO, A1
```

Add the config and necessary jars to the Docker image via the `Dockerfile`:

```
COPY --chown=janusgraph:janusgraph src/log4j-server.properties ${JANUS_HOME}/conf/gremlin-server/

ADD --chown=janusgraph:janusgraph http://central.maven.org/maven2/biz/paluch/logging/logstash-gelf/1.12.0/logstash-gelf-1.12.0.jar ${JANUS_HOME}/lib
ADD --chown=janusgraph:janusgraph http://central.maven.org/maven2/org/apache/commons/commons-pool2/2.4.3/commons-pool2-2.4.3.jar ${JANUS_HOME}/lib
```

This uses `biz.paluch.logging.gelf.log4j.GelfLayout`, but there are probably more libraries available that can format logs in JSON.
