### ISSUE TITLE
8.10 Examples for ConfiguredGraphFactory Lack Session Parameter

### ISSUE THREAD

**Issue by jrhayward** [JanusGraph/janusgraph#1113]
In Documentation version 0.2.0 Chapter 8 section 8.10 the examples show a remote server connection without the session parameter which causes the examples to fail.  The session parameter is required for the variables used in the example to be available on the server.

**Comment by chupman** [comment]
Hi @jrhayward. PR #992 addressed this, but the hosted docs haven't been regenerated so you'd have to compile locally to see the changes. You can  see the changes specific to 8.10 [here](https://github.com/JanusGraph/janusgraph/blob/master/docs/configuredgraphfactory.adoc#examples).

**Comment by jrhayward** [comment]
Thank you
