### ISSUE TITLE
addEdge creates two new vertices

### ISSUE THREAD

**Issue by Miroka96** [JanusGraph/janusgraph#1119]
Hi guys,

what can be broken, if every addEdge (even on newly created vertices) creates two new vertices for it's end. I am using GraphExp for Visualization and on a path of 4 vertices I have 10 instead.

Do edges store different vertexIDs as their start/end point than the real start and end vertices? Because in other words, my edges do not start and end on the vertex they should, but on one equal to the one it should be but with a different Vertex ID.

Despite that, my 'unique' indexes are still kind of broken, like in the previous issues...

**Comment by pluradj** [comment]
code reproducing the issue would be helpful

**Comment by Miroka96** [comment]
Okay, I am sorry for my mistake... I had enabled vertex cut (vertex partitioning), when creating the vertex labels. Now it makes sense.
