### ISSUE TITLE
Both Tinkerpop drop and JanusGraph drop do not work for in-memory Janusgraph

### ISSUE THREAD

**Issue by mengxie18** [JanusGraph/janusgraph#1140]
I am testing a in-memory JanusGraph. At the end of graph creation, I want to clean up the graph by removing all vertices without closing the graph.

**Code**:
`JanusGraph graph =
                JanusGraphFactory.build().set("storage.backend", "inmemory").open();`

I found using Tinkerpop drop() step does not actually remove the nodes from the graph:
http://tinkerpop.apache.org/docs/current/reference/#drop-step

**Code**:
![image](https://user-images.githubusercontent.com/22803085/41997345-8f2f91bc-7a0c-11e8-8840-79830956a2a6.png)

**Console output**:
>>> Graph vertex size 19 edge size 9 creation committed 7236
Graph vertices count before drop 19
Graph vertices count after drop 19
>>> Graph vertex size 38 edge size 18 creation committed 797
Graph vertices count before drop 38
Graph vertices count after drop 38
>>> Graph vertex size 57 edge size 27 creation committed 101
Graph vertices count before drop 57
Graph vertices count after drop 57

On the other hand, I tried JanusGraphFactory.drop(graph) ln 198: https://github.com/JanusGraph/janusgraph/blob/3fb5e75124de9a2b39dece7094c4eff4bb289834/janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java

When debugging into it, I found the JanusGraphManager instance - jgm is null. Therefore it is also not clearing up the graph. Is this because I am using the in-memory graph?

Any solution or workaround for either the Tinkerpop drop() or the JanusGraphFactory drop problem?

Thanks in advance!

**Comment by amcp** [comment]
@mengxie18 can you do the following to help debug the issue. I think you are actually close to fixing it.
1. Fork JanusGraph/janusgraph to mengxie18/janusgraph
2. Add a test case to janusgraph-core in a branch off 0.2.0 branch to reproduce the issue you describe. your code above is 90% a repro, just needs to be added to a test class.
3. see if you can fix the issue for the in-memory backend. Would be interesting to compare JG behaviors for in-memory and berkeleyje with tinkergraph.

**Comment by pluradj** [comment]
You need to iterate the traversal otherwise it won't be executed.

```
g.V().drop().iterate();
```

* https://docs.janusgraph.org/latest/gremlin.html#_iterating_the_traversal

**Comment by mengxie18** [comment]
Thanks @amcp and @pluradj  for your quick reply.
I tried adding .iterate(), but it didn't work. 
I will try to add the test case and debug.
