### ISSUE TITLE
How to do OR query in janusgraph with Solr as Backend Index

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1164]
I have found that 
if terms "tomorrow world" is supplied as query as given below
g.V().has('text',textContains('tomorrow world'))

then the result returned will be 
text: in the world of tomorrow 
while I want all the below given results for above search query
text : in the tomorrow world
text :  tomorrow is saturday
text : hello world

Note : the result with both "tomorrow " and "world" is returned as result while the text containing "tomorrow" only and "world" only is not returned by janusgraph

**Comment by pluradj** [comment]
did you try 
```
g.V().or( has('text', textContains('tomorrow')), has('text', textContains('world')) )
```

**Comment by pra527vin** [comment]
this solution didnt work for me
g.V().or( has('text', textContains('tomorrow')), has('text', textContains('world')) )

**Comment by pra527vin** [comment]
Thanks @pluradj  with some changes it worked

**Comment by pluradj** [comment]
@pra527vin are you able to share your final solution here in case somebody else runs into a similar issue? thanks.
