### ISSUE TITLE
Add Unifi as a production user

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#1169]
As noted in issue #1149, [Unifi Catalog & Discovery](https://unifisoftware.com/product/catalog-discovery/) is built on JanusGraph:

> ### View Data Relationships
>
> Graphically represented by JanusGraph embedded into the Unifi Data Catalog UI, a user can easily determine how datasets and even attributes are related. Understanding where data comes from, the provenance, and lineage are essential to determining data validity.

Unifi approved being listed with the name and logo on JanusGraph README and website.

- [ ] add Unifi by name to JanusGraph README
- [ ] add Unifi logo to website

**Comment by porunov** [comment]
@mbrukman It is currently listed in the `Powered by JanusGraph` section. 
Should we still add a logo to the website? If so, I've created https://github.com/JanusGraph/janusgraph.org/pull/71

**Comment by FlorianHockmann** [comment]
I'm closing this as the link doesn't work any more and I can't find much information about this project at all, not sure if it's still maintained.
