### ISSUE TITLE
How to use es for the index backend???

### ISSUE THREAD

**Issue by AaronCH5** [JanusGraph/janusgraph#1172]
I have seen the doc for the es index backend, now i try to ues java api to verify how to connect to es.
The following code:

object JanusGraphTest {

  def main(args: Array[String]): Unit = {

    // https://github.com/pluradj/janusgraph-scala-example/blob/master/src/main/scala/JanusGraphScalaExample.scala

    // create graph
    // 初始化链接，使用hbase做janusgraph的数据存储
    // val graph = JanusGraphFactory.open("inmemory")
    val graph = JanusGraphFactory.build()
      .set("storage.backend", "hbase")
      .set("storage.hbase.table", "janusgraph05")
      .set("storage.hostname", "yws75, yws76, yws77")
      .set("storage.hbase.short-cf-names", false)
      // .set("storage.hbase.skip-schema-check", true)
      .set("storage.hbase.compression-algorithm", "NONE")
      .set("attributes.custom.attribute1.attribute-class", "java.lang.StringBuffer")
      // serializer-class
      .set("attributes.custom.attribute1.serializer-class", "pluradj.janusgraph.graphdb.database.serialize.attribute.StringBufferSerializer")

      .set("index.zp.backend", "elasticsearch")
      .set("index.zp.hostname", "yws76:9200")
      .set("index.zp.index-name", "jp_test")
      .open()
    val g = graph.traversal()

    /*val graph = JanusGraphFactory.open("data/janusgraph-hbase-es.properties")
    val g = graph.traversal()*/

    // create graph schema
    var mgmt = graph.openManagement()

    println("----| " + mgmt.get("index.search.backend"))

    var person = mgmt.getOrCreateVertexLabel("person")

    val name = mgmt.makePropertyKey("name").dataType(classOf[String]).make()
    val age = mgmt.makePropertyKey("age").dataType(classOf[Integer]).make()
    val weight = mgmt.makePropertyKey("weight").dataType(classOf[java.lang.Double]).make()

    val nameIndex = mgmt.buildIndex("nameIndex", classOf[Vertex]).addKey(name).buildCompositeIndex()
    val ageIndex = mgmt.buildIndex("ageIndex", classOf[Vertex]).addKey(age).buildCompositeIndex()
    val weightIndex = mgmt.buildIndex("weightIndex", classOf[Vertex]).addKey(weight).buildCompositeIndex()

    val defeated = mgmt.makeEdgeLabel("defeated").make()

    val year = mgmt.makePropertyKey("year").dataType(classOf[Integer]).make()
    val score = mgmt.makePropertyKey("score").dataType(classOf[java.lang.Double]).make()

    val yearIndex = mgmt.buildIndex("yearIndex", classOf[Edge]).addKey(year).buildCompositeIndex()
    val scoreIndex = mgmt.buildIndex("scoreIndex", classOf[Edge]).addKey(score).buildCompositeIndex()
    mgmt.commit()

    // verify index status
    mgmt = graph.openManagement()
    println("||nameIndex  : " + mgmt.getGraphIndex("nameIndex").getIndexStatus(mgmt.getPropertyKey("name")))
    println("||ageIndex   : " + mgmt.getGraphIndex("ageIndex").getIndexStatus(mgmt.getPropertyKey("age")))
    println("||weightIndex: " + mgmt.getGraphIndex("weightIndex").getIndexStatus(mgmt.getPropertyKey("weight")))
    println("||yearIndex  : " + mgmt.getGraphIndex("yearIndex").getIndexStatus(mgmt.getPropertyKey("year")))
    println("||scoreIndex : " + mgmt.getGraphIndex("scoreIndex").getIndexStatus(mgmt.getPropertyKey("score")))

    // add vertices and edges
    val tyson = g.addV("person").property("name", "ironmike").property("age", 51).property("weight", 240.5d).next()
    val holyfield = g.addV("person").property("name", "realdeal").property("age", 55).property("weight", 226.0d).next()
    g.V(tyson).as("m").V(holyfield).addE("defeated").property("year", 1996).property("score", 8.5d).to("m").iterate()
    g.V(tyson).as("m").V(holyfield).addE("defeated").property("year", 1997).property("score", 9.7d).to("m").iterate()
    mgmt.commit()
    // get vertex by string index
    println("|---| - " + g.V().has("name", "ironmike").valueMap(true).toList())
    // get vertex by integer index
    println("|---| - " + g.V().has("age", 55).valueMap(true).toList())
    // get vertex by double index
    println("|---| - " + g.V().has("weight", 240.5d).valueMap(true).toList())
    // get edge by integer index
    println("|---| - " + g.E().has("year", 1996).valueMap(true).toList())
    // get edge by double index
    println("|---| - " + g.E().has("score", 9.7d).valueMap(true).toList())
    // close graph
    graph.close()
  }
}

FQ1:
In this  i can save data and index to hbase, but i can't find the index in es, i don't know why??

this is hbase data:
![qq 20180716134858](https://user-images.githubusercontent.com/24953071/42744421-0a9b257c-88ff-11e8-923e-10079723aa65.png)

FQ2:
I want to see the hbase rowkey for clear not hashing.how to do ???

FQ3:
Where can find the java api example/demo for es index backend and hbase storage backend for janusgraph??

TKS

**Comment by AaronCH5** [comment]
@pluradj @robertdale @ptgoetz  Can you help me ?

**Comment by pluradj** [comment]
1. You need to define a mixed index. Your example code only shows composite indexes. Please refer to the JanusGraph documentation https://docs.janusgraph.org/latest/indexes.html#index-mixed . Note that in your graph properties, you've defined the external index as `index.zp.backend`, so when defining the mixed index, you should use `buildMixedIndex('zp')`.

2. The data is stored in the storage backend in a serialized blob. You can't read it directly using the HBase shell or cqlsh (when using Cassandra). You could possibly write a program like the one shared here https://groups.google.com/d/msg/janusgraph-users/dzT5TEJfqGI/i7m2yqRwCAAJ for HBase.

3. You can find examples packaged with the distribution under the `examples` directory. They are also visible in the GitHub repository https://github.com/JanusGraph/janusgraph/tree/0.2.1/janusgraph-examples

Finally, we use the GitHub issues tracker for tracking code fixes. If you have general usage questions, please direct them to the [janusgraph-users](https://github.com/JanusGraph/janusgraph/blob/master/README.md#community) mailing list. You can also search the list for previous answers in case your question has already been asked.

**Comment by AaronCH5** [comment]
@pluradj tks, i see.
