### ISSUE TITLE
Janusgraph query for remote connection with solr andcassandra backend not giving empty results

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1173]
I have used Cassandra as  storage backend and solr as indexing backend .Index is created successfully while seaching
g.V() ..has('userName', textContains('jyoti')) 
works fine and gives result from indexing backend while 
g.V().hasLabel('DocumentArchiveUser').has('userName', textContains('jyoti'))
is not  giving result while the query is write

**Comment by pluradj** [comment]
It would be helpful if you would provide a reproducible test scenario, including the schema/index definitions and some data.

FWIW, this example worked for me:

```
graph = JanusGraphFactory.open('conf/graph.properties')
mgmt = graph.openManagement()
userName = mgmt.makePropertyKey('userName').dataType(String.class).make()
DocumentArchiveUser = mgmt.makeVertexLabel('DocumentArchiveUser').make()
userNameIndex = mgmt.buildIndex('userNameIndex', Vertex.class).
    addKey(userName, Mapping.TEXT.asParameter()).
    buildMixedIndex('search')
mgmt.commit()

// add one user with the vertex label, and one user without it
g = graph.traversal()
g.addV('DocumentArchiveUser').property('userName', '1 jyoti').
    addV().property('userName', '2 jyoti').
    iterate()
g.tx().commit()

// returns both users
g.V().has('userName', Text.textContains('jyoti')).toList()

// returns only 1 user
g.V().hasLabel('DocumentArchiveUser').has('userName', Text.textContains('jyoti')).toList()
```

**Comment by pra527vin** [comment]
@pluradj  I have manually defined the field userName in solr schema.xml in which i have used n gram tokenizer. but when I run the given query
g.V().hasLabel('DocumentArchiveUser').has('userName', Text.textContains('jyoti'))
the query is not sent to solr server

**Comment by pluradj** [comment]
If you want JanusGraph to leverage Solr, you need to define a [mixed index](https://docs.janusgraph.org/latest/index-parameters.html#text-search) as shown above and configure Solr as described in the JanusGraph [documentation](https://docs.janusgraph.org/latest/solr.html).

```
userNameIndex = mgmt.buildIndex('userNameIndex', Vertex.class).
    addKey(userName, Mapping.TEXT.asParameter()).
    buildMixedIndex('search')
```

Simply declaring the field `userName` in the Solr `schema.xml` will not do it.

**Comment by pra527vin** [comment]
@pluradj  I followed the way you have said. Now the query is sent to solr but result is still empty

**Comment by pra527vin** [comment]
@pluradj I have field named "nameUrl"  I have defined mixedIndex in the same way as you said (userName is tokenized using ngram tokenizer in solr server schema.xml) 
nameUrl : ict/newte.pdf
which is tokenize as ict new newt ewt ewte wte newte pdf
and my search query is like
g.V().hasLabel('Document').has('nameUrl', Text.textContains('new'))
but it is returning the empty results , while
g.V().has('nameUrl', Text.textContains('new'))
is returning results
when i see solr log and typed same query as shown the result is fetched from solr admin panel
do I have to make some special configuration for this?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
