### ISSUE TITLE
run  g.V(8304).until(hasId(12392)).repeat(out()).path excetion

### ISSUE THREAD

**Issue by lchqlchq** [JanusGraph/janusgraph#1175]
(1)
gremlin> graph=ConfiguredGraphFactory.open("test001");g=graph.traversal();g.V(8304).until(hasId(12392)).repeat(out()).path
ERROR org.apache.tinkerpop.gremlin,driver.Handler$GremlinResponseHandler - Could not process the response in.netty.handler.codec.CorruptedFrameException: Max frame length of 65535 has been exceed.
how to solve this problem?

**Comment by pluradj** [comment]
Searching [gremlin-users](https://groups.google.com/d/msg/gremlin-users/dBhGQodX6mc/p2zMa_tZAgAJ) finds the answer pretty quickly:

> increase the maxContentLength in the [server yaml](https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml#L35) file and the connectionPool.maxContentLength on the driver configuration

References in the TinkerPop docs
* Gremlin Server https://tinkerpop.apache.org/docs/current/reference/#_configuring_2
* Gremlin Driver https://tinkerpop.apache.org/docs/current/reference/#_configuration

**Comment by pluradj** [comment]
In the future, please use the [`janusgraph-users@` mailing list][mailing-list] for questions and discussion; GitHub issues are for filing specific, concrete bug reports or feature requests.

[mailing-list]: https://github.com/janusgraph/janusgraph#community
