### ISSUE TITLE
graph=ConfiguredGraphFactory.open('test'); mgmt=graph.openManagement();mgmt.getVertexLabels()

### ISSUE THREAD

**Issue by lchqlchq** [JanusGraph/janusgraph#1185]
when using gremlin console to connect gremlin server
run gremlin> graph=ConfiguredGraphFactory.open('test'); mgmt=graph.openManagement();mgmt.getVertexLabels()
will return: 
==>person
==>animal

but when using the same gremlin sentence in java language to query vertex label
it return: 
 {result{object=v[525] class=org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex},result{object=v[2061] class=org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex}}

i want get the label name in java,how to do?

**Comment by pluradj** [comment]
Please use the [`janusgraph-users@` mailing list][mailing-list] for questions and discussion; GitHub issues are for filing specific, concrete bug reports or feature requests.

[mailing-list]: https://github.com/janusgraph/janusgraph#community
