### ISSUE TITLE
How to change a bunch of edges' out/in vertices to another one?

### ISSUE THREAD

**Issue by RaulGuo** [JanusGraph/janusgraph#1193]
I have a condition like this: I have two vertices with label named "community", each one have a bunch of  vertices labeled "follower". Now I want to merge the two communities, which means I want to drop one community vertex(that is not the key though) and point its neighbour vertex to another community vertex. What is the best way to achieve it?

**Comment by mbrukman** [comment]
@RaulGuo — please only use GitHub for filing issues related to specific bugs or feature requests.

This question sounds like an open-ended discussion which is better suited for a forum; please see https://github.com/janusgraph/janusgraph/#community — either `janusgraph-users@` or the Gitter chat would be a better place to discuss this topic.
