### ISSUE TITLE
Single query to add 3 vertex and two edges of depth 2

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1197]
I have to create graph like this

(State) ----hasDistrict--->(District)------hasCity---->(City)

State, District, City => Vertices 
hasDistrict, hasCity=> Edges

State , District and City has respective properies of their own
how to write single query to create this graph?

**Comment by mbrukman** [comment]
@pra527vin — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the `janusgraph-users@` mailing list: https://github.com/janusgraph/janusgraph/#community .
