### ISSUE TITLE
how to speed up performance

### ISSUE THREAD

**Issue by greatsxm** [JanusGraph/janusgraph#1198]
Hi, everyone.
I have created a big graph which has 700 million vertics and 12 billion edges. A mixed index has been created on property 'degree'. The following query statement is executed very slowly. The index is not used in the query. Can anybody give me some advace to speed up its performance?
**g.V(7988832628960).both().dedup().has("degree", inside(0, 2000)).both().dedup().has("degree", inside(0, 2000)).count()**

**Comment by pluradj** [comment]
@greatsxm — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the `janusgraph-users@` mailing list: https://github.com/janusgraph/janusgraph/#community .
