### ISSUE TITLE
What Version is this?

### ISSUE THREAD

**Issue by AaronCH5** [JanusGraph/janusgraph#1202]
This tree can be found by searching information on github, but the files that come directly down without selecting the version at the time of downloading are different from those downloaded from the selected version.
![111](https://user-images.githubusercontent.com/24953071/42996811-4750646e-8c47-11e8-8fba-123d4b62afc3.png)
![222](https://user-images.githubusercontent.com/24953071/42996829-50d84984-8c47-11e8-9f3b-c003539bcb45.png)
![333](https://user-images.githubusercontent.com/24953071/42996863-6e38451a-8c47-11e8-9843-859b032df9cb.png)

**Comment by pluradj** [comment]
This is the commit in question... https://github.com/JanusGraph/janusgraph/commit/7457e1ca8945256560dbd214a19c1dde83b01fc1.

Here is the original PR https://github.com/JanusGraph/janusgraph/pull/1039
```
Merge pull request #1039 from twilmes/0.2-master-merge

Updates from 0.2
```

It was merged into `master` on April 30, 2018. That means this code would be in the `v0.3.0` release. Note that this PR is merging code forward from `0.2` into `master`, so this code is in the `v0.2.1` release also.

**Comment by AaronCH5** [comment]
@pluradj tks,but i see that it's different between 0.2.0 vs 0.2.1, but i can't find the config in 0.2.1,because it has http.auth...conf in 
![jg version](https://user-images.githubusercontent.com/24953071/43692918-c43f5584-995d-11e8-9c38-78c6929cbc03.png),but not contain in 0.2.0,so why? how to release this?
