### ISSUE TITLE
How to connect to Secure Elasticsearch for JanusGraph?

### ISSUE THREAD

**Issue by AaronCH5** [JanusGraph/janusgraph#1206]
Currently, ES is a useful username and password, so if I want to continue using ES as an index backend, how do I configure the corresponding parameters?
       That's all on the official website:
![1](https://user-images.githubusercontent.com/24953071/42992529-5fe3b0c8-8c3b-11e8-9664-57cb0cdca7de.png)

       I tried to look through the source code and found that there was such a parameter in the class:
![2](https://user-images.githubusercontent.com/24953071/42992495-499e0d72-8c3b-11e8-9c15-6518608f3921.png)
      so, I try do this:
![3](https://user-images.githubusercontent.com/24953071/42992582-8402a52c-8c3b-11e8-94ce-323377027856.png)
     but,it occurs error.
![4](https://user-images.githubusercontent.com/24953071/42992667-b30717a4-8c3b-11e8-8395-373922f32264.png)

Then, what should I do ?

**Comment by AaronCH5** [comment]
I see the version 0.3.0 for JG,but i can't find the config in docs.
For example:
     I can find the config in source code 
     
![jg conn](https://user-images.githubusercontent.com/24953071/43692792-dce4363c-995c-11e8-9cc8-df3c4bbfee15.png)
     But in doc i can't find it .
     
![jg doc](https://user-images.githubusercontent.com/24953071/43692811-1b134740-995d-11e8-8a10-1dbdf166a2da.png)
     
      Also in my project i can't load the pom.xml for jg 0.3.0, i can't find the pom in where.
      
![jg pom](https://user-images.githubusercontent.com/24953071/43692874-7d4119b0-995d-11e8-9e3d-baccc58b471a.png)

      So , how can i do this?

**Comment by AaronCH5** [comment]
@pluradj Can you help to release it? TKS

**Comment by pluradj** [comment]
Voting thread is on [`janusgraph-dev`](https://groups.google.com/d/msg/janusgraph-dev/9evIOVkGPRo/tSjg0lEgAAAJ).

@AaronCH5 — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the `janusgraph-users@` mailing list: https://github.com/janusgraph/janusgraph/#community .
