### ISSUE TITLE
Expecting PermanentLockingException : (Expected value mismatch for X: expected=Y vs actual=Z

### ISSUE THREAD

**Issue by graphdb2** [JanusGraph/janusgraph#1212]
Hello,

I try to verify the transaction model of janusgraph with hbase.

So I built an example where two gremlin consoles trying to update the same node and was expecting an exception as the value change between the read and the write but nothing happened.

**Gremlin console 1**
**Step 1**)

There is an index on identifiant
```
graph = JanusGraphFactory.open('conf/janusgraph-hbase.properties')
g = graph.traversal()
g.addV('test').property('identifiant', 1).property('from', 10)
g.tx().commit()
```

**Gremlin console 1**
**Step2**
`toUpdate = g.V().hasLabel('test').has("identifiant", 1).hasNot("to").next()`

**Gremlin console 2**
**Step3**
```
graph = JanusGraphFactory.open('conf/janusgraph-hbase.properties')
g = graph.traversal()
toUpdate = g.V().hasLabel('test').has("identifiant", 1).hasNot("to").next()
```

**Gremlin console 1**
**Step4**
toUpdate.property('to', 11)
g.tx().commit()

**Gremlin console 2**
**Step5**
toUpdate.property('to', 12)
g.tx().commit()

**Comment by twilmes** [comment]
Hi @graphdb2, JanusGraph transaction behavior is dependent on the behavior of the underlying storage engine. If I'm understanding you correctly, you're expecting the sort of behavior you'd see with strict serializable isolation where a read/written conflict would be caught on commit but let me know if I'm misunderstanding. HBase does not provide ACID transactions and Janus will not overlay them on top of it so this is expected behavior. I am currently working on a FoundationDB storage adapter that does provide strict serializability but it's still experimental. If you want to use HBase, you will have to maintain this isolation above the Janus level, for example, through the use of a single reader/writer.

**Comment by graphdb2** [comment]
Yes you are right but I thought hbase had a row level lock : https://blogs.apache.org/hbase/entry/apache_hbase_internals_locking_and

**Comment by twilmes** [comment]
I'm not an HBase expert, @jerryjch might have some better insight into this, but as I read it, the row write lock ensures the row isn't left in an "interleaved" state when concurrent writes happen. The MVCC on reads, prevents seeing the row in an inconsistent state when the data hasn't been fully written. Neither of those guarantees is designed to detect the case where you read a value, and then it changes when you go to write. They would need something beyond the MVCC they have defined to handle that scenario.

**Comment by graphdb2** [comment]
yes but this page say it can be done : https://docs.janusgraph.org/0.2.0/eventual-consistency.html

but nothing happened no exception.

```
mgmt = graph.openManagement()
to = mgmt.getPropertyKey('to')
mgmt.setConsistency(to, ConsistencyModifier.LOCK)
mgmt.commit()
```

**Comment by twilmes** [comment]
Aha, ok, I see what you're saying. Thanks for the sample schema. Your procedure does throw an exception with Cassandra as you have it written. I haven't tried with HBase though. What version of JanusGraph/HBase are you experiencing this with?

**Comment by graphdb2** [comment]
I am using hbase-1.2.6

**Comment by graphdb2** [comment]
I found out I have been caught again by this setting 


`storage.batch-loading=true `

I am getting the exception : Could not commit transaction due to exception during persistence

**Comment by twilmes** [comment]
Good catch, yes, that'll turn off internal checks. We good to close this one then?

**Comment by jerryjch** [comment]
It is all well said here.

**Comment by n5nk** [comment]
Is there an alternative other then enabling batch loading ?
