### ISSUE TITLE
Lucene index support Issue

### ISSUE THREAD

**Issue by ShiniIn** [JanusGraph/janusgraph#1215]
HI,
I was trying out some experiments in Janus graph (0.3.0) with Cassandra as storage and Lucene as backend engine. Basically what I did is I have created some properties and indexed them under a single mixed index using Lucene. Now when I update any single property in the vertex the index does not works properly for any attributes other than string type.

Earlier I had reported the issue on the google group. Details can be found here https://groups.google.com/forum/#!topic/janusgraph-users/y8oxz1KDZhw

Observations:
 I have installed a client to visualise the lucene indexing data. Now when I initially check for the keys in index all the fields are visible in the client. However when I try the same after partially updating the vertex. Only updated and string entries are visible in the client now. So I think there is some issue with  janus graph vertex update. 

Would anyone look into the matter??

**Comment by mad** [comment]
This issues is same as https://github.com/JanusGraph/janusgraph/issues/764

[Here](https://github.com/JanusGraph/janusgraph/pull/1645) fix for that, but not merged yet

**Comment by porunov** [comment]
Fixed by #1645
