### ISSUE TITLE
gremlin-groovy is not an available GremlinScriptEngine

### ISSUE THREAD

**Issue by graphnj** [JanusGraph/janusgraph#1217]
When use bin/gremlin-server.sh ./conf/xxxx.yaml start, the shell report following error:
```
Caused by: java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:263)
```

**Comment by FlorianHockmann** [comment]
Did you encounter this with JanusGraph version 0.3.0? Your `.yaml` config file would be helpful to see what could cause the exception.
One possible reason for this error is that you use a `.yaml` file that is not compatible with TinkerPop 3.3.z and therefore JanusGraph 0.3.0. The `scriptEngines` element should now look something like this:
```
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
```
[Source](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml#L8)
whereas before it looked like this:
```
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
scripts: [scripts/empty-sample.groovy]}}
```
[Source](https://github.com/JanusGraph/janusgraph/blob/a75802b3c17b1aaeda5d9b4446097d80906a5fe3/janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml#L10)

**Comment by graphnj** [comment]
@FlorianHockmann ,
Thanks for your reply, I use the yaml from conf/gremlin-server/gremlin-server.yaml, and diddnot use any old version yaml.  I'm a new user of janusgraph without any old config should be compatible.

The error may be caused in tinkerpop
```
engine.eval(initScript)
->scriptObject.run()   
```
and throw Exception report *No such property: graph for class: Script1* 
I think error for the line "globals << [g : graph.traversal()]" in empty-sample.groovy

thanks

**Comment by graphnj** [comment]
Error reason is :
I config using ES, but didnot start it, so xxx.properties could not be instantiated and will not be available in Gremlin Server, 
After starting ES, it looks like normal, thank you.

Close

**Comment by Ganaa01** [comment]
@graphnj What do you mean by starting ES?? I didn't get it! 

Thanks!

**Comment by RiderToha** [comment]
Facing the same issue when connecting with session: 
`:remote connect tinkerpop.server conf/remote.yaml **session**`

Without session it does not occur.

**Comment by FlorianHockmann** [comment]
@RiderToha (and @VINAYAK179 if you also still have this problem): Please create a new thread on [janusgraph-users](https://groups.google.com/g/janusgraph-users) where you describe your problem exactly with necessary steps to reproduce it. That would make it a lot easier to help you.
The original problem discussed in this issue was apparently a usage error where the graph could not be instantiated but your problem seems different. So we should discuss it separately.
