### ISSUE TITLE
Does Janusgraph have interfaces to query shortest paths?

### ISSUE THREAD

**Issue by huxiaoqing0704** [JanusGraph/janusgraph#1229]

**Comment by pluradj** [comment]
No. There are currently no shortest path algorithms built in, but you could follow this [Gremlin recipe](https://tinkerpop.apache.org/docs/current/recipes/#shortest-path).

@huxiaoqing0704 — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the janusgraph-users@ mailing list: https://github.com/janusgraph/janusgraph/#community .
