### ISSUE TITLE
Allow custom properties in ElasticSearchIndex

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#1242]
From thread from @porunov on [janusgraph-dev](https://groups.google.com/forum/#!topic/janusgraph-dev/xKSouClyIJs)

> I see that in the class "ElasticSearchIndex" in the method "pushMapping(String store, String key, KeyInformation information)" we ignore any custom properties from "KeyInformation information". 

> As for me it is a drawback because we can't use specific features from ElasticSearch like on-disk index sorting, changing `similarity` algorithms for specific fields, using multi-fields and so on.

**Comment by porunov** [comment]
@pluradj I think this issue can be closed because it is resolved.

**Comment by mbrukman** [comment]
Thanks, @porunov!
