### ISSUE TITLE
add documentation for PR workflow

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#1243]
include discussion on determining which branch to use and how to merge fixes up to master

**Comment by chupman** [comment]
I think this was resolved with #1376

**Comment by porunov** [comment]
I also think that this issue is resolved

**Comment by FlorianHockmann** [comment]
Seems pretty clear that this was fixed by that PR. I simply didn't see this issue when I created the PR.
So, I'm closing this. @pluradj: In case you don't agree, just re-open.
