### ISSUE TITLE
Key must have an order-preserving data type to be used as sort key -- UUID as key

### ISSUE THREAD

**Issue by darwinyip** [JanusGraph/janusgraph#1248]
I'm trying to build  an edge index using UUID v4 property:
`mgmt.buildEdgeIndex(edgeLabel, "index_edge_name", Direction.BOTH, Order.decr, uuidProperty)`
which gives the error:
`Key must have an order-preserving data type to be used as sort key`

Why is this not allowed? And are there any workarounds?

**Comment by pluradj** [comment]
Are you using JanusGraph 0.3.0? This issue was fixed with #948

**Comment by darwinyip** [comment]
Thanks. I was still using 0.2.1. Will test on 0.3.0.

**Comment by chupman** [comment]
closed as issues was fixed in JanusGraph 0.3.0. Please feel free to reopen if you are still encountering the issue in 0.30 or greater
