### ISSUE TITLE
Could not find a suitable index to answer graph query and graph scans are disabled

### ISSUE THREAD

**Issue by jfld** [JanusGraph/janusgraph#1258]
Could you please tell me how to solve this problem ?
Could not find a suitable index to answer graph query and graph scans are disabled

**Comment by pluradj** [comment]
These topics are discussed in the [indexing documentation](https://docs.janusgraph.org/latest/indexes.html). If you have `query.force-index=true` declared in your graph configuration, you need to create an index to query your data so it can avoid doing a whole graph scan.

@jfld — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the janusgraph-users@ mailing list: https://github.com/janusgraph/janusgraph/#community .
