### ISSUE TITLE
Create docs for JanusGraph GLV clients

### ISSUE THREAD

**Issue by debasishdebs** [JanusGraph/janusgraph#1276]
JanusGraph GLV clients have been in development since some time. Currently those drivers are available for Python and DotNet.

We will need to update the official JanusGraph docs to add a section for the same. 

A new Topic needs to be created after JanusGraph server, namely **JanusGraph Clients**. The topic will contain 2 section currently, one each for Python and DotNet. 

The docs will refer to Official JanusGraph DotNet repo for DotNet, and Python repo for Python. While the respective libs are hosted on their official channels (eg PyPi for Python) they will keep pointing to official repo. Once hosted, the docs needs to be updated.

Also, since Python GLV docs are available currently under readthedocs, they will need to add a section pointing to same.

**Comment by FlorianHockmann** [comment]
I guess we need to decide first whether we just want to include the docs in the main JanusGraph docs or whether they should be independent. The first approach would of course be easier to implement but we could only release new client docs when a new version of JanusGraph is released which is currently only every few months.
We [already discussed on the mailing list](https://groups.google.com/forum/#!topic/janusgraph-dev/8npH66hMFU0) about creating dedicated sections for the different languages like `docs.janusgraph.org/dotnet/x.y.z/index.html`.

**Comment by WolfgangFahl** [comment]
I never got janusgraph python glv  to work and the bug report #1826 is closed.  So what is the official way to make it work?

**Comment by WolfgangFahl** [comment]
I  don't know how this is solve now and why this ticket is closed? I never retried again given the situation.

**Comment by FlorianHockmann** [comment]
@WolfgangFahl You're talking about Python, but we still simply don't have a Python library for JanusGraph. So, there is also nothing we could document except for the official gremlin-python library and that is already documented here: https://docs.janusgraph.org/interactions/connecting/python/

We currently only have a library for .NET which is now documented: https://docs.janusgraph.org/master/interactions/connecting/dotnet/#janusgraphnet-for-janusgraph-specific-types-and-predicates

By the way, if you want to help improving the situation for Python, then contributions are of course welcome :-)
