### ISSUE TITLE
LogProcessorFramework `removeLogProcessor`/`shutdown` not working

### ISSUE THREAD

**Issue by Prakhar0409** [JanusGraph/janusgraph#1281]
## Description
LogProcessorFramework has method **removeLogProcessor**, which takes the log identifier as the parameter. This however is neither stopping nor removing the log processor. 

Possible reason could be that the `Map processorLogs` in StandardLogProcessorFramework.java, which is being used to remove the logprocessor, was never actually populated while building the log processor. 

## How to reproduce?
* Add a log processor with some log processor identifier
* Do some operation in janusgraph to see that the log processor is functional
* remove the logprocessor using removeLogProcessor method
* Do a operation again to find out that the log processor was not removed

**Comment by codemonk5** [comment]
Hi @galbash , the fix works fine. I (@Prakhar0409 ) just got stuck with the process for corporate CLA that kept delaying this. I have submitted a pull request towards this fix
