### ISSUE TITLE
Add static code analysis into our review process

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1287]
Adding a static code analysis tool to our review process would make reviews more efficient. Such a tool can find and comment on issues like unused code, too complex methods or deviations from the usual code style in a project. This allows reviewers to concentrate on more important issues that such a tool can't find.

I already [proposed this on the dev list](https://groups.google.com/forum/#!msg/janusgraph-dev/ZnevkmsFe_c/IZUbn8YnBAAJ) some time ago where I also described some requirements such a tool should fulfil. [Codacy](https://www.codacy.com/) was the only tool I could find that fulfils all requirements. It supports the languages that are important for us (Java, C#, Python, JavaScript / TypeScript), it has a good GitHub integration and it is free to use for open source projects.

I set up Codacy on my private fork of JanusGraph and my initial version of JanusGraph.Net which is currently in review to be added to JanusGraph:

- [Codacy dashboard for JanusGraph](https://app.codacy.com/project/FlorianHockmann/janusgraph/dashboard)
- [Codacy dashboard for the initial version of JanusGraph.Net](https://app.codacy.com/project/FlorianHockmann/janusgraph-dotnet/dashboard?branchId=8471319)

and I also tried out the review feature with a dummy PR which can be seen in FlorianHockmann/janusgraph#1. Codacy commented there directly on all issues it could find with the code that I tried to add with this PR.

I can't add our projects to Codacy as that requires more privileges. So, it would be good if someone from the TSC could handle that if there are no objections. Codacy simply needs access to the project and then we can decide how it should interact with PRs.

**Comment by FlorianHockmann** [comment]
Since [Codacy includes checkstyle](https://www.codacy.com/blog/codacy-integrates-with-checkstyle/), this would also resolve #726.

**Comment by debasishdebs** [comment]
@FlorianHockmann : Thanks for the idea. After your post, I actually introduced Codacy into my personal [drivers repo](https://app.codacy.com/project/debasishdebs/janusgraph-py/dashboard?branchId=9102382) and I'm slowly and slowly starting to like this tool. Though one drawback I've felt is that, in case of Python, not all the comments are useful. I've to go through each of them, and find barely 1/4-5 useful ones. 

Though that does takes me a bit more time to go through and accordingly resolve all the analysis, but then no tool is perfect tool, and anything which will make the life of reviewers a bit easy should always be welcome.

I would say, if we don't find any better and much more advanced tool in terms of issue findings, then it would be +1 from my side.

**Comment by FlorianHockmann** [comment]
Yes, there are definitely some false positives, but we can simply decide for some rules to disable them if they produce too many false positives or if we don't agree in general with the rule.

**Comment by chupman** [comment]
Even though Codacy includes checkstyle I think it would be good to still add it to maven to enable, or even enforce, local linting as well. Do you already have an .xml file with the correct rules for JanusGraph?

**Comment by FlorianHockmann** [comment]
> Even though Codacy includes checkstyle I think it would be good to still add it to maven to enable, or even enforce, local linting as well.

OK, then we should keep both issues separate.

> Do you already have an .xml file with the correct rules for JanusGraph?

No, I only enabled Codacy with default settings on my fork. I haven't looked into checkstyle itself yet.

**Comment by FlorianHockmann** [comment]
Codacy is now enabled for all repos. We'll use the initial [discussion on the dev list](https://groups.google.com/forum/#!topic/janusgraph-dev/ZnevkmsFe_c) to fine-tune its settings.
