### ISSUE TITLE
Geoshape point coordinates are stored wrongly in ElasticSearch

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#1291]
Right now JanusGraph stores `Geoshape` coordinates wrongly (checked `geo_point`). When we store `geo_point` coordinates in ElasticSearch we must use latitude as 1st parameter and longitude as 2nd parameter. Right now I see that they are swapped. That is why, if we are using ElasticSearch in combination with JanusGraph our `geo_distance` query will not work properly.

Class: `ElasticSearchIndex`
Method: `convertGeoshape(Geoshape geoshape, Mapping mapping)`
line: `new double[]{p.getLongitude(), p.getLatitude()}`

Also, I am not sure, but looking at the code I see that this problem is presented in all shapes of Geoshape class (point, box, circle, line, polygon).

The problem is that coordinates are already stored in ElasticSearch in the wrong format that is why if we fix this bug the release will be not compatible with the previous releases (reindex job should be executed on all indexes which use Geoshape).

**Comment by porunov** [comment]
I see in Geoshape deserializers (`GeoshapeGsonDeserializerV1d0` and `GeoshapeGsonSerializerV2d0`) that they expect longitude to be on the first place and latitude on the second. 
Lines:
`return Geoshape.point(f[1], f[0]);`
and
`shape = Geoshape.point(coordinates.get(1).doubleValue(), coordinates.get(0).doubleValue());`

Is it OK to just swap `1` and `0` indexes in Geoshape deserializers and swap `getLongitude()` with `getLatitude()` in `ElasticSearchIndex` or should we do the same in `Solr` and `Lucene` indexes?

**Comment by FlorianHockmann** [comment]
Why do you think that they are stored wrongly? JanusGraph takes coordinates in the form lat lng, but uses internally GeoJSON and WKT which use the form lng lat. This is a bit confusing, but it seems to me that it's used correctly everywhere.

> When we store geo_point coordinates in ElasticSearch we must use latitude as 1st parameter and longitude as 2nd parameter. Right now I see that they are swapped.

Where did you get that information? I just found this information [in the Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#input-structure):

> Shapes can be represented using either the GeoJSON or Well-Known Text (WKT) format.

So, it seems to me that JanusGraph is using the right format for Elasticsearch.

I also just tried it out with a small example and everything seems to work as expected:
```groovy
gremlin> mgmt = graph.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@9263c54
gremlin> location = mgmt.makePropertyKey('location').dataType(Geoshape.class).cardinality(Cardinality.SINGLE).make()
==>location
gremlin> mgmt.buildIndex('byLocation', Vertex.class).addKey(location).buildMixedIndex('search')
==>byLocation
gremlin> mgmt.commit()
==>null
gremlin> g.addV('god').property('name','test').property('location',Geoshape.point(-77,-160)).iterate()
gremlin> g.V().has('location',geoWithin(Geoshape.circle(-77, -160, 50)))
==>v[20608]
```

**Comment by porunov** [comment]
@FlorianHockmann Thank you a lot for investigating it! You are right, I didn't read the documentation carefully. I was reading this part, but forgot that we use `GeoJSON` style ([ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html)).
> Please note that string geo-points are ordered as lat,lon, while array geo-points are ordered as the reverse: lon,lat.
> 
> Originally, lat,lon was used for both array and string, but the array format was changed early on to conform to the format used by GeoJSON.

Thank you a lot for clarifying. It helped!
