### ISSUE TITLE
Last hbase region range wrong 

### ISSUE THREAD

**Issue by jxping** [JanusGraph/janusgraph#1292]
05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Found local key/row 
    partition KeyRange(left: 249-255-255-  6, right: 250-255-255-  5) on host graph-server-    06,16020,1538222446337
    05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Discarding remote graph-server-02,16020,1538222446481
    05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Discarding remote graph-server-01,16020,1538222447432
    05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Discarding remote graph-server-07,16020,1538222446668
    05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Discarding remote graph-server-03,16020,1538222446893
    05:35:13 DEBUG org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Found local key/row partition KeyRange(left: 254-255-255-  1, right:   0-  0-  0-  0) on host graph-server-06,16020,1538222446337

I have 255 region of hbase 
at the last region of hbase the left to int is bigger than right to int ,this make a wrong key range ,then 
id assign of this node will get a wrong localkeyparition all of this node's id will be the last region of 255 
if you can understand clearly contact me and i will show you the full stack 

    05:35:13 INFO  org.janusgraph.graphdb.database.idassigner.VertexIDAssigner  - Setting individual partition bounds: [[255,0)%256]
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [0] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [1] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [2] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [3] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [4] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [5] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [6] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [7] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [8] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [9] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [10] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [11] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [12] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [13] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [14] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [15] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [16] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [17] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [18] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [19] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [20] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [21] to: 255
    05:35:13 DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy  - Setting partition at index [22] to: 255

**Comment by jxping** [comment]
my version is 0.2.1

**Comment by jxping** [comment]
code of PartitionIDRange
public static List<PartitionIDRange> getIDRanges(final int partitionBits, final List<KeyRange> locals) {
        Preconditions.checkArgument(partitionBits>0 && partitionBits<(Integer.SIZE-1));
        Preconditions.checkArgument(locals!=null && !locals.isEmpty(),"KeyRanges are empty");
        final int partitionIdBound = (1 << (partitionBits));
        final int backShift = Integer.SIZE-partitionBits;
        List<PartitionIDRange> partitionRanges = Lists.newArrayList();
        for (KeyRange local : locals) {
            Preconditions.checkArgument(local.getStart().length() >= 4);
            Preconditions.checkArgument(local.getEnd().length() >= 4);
            if (local.getStart().equals(local.getEnd())) { //Start=End => Partition spans entire range
                partitionRanges.add(new PartitionIDRange(0, partitionIdBound, partitionIdBound));
                continue;
            }

            int startInt = local.getStart().getInt(0);
            int lowerID = startInt >>> backShift;
            assert lowerID>=0 && lowerID<partitionIdBound;
            //Lower id must be inclusive, so check that we did not truncate anything!
            boolean truncatedBits = (lowerID<<backShift)!=startInt;
            StaticBuffer start = local.getAt(0);
            for (int i=4;i<start.length() && !truncatedBits;i++) {
                if (start.getByte(i)!=0) truncatedBits=true;
            }
            if (truncatedBits) lowerID+=1; //adjust to make sure we are inclusive
            int upperID = local.getEnd().getInt(0) >>> backShift; //upper id is exclusive
            //Check that we haven't jumped order indicating that the interval was too small
            if ((local.getStart().compareTo(local.getEnd())<0 && lowerID>=upperID)) {
                discardRange(local);
                continue;
            }
            lowerID = lowerID%partitionIdBound; //ensure that lowerID remains within range
            // if(lowerID>=upperID) then .....
             if (lowerID==upperID) { //After re-normalizing, check for interval colision
                discardRange(local);
                continue;
            }
            partitionRanges.add(new PartitionIDRange(lowerID, upperID, partitionIdBound));
        }
        return partitionRanges;
    }

**Comment by jxping** [comment]
who will fix this issue?
public int getRandomID() {
        //Compute the width of the partition...
        int partitionWidth;
        if (lowerID < upperID) partitionWidth = upperID - lowerID; //... for "proper" ranges
        else partitionWidth = (idUpperBound - lowerID) + upperID; //... and those that "wrap around"
        Preconditions.checkArgument(partitionWidth > 0, partitionWidth);
        return (random.nextInt(partitionWidth) + lowerID) % idUpperBound;
    }

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
