### ISSUE TITLE
Add ObjectNode and ArrayNode serializers

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#1293]
Right now, if we want to set custom properties for mappings in ElasticSearch we should use the next technique:
`Parameter.of(ParameterType.customParameterName("boost"), 5)`

But if we need to set a more complex value (json objects) we are unable to do it. For example, there is no way right now to set custom fields parameter through the `Parameter`. I.e we can't set objects like this:
```
"fields": {
    "exact": {
        "type": "text",
        "analyzer": "standard",
        "similarity": "boolean",
        "boost": 100
    }
}
```

I think it would be good to add support for json serializers.

**Comment by jxping** [comment]
you can do this yourself , just remove janusgraph's elasticsearch index and make your own index with your analyzer
