### ISSUE TITLE
Janusgraph property and elasticsearch not working completely

### ISSUE THREAD

**Issue by shubhamparikh927** [JanusGraph/janusgraph#1297]
Hey Guys,
I have added mixed index in janusgraph to support fulltext search with elasticsearch.

I have mixed index like:
bySynonymLowerIndex = mgmt.buildIndex("bySabSynonym", Vertex.class)
					.addKey("synonymlower", Mapping.TEXTSTRING.asParameter())
					.addKey("sabindex", Mapping.TEXTSTRING.asParameter())
					.buildMixedIndex("search");

I am able to load data into elasticsearch engine.
Also I am able to execute the query successfully.

The issue I am facing is when I hit query :

 g.V().has('code','abc').valueMap()
==>{str=[some text], lastUpdated=[2017-09-24 15:48:17.0], code=[abc], sab=[sab], sabindex=[sabindex], tty=[[CD]], synonymlower=[[some tex]]}

I am getting the result successfully,
But when I try to search with synonymlower and code 
g.V().has('synonymlower', textContains('some text')).has('code','abc').valueMap()

At that time I am getting no result.Though data is present in graph and elastic
And another scenario is same query with different synonymlower and code works successfully.
I rebuild the graph multiple times but not getting positive results.

Thanks in advance for your help.

**Comment by aigod** [comment]
I met the same problem and have no idea.
https://github.com/JanusGraph/janusgraph/issues/1298
