### ISSUE TITLE
use elasticsearch as index backend still warn

### ISSUE THREAD

**Issue by aigod** [JanusGraph/janusgraph#1298]
I use janusgraph 0.3.1, storage backend is hbase , index backend is elasticsearch, everything seems ok。
But after I create an mixed index, search graph still warns:

gremlin> mgmt.getGraphIndex('byTypeAndCodeIndex').getIndexStatus(mgmt.getPropertyKey('code'));
==>ENABLED
gremlin> 
gremlin> g.V().has('code','AUS')
20:47:04 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [(code = AUS)]. For better performance, use indexes
==>v[4104]
gremlin> 

It seems that the index didn't work, but why?

**Comment by pluradj** [comment]
From the [indexing docs](https://docs.janusgraph.org/latest/indexes.html#graph-indexes)

> Graph indexes built against property keys that are already in use without being constrained to a newly created label require the execution of a [reindex procedure](https://docs.janusgraph.org/latest/index-admin.html#reindex) to ensure that the index contains all previously added elements.

**Comment by aigod** [comment]
I have reindexed before executing quering, and it is still warning

graph = JanusGraphFactory.open("conf/my-hbase-es.properties");
graph.io(graphml()).readGraph('data/air-routes-latest.graphml');

mgmt = graph.openManagement()
type = mgmt.getPropertyKey("type")
code = mgmt.getPropertyKey("code")
mgmt.buildIndex('byTypeAndCodeIndex',Vertex.class).addKey(type).addKey(code).buildMixedIndex("search")
mgmt.commit()
ManagementSystem.awaitGraphIndexStatus(graph, 'byTypeAndCodeIndex').call()

mgmt = graph.openManagement();
mgmt.updateIndex(mgmt.getGraphIndex('byTypeAndCodeIndex'), SchemaAction.REINDEX).get();
mgmt.commit()

g = graph.traversal();
g.V().has('type','airport').has('code','TTE');

///// still warn
mgmt = graph.openManagement();
mgmt.updateIndex(mgmt.getGraphIndex("byTypeAndCodeIndex"),SchemaAction.ENABLE_INDEX).get()
mgmt.commit()

mgmt=graph.openManagement();
mgmt.getGraphIndex('byTypeAndCodeIndex').getIndexStatus(mgmt.getPropertyKey('code'));
==>ENABLED
mgmt.commit()

graph.close()
graph = JanusGraphFactory.open("conf/my-hbase-es.properties");
g = graph.traversal();

gremlin> g.V().has('code','AUS')
20:47:04 WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [(code = AUS)]. For better performance, use indexes
==>v[4104]


I have repeated many time, it still warn, It seems that the mixed  index didn't work。my data look like:

<node id='1'>
    <data key='labelV'>airport</data>
    <data key='type'>airport</data>
    <data key='code'>ATL</data>
    <data key='icao'>KATL</data>
    <data key='city'>Atlanta</data>
    <data key='desc'>Hartsfield - Jackson Atlanta International Airport</data>
    <data key='region'>US-GA</data>
    <data key='runways'>5</data>
    <data key='longest'>12390</data>
    <data key='elev'>1026</data>
    <data key='country'>US</data>
    <data key='lat'>33.6366996765137</data>
    <data key='lon'>-84.4281005859375</data>
  </node>

Looking forward to your response, thank you.

**Comment by pluradj** [comment]
In order to match the index that you defined, you need a query that includes `type` and `code`. Your example query `g.V().has('code','AUS')` only includes `code`.

**Comment by Dalen-fly** [comment]
我知道怎么回事。
https://docs.janusgraph.org/v0.3/index-backend/search-predicates/
需要使用Predicate，查询时才会使用索引，比如textContains（）、eq() ,用法如下：
g.E().has("reason", textContains("loves"))
g.E().has("reason", eq("loves")) 
// 想用 eq("loves") 的话，这里需要在建索引时指定类型为String   .addKey(reason,Mapping.String.asParameter())
不指定的话，默认的类型是Text, 不能进行eq（）查询，详见https://docs.janusgraph.org/v0.3/index-backend/text-search/
