### ISSUE TITLE
How to compile and build the system from source code

### ISSUE THREAD

**Issue by oushu1liwenhui1** [JanusGraph/janusgraph#1304]
I compiled the code by using this command：
mvn clean install
And how to make it like the releases?What shall I to do next? 

THX

**Comment by pluradj** [comment]
This is covered in [BUILDING.md](https://github.com/JanusGraph/janusgraph/blob/v0.3.1/BUILDING.md)

> To build the distribution archive:
```
mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true
```
> This command generates the distribution archive in `janusgraph-dist/janusgraph-dist-hadoop-2/target/janusgraph-$VERSION-hadoop2.zip`

@oushu1liwenhui1 -- please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the janusgraph-users@ mailing list: https://github.com/janusgraph/janusgraph/#community .
