### ISSUE TITLE
Mitigate dependencies on software with non-permissive licenses

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#132]
Work being done in PR #137 revealed the following:

- [x] org.acplt:oncrpc:1.0.7 - LGPL
- [x] com.vividsolutions:jts:1.13 - LGPL
- [x] com.github.stephenc.high-scale-lib:high-scale-lib:1.1.4 - Public Domain
- [x] org.tukaani:xz:1.0 - Public Domain
- [x] org.reflections:reflections:0.9.9-RC1 - WTFPL

**Comment by pluradj** [comment]
Berkeley DB JE license was changed to Apache in version 7.3.7, see https://github.com/JanusGraph/janusgraph/issues/100

**Comment by amcp** [comment]
@pluradj great, removing.

**Comment by ptgoetz** [comment]
JSONP should be okay since we are only including it in binary form (we would select CDDL in the LICENSE file).

Here's the relevant info for how Apache handles these types of licenses, also known as "Category B": https://www.apache.org/legal/resolved#category-b

**Comment by amcp** [comment]
Completing #133 and #79 will address the JTS dependency

**Comment by trixpan** [comment]
xz is also used by other ASL projects including Apache Commons - Compress and Apache Tika

**Comment by sjudeng** [comment]
It looks like maybe we can close this issue out? #186 mitigated the oncrpc dependency and JTS is fully optional at this point as well (#400 resolved the last remaining issue I'm aware of).

**Comment by pluradj** [comment]
I think so. I took a look again at the results of `mvn project-info-reports:dependencies`. It looks pretty clean, even with the new code in `janusgraph-codepipelines-ci`.

**Comment by amcp** [comment]
looks good, closing
