### ISSUE TITLE
No configuration to connect to cassandra with two-way SSL

### ISSUE THREAD

**Issue by daniesilamdocs** [JanusGraph/janusgraph#1324]
It should be possible to connect a janusgraph client to a cassandra cluster which is set up with `require_client_auth: true` . Currently, the janusgraph configuration supports setting `storage.cassandra.ssl.truststore` parameters, but not for keystore.

This was tested with janusgraph 0.2.0 and the `cassandra` backend, but after reviewing the code it appears to be the same with janusgraph 0.3.1 and the `cql` backend.

Is there some configuration I'm missing or would this be a new feature?

**Comment by hardikhhh1** [comment]
I am facing the same problem.

**Comment by callajd** [comment]
We ran into this issue specifically for CQL. We'll push the patch upstream once my organization gets the CCLA sorted.

Our fix only addresses CQL and not Cassandra, so I'm not sure if we prefer separate issues for the two or not.  If so, let me know and I'll split the CQL issue out on its own.

**Comment by FlorianHockmann** [comment]
@callajd The Cassandra backend will be removed in a future release of JanusGraph as Thrift is already deprecated for Cassandra and support for it will also be removed completely in a future Cassandra release, so it's not necessary to add such a new feature to that backend.
