### ISSUE TITLE
When creating a graph, report the following error ：java.lang.IllegalArgumentException: Must provide vertex id.The janusgraph version is 0.3.0

### ISSUE THREAD

**Issue by lmcrazy** [JanusGraph/janusgraph#1328]
Please help to have a look, thanks!
I want to use a user-defined ID,I've been configured for  @initialization.But it not work.
.My config is .
![image](https://user-images.githubusercontent.com/9508140/49197894-bd9e9f00-f3cb-11e8-877b-6cd845157c50.png)

My gremlin is 

`map = new HashMap<String, Object>();
map.put("storage.backend","hbase");
map.put("storage.hostname","172.16.x.x");
map.put("graph.set-vertex-id",true);
map.put("graph.graphname", "gtest");
ConfiguredGraphFactory.createConfiguration(new MapConfiguration(map));
`

The following error :
![image](https://user-images.githubusercontent.com/9508140/49197845-76181300-f3cb-11e8-8fe0-02e528382eee.png)

**Comment by chupman** [comment]
you set graph.set-vertex-id to true which means you told JanusGraph you would provide the ids for all vertices. I would reccomend leaving it as false. Also please ask usage, configuration, and general questions in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph.
