### ISSUE TITLE
Mark JTS as optional in janusgraph-solr and update docs

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#133]
JTS is currently a non-optional dependency in janusgraph-solr and is distributed with JanusGraph (and previously Titan) releases. What could be done is to mark it as optional in the pom.xml files so it's available for tests and users with requirements for relevant features (Solr, Geoshapes, etc.) can manually add it to their lib directory. Docs also need to be updated to instruct users to manually add the dependency.

From @sjudeng - good catch:
Looks like the longer term solution might be a new Eclipse Foundation [project aiming to replace JTS](https://www.locationtech.org/projects/technology.jts), ([repo](https://github.com/locationtech/jts), [proposal](https://www.locationtech.org/proposals/jts-topology-suite)). It's being developed by LocationTech, who also develop Spatial4j, through-which the JTS dependency comes in to Solr/JanusGraph. I'd guess the roadmap is for a stable new-JTS release and then a Spatial4j update/release migrating to same, at which point JanusGraph could update as well (likely involving a Solr version upgrade). I don't think a full migration in JanusGraph would be possible until Spatial4j and Solr were updated to use JTS 2. The good news is the core Spatial4j developer, who I think also is a core contributor on the Solr spatial connectors, has been active on the JTS 2 mailing list so he is at least aware of the effort.

**Comment by pluradj** [comment]
I looked around at some other projects: [Apache Ignite](https://github.com/apache/ignite/tree/master/modules/geospatial) uses a Maven profile to handle it, and [Elasticsearch](https://github.com/elastic/elasticsearch/blob/v1.5.2/pom.xml#L179) marks it as optional.

**Comment by twilmes** [comment]
Resolved by #189.
