### ISSUE TITLE
Is there a way to convert cypher to Gremlin 

### ISSUE THREAD

**Issue by mingjinc** [JanusGraph/janusgraph#1332]
we are using neo4j community as graph database. met the problem of limitation of cluster, hot-backup. wonder to switch to janusgraph, but we have lots of cypher statement before, is there a good way for us to convert to Gremlin language which is supported by janusGraph?

**Comment by mbrukman** [comment]
For future reference, this type of open-ended question is best suited for the janusgraph-users@ mailing list.

That said, you probably want to look at https://github.com/opencypher/cypher-for-gremlin, specifically this directory: https://github.com/opencypher/cypher-for-gremlin/tree/master/translation which says:

> # Cypher to Gremlin Translation
>
> The translation module provides facilities to:
>
> * parse Cypher queries using the Cypher frontend,
> * produce a translation to Gremlin,
> * transform results to a format that is accepted by a Gremlin Server-based database [...]
