### ISSUE TITLE
Update Hbase docs: storage.hbase-config is now storage.hbase.ext

### ISSUE THREAD

**Issue by kottmann** [JanusGraph/janusgraph#134]
The documentation explains how to pass Hbase configuration settings through JanusFactory to HBase
in section 16.2:
http://docs.janusgraph.org/0.1.0-SNAPSHOT/hbase.html

"By prefixing the respective HBase configuration option with storage.hbase-config in the Janus configuration it will be passed on to HBase at initialization time."

I tried this, looked it up in the code and came to the conclusion that the property name changed to "storage.hbase.ext". The documentation should be updated accordingly.

**Comment by jerryjch** [comment]
Fixed by PR #135
