### ISSUE TITLE
Do you have plans to support MySQL?

### ISSUE THREAD

**Issue by htpbackup** [JanusGraph/janusgraph#1340]
Support for various storage backends but without Relational DBMS such as MySQL.

**Comment by porunov** [comment]
You should ask such questions here: https://groups.google.com/forum/#!forum/janusgraph-users . Issues are used only for bug reports and feature requests.

Is there some features you are looking for in MySQL which might be useful for janusgraph?

**Comment by htpbackup** [comment]
Sorry but i think that's a feature request. Many systems have already deployed MySQL, and I don't want to install any more databases for convenience.

**Comment by chupman** [comment]
JanusGraph is opensource and we accept pull requests. To better answer your question, I am not currently aware of any efforts to add MySQL as a storage backend.

**Comment by htpbackup** [comment]
thx
