### ISSUE TITLE
Dependency BerkleyJE not found

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1344]
Central repository contain only 18.3.12:

![image](https://user-images.githubusercontent.com/56705/49933140-f2d2e300-fedb-11e8-9adc-09be9195e1f8.png)

![image](https://user-images.githubusercontent.com/56705/49934051-64ac2c00-fede-11e8-9dcd-e69091d4ed00.png)

**Comment by pluradj** [comment]
It is hosted on the Oracle release repository, see the reference in the [`pom.xml`](https://github.com/JanusGraph/janusgraph/blob/v0.3.1/pom.xml#L165)
