### ISSUE TITLE
Add Tom Sawyer graph database browser to visualization category

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#1345]
Per [Tom Sawyer Software post on Twitter](https://twitter.com/TSawyerSoftware/status/1070793046818725888):

> #TSPerspectives 8.2.2 is now available! This release offers @JanusGraph and @StardogHQ support, large graph performance boost, improved #XML data integration, and more. http://bit.ly/2BW1UvM  #JanusGraph #Stardog

We should add them to the list of visualization tools in `README.md` that are compatible with JanusGraph.

**Comment by FlorianHockmann** [comment]
Fixed with a [CTR commit](https://github.com/JanusGraph/janusgraph/commit/fb1c633849ddffc27dd370b9dee4fada1154e7d9). I linked their [product page](https://www.tomsawyer.com/perspectives/) as that describes the product and at least shows our logo.
