### ISSUE TITLE
Property datatype not checked

### ISSUE THREAD

**Issue by leafty** [JanusGraph/janusgraph#136]
In the [documentation (ch5)](http://docs.janusgraph.org/0.1.0-SNAPSHOT/schema.html#_property_key_data_type), it reads that "Use dataType(Class) to define the data type of a property key. JanusGraph will enforce that all values associated with the key have the configured data type and thereby ensures that data added to the graph is valid."

However, while playing around with JanusGraph, I've found that datatypes are not enforced.

```sh
./bin/gremlin.sh

[...]

gremlin> graph = JanusGraphFactory.open('conf/janusgraph-berkeleyje-es.properties')
==>standardjanusgraph[berkeleyje:[...]/janusgraph/conf/../db/berkeley]
gremlin> GraphOfTheGodsFactory.load(graph)
==>null
gremlin> mgmt = graph.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@23e86863
gremlin> name = mgmt.getPropertyKey('name')
==>name
gremlin> name.dataType()
==>class java.lang.String
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[berkeleyje:[...]/janusgraph/conf/../db/berkeley], standard]
gremlin> tx = g.tx()
==>org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction@1618c98a
gremlin> g.addV().property('name', [1,'abc'])
==>v[8336]
gremlin> tx.commit()
==>null
```

After restarting the gremlin shell:

```sh
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-berkeleyje-es.properties')
==>standardjanusgraph[berkeleyje:[...]/janusgraph/conf/../db/berkeley]
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[berkeleyje:[...]/janusgraph/conf/../db/berkeley], standard]
gremlin> g.V().has('name', [1, 'abc'])
==>v[8336]
gremlin> g.V(8336).valueMap()
==>[name:[[1, abc]]]
```

In the [addProperty](https://github.com/JanusGraph/janusgraph/blob/01fc5b66725443a67e549be6a05c54e71eec655a/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java#L723) method, I see that cardinality and index constraints are checked, but the datatype is not. Maybe it could be done there?

**Comment by pluradj** [comment]
The value `[1, 'abc']` was coerced into a `String` with value `"[1, 'abc']"`. You can check its data type with `g.V(8336).properties('name').value().next().getClass()`.

**Comment by leafty** [comment]
Ok, so I've seen [here](https://github.com/JanusGraph/janusgraph/blob/01fc5b66725443a67e549be6a05c54e71eec655a/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java#L573-L599) that serializers associated to the datatype are responsible for the type conversion.

From the wording of the documentation, I thought it would be more strict on types and I guess it can be helpful to allow things like `g.V().next().property('age', 52L)` to not throw an error while `age` is typed as `Integer`.

However there might be cases where this could draw some confusion:
```sh
gremlin> x = new LinkedHashSet()
gremlin> x.add(4)
==>true
gremlin> x.add(5)
==>true
gremlin> y = new LinkedHashSet()
gremlin> y.add(5)
==>true
gremlin> y.add(4)
==>true
gremlin> g.V(8336).property('name', x)
==>v[8336]
gremlin> g.V().has('name', x)
==>v[8336]
gremlin> g.V().has('name', y)
gremlin> x == y
==>true
gremlin> x.toString()
==>[4, 5]
gremlin> y.toString()
==>[5, 4]
```

It might be a good idea to mention the conversion by serializers in the documentation.

Also, looking [here](https://github.com/JanusGraph/janusgraph/blob/01fc5b66725443a67e549be6a05c54e71eec655a/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java#L584-L592), the original exception is not propagated.
