### ISSUE TITLE
Could not re-enable or remove a composite index

### ISSUE THREAD

**Issue by oushu1liwenhui1** [JanusGraph/janusgraph#1363]
hello,there are two problem.
first,I disabled a composite index inorder to remove it ,but it can't be removed and the result is "Update action [REMOVE_INDEX] cannot be invoked for index with status [INSTALLED]"
second ,when I tried to re-enable the index ,it showed "Update action [ENABLE_INDEX] cannot be invoked for index with status [INSTALLED]",so I try to register it but failed.
Is it a bug or I did not operate it correctly.
thanks

**Comment by FlorianHockmann** [comment]
Take a look at [this diagram about the lifecycle of an index](https://github.com/JanusGraph/janusgraph/wiki/Indexing). It shows that the only allowed actions for an index which is in the status `INSTALLED` are `REGISTER_INDEX` and `DISABLE_INDEX`. You can only remove the index after it has been already disabled.

Please ask questions like these in the future on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users). We really only use GitHub issues for bug reports or feature requests.
