### ISSUE TITLE
incorrect configuration example in CFG docs

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1372]
In the [CFG docs](
https://docs.janusgraph.org/latest/configuredgraphfactory.html#configuring-JanusGraph-server-for-configuredgraphfactory)

`gremlin.graph=org.janusgraph.core.JanusGraphFactory`
should be:
`gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory`

I noticed it because of a user reporting difficultly with configuration in the [user group](https://groups.google.com/forum/#!topic/janusgraph-users/w2_qMchATnw)

If anyone wanted to try out contributing this would be a great issue to start out with and learn the process. If no one takes it before the 0.2.3 release I'll make the update.

**Comment by jgolatkar** [comment]
hi @chupman .I would like to work on this issue. How should I proceed to make this change?

**Comment by chupman** [comment]
Hi @jgolatkar. The first place to start is the [Contributing page](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md). Which will fist point you to the [legal page](https://github.com/JanusGraph/legal) that contains links to the corporate CLA and [individual CLA](https://github.com/JanusGraph/legal/blob/master/JanusGraph_ICLA_1.0.pdf) forms. You'll need to fill one of those out (probably individual), scan it, and email it to  janusgraph-cla (at) googlegroups.com.

Once you have your CLA setup you can just follow the instructions in [Contributing](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) to clone the repo, setup a fork, and submit a PR. This change will target the 0.2 branch and then later merged into master.  Once a have the CLA and open a PR we'd work through any remaining questions or issues in the PR. 

If you have any questions feel free to reach out.

**Comment by jgolatkar** [comment]
Thanks! I'll start with the CLA process and will let you know if I
encounter any difficulty with the PR or have any questions.

**Comment by porunov** [comment]
@chupman I think we should start preparing soon for `0.2.3`. Will you be able to make an update?

**Comment by chupman** [comment]
@porunov this should only be a 5-10 minute PR. I'll put it in at the end of the week if no one wants to take it.

**Comment by chupman** [comment]
fixed in #1502
