### ISSUE TITLE
org.janusgraph.graphdb.management.utils.ConfigurationManagementGraphNotEnabledException: Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.

### ISSUE THREAD

**Issue by cyckax** [JanusGraph/janusgraph#1382]
Hi

I've followed steps as the doc said and I run the server like this bin/gremlin-server.sh conf/gremlin-server/socket-gremlin-server.yaml

my socket-gremlin-server.yaml looks like following:
host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphManager: org.janusgraph.graphdb.management.JanusGraphManager
graphs: {
  graph: conf/gremlin-server/janusgraph-hbase-es.properties,
  ConfigurationManagementGraph: conf/gremlin-server/JanusGraph-configurationmanagement.properties 
}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  # Older serialization versions for backwards compatibility:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 10000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536

and My JanusGraph-configurationmanagement.properties looks like 

gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=hbase
graph.graphname=ConfigurationManagementGraph
storage.hostname=host1,host2,host3,host4,host5
storage.port=2181

So I think I have already add the key name ConfigurationManagementGraph in yaml file, and why I still has this kind of problems??

![image](https://user-images.githubusercontent.com/9485649/51376567-9c446e80-1b43-11e9-8d02-ac58e803bcbe.png)

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by jsndh-pm** [comment]
> ve already add the key name ConfigurationManagementGraph in yaml file, and why I still has this kind of problems??



> Hi
> 
> I've followed steps as the doc said and I run the server like this bin/gremlin-server.sh conf/gremlin-server/socket-gremlin-server.yaml
> 
> my socket-gremlin-server.yaml looks like following:
> host: 0.0.0.0
> port: 8182
> scriptEvaluationTimeout: 30000
> channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
> graphManager: org.janusgraph.graphdb.management.JanusGraphManager
> graphs: {
> graph: conf/gremlin-server/janusgraph-hbase-es.properties,
> ConfigurationManagementGraph: conf/gremlin-server/JanusGraph-configurationmanagement.properties
> }
> scriptEngines: {
> gremlin-groovy: {
> plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
> org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
> serializers:
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
> 
> # Older serialization versions for backwards compatibility:
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
>       processors:
> 
>     * { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
> 
>     * { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
>       metrics: {
>       consoleReporter: {enabled: true, interval: 180000},
>       csvReporter: {enabled: true, interval: 10000, fileName: /tmp/gremlin-server-metrics.csv},
>       jmxReporter: {enabled: true},
>       slf4jReporter: {enabled: true, interval: 180000},
>       gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
>       graphiteReporter: {enabled: false, interval: 180000}}
>       maxInitialLineLength: 4096
>       maxHeaderSize: 8192
>       maxChunkSize: 8192
>       maxContentLength: 65536
>       maxAccumulationBufferComponents: 1024
>       resultIterationBatchSize: 64
>       writeBufferLowWaterMark: 32768
>       writeBufferHighWaterMark: 65536
> 
> 
> and My JanusGraph-configurationmanagement.properties looks like
> 
> gremlin.graph=org.janusgraph.core.JanusGraphFactory
> storage.backend=hbase
> graph.graphname=ConfigurationManagementGraph
> storage.hostname=host1,host2,host3,host4,host5
> storage.port=2181
> 
> So I think I have already add the key name ConfigurationManagementGraph in yaml file, and why I still has this kind of problems??
> 
> ![image](https://user-images.githubusercontent.com/9485649/51376567-9c446e80-1b43-11e9-8d02-ac58e803bcbe.png)



> Hi
> 
> I've followed steps as the doc said and I run the server like this bin/gremlin-server.sh conf/gremlin-server/socket-gremlin-server.yaml
> 
> my socket-gremlin-server.yaml looks like following:
> host: 0.0.0.0
> port: 8182
> scriptEvaluationTimeout: 30000
> channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
> graphManager: org.janusgraph.graphdb.management.JanusGraphManager
> graphs: {
> graph: conf/gremlin-server/janusgraph-hbase-es.properties,
> ConfigurationManagementGraph: conf/gremlin-server/JanusGraph-configurationmanagement.properties
> }
> scriptEngines: {
> gremlin-groovy: {
> plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
> org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
> org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
> serializers:
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
> 
> # Older serialization versions for backwards compatibility:
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
> 
>     * { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
>       processors:
> 
>     * { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
> 
>     * { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
>       metrics: {
>       consoleReporter: {enabled: true, interval: 180000},
>       csvReporter: {enabled: true, interval: 10000, fileName: /tmp/gremlin-server-metrics.csv},
>       jmxReporter: {enabled: true},
>       slf4jReporter: {enabled: true, interval: 180000},
>       gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
>       graphiteReporter: {enabled: false, interval: 180000}}
>       maxInitialLineLength: 4096
>       maxHeaderSize: 8192
>       maxChunkSize: 8192
>       maxContentLength: 65536
>       maxAccumulationBufferComponents: 1024
>       resultIterationBatchSize: 64
>       writeBufferLowWaterMark: 32768
>       writeBufferHighWaterMark: 65536
> 
> 
> and My JanusGraph-configurationmanagement.properties looks like
> 
> gremlin.graph=org.janusgraph.core.JanusGraphFactory
> storage.backend=hbase
> graph.graphname=ConfigurationManagementGraph
> storage.hostname=host1,host2,host3,host4,host5
> storage.port=2181
> 
> So I think I have already add the key name ConfigurationManagementGraph in yaml file, and why I still has this kind of problems??
> 
> ![image](https://user-images.githubusercontent.com/9485649/51376567-9c446e80-1b43-11e9-8d02-ac58e803bcbe.png)
--------------------------------------------------------------------------

You also need to type this instruction in the gremlin command line:

      gremlin>  :remote console     # This part is necessary to send all commands to remote server

-------------------------------------------------------------------------------------
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
==>Configured localhost/127.0.0.1:8182, localhost/0:0:0:0:0:0:0:1:8182-[24641f23-41f0-4ee1-9bb7-1211c4305cab]

gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182, localhost/0:0:0:0:0:0:0:1:8182]-[24641f23-41f0-4ee1-9bb7-1211c4305cab] - type ':remote console' to return to local mode

**Comment by jsndh-pm** [comment]
By the way, I get the that exception, but when I try to do the same through Java Driver. Does anyone have any idea about it ?

I meant if someone has a COMPLETE Java example (not only small fragments of source code like official documentation), because I've been trying to use this database but It's almost impossible ... A lots of issues and a tiny REAL documentation :'(

**Comment by ChenZhaobin** [comment]
@cyckax  did you solved this issue ,I met with the same problem,and cannot find a way out for 3 days ,although I belive I have configured following website docs

**Comment by sridhar34** [comment]
I am getting same error, can you please let me know how did you resolve this issue
