### ISSUE TITLE
How to create Vertex and Edge if not existed in 1 query gremlin

### ISSUE THREAD

**Issue by thangdc94** [JanusGraph/janusgraph#1385]
I find the following code to create edge if it has not existed yet.

```
g.V().hasLabel("V1")
.has("userId", userId).as("a")
.V().hasLabel("V1").has("userId", userId2)
.coalesce(
        bothE("link").where(outV().as("a")),
        addE("link").from("a")
)
```
It works fine but I want to create both vertices and edge if they are not existed in 1 query.

I try the following code with new graph, it just create new vertices but no relation between them.

```
g.V().hasLabel("V1")
.has("userId", userId).fold()
.coalesce(
        unfold(),
        addV("V1").property("userId", userId1)
).as("a")
.V().hasLabel("V1").has("userId", userId2).fold()
.coalesce(
        unfold(),
        addV("V1").property("userId", userId2)
)
.coalesce(
        bothE("link").where(outV().as("a")),
        addE("link").from("a")
)
```

**Comment by FlorianHockmann** [comment]
Please only create an issue here to report a bug or suggest a new feature. For general usage questions like yours, you can use [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) or [gremlin-users](https://groups.google.com/forum/#!forum/gremlin-users) if the question is about Gremlin in general.

In case anyone else finds this in the future and has the same question, it was answered already on janusgraph-users:
https://groups.google.com/forum/#!msg/janusgraph-users/AS-_W9SaWS4/rJTInVJ_CwAJ
