### ISSUE TITLE
Add a PR Review Template for contributors

### ISSUE THREAD

**Issue by kottmann** [JanusGraph/janusgraph#139]
To make the life of the maintainers and contributes easier I would like to propose to add a PR Review Template that is shown when the PR is send. The contributor then sees the template and can fill it out. This should lead to a smoother process which requires less interaction between maintainers and contributors.

**Comment by pluradj** [comment]
Do you have an example template, perhaps from another open source project, that could be reused?

**Comment by kottmann** [comment]
Have a look at this commit:
https://github.com/apache/opennlp/commit/decaab59b5f75c478efe3add62373c9781f4df12

What is the best way to start a discussion with Janus Graph people about that? 

You can take that and adapt that to your needs.

**Comment by amcp** [comment]
Took a look

@kottmann Perhaps a thread on the google group would be appropriate. Some adjustments would need to be made, but I think it is close.

**Comment by kottmann** [comment]
Great, let me put together a PR and so we have a basis for discussions.

**Comment by robertdale** [comment]
PR template was merged.
