### ISSUE TITLE
Move to reactive approach

### ISSUE THREAD

**Issue by kptfh** [JanusGraph/janusgraph#1402]
As I can see that janusgraph is heavily relies on storage backend (the grate majority of request time may be spent communicating with storage).
Most of currently implemented storage backends(Cassandra, Elasticsearch) as well as most of the NoSQL DBs (Aerospike, Redis, Couchbase) provide async API and this process is accelerating.
My assumption is that janusgraph can benefit from moving to reactive architecture especially in terms of  concurrent requests per node.

**Comment by farodin91** [comment]
Design decisions should be discussed on https://groups.google.com/group/janusgraph-dev
