### ISSUE TITLE
h2 title fields in docs show scroll bar in ie and chrome

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1404]
I noticed today from a windows machine that in the docs a scroll bar will appear next to all the `<h2.title>` fields, which is all the section headings. The easy fix is to apply `overflow: hidden` to h2.title in the css

**Comment by porunov** [comment]
Related to: https://github.com/JanusGraph/docs.janusgraph.org/issues/30

**Comment by farodin91** [comment]
Fixed by switching theme
