### ISSUE TITLE
Missing Pom for janusgraph-hbase-core

### ISSUE THREAD

**Issue by fppt** [JanusGraph/janusgraph#1408]
Hi All,

I am trying to get OLAP queries running against my janus graph (3.1.0) backed by Cassandra 3.11. OLTP everything is looking good so far. When I add the dependency for janusgraph-hadoop-2 I get the following warning:

```
[WARNING] The POM for org.janusgraph:janusgraph-hbase-core:jar:0.3.1 is missing, no dependency information available
```

In my scala app this warning is a hard fail:

```
[info] Updating ...
[warn] 	module not found: org.janusgraph#janusgraph-hbase-core;0.3.1
[warn] ==== local: tried
[warn]   /Users/filipeteixeira/.ivy2/local/org.janusgraph/janusgraph-hbase-core/0.3.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/janusgraph/janusgraph-hbase-core/0.3.1/janusgraph-hbase-core-0.3.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/filipeteixeira/.sbt/preloaded/org.janusgraph/janusgraph-hbase-core/0.3.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/filipeteixeira/.sbt/preloaded/org/janusgraph/janusgraph-hbase-core/0.3.1/janusgraph-hbase-core-0.3.1.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.janusgraph#janusgraph-hbase-core;0.3.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.janusgraph:janusgraph-hbase-core:0.3.1
[warn] 		  +- org.janusgraph:janusgraph-hadoop-core:0.3.1 (/Users/filipeteixeira/Workspace/log-route-svc/build.sbt#L10-23)
[warn] 		  +- org.janusgraph:janusgraph-hadoop-2:0.3.1 (/Users/filipeteixeira/Workspace/log-route-svc/build.sbt#L10-23)
[warn] 		  +- com.takealot:log-route-svc_2.12:1.0-SNAPSHOT
```

I see that pom is also missing from the [Maven Repo](https://search.maven.org/search?q=g:org.janusgraph).

Anyway to workaround this?

**Comment by vtslab** [comment]
This question is very old, so probably not relevant anymore. To support proper closing, I add the following suggestions how this could have been solved.
1. The proper way to add janusgraph-hadoop dependencies is to use the "janusgraph-hadoop" artifactId, not janusgraph-hadoop-2. By default, janusgraph is built with hadoop2 and the janusgraph-hadoop-2 artifact is not intended for hadoop version selection in the application maven/gradle/sbt file.
2. Local caching of artifacts sometimes leads to error messages in case of failed downloads, so cleaning the local cache sometimes helps solving dependency availability issues.

**Comment by farodin91** [comment]
We removed janusgraph-hbase-core completely
