### ISSUE TITLE
Mix Index query not working for Nepali Unicode characters

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1416]
I have been using janusgraph with cassandra as storage backend and solr as Indexing backind .
Here is my schema description :

mgmt = graph.openManagement()
mgmt.makeVertexLabel('Product').make()
productname = mgmt.makePropertyKey('productName').dataType(String.class).cardinality(Cardinality.SINGLE).make()
price = mgmt.makePropertyKey('productName').dataType(Int.class).cardinality(Cardinality.SINGLE).make()
mgmt.buildIndex('ProductIndex',Vertex.class).addKey(productName,Mapping.TEXT.getParameter()).buildMixedIndex("search")
mgmt.buildIndex('priceIndex',Vertex.class).addKey(price).buildCompositeIndex()
mgmt.commit()

Add Product :

g.addV('Product').property('productName','कोदोको पिठो').property('price','Rs.100')
g.addV('Product').property('productName','Honey').property('price','Rs.200')
g.addV('Product').property('productName','Corn Flakes').property('price','Rs.150')

Search Queries :
1. g.V().hasLabel('Product').has('productName','Honey') 
	-> returns 1 result
2. g.V().has('productName',textContains('hon')) 
	-> returns one result
3. g.V().has('productName',textContains('कोदोको'))
	-> returns 3 result i.e all indexed results
	
When I ran solr in foreground mode and saw logs of solr for these janusgraph queries 

for query 2 :
019-02-14 06:50:35.302 INFO  (qtp736709391-46) [   x:ProductIndex] o.a.s.c.S.Request[ProductIndex]  webapp=/solr path=/select params={q=*:*&fl=id&start=0&fq=productName:(hon)+&rows=50&wt=javabin&version=2} hits=1 status=0 QTime=0

for query 3 :
2019-02-14 06:50:35.402 INFO  (qtp736709391-46) [   x:ProductIndex] o.a.s.c.S.Request [ProductIndex]  webapp=/solr path=/select params={q=*:*&fl=id&start=0&fq=&rows=50&wt=javabin&version=2} hits=3 status=0 QTime=2

It is seen that for query no. 3 there is no fiter productName seen in the solr query convertex by janusgraph
How to make productName visible for query 3?
Is there any way to configure encodig to UTF-8 in janusgraph?

**Comment by FlorianHockmann** [comment]
This was addressed on Gitter and all that was needed was a custom analyzer. I created #1423 to add this information to our docs as this question is frequently asked.
