### ISSUE TITLE
Implement TTL in berkeleyje backend

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#142]
BerkeleyJE recently introduced TTL support. Since we updated our dependency on it, we can also have the store manager implement TTL.

**Comment by mad** [comment]
I'm try to implement this feature, but berkeleyje support only HOURS/DAYS granularity of TTL [WriteOptions.setTTL](https://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/WriteOptions.html#setTTL-int-java.util.concurrent.TimeUnit-)

How this feature may be tested? Is it needs addition set of long tests?

Here implementation without tests https://github.com/mad/janusgraph/tree/142-add-ttl-to-berkeleyje

**Comment by mad** [comment]
Fixed here #1677
