### ISSUE TITLE
Modernize Documentation

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1420]
Following [the discussion on janusgraph-dev](https://groups.google.com/forum/#!topic/janusgraph-dev/KzyxrrPfnek), we want to modernize JanusGraph's docs and the homepage. The goals of this modernization are:

- A modern design. The current design is based on that of Titan and looks quite dated according to feedback from different users/contributors.
- Homepage and docs should have the same design.
- Making it easier for readers to suggest changes. (Many projects have an _edit_ button for that directly in the docs.)
- Enabling an easier update of the docs so we can update the docs also between releases, if we want to.

**Comment by farodin91** [comment]
TODO
* [ ] travis integration
* [ ] multi version support
* [ ] check that documentation is include in released zip of janusgraph
* [x] check links
* [x] link checker integration (by mkdocs only for md)
* [x] Make release and changelog more visible
* [x] Add links to old documtation into the changelog
* [ ] Check all old reference to asciidoc and remove them
* [x] Rebase to branch 0.2 (Only 4 commit more than in current master) **We would have all currently support version as modern documentation.** 
* basics.adoc and markdown in to be checked for branch 0.2

Things to do in a follow up PR:
1.  Merge into v0.3 branch and integrate all doc changes
2.  Merge into master branch and integrate all doc changes

Can be done in follow up PR:
* fix all code box
* spellcheck
* convert documentation into a pdf
* automate reading of current version maven (also deps)

I will work on travis ci part and multi version support

**Comment by FlorianHockmann** [comment]
I just merged @farodin91's initial PR to [this feature branch](https://github.com/JanusGraph/janusgraph/commits/Issue_1420_ModernizeDocumentation). If others want to contribute to this issue, then just create a PR against that branch.
As already discussed on janusgraph-dev, we will merge these PRs with only minimal review and then do a full review when the feature branch gets merged in a release branch.

@JanusGraph/maintainers: Could you set up gh-pages for this feature branch so we have a preview of the docs?

**Comment by farodin91** [comment]
@JanusGraph/maintainers If a branch with this name is created, it will work automatically. 
Only thing todo is to allow TravisCI to push into this branch.

**Comment by FlorianHockmann** [comment]
I created the `gh-pages` branch. Someone from the TSC now just needs to give Travis access to that branch as described [here](https://docs.travis-ci.com/user/deployment/pages/).

**Comment by mbrukman** [comment]
If you'd like to update janusgraph.org, note that it's tracked in a different repo: https://github.com/janusgraph/janusgraph.org (and docs.janusgraph.org is similarly in a different repo) — you can certainly push there instead of `gh-pages` branch on this repo.

My preference for having website (and any generated docs) in a separate repo is that `git clone` pulls down the full revision history of all files and branches, and having Travis push a new branch for every file update will keep bloating the repository without limits. Having it separated into janusgraph.org or docs.janusgraph.org makes the code repo much smaller, and we can evolve the website repo orthogonally to the code repo (most users will never touch the website repo, but most developers will interact with the main code repo regularly).

Thoughts?

**Comment by farodin91** [comment]
> My preference for having website (and any generated docs) in a separate repo is that `git clone` pulls down the full revision history of all files and branches, and having Travis push a new branch for every file update will keep bloating the repository without limits.

Travis is able to remove the complete history of a branch so only one commit exists.

During the development, we would like to see the result, so can create a test repo and use `gh-pages` in this test repo or use `gh-pages` in this https://github.com/janusgraph/janusgraph. Afterward, we could change the repo to https://github.com/janusgraph/janusgraph.org.

A good thing of using a different repo, we could easily replace the frontend page with a custom site in the future.

**Comment by FlorianHockmann** [comment]
> Having it separated into janusgraph.org or docs.janusgraph.org makes the code repo much smaller, and we can evolve the website repo orthogonally to the code repo (most users will never touch the website repo, but most developers will interact with the main code repo regularly).

The reasoning for moving the sources for the docs and the homepage in the same repo is that it makes it easier to give both the same design and also that currently the `README.md` in the main repo and janusgraph.org share a lot of content. If someone for example wants to add a visualization tool, then two pull requests are necessary for that right now.

A different repo for the generated docs + homepage seems to make sense though (instead of using a `gh-pages` branch in the main repo). Could you create a test repo for that, @mbrukman and give Travis access? We shouldn't use any of the current repos as long as this still lives in a feature branch that we can use to test out things.

**Comment by FlorianHockmann** [comment]
I just deleted the feature branch here again as @farodin91 already created a PR for the `0.2` branch and also the `gh-pages` branch as the idea is now to put the generated docs into a different repo as described above.

**Comment by porunov** [comment]
I think splitting documentation and main page is better then using them as a single web site.

> The reasoning for moving the sources for the docs and the homepage in the same repo is that it makes it easier to give both the same design and also that currently the README.md in the main repo and janusgraph.org share a lot of content. If someone for example wants to add a visualization tool, then two pull requests are necessary for that right now.

I think we can still use the same design but in two different web sites. Web site for documentation and web site for main page. Main page and `README.md` share a lot but they are not identical and shouldn't be. For example, I don't need to see a lot of badges on the main page but the are convenient in in github repo. I don't think that it is a problem to provide 2 PRs to add a visualization tool.

Also, I think that the main page may be changed in the future to have another stile which is more appealing for a main page. If we have main page and documentation represented together as a single website it will be harder to change the main page style.

I think that the main page could be without `search`, `changelog` and `table of contents`. Something close to this (docs button should be also present):
![Screenshot from 2019-05-10 14-07-04](https://user-images.githubusercontent.com/17673243/57523359-6ebb4500-732d-11e9-84af-45737f34faf3.png)

I think `mkdocs` is really good for documentation but I am not sure that it is good for the main page. I think something more appealing could be used. But it it is really much better than the current main page.

**Comment by porunov** [comment]
I've started to make a main page based on some available styles. I will try to provide my demo page soon

**Comment by porunov** [comment]
Updated style of `janusgraph.org`. Waiting for reviews. PR is https://github.com/JanusGraph/janusgraph.org/pull/64

DEMO: https://porunov.github.io/janusgraph.org

**Comment by farodin91** [comment]
We just rollout the first build of the new documentation: https://janusgraph.github.io/janusgraph/

**Comment by porunov** [comment]
@farodin91 I've just search quickly through new build and it looks very good to me. Change log is correct for all versions, configuration references are correct also. Search works specifically for the selected version. Docs editing pointing to correct github files for the selected version.

I think we can change the domain `docs.janusgraph.org` to point to a new docs.

**Comment by farodin91** [comment]
I should add a dns entry for the old documentation, such as, `docs-old.janusgraph.org`. 

Before update the url, we should ask on the mailing list for a final check.

**Comment by porunov** [comment]
@farodin91 I think it can take some time to get `docs-old.janusgraph.org` because `janusgraph.org` is controlled by The Linux Foundation. I am not sure we have direct access for DNS records.

**Comment by porunov** [comment]
@farodin91 Will you post a message into the mailing list?

**Comment by farodin91** [comment]
I will write a message for the mailing list later today.

**Comment by farodin91** [comment]
@porunov the master and v0.4 seems due to issue in the Travis chi file. I will check the issue tomorrow.

**Comment by porunov** [comment]
The documentation is launched on https://docs.janusgraph.org

**Comment by farodin91** [comment]
@FlorianHockmann @porunov We are done with this part of modernize our documentation, or?

**Comment by porunov** [comment]
@farodin91 Yes this issue was resolved when you updated documentation. Thank you
