### ISSUE TITLE
How to use combination of analyzer while using solr as Indexing 

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1422]
This is how I use custom analyzer for solr
mgmt = graph.openManagement()
string = mgmt.makePropertyKey('string').dataType(String.class).make()
text = mgmt.makePropertyKey('text').dataType(String.class).make()
mgmt.buildIndex('string', Vertex.class).addKey(string, Mapping.STRING.asParameter(), Parameter.of(ParameterType.STRING_ANALYZER.getName(), 'org.apache.lucene.analysis.standard.StandardTokenizer')).buildMixedIndex("search")
mgmt.buildIndex('text', Vertex.class).addKey(text, Mapping.TEXT.asParameter(), Parameter.of(ParameterType.TEXT_ANALYZER.getName(), 'org.apache.lucene.analysis.core.WhitespaceTokenizer')).buildMixedIndex("search")
mgmt.commit()

But I need to use filters after analyzing field in solr so I have configured solr schema.xml like this 
![image](https://user-images.githubusercontent.com/18022460/52920679-77583c80-3337-11e9-856d-1a66664da410.png)

How to configure text_ngam wholistically in sjanusgraph so that my query is analysed by Standard tokenizer abd the filtered with NGramFilter and lowercased

**Comment by porunov** [comment]
@pra527vin , for questions you should use this group: 
https://groups.google.com/forum/#!forum/janusgraph-users

GitHub issues are used for feature requests and bug reports.

**Comment by FlorianHockmann** [comment]
Closed, as @porunov said, please use janusgraph-users to ask questions.
