### ISSUE TITLE
Tests fail on the release version 0.2.2?

### ISSUE THREAD

**Issue by ntrhieu89** [JanusGraph/janusgraph#1430]
Hi,

I download the source code of the stable release version 0.2.2 and open it with IntelliJ. When I run the test suite with IntelliJ, it reports that 40 tests fail (total 4495 tests, ignored 382 tests and passed 4073 tests).

Does anyone know what's wrong with the 40 failed tests?

Thanks,

**Comment by farodin91** [comment]
Some tests didn't work directly in Intellij. Maven is doing some pre setup tasks before the tests. So, you should run your using maven. I'm working on this task. This task will require some time.

Besides, some tests are flaky.

**Comment by FlorianHockmann** [comment]
[TESTING.md](https://github.com/JanusGraph/janusgraph/blob/master/TESTING.md) describes how you can execute the different tests.

Despite that, please ask questions like these about development aspects of JanusGraph in [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev). We don't use issues for questions.
So, I'm closing this one.
