### ISSUE TITLE
Within() predicate in 0.2.2

### ISSUE THREAD

**Issue by darwinyip** [JanusGraph/janusgraph#1435]
Seems like some of the predicates listed in http://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates are not available in Janusgraph. Having `within()` would be a big plus since it simplifies a lot of code. EIther that, or I don't know where they are located.

**Comment by farodin91** [comment]
We are running on JanusGraph 0.3.1 and `within` works perfectly.

**Comment by farodin91** [comment]
Sorry thought of `inside`.

**Comment by porunov** [comment]
I thought all predicates should work. Do we have any unsupported predicates?

@darwinyip Do you have an example where `P.within(...)` doesn't work? I didn't try it yet. 

In our setup `P.inside(...)` also works.

**Comment by darwinyip** [comment]
@porunov Please disregard. I couldn't find P in the janusgraph libraries. Did not know they were part of gremlin instead.
