### ISSUE TITLE
A problem about gremlin language

### ISSUE THREAD

**Issue by liuyt-15** [JanusGraph/janusgraph#1443]
Hello，everyone!
I meet a problem about gremlin language .
![image](https://user-images.githubusercontent.com/22389288/53395105-f99dcc00-39db-11e9-870b-6ea54910ca7a.png)
It shows that "where(out('xx').is(eq('b')) " does not work because node_id = 491584 has the same target_node(9019480) with 565320.
I'm looking forward to receiving your message.
Thanks!

**Comment by porunov** [comment]
@liuyt-15 
you should change `is(eq('b'))` to `as('b')`. Also, I think the whole `where` clause is redundant in this situation.

Also, it looks like your issue isn't a bug report or feature request but rather a question about Gremlin language usage. You should ask those questions in the [Gremlin users group](https://groups.google.com/forum/#!forum/gremlin-users).

I am closing this issue as it looks like a question. Please, feel free to reopen if you still think that it is a bug report or feature request but then clarify your issue.
