### ISSUE TITLE
Remove travis tests for unsupported/EOL backend

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1452]
We should remove tests for EOL backends from travis per this [janusgraph-dev discussion](https://groups.google.com/forum/#!topic/janusgraph-dev/MA69slAbNvc)

**Comment by FlorianHockmann** [comment]
Based on our discussion in #1453 to remove all support for a backend version in a single PR (code, tests, and so on) and to split this into different issues for the different backends, I just created issues for the different backends: #1490, #1491, #1492, #1493, and #1494.
So I'm closing this as it's included in these issues.
