### ISSUE TITLE
Flaky Solr test: testIndexReplay

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1458]
```java
Failed tests: 
  BerkeleySolrTest>JanusGraphIndexTest.testIndexReplay:1267 expected:<4> but was:<5>
```

This failed already with Solr5 and Solr7.

This is related to #1335 which reports the same problem, but for Elasticsearch 1.

**Comment by farodin91** [comment]
Can you link a build? This test has already a marking, see https://github.com/JanusGraph/janusgraph/blob/8c492b0e29dad1f4754b5690eef4da94a33e2d75/janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java.

**Comment by FlorianHockmann** [comment]
It should have been these builds:

- [1843](https://travis-ci.org/JanusGraph/janusgraph/builds/492193490): Targeted `0.2` which didn't get the flaky marking.
- [1902](https://travis-ci.org/JanusGraph/janusgraph/builds/498592012): This build belongs to [this commit](https://github.com/JanusGraph/janusgraph/commit/4682509e753f7934dc6fd9da30989248181d758f) which was merged before the flaky marking was added. So the test probably just failed the number of retries in Travis.

So, this really seems to be not an issue any more.
