### ISSUE TITLE
Add sorting parameters to JanusGraphIndexQuery

### ISSUE THREAD

**Issue by VladimirBogomolov** [JanusGraph/janusgraph#1468]
My team use LuceneIndex as backend for janus graph in our project and we often have to make some raw query to luceneindex like this:
janusGraph.indexQuery(indexName, queryString)
And we often need to receive sorted result. Why you don't to add sorting parameters to JanusGraphIndexQuery. 
What do you think?
I can make PR.

**Comment by porunov** [comment]
@VladimirBogomolov PRs are always welcome. Feel free to provide one. 

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions to provide a correct PR: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

**Comment by porunov** [comment]
Fixed by #1471
