### ISSUE TITLE
Build Janusgraph

### ISSUE THREAD

**Issue by DamienLF** [JanusGraph/janusgraph#150]
Hi,

I tried to build Janusgraph with `mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true` but an error occurred at "Building JanusGraph-Hadoop: 2.x Compatibility Shim 0.1.0-SNAPSHOT" : 

> INFOS: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
mars 06, 2017 10:20:54 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute

> [ERROR] Plugin org.apache.maven.plugins:maven-failsafe-plugin:2.15 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-failsafe-plugin:jar:2.15: Could not transfer artifact org.apache.maven.plugins:maven-failsafe-plugin:pom:2.15 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

Also, do you plain to make an official Dockerfile or an official release available ?

**Comment by DamienLF** [comment]
I ran it on Ubuntu 16.04.2 LTS with openjdk version "1.8.0_121" and Apache Maven 3.3.9.

**Comment by pluradj** [comment]
The error indicates a network connection issue with Maven Central `https://repo.maven.apache.org:443: Connection reset`. I'd suggest trying again later on. FWIW, I just ran successfully a clean build against `master` using that exact same command.

Re: Dockerfile -- see https://github.com/JanusGraph/janusgraph/issues/140

**Comment by cachance7** [comment]
@DamienLF Did you ever resolve this? I encounter the exact same thing each time I have tried to build over the past week.

**Comment by DamienLF** [comment]
@cachance7 Yes, just try again later in the day. You may have to try multiple times before it works...
Also, you can download the jar directly (https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-failsafe-plugin/2.15/) and try to build with this jar (I didn't try this solution)
