### ISSUE TITLE
Document how to specify additional parameters during index build (e.g. date format for ElasticSearch)

### ISSUE THREAD

**Issue by MichaelMarkieta** [JanusGraph/janusgraph#153]
There is no documentation on how to specify additional parameters during index building (e.g. date formats for ElasticSearch https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html). I am not even sure if this can be done at this point? I got to this point in the source and then I got stuck: https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java#L619-L623

**Comment by sjudeng** [comment]
Setting custom date formats for ES is not currently supported. Mapping customization is currently limited to string types. The [index parameters documentation](http://docs.janusgraph.org/0.1.0-SNAPSHOT/index-parameters.html) includes examples showing using different [Mapping](https://github.com/JanusGraph/janusgraph/blob/206c59256fe2eea39044cd26708722c5bb1d1586/janusgraph-core/src/main/java/org/janusgraph/core/schema/Mapping.java) values to control string type/index (analyzed/not-analyzed) during mixed index creation.

**Comment by MichaelMarkieta** [comment]
I guess the only way around this is to modify the mapping after the index is created for now.

ES allows date formats to be modified on existing indexes. For example: 

```
curl -X PUT http://localhost:9200/janusgraph/_mappings/byArrivalTime --data '{"properties": {"arrival_time": {"type": "date", "format": "date_time_no_millis"}}}'
```
