### ISSUE TITLE
Range limit -1 is not supported by JanusGraph

### ISSUE THREAD

**Issue by ntrhieu89** [JanusGraph/janusgraph#1534]
When I look at this class, the limit is assumed to be >= 0.

[https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java#L53](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java#L53)

However, in Gremlin, it uses the limit -1 as infinity.

[https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java#L1818](https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java#L1818)

This Gremlin test [https://github.com/apache/tinkerpop/blob/master/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeTest.java#L439](https://github.com/apache/tinkerpop/blob/master/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeTest.java#L439) passes on JanusGraph because it assumes property `age` has Cardinality LIST. If property `age` has Cardinality SINGLE, then the error happens.

I can reproduce the issue using Gremlin console with BerkeleyDB as the storage backend:

```
gremlin> graph = JanusGraphFactory.open('/Users/hieunguyen/janusgraph-berkeley.properties')
==>standardjanusgraph[berkeleyje:/Users/hieunguyen/janusgraph-0.3.1-hadoop2/db/berkeley]
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[berkeleyje:/Users/hieunguyen/janusgraph-0.3.1-hadoop2/db/berkeley], standard]
gremlin> g.addV().property("name", "marko").property("age", 29).next();
==>v[20481080]
gremlin> g.addV().property("name", "vardas").property("age", 27).next();
==>v[20481048]
gremlin> g.addV().property("name", "josh").property("age", 32).next();
==>v[10241032]
gremlin> g.addV().property("name", "peter").property("age", 35).next();
==>v[20482072]
gremlin> g.V().order().by("age").skip(1).values("name");
Non-negative limit expected: -1
```

Note that if we swap `skip()` with `values()`, it runs fine:
```
gremlin> g.V().order().by("age").values("name").skip(1)
14:13:55 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>marko
==>josh
==>peter
```

**Comment by ntrhieu89** [comment]
Could someone that is familiar with the code suggest me a good way to handle this issue?

**Comment by mad** [comment]
Simplified example
```
gremlin> graph=JanusGraphFactory.open("inmemory")
==>standardjanusgraph[inmemory:[127.0.0.1]]
gremlin> g=graph.traversal()
==>graphtraversalsource[standardjanusgraph[inmemory:[127.0.0.1]], standard]
gremlin> g.V().skip(1)
Non-negative limit expected: -1
```
`QueryUtil.convertLimit` handle no-limit different that tinkerpop

For workaround change `skip(n)` step to `range(n, Integer.MAX_VALUE)`
