### ISSUE TITLE
Janusgraph 0.3.1 Use gremlin reindex by MapReduceIndexManagement

### ISSUE THREAD

**Issue by COBSNAN** [JanusGraph/janusgraph#1535]
Janusgraph version 0.3.1
storage backend:cassandra
`storage.backend=cql`
use gremlin reindex by MapReduceIndexManagement have error
`Store manager class class org.janusgraph.diskstorage.cql.CQLStoreManageris not supported`
![image](https://user-images.githubusercontent.com/5803018/56342341-50f53700-61ea-11e9-99e3-1b0ebab67ae1.png)

Now,is not support cql type?

**Comment by miofy** [comment]
`MapReduceIndexManagement` supports: 
```
CassandraEmbeddedStoreManager
CassandraThriftStoreManager
AstyanaxStoreManager
HBaseStoreManager
```
But not support `CQLStoreManager`.

**Comment by COBSNAN** [comment]
> `MapReduceIndexManagement` supports:
> 
> ```
> CassandraEmbeddedStoreManager
> CassandraThriftStoreManager
> AstyanaxStoreManager
> HBaseStoreManager
> ```
> But not support `CQLStoreManage
