### ISSUE TITLE
Can I use GraphQL to query JanusGraph data? 

### ISSUE THREAD

**Issue by mingjinc** [JanusGraph/janusgraph#1536]

**Comment by mbrukman** [comment]
Please only use GitHub for reporting bugs or feature requests. General open-ended questions such as this one should be posted on the janusgraph-users@ mailing list or on the chat channel.

See links on the main README: https://github.com/JanusGraph/janusgraph/#community for details.

**Comment by mbrukman** [comment]
Additionally, before posting a new question, please search the archives:
https://groups.google.com/forum/#!forum/janusgraph-users
searching for `graphql` shows an earlier thread that was posted there previously.
