### ISSUE TITLE
tests fail when initialize JanusGraphElasticsearchContainer

### ISSUE THREAD

**Issue by hypnosding** [JanusGraph/janusgraph#1550]
Tests fail and got following error
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.541 s <<< FAILURE! - in org.janusgraph.diskstorage.es.BerkeleyElasticsearchTest
[ERROR] org.janusgraph.diskstorage.es.BerkeleyElasticsearchTest  Time elapsed: 10.541 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.janusgraph.diskstorage.es.BerkeleyElasticsearchTest.<clinit>(BerkeleyElasticsearchTest.java:40)

This error also happened when run tests as org.janusgraph.diskstorage.es.ElasticsearchConfigTest, org.janusgraph.diskstorage.es.ElasticsearchIndexTest, and so on.

When looking at the test code, all the above cases fail at 
public static JanusGraphElasticsearchContainer esr = new JanusGraphElasticsearchContainer();

Please take a look at this and let me know if more information is needed.

**Comment by farodin91** [comment]
I have some questions. 
Which platform do you use?
Do you have installed docker and have access to it?

**Comment by hypnosding** [comment]
Thanks @farodin91
I try to build Janusgraph on Ubuntu 18.04.2 LTS which is hosted on an Azure VM.
Maven 3.6.0 and OpenJDK 1.8.0_191 were used.
I don't have docker installed on that machine.

**Comment by farodin91** [comment]
As described in the testing.md, you need docker to run elasticsearch tests. We use testcontainers-java to run these tests.

**Comment by hypnosding** [comment]
@farodin91 Thanks a lot!
