### ISSUE TITLE
why the class Stopwatch have same name and package with the guava??? 

### ISSUE THREAD

**Issue by llfioenig** [JanusGraph/janusgraph#1555]
the classes com.google.common.base.Stopwatch and com.google.common.io.Closeables  have same name and package with the guava,when I run janusgraph with spark use   the following code :

val (sc, conf) = getScAndConf(env, tableName)
        val rdd = sc.newAPIHadoopRDD(conf, classOf[HBaseInputFormat], classOf[NullWritable], classOf[VertexWritable])
            .map(a => {
                val graph = new mutable.HashMap[String, Any]();
                val vertex = new mutable.HashMap[String, Any]()
                graph.put("vertex", vertex)
                vertex.put("id", a._2.get().id())
                vertex.put("label", a._2.get().label())
                val v = a._2.get().properties()
                while (v.hasNext) {
                    val n = v.next()
                    vertex.put(n.key(), n.value())
                }

                val edges=new mutable.ListBuffer[mutable.HashMap[String, Any]]
                graph.put("edges",edges);
                val e=a._2.get().edges(Direction.BOTH)
                while(e.hasNext){
                    val a=e.next()
                    val edge = new mutable.HashMap[String, Any]()
                    edge.put("id", a.id())
                    edge.put("label", a.label())
                    edge.put("inVertex", a.inVertex().id())
                    edge.put("outVertex", a.outVertex().id())
                    val ep=a.properties()
                    while(ep.hasNext){
                        val edgeP=ep.next()
                        edge.put(edgeP.key(), edgeP.value())
                    }
                    /*a.properties().forEachRemaining((edgeP:Property[Any]) => {
                        edge.put(edgeP.key(), edgeP.value())
                    })*/
                    edges+=edge
                }
                graph
            }).foreach(println)
        sc.stop()

I get the following error:
![image](https://user-images.githubusercontent.com/2876163/57280969-8d76cd00-70dc-11e9-8aa5-47759a003131.png)

I find the program use the class Stopwatch of guava ,but it should use the class of janusgraph-hbase. Dose you have any solution?

**Comment by FlorianHockmann** [comment]
We only use issues for bug reports or feature requests. Please ask usage questions in our [janusgraph-users Google group](https://groups.google.com/forum/#!forum/janusgraph-users) or in our [Gitter chat](https://gitter.im/janusgraph/janusgraph).
