### ISSUE TITLE
Date serializer failed when value is numeric-string

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1558]
Code for reproduce
```
gremlin> graph = JanusGraphFactory.open("inmemory")
==>standardjanusgraph[inmemory:[127.0.0.1]]
gremlin> 
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[inmemory:[127.0.0.1]], standard]
gremlin> 
gremlin> g.addV().property('a', new Date())
==>v[4224]
gremlin> g.addV().property('a', "1557305024351")
Value [1557305024351] is not an instance of the expected data type for property key [a] and cannot be converted. Expected: class java.util.Date, found: class java.lang.String
Type ':help' or ':h' for help.
```

**Comment by mad** [comment]
Legacy software use string form for Integer/Number/Double properties, Serializers for thats type properly handle numeric in string form, but DateSerializer don't

Two way for add ISO 8601 supports, through StdDateFormat provided by jackson and available through TP3 and DateTimeFormatter from java. I'm add StdDateFormat because more robust and support additional format RFC1123

**Comment by FlorianHockmann** [comment]
OK, that makes sense, especially because the other serializers also accept string representations. I wasn't aware of that.
