### ISSUE TITLE
ERROR org.apache.spark.SparkContext  - Error initializing SparkContext

### ISSUE THREAD

**Issue by zhentaowang** [JanusGraph/janusgraph#1560]
23:11:34 ERROR org.apache.spark.SparkContext  - Error initializing SparkContext.
org.apache.spark.SparkException: Could not parse Master URL: 'yarn'
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2760)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:501)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
        at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
        at org.apache.tinkerpop.gremlin.spark.structure.Spark.create(Spark.java:52)
        at org.apache.tinkerpop.gremlin.spark.structure.Spark.create(Spark.java:60)
        at org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer.lambda$submitWithExecutor$1(SparkGraphComputer.java:233)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
23:11:34 WARN  org.apache.spark.metrics.MetricsSystem  - Stopping a MetricsSystem that is not running
org.apache.spark.SparkException: Could not parse Master URL: 'yarn'

**Comment by zhentaowang** [comment]
**The following is spark-yarn.sh:**
#!/bin/bash

#Variables to be adapted to the actual environment

#GREMLIN_HOME=/opt/apache-gremlin-console-3.1.0-incubating
GREMLIN_HOME=/opt/janusgraph-0.3.1-hadoop2
export SPARK_HOME=/usr/hdp/2.6.0.3-8/spark
export HADOOP_HOME=/usr/hdp/2.6.0.3-8/hadoop
export HADOOP_CONF_DIR=/usr/hdp/2.6.0.3-8/hadoop/etc/hadoop

#Have TinkerPop find the hadoop cluster configs and hadoop native libraries
export CLASSPATH=$HADOOP_CONF_DIR
export JAVA_OPTIONS="-Djava.library.path=$HADOOP_HOME/lib/native"
export HADOOP_GREMLIN_LIBS=$GREMLIN_HOME/ext/spark-gremlin/lib:$GREMLIN_HOME/ext/tinkergraph-gremlin/lib

cd $GREMLIN_HOME
[ ! -e empty ] && mkdir empty
export HADOOP_GREMLIN_LIBS=$GREMLIN_HOME/empty
bin/gremlin.sh

**The following is hadoop-gryo.properties:**
gremlin.graph=org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph
gremlin.hadoop.graphReader=org.apache.tinkerpop.gremlin.hadoop.structure.io.gryo.GryoInputFormat
gremlin.hadoop.graphWriter=org.apache.tinkerpop.gremlin.hadoop.structure.io.gryo.GryoOutputFormat
gremlin.hadoop.jarsInDistributedCache=true

gremlin.hadoop.inputLocation=hdfs://630-dev-new/wzt/tinkerpop-modern.kryo
gremlin.hadoop.outputLocation=output

#####################################

GiraphGraphComputer Configuration
#####################################
giraph.minWorkers=2
giraph.maxWorkers=2
giraph.useOutOfCoreGraph=true
giraph.useOutOfCoreMessages=true
mapred.map.child.java.opts=-Xmx1024m
mapred.reduce.child.java.opts=-Xmx1024m
giraph.numInputThreads=2
giraph.numComputeThreads=2

giraph.maxPartitionsInMemory=1
giraph.userPartitionCount=2
####################################

SparkGraphComputer Configuration
####################################

#use yarn-client, standalone master url (spark://23.195.26.187:7077), or local
spark.master=yarn-client

#spark.submit.deployMode=client

#Cache the Spark jar in HDFS so that it doesn't need to be distributed each time an application runs (optional)
spark.yarn.jars=hdfs://630-dev-new/user/ambari-qa/share/lib/spark/spark-assembly-1.6.3.2.6.0.3-8-hadoop2.7.3.2.6.0.3-8.jar

#additional Hadoop distro variables required for YARN ApplicationMaster
spark.yarn.am.extraJavaOptions=-Dhdp.version=2.6.0.3-8 -Djava.library.path=/usr/hdp/2.6.0.3-8/hadoop/lib/native

#keep executor memory within YARN Container bounds
spark.executor.memory=512m

spark.yarn.appMasterEnv.CLASSPATH=/opt/janusgraph-0.3.1-hadoop2/ext/spark-gremlin/lib:/usr/hdp/2.6.0.3-8/hadoop/etc/hadoop
spark.executor.extraClassPath=/opt/janusgraph-0.3.1-hadoop2/ext/spark-gremlin/lib:/usr/hdp/2.6.0.3-8/hadoop/etc/hadoop
spark.driver.extraLibraryPath=/usr/hdp/2.6.0.3-8/hadoop/lib/native
spark.executor.extraLibraryPath=/usr/hdp/2.6.0.3-8/hadoop/lib/native
gremlin.spark.persistContext=true

**The following is excute code:** 
graph = GraphFactory.open('/opt/janusgraph-0.3.1-hadoop2/conf/hadoop-graph/hadoop-gryo.properties')
g = graph.traversal().withComputer(SparkGraphComputer)
g.V().count()

**Comment by FlorianHockmann** [comment]
This is most likely not a bug in JanusGraph, but a usage error, e.g., a mistake in your configuration. Since we only use GitHub issues for feature requests and bug reports, please ask this again in our Google group [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users).

**Comment by zhentaowang** [comment]
@FlorianHockmann ok, thanks

**Comment by lhaiq** [comment]
@zhentaowang 您怎么解决的呢
