### ISSUE TITLE
Support GraphBinary serialization format

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1564]
TinkerPop introduced a new serialization format in version 3.4.0: GraphBinary. Short description [from the upgrade docs](http://tinkerpop.apache.org/docs/3.4.0/upgrade/#_graphbinary):

> GraphBinary is a new language agnostic, network serialization format designed to replace Gryo and GraphSON. At this time it is only available on the JVM, but support will be added for other languages in upcoming releases.

[According to first benchmarks](https://issues.apache.org/jira/browse/TINKERPOP-1942?focusedCommentId=16667028&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16667028), this provides a performance improvements between 1 and 2 orders of magnitude over GraphSON.

[Full documentation](http://tinkerpop.apache.org/docs/3.4.0/dev/io/#graphbinary)

**Comment by porunov** [comment]
From this TinkerPop [changelog](https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc#tinkerpop-344-release-date-not-officially-released-yet) I see that `GraphBinary` support is added for Python also but that TinkerPop version isn't released yet.
I was thinking, can we implement this feature or should we wait for `GraphBinary` support in `.NET` also?
I think that would be nice to implement for performance improvement.

**Comment by FlorianHockmann** [comment]
Without having any statistics to back this up, I'd say that most JanusGraph users use Java (or another JVM based language). So, I don't see why we should wait for .NET support of GraphBinary in TinkerPop.

**Comment by taabodim** [comment]
Hi @porunov and @FlorianHockmann, 
I can help you guys with this as well. just need a little of guidance about where to start from.

**Comment by FlorianHockmann** [comment]
Great to hear, @taabodim! First thing I would do is just to get familiar with GraphBinary. The best place for that is probably the [dev documentation of TinkerPop](http://tinkerpop.apache.org/docs/3.4.5/dev/io/#graphbinary). Especially for the implementation, [the GraphBinary implementation of TinkerPop](https://github.com/apache/tinkerpop/tree/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary) should also be very helpful.

In the end, it should only be necessary for JanusGraph to implement serialization support for the JanusGraph specific types, similar to how we do it for GraphSON. So, I would check [the current GraphSON implementation in JanusGraph](https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop).
JanusGraph specific types should be these:

- Text predicates (`textContains` and so on)
- Geo predicates (`geoWithin`, ...)
- Geo types (`Point`, `Circle`, ...)
- [RelationIdentifier](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-driver/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifier.java) which is the JanusGraph edge id

JanusGraph will probably need its own GraphBinary IO registry that has serializers and deserializers registered for these types like the `JanusGraphIoRegistry` right now. This registry will then need to be added to the `gremlin-server.yaml` to enable it on the server side and we need to use it in `janusgraph-driver`.

**Comment by taabodim** [comment]
Thanks @FlorianHockmann, for the explanation. I will go through the code and try to implement a first version.

**Comment by farodin91** [comment]
@taabodim I didn't see that you are working on it. 
I finished a first version.
