### ISSUE TITLE
Implement the linux foundation CLA tool

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1586]
As discussed in this [thread](https://groups.google.com/forum/#!topic/janusgraph-dev/b_VkkGYN_8A) the CLA tool is ready for use and can be implemented by JanusGraph.

**Comment by porunov** [comment]
I really would like to see it implemented in JanusGraph

**Comment by mbrukman** [comment]
@jmertic from The Linux Foundation is tracking the work to import JanusGraph ICLA/CCLA into the CLA automation tool, and will post further updates as they become available.

**Comment by porunov** [comment]
JanusGraph is using EasyCLA for a while. Closing this issue as resolved.
