### ISSUE TITLE
enable cron testing of Cassandra versions covered by .travis.yml.cassandra

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1594]
The Cassandra tests for version `2.2.10`, `3.0.14`, and `3.11.0` have to be manually run right now. Tests that fail in Cassandra 3 were introduced 10 months ago that I just found today. I don't believe there were any user issues as result, but it's still a good indicator that this should be run in an automated fashion. 

I propose adding the contents of `.travis.yml.cassandra` to `.travis.yml` based off the conditional that the `TRAVIS_EVENT_TYPE` environment variable has the value `cron`. I might also be able to have it run off of a commit message string similar to [skip ci]

I think running this more comprehensive test weekly would be appropriate.

**Comment by chupman** [comment]
@porunov let me know if you have any questions on the release process. Sorry I let this block as long as I did.

**Comment by porunov** [comment]
@chupman Thank you! I will start the release process tomorow morning.
