### ISSUE TITLE
NOT_EQUAL condition handled different for index backends

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1597]
This test produce different results for index backends

```
query = new IndexQuery(store, PredicateCondition.of(STRING, Cmp.NOT_EQUAL, "Tom Jerry"));
assertEquals(0, tx.queryStream(query).count(), query.toString());
```
Add these lines to `IndexProviderTest.testCustomAnalyzer` and run tests

Lucene - failed
Solr - failed
ES - success

Expected here https://github.com/JanusGraph/janusgraph/pull/1406

**Comment by porunov** [comment]
Fixed in #1406
