### ISSUE TITLE
Some GLOBAL configurations cannot be modified when following the step listed in the document

### ISSUE THREAD

**Issue by cjxqhhh** [JanusGraph/janusgraph#1603]
Hi, I have problem modifying the GLOBAL configuration tx.max-commit-time。

The default value of tx.max-commit-time is 10s and at first I changed it to 0.05s which worked as expected, and then I found it was too short so I decide to change it to 5s. 
However, after I call the mgmt.commit(), the value of tx.max-commit-time came back to the original value which is 0.05s.

The steps are as follows:

mgmt = graph.openManagement();
for (String string : mgmt.getOpenInstances()) {if (!string.endsWith("(current)")) {mgmt.forceCloseInstance(string);} }
mgmt.commit();

mgmt = graph.openManagement()
mgmt.set('tx.max-commit-time',Duration.ofMillis(5000))
mgmt.commit()

Thanks in advance~

**Comment by cjxqhhh** [comment]
Does this configuration can only be changed for one time?

**Comment by FlorianHockmann** [comment]
Closed, as questions like these belong on janusgraph-users where [it was also posted](https://groups.google.com/forum/#!topic/janusgraph-users/w_AS-uF9PnU).
