### ISSUE TITLE
Write-ahead log not fixing all the failures

### ISSUE THREAD

**Issue by cjxqhhh** [JanusGraph/janusgraph#1604]
I have about 400 threads writing data to the janusgraph(hbase+es), because of the timeout exception of httpclient library used in the RestElasticsearchClient, I enable the WAL of janusgraph to automatically fix the secondary failures. However, the recovery process cannot fix all the failures and I have to re-run the JanusGraphFactory.startTransactionRecovery(graph, startInstant) from the startInstant again to get all the secondary failures fixed.
Any idea why this happens?
And what happens if the recovery failed? Is there any mechanism to handler this circumstance?
Thanks in advance.

**Comment by FlorianHockmann** [comment]
You already posted the same question to [janusgraph-users](https://groups.google.com/forum/#!topic/janusgraph-users/XrQJ15_c0cU) which is actually the right place for questions like these.
Please don't repost here, especially since we're only using issues for bug reports or feature requests.
