### ISSUE TITLE
Adjacent vertex optimization does not work

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1611]
When we query graph through  gremlin server all vertices deserialized as DetachedVertex, but  AdjacentVertexFilterOptimizerStrategy handle only JanusGraphVertex, those adjacent optimization can't apply

Not need handle only JanusGraphVertex, because all things do in [BaseVertexCentricQueryBuilder](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java#L109)  

Example of code

```
@Test
    void shouldNotFailedWithDetachedVertex() {
        final Graph graph = StorageSetup.getInMemoryGraph();
        GraphTraversalSource g = graph.traversal();
        g.addV("A").property("p", "1").as("a")
         .addV("A").property("p", "2").as("b")
         .addE("E").from("a").to("b")
         .iterate();
        g.tx().commit();
        g.withStrategies(AdjacentVertexFilterOptimizerStrategy.instance());

        Vertex v1 = g.V().has("p", "1").next();
        Vertex v2 = g.V().has("p", "2").next();
        v1 = DetachedFactory.detach(v1, false);
        v2 = DetachedFactory.detach(v2, false);

        assertTrue(g.V(v1).bothE("E").filter(__.otherV().is(v2)).hasNext());
    }

```

**Comment by porunov** [comment]
Fixed by #1612
