### ISSUE TITLE
Clean up Hadoop1 from doc and other places since Hadoop1 support was removed

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#162]
Since [Hadoop1 support was removed](https://github.com/JanusGraph/janusgraph/commit/0931a34c70168734be7da369a0c398fdb356693a), we should update the example command lines in [`docs/intro.txt`](
https://github.com/JanusGraph/janusgraph/blob/dc67ce73c08e79fa65b30bc8280861056070c573/docs/intro.txt#L153-L157) accordingly, because it's currently broken.

**Comment by jerryjch** [comment]
I will provide a PR.  Will also search for any other mention or occurrence of hadoop1

**Comment by mbrukman** [comment]
PR to fix this issue was merged.
