### ISSUE TITLE
Read Cassandra dirty data!

### ISSUE THREAD

**Issue by VforJuvenile** [JanusGraph/janusgraph#1639]
```
gremlin> :> g.V().has("aai-node-type","global-service-instance").valueMap()
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{update-time=[2019-06-13 03:01:41], aai-last-mod-ts=[1560395034320], service-instance-id=[604f5e42-65c8-4d40-99b0-0bb4d444b0ed], service-type=[Site2Tic], aai-uri=[/ebod-manager/global-service-instances/global-service-instance/604f5e42-65c8-4d40-99b0-0bb4d444b0ed], create-time=[2019-06-13 03:01:41], aai-created-ts=[1560394902141], source-of-truth=[MSO], tenant-id=[63a9213b-77a1-4a81-a06f-5bc6792e9ce7], tenant-name=[hss_1], aai-node-type=[global-service-instance], aai-uuid=[d6d34f7d-a0da-46a2-ab0c-ddae9b54f17c], resource-version=[1560395034320], name=[hqy-site2tic-L3-2], last-mod-source-of-truth=[MSO], status=[normal]}
```
Why empty data can be obtained through has() properties conditions!

**Comment by VforJuvenile** [comment]
I user janusgraph version is 0.2.0,cassandra version is 2.1.20 !

**Comment by porunov** [comment]
@VforJuvenile `0.2.x` version is EOL now. I would suggest to upgrade to `0.3.x` (the latest is 0.3.2 version) and check if this behavior still exists.

See upgrade instructions here: https://docs.janusgraph.org/latest/upgrade.html

Also, to reproduce this behavior by other people you should write reproduction steps.
1. Commands for schema creation (including indexes if they exist). If you are using mixed indexes you should also write an index storage name and version.
2. Commands for data upload.
3. Other commands which should be executed to reproduce this behavior.

**Comment by FlorianHockmann** [comment]
This looks like an issue of [ghost vertices](https://docs.janusgraph.org/0.3.2/eventual-consistency.html#ghost-vertices) which is a known issue of JanusGraph with eventually consistent backends like Cassandra. The linked section of the docs already mention some strategies to mitigate the issue.
