### ISSUE TITLE
bin/janusgraph.sh start fails if db directory does not exist

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1660]
While testing the [0.4.0 release candidate](https://github.com/JanusGraph/janusgraph/releases/tag/v0.4.0), I noticed that `bin/janusgraph.sh start` fails if the `db` directory does not exist already which is used by Cassandra and Elasticsearch to store data permanently.

This problem was likely introduced by the update of the Cassandra version.

Since the `janusgraph.sh` script already assumes that the `db` directory is used (it's hard coded in the `clean()` method), we can also directly create the directory if it doesn't exist already.

**Comment by FlorianHockmann** [comment]
Fixed with a [CTR commit](https://github.com/FlorianHockmann/janusgraph/commit/37343a6759f7f0b45a6ec9202d720cb2854e8450).

**Comment by porunov** [comment]
Should the staging Sonatype repository be deleted and reuploaded now?

**Comment by FlorianHockmann** [comment]
> Should the staging Sonatype repository be deleted and reuploaded now?

Yes, that's what I'll be doing next.
