### ISSUE TITLE
support for openCypher?

### ISSUE THREAD

**Issue by kant111** [JanusGraph/janusgraph#1661]
any plan to support openCypher natively? instead of cypher to gremlin conversion?

**Comment by vtslab** [comment]
JanusGraph relies on the TinkerPop graph traversal machine which only accepts gremlin bytecode. So, cypher to gremlin conversion cannot be avoided. See, the related thread on: [https://groups.google.com/forum/#!searchin/gremlin-users/opencypher%7Csort:date/gremlin-users/hNOE54h6U7k/iq6aUd-CBAAJ](https://groups.google.com/forum/#!searchin/gremlin-users/opencypher%7Csort:date/gremlin-users/hNOE54h6U7k/iq6aUd-CBAAJ)
Question like these as are best asked on the JanusGraph community forum at: [https://groups.google.com/forum/#!forum/janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)

**Comment by farodin91** [comment]
I would be good to add a document. how to use https://github.com/opencypher/cypher-for-gremlin with JanusGraph.

**Comment by peey** [comment]
These two issues are dupes https://github.com/JanusGraph/janusgraph/issues/1924

**Comment by peey** [comment]
And so is this https://github.com/JanusGraph/janusgraph/issues/161

**Comment by FlorianHockmann** [comment]
Thanks for noting @peey. I'll close this one and the other duplicate as #161 was the first issue for this feature request.
