### ISSUE TITLE
Example mvn clean install raise error

### ISSUE THREAD

**Issue by Litchilitchy** [JanusGraph/janusgraph#1663]
I am following the instructions of `readme.md` in example directory and when I go into the directory and `mvn clean install`, an error is raised

```
[FATAL] Non-resolvable parent POM for org.janusgraph:janusgraph-examples:
[unknown-version]: Could not find artifact org.janusgraph:janusgraph:pom:0.4.0 
in google-maven-central 
(https://maven-central.storage.googleapis.com/repos/central/data/) and 
'parent.relativePath' points at wrong local POM @ line 3, column 13
```
The mirror I am using is 
```
<mirror>
  <id>google-maven-central</id>
  <name>Google Maven Central</name>
  <url>https://maven-central.storage.googleapis.com/repos/central/data/</url>
  <mirrorOf>central</mirrorOf>
</mirror> 
```
I tried some other mirrors and also the same error, how to fix it?

**Comment by vtslab** [comment]
With the following in ~/.m2/settings.xml the mvn clean install works for me:
<settings>
  <mirrors>
    <mirror>
      <id>google-maven-central</id>
      <name>GCS Maven Central mirror</name>
      <url>https://maven-central.storage-download.googleapis.com/repos/central/data/</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
This is on a Ubuntu 18.04 system with maven-3.6.0 and java 1.8.
I suggest you remove your local cache at ~/.m2/repository/org/janusgraph and retry.
Questions like these are best asked on the JanusGraph community forum at: [https://groups.google.com/forum/#!forum/janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)

**Comment by porunov** [comment]
Closing as it is answered by @vtslab
