### ISSUE TITLE
where is janusgraph-distribution/lib folder?

### ISSUE THREAD

**Issue by lhaiq** [JanusGraph/janusgraph#1666]
the document(https://docs.janusgraph.org/0.3.2/hadoop-tp3.html) write i should  janusgraph-distribution/lib into /opt/lib/janusgraph/ ,but i can't find this folder.

**Comment by vtslab** [comment]
janusgraph-distribution/lib is placeholder folder name for a specific distribution, so for a distribution with version 0.3.2-hadoop2, the actual folder name would be janusgraph-0.3.2-hadoop2/lib

Questions like these are best posted on the janusgraph users community forum at: [https://groups.google.com/forum/#!forum/janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)

**Comment by porunov** [comment]
Closing as it is answered by @vtslab
