### ISSUE TITLE
Janusgraph 0.4.0 not available on Maven central

### ISSUE THREAD

**Issue by caamartin35** [JanusGraph/janusgraph#1669]
Janusgraph 0.4.0 release is not available on the maven central repository. I am able to get the 0.4.0 release and run the JanusGraphServer, but in trying to develop a Java client that interacts with it I am forced to use janusgraph-core 0.3.2 and janusgraph-core-hbase 0.3.2 resulting in methods/classes not existing. 

The methods/classes not existing is primarily a result of the jump from HBase 1.4.4 supported by JG 0.3.2 to HBase 2.1.5 supported by JG 0.4.0. I am running HBase 2.1.5 currently so I would like to use JG 0.4.0 on both the server and client side.

**Comment by porunov** [comment]
@caamartin35 I am not sure I understand your issue but JanusGraph 0.4.0 available at Maven central: 
https://search.maven.org/artifact/org.janusgraph/janusgraph-core/0.4.0/jar

Possible you are searching at another nexus which have some delays with repositories synchronization (like https://mvnrepository.com/artifact/org.janusgraph/janusgraph-core ).

**Comment by caamartin35** [comment]
Yep what you said was my problem. I couldn’t find it at the second link and assumed it wasn’t up there at all. I’ll close this, thanks
