### ISSUE TITLE
Utilizing Geoshape in client applications when connecting to Gremlin Server

### ISSUE THREAD

**Issue by MichaelMarkieta** [JanusGraph/janusgraph#167]
More a question than an issue -- would there be a way to add vertices or edges that have `class Geoshape` properties, or indexes using the `class Geoshape` as the datatype using client software that communicates through `gremlin-server`? Its not clear to me that its possible to, say, write a python script that uses all of what JanusGraph has to offer under the hood because I am not clear if we can leverage what gremlin-server has access too (e.g. `class Geoshape`, `function openManagement()`, etc).

**Comment by robertdale** [comment]
You can definitely do it through submitting groovy scripts.  To use the native GLV, you'll need serializers on both ends which I don't think are there for most things.

**Comment by robertdale** [comment]
See also #239

**Comment by robertdale** [comment]
@MichaelMarkieta  This should be resolved. Please close the issue.

**Comment by pluradj** [comment]
Closing. Thanks @robertdale
