### ISSUE TITLE
It's seems that by running bin/janusgraph.sh it's always expect a thrift driver is running (Cassandra). I want to connect external Cassandra service with the same command. Please let me know how to do it. Thanks

### ISSUE THREAD

**Issue by ARNABKUMARPAN** [JanusGraph/janusgraph#1713]
Without thrift

**Comment by mbrukman** [comment]
You've deleted the instructions that say GitHub issues are for feature requests or bug reports.

For support questions such as this one, please use mailing list or chat: https://github.com/JanusGraph/janusgraph/#community
