### ISSUE TITLE
Use EntryArrayList instead of StaticArrayEntryList

### ISSUE THREAD

**Issue by kptfh** [JanusGraph/janusgraph#1719]
Consider use EntryArrayList instead of StaticArrayEntryList to avoid data buffers copying in SliceQuery.getSubset().
StaticArrayEntryList copies all data buffers from elements to internal data buffer. EntryArrayList instead keeps elements as they are.

**Comment by mad** [comment]
Hi @kptfh 

But this approach may consume more memory because StaticArrayEntryList backed by primitive arrays, but EntryArrayList backed by object array, sometimes it may critical. Approx 16 times more

**Comment by porunov** [comment]
Fixed in #2084
