### ISSUE TITLE
Cassandra library mismatch in 0.4.0

### ISSUE THREAD

**Issue by oskar700** [JanusGraph/janusgraph#1727]
When working on a Spark reindexing job for JanusGraph with a Cassandra store I got this exception:

``
Exception in thread "main" java.lang.NoSuchFieldError: DEFAULT_SSL_CIPHER_SUITES
	at org.apache.cassandra.hadoop.cql3.CqlConfigHelper.getSSLOptions(CqlConfigHelper.java:533)
	at org.apache.cassandra.hadoop.cql3.CqlConfigHelper.getCluster(CqlConfigHelper.java:315)
``

This exception is thrown form the client code (in cassandra-all-2.2.13.jar) when attempting to access the constant DEFAULT_SSL_CIPHER_SUITES in the driver.
Driver version shipped with 0.4.0 is 3.7.1.  Inspecting the driver versions I found this constant was removed from the driver in version 3.0 and doesn't exist in any of the later versions.

**Comment by FlorianHockmann** [comment]
This seems to be basically the same issue as #1673, only that this is about SSL options and #1673 is about authentication options, but the underlying problems seems to be roughly the same.

**Comment by zblumen** [comment]
I think I am running into this issue on janusgraph 0.52 when attempting OLAP SParkGraphComputer traversals. 

janusgraph user group thread: [https://groups.google.com/forum/#!topic/janusgraph-users/eFHzJd_OF0s](https://groups.google.com/forum/#!topic/janusgraph-users/eFHzJd_OF0s)

Curious if there are plans to resolve this soon.  Looking over  #1673 , I think it fixed the issue with Mapreduce re-indexing, but not for OLAP traversal where this issue also exists.

**Comment by farodin91** [comment]
This problem will be resolved with our release of version 0.6. It is already fix in master.
