### ISSUE TITLE
Janus as an RDF store

### ISSUE THREAD

**Issue by ert5yrtjyfgdrfrt** [JanusGraph/janusgraph#174]
There seems to be a significant difference in the implementation of "graph/property stores" and "RDF stores". Is Janus a "graph/property store" or an "RDF store"? Or can it work with both models? For example, can I load RDF dumps such as DBPedia and Wikidata, and submit SPARQL queries to it?

**Comment by pluradj** [comment]
The issues tracker is for bug tracking. Please use the [mailing list](https://groups.google.com/d/msg/janusgraph-users/I4rW_KhcgFE/DpjNd8ECCwAJ) for general questions and answers like this one. Thanks!
