### ISSUE TITLE
Make full build work again.

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#1743]
The full build flag is not working as expected. For cassandra and cql tests, we have to activate docker-compose before and overwrite a config setting. 

Idea: Checkout to split up builds and try to activate tinkerpop tests.

**Comment by farodin91** [comment]
Scylla should be also tested with full build

**Comment by porunov** [comment]
@farodin91 is this issue resolved?
I see that we added ScyllaDB tests. I see only the next `FIXME` comment:
https://github.com/JanusGraph/janusgraph/blob/6310a22b28943be2458891cfcb5401147af3fd25/.github/workflows/ci-backend-cql.yml#L96

**Comment by farodin91** [comment]
I don't think it fixed yet

**Comment by farodin91** [comment]
I would say we could close this ticket.
