### ISSUE TITLE
janusgraph storage backend use hbase(1.4.9) error

### ISSUE THREAD

**Issue by fenglex** [JanusGraph/janusgraph#1745]
when use hbase for storage backend,with error "   org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend"
,and hbase table will not create ，The same problem did not happen in 0.3.1，all config is same

**Comment by farodin91** [comment]
Could you provide the test version?

**Comment by fenglex** [comment]
Test with janusgraph 0.4.0

**Comment by farodin91** [comment]
Do you checkout the upgrade instructions for hbase? https://docs.janusgraph.org/latest/upgrade.html

**Comment by fenglex** [comment]
I will try use hbase 2.1.*
