### ISSUE TITLE
 withRemote is deprecated

### ISSUE THREAD

**Issue by benben17** [JanusGraph/janusgraph#1747]
janusgraph 0.4.0 
<janusgraph.version>0.4.0</janusgraph.version>
<tinkerpop.version>3.4.1</tinkerpop.version> 
GraphTraversalSource g = graph.traversal().withRemote(DriverRemoteConnection.using(cluster));

when i use  "withRemote" ,i got withRemote is deprecated , How to Substitute it and fix it 
tks

**Comment by mad** [comment]
HI @benben17, can you press y for display full stack trace?

**Comment by farodin91** [comment]
Checkout this (section)[http://tinkerpop.apache.org/docs/3.4.3/reference/#connecting-gremlin-server] of the tinkerpop reference.

**Comment by benben17** [comment]
thx,solve it
