### ISSUE TITLE
Too much log/unneeded stack trace

### ISSUE THREAD

**Issue by devent** [JanusGraph/janusgraph#1763]
I tried out JanusGraph 0.4.0 and was surprised to have a NullPointerException in the logs. I then looked at the source and there was just `log.debug("Opened database {}", name, new Throwable());` Do we need the stack trace here? At least it should be a `log.trace` for the stack trace, i.e. something like

```
if (log.isTraceEnabled()) {
    log.trace("Opened database {}", name, new Throwable());
} else {
    log.debug("Opened database {}", name);
}
```

https://github.com/JanusGraph/janusgraph/commit/9c324de3df7e6c72adaab9ab69cd11e859a1e71f

```
20:03:27.898 [main] DEBUG org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager - Opened database janusgraph_ids
java.lang.Throwable: null
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.openDatabase(BerkeleyJEStoreManager.java:184)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.openDatabase(BerkeleyJEStoreManager.java:46)
```

**Comment by farodin91** [comment]
Do you like to remove the throwable?

**Comment by devent** [comment]
Do you need the stack trace in this place? Because the only point of the throwable is to have the stack trace. I don't know, it was added by @dalaro in 2014.

**Comment by farodin91** [comment]
It should only log the debug output.

**Comment by RushikeshSawant** [comment]
Hi @farodin91 I have created PR based on comments here: https://github.com/JanusGraph/janusgraph/pull/1862

Hope this address the issue.
