### ISSUE TITLE
it could not be sent to the server - Reason: org.apache.tinkerpop.gremlin.driver.ser.SerializationException: java.lang.IllegalArgumentException: Class is not registered: org.janusgraph.core.attribute.Geoshape

### ISSUE THREAD

**Issue by bingbingll** [JanusGraph/janusgraph#1786]

**Comment by FlorianHockmann** [comment]
Please use our community channels (like our [janusgraph-users Google group](https://groups.google.com/forum/#!forum/janusgraph-users) or our [Gitter chat](https://gitter.im/janusgraph/janusgraph)) for questions about problems like this one as indicated in the issue template you deleted when creating the issue.

Now for your concrete problem, you probably just need to add the JanusGraph io registry as shown [here](https://github.com/JanusGraph/janusgraph/blob/76afdc7d3bb0f997dd7bc926a685ef72ea742dd1/janusgraph-examples/example-remotegraph/conf/remote-objects.yaml#L20).
