### ISSUE TITLE
retry_on_conflict for mixed index

### ISSUE THREAD

**Issue by nareshbabuy** [JanusGraph/janusgraph#1797]
retry_on_conflict for mixed index
i have already fixed by overriding RestElasticSearchClient, 

can can find more details here :  https://groups.google.com/forum/#!searchin/janusgraph-users/retry_on_conflict%7Csort:date/janusgraph-users/ixIRJVQTqto/erbBXbUTAwAJ

**Comment by farodin91** [comment]
@nareshbabuy Do you like to work on it?

**Comment by nareshbabuy** [comment]
Yes, I have code ready. I will raise merge request
