### ISSUE TITLE
JanusGraph disable index on large schema

### ISSUE THREAD

**Issue by mohantyshubhram** [JanusGraph/janusgraph#1799]
Hi, 
As I am using Janus as the graph database for our product, I have across numerous occasions where index is out of sync with the graph contents.
This in turn results into inconsistencies within the product. In order to handle this I am using the various utilities provided by Janus. Now, in scenarios
where there is no other option than to rebuild index, the first step that I perform here is disableIndex . This works well for smaller schema, but what I 
observed recently is that when I perform the same on larger schema, the status of the index doesn't change from Installed to Disabled even after long wait.

As per IndexManagement link (https://docs.janusgraph.org/advanced-topics/index-admin/) , we can go for MapReduce option only for performing  following actions :
1. Reindex
2. RemoveIndex 

I am using the following code for disabling index as suggested in documentation :

m = graph.openManagement()
nameIndex = m.getGraphIndex('name')
m.updateIndex(nameIndex, SchemaAction.DISABLE_INDEX).get()
m.commit()
graph.tx().commit()

ManagementSystem.awaitGraphIndexStatus(graph, 'name').timeout(MAX_WAIT_TIME, ava.time.temporal.ChronoUnit.MINUTES).status(SchemaStatus.DISABLED).call() 

Even, I tried increasing the MAX_WAIT_TIME here, but the status doesn't change to DISABLED.

This works perfectly fine for smaller schema.

So, is there a way we can distribute this operation? I could not find much information about this in JanusGraph documentation.

Regards,
Shubhram

**Comment by FlorianHockmann** [comment]
@mohantyshubhram Please use our community channels for question like this one as we only use issues for feature requests or bug reports as indicated in the issue template you deleted while creating this issue. You can also find the community channels in [the README.md](https://github.com/JanusGraph/janusgraph#community).

**Comment by mohantyshubhram** [comment]
Hi Florian,
Thanks for reaching out. I am trying to post a topic in JanusGraph Users
group but I am getting the following error.
PFA the screenshot. Could you please assist me on this?

Regards,
Shubhram
