### ISSUE TITLE
java.lang.ExceptionInInitializerError when running CQL tests

### ISSUE THREAD

**Issue by fruch** [JanusGraph/janusgraph#1802]
I'm trying to run the CQL test with an external scylla server:
following the testing.md file, like that:

```
mvn clean install -pl janusgraph-cql -Dstorage.hostname=10.0.114.208 -Dtest=**/cql/*
```

all the tests are failing with the same error:
```
[ERROR] org.janusgraph.diskstorage.cql.CQLDistributedStoreManagerTest  Time elapsed: 10.343 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.janusgraph.diskstorage.cql.CQLDistributedStoreManagerTest.<clinit>(CQLDistributedStoreManagerTest.java:36)
```

**Comment by farodin91** [comment]
CQL Backend are no longer support a external server. You can only use a container. For scylla tests, you can use the profile `mvn clean install -pl janusgraph-cql -Pscylladb`.
