### ISSUE TITLE
Travis CI should run on release branch

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#182]
Travis CI is currently running using a branch safelist, which includes `master` and `coverity_scan` but not the `jg01` release branch.

**Comment by mbrukman** [comment]
I'm all for it, but can we please rename the `jg01` branch first? See [my proposal](https://groups.google.com/d/msg/janusgraph-dev/YLnWWeNi0Ug/CvMKlKxpEgAJ) on the mailing list; would love to get your thoughts on this.
