### ISSUE TITLE
"filter-partitioned-vertices" option seems to return "false" always.

### ISSUE THREAD

**Issue by inho1213** [JanusGraph/janusgraph#1825]
Hello.

All vertices in my JanusGraph cluster are using partition.
So I set "janusgraphmr.ioformat.filter-partitioned-vertices=true". (I am using OLAP with spark.)
But it does not work.

I found that JanusGraphHadoopSetupImpl's getFilterPartitionedVertices method returns always "false".

```
JanusGraphHadoopSetupImpl.java

public boolean getFilterPartitionedVertices() {
        return scanConf.get(JanusGraphHadoopConfiguration.FILTER_PARTITIONED_VERTICES);
}

BasicConfiguration.java

public<O> O get(ConfigOption<O> option, String... umbrellaElements) {
        verifyOption(option);
        O result = config.get(super.getPath(option,umbrellaElements),option.getDatatype());
        return option.get(result);
}

AbstractConfiguration.java

protected String getPath(ConfigElement option, String... umbrellaElements) {
        verifyElement(option);
        return ConfigElement.getPath(option,umbrellaElements);
}
```

"ConfigElement.getPath" returns "ioformat.filter-partitioned-vertices", but the "config" variable only contains "janusgraphmr.ioformat.filter-partitioned-vertices".

So I fixed "getFilterPartitionedVertices" temporarily like below code:

```
return JanusGraphHadoopConfiguration.FILTER_PARTITIONED_VERTICES.get(scanConf.getConfiguration().get(ConfigElement.getPath(JanusGraphHadoopConfiguration.FILTER_PARTITIONED_VERTICES, true), JanusGraphHadoopConfiguration.FILTER_PARTITIONED_VERTICES.getDatatype()));
```

I just set "ConfigElement.getPath"'s second argument "includeRoot" to "true".
After that the configuration works fine.
I think this is a bug.

Thanks.

**Comment by farodin91** [comment]
@inho1213 Thank you for the finding. Do you like to fix this issue?

**Comment by inho1213** [comment]
@farodin91 Please check https://github.com/JanusGraph/janusgraph/pull/1829
