### ISSUE TITLE
GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server.

### ISSUE THREAD

**Issue by EthanPhan** [JanusGraph/janusgraph#1826]
I'm getting an exception when try to traverse a graph using gremlin python. I'm running janusgraph 0.4.0 with `gremlin-server-configuration.yaml` without any modification.

This is the piece of code i used:

```
graph = Graph()
g = graph.traversal().withRemote(DriverRemoteConnection('ws://localhost:8182/gremlin','g'))
hkVertexId = g.V().has('airport', 'code', 'HKG').id().next()
```

the exception:
```
GremlinServerError                        Traceback (most recent call last)
<ipython-input-4-f1af277c0958> in <module>
----> 1 hkVertexId = g.V().has('airport', 'code', 'HKG').id().next()
      2 hkVertexId

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/process/traversal.py in next(self, amount)
     86     def next(self, amount=None):
     87         if amount is None:
---> 88             return self.__next__()
     89         else:
     90             count = 0

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/process/traversal.py in __next__(self)
     45     def __next__(self):
     46         if self.traversers is None:
---> 47             self.traversal_strategies.apply_strategies(self)
     48         if self.last_traverser is None:
     49             self.last_traverser = next(self.traversers)

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/process/traversal.py in apply_strategies(self, traversal)
    504     def apply_strategies(self, traversal):
    505         for traversal_strategy in self.traversal_strategies:
--> 506             traversal_strategy.apply(traversal)
    507 
    508     def apply_async_strategies(self, traversal):

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/driver/remote_connection.py in apply(self, traversal)
    146     def apply(self, traversal):
    147         if traversal.traversers is None:
--> 148             remote_traversal = self.remote_connection.submit(traversal.bytecode)
    149             traversal.remote_results = remote_traversal
    150             traversal.side_effects = remote_traversal.side_effects

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/driver/driver_remote_connection.py in submit(self, bytecode)
     52     def submit(self, bytecode):
     53         result_set = self._client.submit(bytecode)
---> 54         results = result_set.all().result()
     55         side_effects = RemoteTraversalSideEffects(result_set.request_id, self._client,
     56                                                   result_set.status_attributes)

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/driver/resultset.py in cb(f)
     88         def cb(f):
     89             try:
---> 90                 f.result()
     91             except Exception as e:
     92                 future.set_exception(e)

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/driver/connection.py in _receive(self)
     78             while True:
     79                 data = self._transport.read()
---> 80                 status_code = self._protocol.data_received(data, self._results)
     81                 if status_code != 206:
     82                     break

~/.env_tf20_p37/lib/python3.7/site-packages/gremlin_python/driver/protocol.py in data_received(self, message, results_dict)
    108         else:
    109             del results_dict[request_id]
--> 110             raise GremlinServerError(message["status"])

GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server.
```

My guess is that `gremlin-server-configuration.yaml` doesn't run the `scripts/empty-sample.groovy` but if I try to run the scrip like this:

```
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
```

I can not use `ConfiguredGraphFactory` and get this exception instead:

```
Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.
```

Can some one help me with this?

**Comment by EthanPhan** [comment]
by checking the log of gremlin-server and following the solution here `https://stackoverflow.com/questions/53185602/gremlin-python-connecting-to-existing-janusgraph`, I have resolved the issue.

**Comment by WolfgangFahl** [comment]
Why is this closed? I am running into the same error when running: 
`$ docker run -it -p 8182:8182 janusgraph/janusgraph`
as explained in https://docs.janusgraph.org/getting-started/installation/
and the python code from 
https://docs.janusgraph.org/connecting/python/

**Comment by FlorianHockmann** [comment]
@WolfgangFahl I just tried it and everything worked. Did you actually get the error described above or did the traversal simply fail because there was no vertex with the name `hercules` in the graph?

**Comment by WolfgangFahl** [comment]
@FlorianHockmann  thx for looking into this. I changed the test to:
    ```
   gV=g.V()
        # we have a traversal now
        #assert isinstance(gV,GraphTraversal)
        # convert it to a list to get the actual vertices
        vList=gV.toList()
```
and the toList() call fails.

**Comment by FlorianHockmann** [comment]
The code works for me. Could you please create a thread on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) for this with the full code? I think it makes more sense to discuss this over there than in a closed issue.

**Comment by WolfgangFahl** [comment]
Why is the issue closed if it does not work? Works for me is IMHO not a valid answer. I am trying to debug this with 

    docker run -it  janusgraph/janusgraph /bin/bash

**Comment by WolfgangFahl** [comment]
especially I wonder what https://stackoverflow.com/questions/53185602/gremlin-python-connecting-to-existing-janusgraph has to do with this error ... because that link is used as a reason to close the issue in the first place.

**Comment by FlorianHockmann** [comment]
@WolfgangFahl The issue is closed because the issue creator closed it himself. So he came to the conclusion that his issue was not caused by a bug in JanusGraph.
If you currently have a problem with JanusGraph then you can ask on janusgraph-users as I mentioned. But I see that you [already created a new thread there](https://groups.google.com/forum/#!topic/janusgraph-users/ZQIf4jpJWSM) and what you're describing there has nothing to do with this issue from what I can see except that you are also accessing JanusGraph from Python. That's why I suggest that we stop the discussion here.

**Comment by WolfgangFahl** [comment]
The current state of affairs is:

Accessing a Ubuntu 18.04 LTS docker via it's IP works. Accessing a MacOS 10.13.6 one whith localhost it doesn't. Now i'd like to know whether his is a version issue. How can i check that so we can decide whether the bug needs to be reopened? 

here is the full code as requested:

```
'''
Created on 28.03.2020

@author: wf
'''
import unittest

from gremlin_python import statics
from gremlin_python.structure.graph import Graph
from gremlin_python.process.graph_traversal import __
from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection

class JanusGraphTest(unittest.TestCase):


    def setUp(self):
        pass


    def tearDown(self):
        pass


    def testJanusGraph(self):
        graph = Graph()
        connection = DriverRemoteConnection('ws://localhost:8182/gremlin', 'g')
        # The connection should be closed on shut down to close open connections with connection.close()
        g = graph.traversal().withRemote(connection)
        # get the vertices
        gV=g.V()
        # we have a traversal now
        #assert isinstance(gV,GraphTraversal)
        # convert it to a list to get the actual vertices
        vList=gV.toList()
```

**Comment by WolfgangFahl** [comment]
Why is this closed? It does not work.

**Comment by FlorianHockmann** [comment]
@WolfgangFahl I don't see that these threads are all related to the same problem. They only seem to have in common that gremlin-python is used. From what I can see, the users who started those threads solved their problems so it doesn't make much sense to continue the discussion in either of these threads. Exactly the same also applies to this issue here.

The issue [you described on janusgraph-users](https://groups.google.com/forum/#!topic/janusgraph-users/ZQIf4jpJWSM) seems also to be very specific as you simply don't have enough disk space available apparently and completely unrelated to the other issues you mention and also to this issue here. So, please let us continue the discussion over there. If you have a different issue with JanusGraph, then you can simply create another thread on janusgraph-users for that.

**Comment by WolfgangFahl** [comment]
@FlorianHockmann shall I create a new specific issue for the failure of the docker image on MacOs?

**Comment by FlorianHockmann** [comment]
Yes, I think that a separate issue makes sense if it's not related to the disk space problem. I would also first create that on janusgraph-users as we can collect all necessary information there first and others might be able to help you troubleshoot the problem.

**Comment by ManfredLange** [comment]
For what it is worth: I ran into the same error message. What solved it for me was removing the JanusGraph container and create a new one. This may or may not work for others as well.

**Comment by rahul-bera-classplus** [comment]
I am getting same error with janusgraph /janusgraph:latest docker image gremlin-python 3.5 python 3.8 ! is this resolved ?

**Comment by farodin91** [comment]
@rahul-bera-classplus  If your are using configured graph factory, please checkout following doc https://docs.janusgraph.org/operations/configured-graph-factory/#overview with a hint to Graph traversal bindings section.

**Comment by Givemeurcookies** [comment]
Can confirm that the same issue happens on Windows using the JanusGraph Docker image. It never happens in a new install but after some time I get the `The traversal source [g] for alias [g] is not configured on the server.` error. Only using JanusGraph in development now so I just spin up a new docker when it happens.

Might be a bug caused by unexpected shutdown of JanusGraph as I sometimes have to kill Docker due to excessive RAM usage.

**Comment by ManfredLange** [comment]
Although, I can resolve this issue with ditching the container and creating a new one, I'd prefer I wouldn't have to do that.

My preference would be that a container, including the JanusGraph one is able to start successfully at least when it is started and shutdown using regular docker or docker-compose commands for gracefully shutting down the container.

How can I help with diagnosing this further?

**Comment by FlorianHockmann** [comment]
> [...] Therefore I'd like to dig a little deeper to understand what causes this and ideally find a solution that doesn't require re-creating the container.
> 
> How can I help with diagnosing this further?

This error most likely occurs because the configured storage backend could not be reached during startup of JanusGraph Server. If you're using Docker Compose and have the storage backend and JanusGraph in the same compose file, then this can happen if JanusGraph Server gets started by Docker Compose before the storage backend is completely started.
Restarting the JanusGraph server container usually helps in this scenario as it gives the storage backend enough time to start.

The JanusGraph Server docker container already employs a waiting strategy to wait for the storage backend to be up. The wait time can be configured with the [environment variable](https://github.com/JanusGraph/janusgraph-docker#docker-environment-variables) `JANUS_STORAGE_TIMEOUT` which is 60s by default.

Are you using the official JanusGraph docker image? Have you tried increasing this timeout value?

**Comment by WolfgangFahl** [comment]
I think this is a bug and should be fixed. I don't  understand why this ticket is closed. At least the message
```
[GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server.](https://github.com/JanusGraph/janusgraph/issues/1826#) 
```
is misleading and if this can only be solve upstream at ticket might be neede in the Apache Gremlin project itself. For me this is still a showstopper and i never tried again given the complicated necessary setup and the frustration involved in not being able to run things "out of the box".

**Comment by bonya** [comment]
I am running in the same issue on MacBook Pro with M1. I have fixed the issue by building ARM-based container locally from https://github.com/JanusGraph/janusgraph-docker.

**Comment by li-boxuan** [comment]
I agree that the error message is incomplete if not misleading. The rule of thumb is to look at the server-side logs to find the real exception.

**Comment by isohrab** [comment]
I faced this problem too. In my case I didn't changed anything in my code/environment. The only things that happened were:
1. Mac update
2. Docker update

So I just re-installed docker and everything worked as normal again.
Definitely the error message is misleading
