### ISSUE TITLE
Is Neo4j not open source?

### ISSUE THREAD

**Issue by zhouhao-learning** [JanusGraph/janusgraph#1835]
Is Neo4j a paid version? If you want to use it in an industrial project, you must pay for the Enterprise Edition, otherwise you can't use it?

**Comment by mbrukman** [comment]
Hi @zhouhao-learning, GitHub issues are only for submitting feature requests and bug reports, not for general questions or discussions; please use our email lists or chat for that.

That said, you're asking a legal question about Neo4j licensing on an issue for the JanusGraph project. Unfortunately, we cannot provide legal advice, especially about other projects' licensing terms. Please ask Neo4j themselves at http://github.com/neo4j/neo4j or better yet, have your lawyer review their licensing terms to make a final determination.

Best of luck in your graph project!

**Comment by zhouhao-learning** [comment]
@mbrukman 
I am very sorry, Could you give me a contact email address?

**Comment by mbrukman** [comment]
@zhouhao-learning — you're asking for a contact email address for Neo4j? We are not affiliated with Neo4j; please visit https://neo4j.com/ for further details, including their contact information. 

Looks like https://community.neo4j.com is where you can discuss Neo4j with other community members, so that may be helpful for you.

**Comment by zhouhao-learning** [comment]
@mbrukman 
No, no, I need an email address that can communicate with you.

**Comment by mbrukman** [comment]
@zhouhao-learning — please note that I am not a lawyer and cannot answer any legal or licensing questions. I also cannot provide private 1:1 support; if you have questions about JanusGraph, please take a look at our community support options: https://github.com/JanusGraph/janusgraph/#community .

If you are looking for paid graph consulting / support for your project, the folks at Expero can help you (they work with many graph databases, including JanusGraph): https://www.experoinc.com/solutions/graph

Hope this helps.

**Comment by zhouhao-learning** [comment]
@mbrukman 
I mean, can you give me an email address to contact you? I want to discuss Janus Graph with you, not Neo4j.
