### ISSUE TITLE
Documentation updates to support 0.1.0 release

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#184]
Documentation should be updated as described in [RELEASING.md](https://github.com/JanusGraph/janusgraph/blob/master/RELEASING.md#preparing-documentation) in preparation for the 0.1.0 release.

**Comment by mbrukman** [comment]
Note: https://github.com/JanusGraph/janusgraph/issues/203 should be addressed prior to closing this issue.

**Comment by mbrukman** [comment]
@sjudeng — does anything else need to be done prior to closing this issue? Looks like all PRs and issues referenced here have been merged & closed, respectively.

**Comment by sjudeng** [comment]
@mbrukman The only thing left that I'm aware of is updating [CHANGELOG.asc](https://github.com/JanusGraph/janusgraph/blob/325d6da8895ef329390df3a11f5e490f99160cba/CHANGELOG.asc) and [changelog.txt](https://github.com/JanusGraph/janusgraph/blob/325d6da8895ef329390df3a11f5e490f99160cba/docs/changelog.txt) to replace "TBD" with the actual 0.1.0 release date, which we don't know exactly yet. Not sure if that update needs to be tracked under this issue.

**Comment by mbrukman** [comment]
I don't think we should track in this bug; that should just be a step in the release instructions. I'm assuming we can release v0.1.0 as soon as all the issues on the milestone are closed, so I think we should close this issue and release as soon as the other issue is resolved. Thoughts?

**Comment by sjudeng** [comment]
Yep agreed.
