### ISSUE TITLE
Prepacked distribution on windows

### ISSUE THREAD

**Issue by mrvanti88** [JanusGraph/janusgraph#1865]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 0.4.0

I don't know if everyone knew this already but windows seems to not handle running Janusgraph "out of the box".

Error:
Gremlin server doesn't start.

Possible cause:
The function "find" in bash-scripts seem to collide with windows "find" function.

Possible solution:
In janusgraph.sh, change:

```
if [ -n "$VERBOSE" ]; then
        "$BIN"/gremlin-server.sh conf/gremlin-server/gremlin-server.yaml &
    else
        "$BIN"/gremlin-server.sh conf/gremlin-server/gremlin-server.yaml >/dev/null 2>&1 &
    fi
```
To:
```
if [ -n "$VERBOSE" ]; then
        "$BIN"/gremlin-server.bat conf/gremlin-server/gremlin-server.yaml &
    else
        "$BIN"/gremlin-server.bat conf/gremlin-server/gremlin-server.yaml >/dev/null 2>&1 &
    fi
```

**Comment by FlorianHockmann** [comment]
How are you trying to execute this script under Windows? It's a bash script. So, it's expected to not work under Windows (at least not if you're not using the WSL).

In the future, please post first on janusgraph-users as indicated in the issue template as we can better answer questions there or help with problems and if it's really a bug, we can still create an issue here and have more information then to actually tackle the bug.

**Comment by mrvanti88** [comment]
Sorry.

I didn't find anything on the subject of my problem so I thought it would be nice for you guys to either fix it or add it to janusgraph documentation.

Regards

**Comment by FlorianHockmann** [comment]
Thanks, we already have an issue for this: #950. So, I'm closing this one.

We don't seem to have many contributors who want to run JanusGraph on Windows. So, if you want to contribute, that would of course be more than welcome.
