### ISSUE TITLE
OLAP filters out vertices with no edges and no properties

### ISSUE THREAD

**Issue by PandaBlame** [JanusGraph/janusgraph#1866]
I find out that, when OLAP traverses, if a vertex has no edges and no properties, it will be filtered out. Is this necessary？

If it's necessary, may be need to add hints to the document. Because this problem bothered me for a long time. After checking my spark, yarn, HBase and janusgraph configurations, I had to check the code to find out this filtering operation.

**Comment by farodin91** [comment]
If you check out the code and you spot the interesting code lines, it would be good to add these code lines.

**Comment by PandaBlame** [comment]
> If you check out the code and you spot the interesting code lines, it would be good to add these code lines.

[https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java](url)

At line 186.

**Comment by farodin91** [comment]
Could add an example for your graph and how you create the graph? Config, Schema creation and graph.

This should only filter internal vertices.

**Comment by PandaBlame** [comment]
`gremlin.graph=org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph
gremlin.hadoop.graphReader=org.janusgraph.hadoop.formats.hbase.HBaseInputFormat
gremlin.hadoop.graphWriter=org.apache.tinkerpop.gremlin.hadoop.structure.io.gryo.GryoOutputFormat
gremlin.hadoop.defaultGraphComputer=org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer

gremlin.hadoop.jarsInDistributedCache=true
gremlin.hadoop.inputLocation=none
gremlin.hadoop.outputLocation=output
gremlin.spark.graphStorageLevel=MEMORY_ONLY
gremlin.spark.persistContext=true
gremlin.spark.persistStorageLevel=MEMORY_ONLY

spark.master=yarn
spark.deploy-mode=cluster
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.kryo.registrator=org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator

janusgraphmr.ioformat.conf.storage.backend=hbase
janusgraphmr.ioformat.conf.storage.batch-loading=false
janusgraphmr.ioformat.conf.storage.buffer-size=1024
janusgraphmr.ioformat.conf.storage.conf-file=
janusgraphmr.ioformat.conf.storage.connection-timeout=10000
janusgraphmr.ioformat.conf.storage.drop-on-clear=true
janusgraphmr.ioformat.conf.storage.hostname=bigdata173,bigdata172,bigdata171
janusgraphmr.ioformat.conf.storage.page-size=100
janusgraphmr.ioformat.conf.storage.parallel-backend-ops=true
janusgraphmr.ioformat.conf.storage.port=2181
janusgraphmr.ioformat.conf.storage.read-only=false
janusgraphmr.ioformat.conf.storage.read-time=10000
janusgraphmr.ioformat.conf.storage.setup-wait=60000
janusgraphmr.ioformat.conf.storage.transactions=true
janusgraphmr.ioformat.conf.storage.write-time=100000

janusgraphmr.ioformat.conf.storage.hbase.compression-algorithm=GZ
janusgraphmr.ioformat.conf.storage.hbase.short-cf-names=true
janusgraphmr.ioformat.conf.storage.hbase.skip-schema-check=false
janusgraphmr.ioformat.conf.storage.hbase.snapshot-name=janusgraph-snapshot
janusgraphmr.ioformat.conf.storage.hbase.snapshot-restore-dir=/var/folders/6j/qx_p_qn92s314cj36mkgzg9h0000gn/T/
janusgraphmr.ioformat.conf.storage.hbase.table=janusgraph`

No schema creation. I added a Vertex likes g.addV("vertex"). And then this  vertex been filtered out.

**Comment by farodin91** [comment]
I will check it later today.

**Comment by YevIgn** [comment]
If we need to filter out only system vertices (as the [comment](https://github.com/JanusGraph/janusgraph/blob/05f4f9436cf80c1eb9f3bcbdc6bbe94160f11805/janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java#L184) states) - can't we just return null for the schema vertices? I have created a sample change - https://github.com/JanusGraph/janusgraph/pull/1906
