### ISSUE TITLE
config factory failed

### ISSUE THREAD

**Issue by yuqin11** [JanusGraph/janusgraph#1869]
when i config janusgraoh factory as instruction, but i can ConfiguredGraphFactory.createConfiguration(new MapConfiguration(map)); i can not open graph:ConfiguredGraphFactory.open("graph1")

{
    "Exception-Class": "com.datastax.driver.core.exceptions.SyntaxError",
    "exceptions": [
        "com.datastax.driver.core.exceptions.SyntaxError"
    ],
    "message": "line 2:33  : syntax error...\n",
    "stackTrace": "com.datastax.driver.core.exceptions.SyntaxError: line 2:33  : syntax error...\n\n\tat com.datastax.driver.core.Responses$Error.asException(Responses.java:143)\n\tat com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)\n\tat com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:196)\n\tat com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:50)\n\tat com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:827)\n\tat com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:661)\n\tat com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1083)\n\tat com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1006)\n\tat io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)\n\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:725)\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:400)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:300)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\n"

**Comment by FlorianHockmann** [comment]
This sounds more like a usage error than a bug. As the text in the issue template that you deleted while creating this issue indicated, we don't use GitHub issues for usage questions like this one, but only for confirmed bugs or feature requests. But I see that you already created [a question for this on StackOverflow](https://stackoverflow.com/questions/58555302/why-janusgraph-config-factory-did-not-work) which is a better place for such a problem.
If it turns out in the end that there actually is a bug in JanusGraph resulting in this error, then we can still create an issue and have more information then to reproduce the problem and address it.

**Comment by yuqin11** [comment]
I don't think it's a usage error, any one who can help me solve it ? And nobody in stackoverflow knows how to solve this problem.





祝：身体健康 事业顺利
BEST WISHES
Qin Yu/余秦
 SJTU/上海交通大学
 Mechanical Engineering and Power Engineering
 机械动力工程学院
 Tel：15736075158
 E-mail：yuqinjh@sjtu.edu.cn
            1130255696@qq.com


 





------------------ 原始邮件 ------------------
发件人: "Florian Hockmann"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 晚上10:37
收件人: "JanusGraph/janusgraph"<janusgraph@noreply.github.com>;
抄送: "Qin Yu(余秦)"<1130255696@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JanusGraph/janusgraph] config factory failed (#1869)




This sounds more like a usage error than a bug. As the text in the issue template that you deleted while creating this issue indicated, we don't use GitHub issues for usage questions like this one, but only for confirmed bugs or feature requests. But I see that you already created a question for this on StackOverflow which is a better place for such a problem.
 If it turns out in the end that there actually is a bug in JanusGraph resulting in this error, then we can still create an issue and have more information then to reproduce the problem and address it.
