### ISSUE TITLE
How to ensure the lock when multi thread updates or inserts data？

### ISSUE THREAD

**Issue by aqzwy** [JanusGraph/janusgraph#1875]
When batch updating data, how to ensure that the data with the same ID is not updated at the same time

**Comment by FlorianHockmann** [comment]
Closed as we don't use GitHub issues for questions, but only for bugs or feature requests. Please ask your question instead in one of our community channels like our [janusgraph-users Google group](https://groups.google.com/forum/#!forum/janusgraph-users).
