### ISSUE TITLE
Is the vertex directed the edge to itself is a bug?

### ISSUE THREAD

**Issue by wjtien** [JanusGraph/janusgraph#1889]
gremlin> g.V(24600).inE()
==>e[7ib-izc-6c5-izc][24600-subscription->24600]
gremlin> g.V(24600).outE()
==>e[7ib-izc-6c5-izc][24600-subscription->24600]
gremlin> g.V(24600).bothE()
==>e[7ib-izc-6c5-izc][24600-subscription->24600]
==>e[7ib-izc-6c5-izc][24600-subscription->24600]
gremlin> g.V(24600).in()
==>v[24600]
gremlin> g.V(24600).out()
==>v[24600]

jg0.4、 cql

**Comment by FlorianHockmann** [comment]
Please ask questions like this one in one of our [community channels](https://github.com/JanusGraph/janusgraph#community). I'll close this one as we don't use issues for questions, but only for bug reports or feature requests.
If you think you found a bug, the best way is still to ask first for example on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) as we can better help you there. If we then confirm that it's a bug, we can still create an issue here with a more detailed explanation.

For your specific question: An edge that connects a vertex with itself is perfectly valid. So, I don't see why this should be a bug.
