### ISSUE TITLE
about VertexCache

### ISSUE THREAD

**Issue by lhaiq** [JanusGraph/janusgraph#1894]
hi,
 why GuavaVertexCache created in StandardJanusGraphTx,and StandardJanusGraphTx belong every thread, so ,GuavaVertexCache  can't be shared in muti thread.Is there any reason to do that?

**Comment by FlorianHockmann** [comment]
As the text in the issue template that you deleted while creating this issue already said, we don't use issues for questions like this one, but only for bug reports and feature requests. So, I'm closing this one.

Please use one of our community channels like [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) instead to ask questions.
