### ISSUE TITLE
Gremlin console - please include LinkedDataSail

### ISSUE THREAD

**Issue by darrenleeweber** [JanusGraph/janusgraph#190]
https://github.com/tinkerpop/gremlin/wiki/LinkedData-Sail

The examples at https://github.com/tinkerpop/gremlin/wiki/LinkedData-Sail#the-mechanics-of-linkeddatasail do not work using the `./bin/gremlin.sh` bundled with JanusGraph.  Please add the appropriate JAR dependencies for this.

In general, the use case is to have JanusGraph serve as the persistence layer and/or storage cache for linked open data traversals.

**Comment by darrenleeweber** [comment]
The sail functionality should be available, it was added to the console in
https://github.com/tinkerpop/gremlin/commit/d4410d81869069536014f0ced6b52d783bed2073

**Comment by twilmes** [comment]
Hi Darren.  The sail functionality that you're referencing was compatible with TinkerPop version 2.  JanusGraph is currently on Apache TinkerPop 3 (3.2.3 specifically).  TinkerPop moved to the ASF awhile ago and up to date docs & code can be found at [here](http://tinkerpop.apache.org/).  Having said that, there may be some work underway to upgrade the sail implementation according to this [thread](https://groups.google.com/d/msg/gremlin-users/nTXugSIzHc8/brUGQU-pCAAJ).

**Comment by darrenleeweber** [comment]
I need to follow up on those links ^^, but thought it might help to link over to a related attempt to get it working in https://github.com/joshsh/ripple/issues/64

**Comment by twilmes** [comment]
I'm going to close this one out and this can be reevaluated when a TinkerPop 3 compatible version of the sail implementation is available.
