### ISSUE TITLE
There is no Date class mixed index build

### ISSUE THREAD

**Issue by yuqin11** [JanusGraph/janusgraph#1904]
janusgraph 0.3.1 
How to build a mixed index with Date.class property?And how to retrive Date property? There is not any imformation in your doc.
for example here is doc about GeoShape data

**Comment by yuqin11** [comment]
[`GeoShape data`](https://docs.janusgraph.org/v0.3/index-backend/text-search/)

**Comment by FlorianHockmann** [comment]
Please ask usage questions in on of our [Community channels](https://grafana.seclab-apphost-gdata.gdata.de/d/0JW347-mk/hiveresultfetcher?orgId=1&from=now-24h&to=now) as we're only using issues for feature requests or bug reports as indicated in the issue template you deleted while creating this issue.
