### ISSUE TITLE
how to print schema 

### ISSUE THREAD

**Issue by hubuyt** [JanusGraph/janusgraph#1907]
graph = JanusGraphFactory.open('conf/gremlin-server/janusgraph-hbase-es.properties');
mgmt = graph.openManagement()
mgmt.printSchema()

I type code as  above  but exception has happen

![image](https://user-images.githubusercontent.com/11042146/70787249-3e5aee00-1dc9-11ea-9fbc-6799ada6c726.png)

**Comment by hubuyt** [comment]
![image](https://user-images.githubusercontent.com/11042146/70787624-086a3980-1dca-11ea-90ea-4d5564e77272.png)

**Comment by FlorianHockmann** [comment]
Please ask usage questions in on of our [Community channels](https://grafana.seclab-apphost-gdata.gdata.de/d/0JW347-mk/hiveresultfetcher?orgId=1&from=now-24h&to=now) as we're only using issues for feature requests or bug reports as indicated in the issue template you deleted while creating this issue.
