### ISSUE TITLE
JanusGraphManager  Question

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [JanusGraph/janusgraph#1910]
ERROR org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Could not invoke constructor on class org.janusgraph.graphdb.management.JanusGraphManager (defined by the 'graphManager' setting) with one argument of class Settings

How to solve？

**Comment by FlorianHockmann** [comment]
Please ask usage questions in on of our [Community channels](https://github.com/JanusGraph/janusgraph#community) as we're only using issues for feature requests or bug reports as indicated in the issue template you deleted while creating this issue.
