### ISSUE TITLE
Improve CQL Iterator performance

### ISSUE THREAD

**Issue by gguttikonda** [JanusGraph/janusgraph#1925]
CQLPagingIterator currently stores `lastPagingState`, this makes pagination of CQL easy. However, `getPagingState` can be little slow as it calculates md5sum of the entire resultset before returning the state. Since `lastPagingState` is not exposed outside the class, it can be modified to `getPagingStateUnsafe`. 

For confirmed bugs, please report:
- Version:  0.4.0
- Storage Backend: CQL
- Mixed Index Backend: Elastic
- Mailing list Thread URL:
- Steps to Reproduce:

**Comment by porunov** [comment]
Fixed by #1926
