### ISSUE TITLE
Configuration docs don’t specify where / how to update configuration

### ISSUE THREAD

**Issue by bionicles** [JanusGraph/janusgraph#1928]
The docs pages for configuration have examples for what the configuration should be, but don’t actually specify what 

I just want to deploy a load balanced autoscaling JanusGraph cluster with the cypher for Gremlin plugin using the JanusGraph docker on AWS ECS and point it at the managed Cassandra service endpoint 

cassandra.us-east-1.amazonaws.com:9142

this would allow our startup to have a scalable graph without needing to worry about servers. 

The problem is, the dockerfile isn’t set up for Cassandra and doesn’t include the cypher plugin. How do you think we could improve the docs to make this use case more clear?

It’d be great to easily deploy JanusGraph Serverless on AWS with a script/template like CDK or Terraform

**Comment by FlorianHockmann** [comment]
The documentation for the Docker image is currently handled in the JanusGraph/janusgraph-docker repository where you already created an issue for docs about how to configure it for Cypher: JanusGraph/janusgraph-docker#49.
How the image can be configured for Cassandra with environment variables is already explained [in the README.md](https://github.com/JanusGraph/janusgraph-docker#docker-environment-variables). If you think that anything is missing there, then you can create an issue for that in JanusGraph/janusgraph-docker.
