### ISSUE TITLE
Dependency janusgraph-core 0.4.1 not available in maven repository

### ISSUE THREAD

**Issue by wolf7691** [JanusGraph/janusgraph#1932]
The dependency janusgraph-core 0.4.1 is still not available in the maven repository.

**Comment by FlorianHockmann** [comment]
Yes because it wasn't released yet. The release will be announced here: https://groups.google.com/forum/#!forum/janusgraph-users
The GitHub releases page already lists the release but it's marked as _pre-release_ because it's only a release candidate at this point.
