### ISSUE TITLE
Reindexing should not be necessary when the index uses a new key

### ISSUE THREAD

**Issue by rngcntr** [JanusGraph/janusgraph#1947]
This is mostly related to #1190. 

From the [docs](https://docs.janusgraph.org/index-management/index-reindexing/):
> Graph Index and Vertex-centric Indexes describe how to build graph-global and vertex-centric indexes to improve query performance. These indexes are immediately available if the indexed keys or labels have been newly defined in the same management transaction. In this case, there is no need to reindex the graph and this section can be skipped.

This is indeed the case for Composite Indexes, as implemented by @FlorianHockmann in #1192.
Although, for relation type indexes (e.g. vertex-centric indexes) a newly created index will still require a reindex operation even if one of the sort keys is new and therefore the index will be empty. There exists a check on whether or not the relation type itself is new:
https://github.com/JanusGraph/janusgraph/blob/a368faedc94c5ffe61d152a1f6a31f1556681340/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java#L300
This should be extended to also set the status to ENABLED if at least one of the sortKeys is newly created.

**Comment by porunov** [comment]
Fixed by #1949
