### ISSUE TITLE
janusgraph-core 0.4.1 dependency causes "java.util is accessible from more than one module"

### ISSUE THREAD

**Issue by wolf7691** [JanusGraph/janusgraph#1948]
If I switch from janusgraph-core 0.4.0 to 0.4.1, I get errors like
The package java.util is accessible from more than one module: <unnamed>, java.baseJava(8390063)
if I use, e.g., java.utils.list or java.utils.map.

My environment is OpenJDK 11.0.5+10 on a Windows 10 machine.

**Comment by FlorianHockmann** [comment]
JanusGraph is currently only supported on Java 8. So, please try that and if the error still occurs, we can re-open this issue.
