### ISSUE TITLE
Fix printSchema() in Management api to show VCI label against Relation Index rather than Edge Index

### ISSUE THREAD

**Issue by Amiya29** [JanusGraph/janusgraph#1955]
VCI is unclear from current print schema.

---------------------------------------------------------------------------------------------------
Vertex Index Name              | Type        | Unique    | Backing        | Key:           Status |
---------------------------------------------------------------------------------------------------
name                           | Composite   | true      | internalindex  | name:         ENABLED |
vertices                       | Mixed       | false     | search         | age:          ENABLED |
---------------------------------------------------------------------------------------------------
Edge Index (VCI) Name          | Type        | Unique    | Backing        | Key:           Status |
---------------------------------------------------------------------------------------------------
edges                          | Mixed       | false     | search         | reason:       ENABLED |
                               |             |           |                | place:        ENABLED |
---------------------------------------------------------------------------------------------------
Relation Index                 | Type        | Direction | Sort Key       | Order    |     Status |
---------------------------------------------------------------------------------------------------
battlesByTime                  | battled     | BOTH      | time           | desc     |    ENABLED |
---------------------------------------------------------------------------------------------------

VCI is showing against Edge Index, where as VCI are showing under Relation Index.

Hence proposing Relation Index (VCI) will be more appropriate.  

Discussed at https://groups.google.com/forum/#!topic/janusgraph-users/4QceSPhKs0s

**Comment by steve-todorov** [comment]
Has there been any updates on this? :)

**Comment by mad** [comment]
Current output lack of index constants

It would be great if output print out by alphabetically order

**Comment by li-boxuan** [comment]
@mad Do you want to create a separate issue? The original problem proposed by this issue has been fixed in https://github.com/JanusGraph/janusgraph/pull/2489 as part of the 0.6.0 release.
