### ISSUE TITLE
Lucene query tokenizing for custom analyzer doesn't work properly

### ISSUE THREAD

**Issue by VladimirBogomolov** [JanusGraph/janusgraph#1962]
If use CustomAnalyzer with filter that returns more than one token for one analyzing word then get wrong lucene query.
For reproduce that bug you shold configure CustomAnalyzer with, for example SynonymFilter, RussianLuceneMorphology or something like.
Example.
I use SynonymFilter and I have query "clear", after tokenizer has been applied we get next tokens: "clear", "change", "modify", "unclutter", "alter" (https://www.synonym.com/synonyms/clear). Now tokens are used for building query and I have 
`+fieldName:clear +field:change +fieldName:modify +fieldName:unclutter +fieldName:alter`,
but should be 
`fieldName:clear field:change fieldName:modify fieldName:unclutter fieldName:alter`

- Version:  0.4.1, master branch has that bug too
- Storage Backend: Berkeley
- Mixed Index Backend: Lucene
- Mailing list Thread URL:
- Steps to Reproduce:

**Comment by porunov** [comment]
Fidex in #1963
