### ISSUE TITLE
[Doc] Explain in-memory backend usage in basic-usage section

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#1989]
https://docs.janusgraph.org/getting-started/basic-usage/#loading-the-graph-of-the-gods-into-janusgraph is probably the first thing a new user wants to try to play around with JanusGraph, yet it requires users to have an external storage backend configured and up. If there is some instruction on how to quickly run JanusGraph with an in-memory backend, that would be very newbie-friendly.

In-memory backend is introduced in https://docs.janusgraph.org/storage-backend/inmemorybackend/, but that would require some careful reading and exploration until users find this doc. Before that, they might have already given up. It would be nice to have it mentioned in the basic-usage section.

Maybe a janusgraph-inmemory.properties file can also be added to https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-dist/src/assembly/cfilter/conf and mention it in the basic-usage section.

**Comment by farodin91** [comment]
Thank you for the comment. Do you like to add such section? For me as long time user, it is hard to write such sections.

**Comment by li-boxuan** [comment]
Sure, will create a PR soon
