### ISSUE TITLE
Meta Properties of a vertex property missing after retrieving data from cassandra DB 

### ISSUE THREAD

**Issue by hotcoder** [JanusGraph/janusgraph#1996]
I am using Janus Graph and we are facing issue , when we want to handle meta properties of a vertex property , issue is meta properties are missing , we are not able to see them , i doubt on the class   `org.janusgraph.hadoop.formats.util.JanusGraphVertexDeserializer ` ,  here data is being deserialized , and i did not see any code to retrieve meta properties here , is this need to implemented or am missing something ?

janusgraph-hadoop-core-0.4.0  jar version

For complete details 

https://stackoverflow.com/questions/60221573/how-to-retrieve-meta-properties-defined-for-a-vertex-property-in-java-code

It seems their is code issue

**Comment by hotcoder** [comment]
@spmallette any suggestion please

**Comment by hotcoder** [comment]
@pluradj Plurad

**Comment by YevIgn** [comment]
@FlorianHockmann Looks like the root cause is easy to fix - opened PR - https://github.com/JanusGraph/janusgraph/pull/2173

It seems that decoding of meta-properties was simply missed for property vertices.
