### ISSUE TITLE
AbstractJanusGraphAssemblyIT.command

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#2024]
## Flaky Test

* **Test Name:** `JanusGraphScriptIT.testGraphOfTheGodsGraphSON:26->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:106->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:81->AbstractJanusGraphAssemblyIT.parseTemplateAndRunExpect:102->AbstractJanusGraphAssemblyIT.expect:121->AbstractJanusGraphAssemblyIT.command:160 expected: <0> but was: <1>`
* **Branch:** `master`

### Stack Trace

```[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 69.586 s <<< FAILURE! - in org.janusgraph.pkgtest.JanusGraphScriptIT

[ERROR] testGraphOfTheGodsGraphSON  Time elapsed: 69.393 s  <<< FAILURE!

org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

	at org.janusgraph.pkgtest.JanusGraphScriptIT.testGraphOfTheGodsGraphSON(JanusGraphScriptIT.java:26)

[INFO] 

[INFO] Results:

[INFO] 

[ERROR] Failures: 

[ERROR]   JanusGraphScriptIT.testGraphOfTheGodsGraphSON:26->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:106->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:81->AbstractJanusGraphAssemblyIT.parseTemplateAndRunExpect:102->AbstractJanusGraphAssemblyIT.expect:121->AbstractJanusGraphAssemblyIT.command:160 expected: <0> but was: <1>

[INFO] 

[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by porunov** [comment]
@farodin91 the `release` phase currently fails in master. Do you know what it might be?

**Comment by farodin91** [comment]
I'm on it. It is due to the following PR: https://github.com/JanusGraph/janusgraph/pull/1919.
The branch wasn't tested on newest master branch.
