### ISSUE TITLE
Trigger Travis CI jobs

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#2035]
For some reason, Travis CI stopped to execute any builds for JanusGraph. About half of the builds was finished in the latest build here https://travis-ci.org/JanusGraph/janusgraph/builds/660314394
After that no more jobs were picked up by Travis CI. I was trying to cancel the build, then I tried to restart some particular jobs. It didn't work. After that I tried to restart the whole build. It doesn't work still. For more than an hour now, TravisCI don't want to run any builds anymore in JanusGraph repository.
I was also tried to clear the whole cache in Travis CI and trigger custom build but it didn't work also.

Does anyone know what could be the reason for this?

**Comment by mbrukman** [comment]
I was thinking maybe we ran out of build minutes for the month, but it turns out that open source projects get unlimited build minutes (but parallelism is throttled), so that can't be the issue.

https://travis-ci.com/plans says (emphasis mine):

> # Free for Open Source
> We love Open Source and offer a free plan for your projects. **You will receive unlimited builds and 5 concurrent jobs for free,** along with all the other features you've come to love from Travis CI.

Should we consider alternative CI/CD solutions?

* [GitHub now provides free CI/CD](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/)
* [Circle CI](https://circleci.com/)
* etc.

**Comment by porunov** [comment]
Looks like 7 minutes ago 2 workers are started. We used to have 5 workers. Maybe TravicCI are making some changes. I think we can wait a little bit, if all 5 workers are live again, we will be able to close this issue

**Comment by porunov** [comment]
@mbrukman other CI/CD might be an option but we need to research their limitations for open source projects. If they have enough resources (workers, build minutes, etc.) then it might be a good option to switch to another CI/CD.

**Comment by porunov** [comment]
GitHub actions has 20000 build minutes per month (which we might easily run out of).
Circle CI has only 1 free concurent job with 2500 credits per week (the smallest machine takes 5 credits per minute). Definitely too small for us.

**Comment by porunov** [comment]
So, to understand out needs:
Simple build takes about 10 hours of build minutes - about 600 minutes. It is executed in about 2 hours with using 5 parallel workers.
Full build takes about 20 hours of build minutes - about 1200 minutes.

During the last week we executed about 40 builds (not all of them are executed fully but most of them does).
So, roughly 40 * 600 = 24000 build minutes per week. Or ~= 96000 build minutes per month.

**Comment by porunov** [comment]
All 5 Travic workers are live again, so I think the issue was temporary and it is now resolved
