### ISSUE TITLE
Vertex does not support user supplied identifiers

### ISSUE THREAD

**Issue by yuqin11** [JanusGraph/janusgraph#2049]
For discussion on internal implementation details of JanusGraph or proposing a [major new feature or subproject](https://docs.janusgraph.org/development/#development-decisions) use the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).

**Describe the feature:**
I want import billions of data into janusgraph, and i have unique ids of each vertex, import data with unique ids can spped import task . but janus graph do not support ids of vertex. 

**Describe a specific use case for the feature:**
I want to use this feature.
graph = TinkerGraph.open()
g = graph.traversal()
v1 = g.addV("person").property(id, 1).property("name", "marko").property("age", 29).next()

**Comment by porunov** [comment]
Set configuration parameter `graph.set-vertex-id` to `true` to use user supplied identifiers (https://docs.janusgraph.org/basics/configuration-reference/#graph).
```
v1 = g.addV("person").property(T.id, 1L).property("name", "marko").property("age", 29).next()
```

**Comment by porunov** [comment]
Please, use the next group to post questions about JanusGraph usage: https://groups.google.com/forum/#!forum/janusgraph-users
Use the next group to post questions about Gremlin usage: https://groups.google.com/forum/#!forum/gremlin-users

**Comment by yuqin11** [comment]
Hello I stiil have a question:

**Comment by yuqin11** [comment]
I still have a question:
when i configured ConfiguredGraphFactory  in gremlin-server
when the server is stopped for some reason.
when i restart the gremlin server.
the server get an error with: 
there hava an janusgraph xxxxxx-id has already been opened. 
can ConfiguredGraphFactory be reopened?

**Comment by yuqin11** [comment]
because i have configured many graph  in that ManagementConfigureGraph.

**Comment by yuqin11** [comment]
I visit the graph by 
ConfiguredGraphFactory.open("kgnlp_sddl");g1.trasversal().V().has(/xxx/,/xxx/)
