### ISSUE TITLE
Add pointers for accessing JanusGraph via other libraries

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#205]
We've received a number of questions for how to access JanusGraph from different programming languages, or native libraries with bindings to access JanusGraph other than Java.

We should either collect a set of well-tested libraries that work with JanusGraph either via TinkerPop or Gremlin, or link to existing lists such as:

* https://github.com/mohataher/awesome-tinkerpop#wrappers
* http://tinkerpop.apache.org/

that are maintained elsewhere.

**Comment by FlorianHockmann** [comment]
I agree that it would be a good idea to include this information in the documentation. It's a very important decision point for most people that evaluate different databases how good the support in their programming language is. Unfortunately, some people will probably not directly grasp completely how JanusGraph and TinkerPop are related and that they can check the TinkerPop website for such information.
But JanusGraph has a real advantage in this regard thanks to the Gremlin language variants (GLVs) which make it feel very natural to work with Gremlin compared to other databases where you usually have to construct some query string and send that manually to the database.
So the documentation could explain that JanusGraph can be queried with Gremlin and that therefore all Gremlin drivers can be used with JanusGraph. Then a short explanation of Gremlin language variants with a link to the respective section in the TinkerPop documentation would show how easy it is to work with Gremlin in one of the languages with a GLV (currently only Java, Groovy, and Python with JavaScript and C# under way).

**Comment by babarinde** [comment]
+1

**Comment by FlorianHockmann** [comment]
I wrote some documentation on how to connect to JanusGraph Server in general and from .NET in particular for the JanusGraph.Net library. Previews for these docs are available via GitHub:

* [Connecting to JanusGraph ](https://github.com/GDATASoftwareAG/janusgraph/blob/gremlin-dotnet-extensions/docs/connecting.adoc) is the main part of the added chapter.
* [Connecting from .NET](https://github.com/GDATASoftwareAG/janusgraph/blob/gremlin-dotnet-extensions/docs/connecting-via-dotnet.adoc) first explains how to connect to JanusGraph Server with just Gremlin.Net and the second part is for the JanusGraph.Net library.

If you think that this is going in the right direction, then I could add similar sections for Java and maybe Python and then create a PR for this ticket.
