### ISSUE TITLE
Wrong information about default backend in documentation

### ISSUE THREAD

**Issue by rngcntr** [JanusGraph/janusgraph#2069]
The [Docs](https://docs.janusgraph.org/getting-started/installation/#local-installation) state that executing `/bin/gremlin-server.sh start` without configuring a backend will use `inmemory` by default.

This is **not** the case.
If no backend was configured, a CQL-ES configuration is the default.

**Comment by porunov** [comment]
Related #2067

**Comment by rngcntr** [comment]
Thanks @porunov
As your PR targets v0.5, all earlier versions of the documentation should be updated to __not__ contain the part of the documentation, that does not apply to these versions

**Comment by porunov** [comment]
@rngcntr agree. Documentation should be updated

**Comment by porunov** [comment]
Fixed in #2070
