### ISSUE TITLE
the most stable version for enterprise is?for distribute database

### ISSUE THREAD

**Issue by JAVAnewerfee** [JanusGraph/janusgraph#2071]
For discussion on internal implementation details of JanusGraph or proposing a [major new feature or subproject](https://docs.janusgraph.org/development/#development-decisions) use the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).

**Describe the feature:**
TODO

**Describe a specific use case for the feature:**
TODO

**Comment by FlorianHockmann** [comment]
We're only using GitHub for feature requests or to report a bug. Please post questions like that in one of our community channels:
https://github.com/JanusGraph/janusgraph#community
