### ISSUE TITLE
valueMap's Execution is too slow

### ISSUE THREAD

**Issue by myYoungYan** [JanusGraph/janusgraph#2074]
i get a Vertex(uid:12) have 50W edges(lable:follow) ,  i call valueMap  make the total msec 131238.259 ,  how i can boost execution productivity??

`g.V().has('uid', 12).both("follow").valueMap().profile();
==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
JanusGraphStep([],[uid.eq(12)])                                        1           1           0.771     0.00
    \_condition=(uid = 12)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=multiKSQ[1]@2000
    \_index=byuidUnique
  optimization                                                                                 0.028
  optimization                                                                                 0.254
JanusGraphVertexStep(BOTH,[follow],vertex)                        500004      500004        1317.415     1.00
    \_condition=type[follow]
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=org.janusgraph.diskstorage.keycolumnvalue.SliceQuery@a462d1fc
    \_vertices=1
  optimization                                                                                 0.076
  backend-query                                                   500004                       0.011
    \_query=org.janusgraph.diskstorage.keycolumnvalue.SliceQuery@a462d1fc
PropertyMapStep(value)                                            500004      500004      129920.073    99.00
                                            >TOTAL                     -           -      131238.259        -`

**Comment by FlorianHockmann** [comment]
We're only using GitHub for feature requests or to report a bug. Please post questions like that in one of our community channels:
https://github.com/JanusGraph/janusgraph#community

I'd suggest posting this on [https://groups.google.com/forum/#!forum/janusgraph-users]. Please make sure however that you post all relevant information, including how many neighbours your starting vertex as as you return the `valueMap` of all neighbours of that vertex and please make especially sure that your data is properly formatted as it's hard to read like that.
