### ISSUE TITLE
Replace com.datastax.cassandra with com.datastax.oss

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#2091]
If we want to support cassandra 4 and higher, we have to replace the driver library. 

We already had a PR to do this: https://github.com/JanusGraph/janusgraph/pull/1733

**Comment by porunov** [comment]
Just small notice about #1733 . I remember when I was checking it, I noticed there several small bugs (like, sometimes it uses `isLessThan` instead of `isLessThanOrEqualTo` and similar misspells). So, if someone is using that PR as a base, make sure to check all prepared queries line by line.

**Comment by porunov** [comment]
Also, related / duplicate PR: #1510

**Comment by farodin91** [comment]
I didn' t saw this.
