### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#21]
We should use a service such as [Coveralls](https://coveralls.io/), [Codecov](https://codecov.io/), or [Circle CI](https://circleci.com/docs/code-coverage/)'s built-in support to track code coverage by tests.

Code coverage is an imperfect metric of test quality (necessary, but not sufficient), but it's an additional useful signal to keep in mind when assessing the quality of the overall test suite.

**Comment by fppt** [comment]
If I may suggest [Codecov](https://codecov.io/), the module coverage it provides is quite nice or at least not [Coveralls](https://coveralls.io/) because we had issues with it slowing down parallel builds.

**Comment by mbrukman** [comment]
[Codecov is set up](https://codecov.io/gh/JanusGraph/janusgraph) — we just need to add a tiny amount of config to our `.travis.yml` but since we're not running any tests during our Travis CI build, we'll likely get a consistent 0% coverage.

At this point, we need to fix our test suite to run within reasonable time limits and enable tests to run continuously, at which point we can enable Codecov to start gathering coverage measurements.

**Comment by FlorianHockmann** [comment]
I just saw the linked PR (#464) where this was added and that PR includes [a comment from Codecov](https://github.com/JanusGraph/janusgraph/pull/464#issuecomment-322971751) with the coverage report. Any reason why we don't have that any more?
I think Codecov is well hidden right now. I didn't even know that we still have it active :-/

@sjudeng maybe?
