### ISSUE TITLE
Update IBM entry on managed JanusGraph

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#2112]
The [`README.md`][readme-compose] "Users" section currently has a link in the managed offering subsection pointing to https://www.compose.com/databases/janusgraph which redirects to https://www.compose.com/ and in fact, there's no mention of "JanusGraph" anywhere on the front page of that website.

https://help.compose.com/docs/janusgraph-for-compose says:

> ### JanusGraph Deprecation
>
> As of September 2019, Compose will soon no longer support JanusGraph on the platform. Provisioning of new JanusGraph deployments is disabled.

That said, we can still find JanusGraph listed as an option:

* https://www.ibm.com/cloud/compose/janusgraph

However, this is still listed under "Compose" (which is documented as deprecated above), so is this also deprecated, but simply not updated?

Is JanusGraph no longer a managed offering by IBM Compose and should it be removed or should it be updated to point to a new location?

[readme-compose]: https://github.com/JanusGraph/janusgraph/blob/457b832315bba0e26806bfd776ff9bea4346bad9/README.md#users

**Comment by jdmintz** [comment]
JanusGraph is deprecated on Compose.com and remains Beta in the IBM Cloud

**Comment by FlorianHockmann** [comment]
Seems like JanusGraph is now completely unsupported on Compose:

> JanusGraph Deprecation
>
> As of September 2019, Compose will soon no longer support JanusGraph on the platform. Provisioning of new JanusGraph deployments is disabled.

https://help.compose.com/docs/janusgraph-for-compose#additional-resources-and-related-articles

@jdmintz Do you have any resource about JanusGraph in "IBM Cloud"? I searched for it but didn't find anything other than Compose.

But I think we should remove the mention from the README.md now. If there is something else from IBM for hosted JanusGraph, then we can still add that later back.

**Comment by jdmintz** [comment]
Hi Florian, it is no longer on Compose.com, although it remains available
as beta on IBM Cloud,
https://cloud.ibm.com/catalog/services/compose-for-janusgraph.

 You can remove it from the Readme for now.

-j

**Comment by FlorianHockmann** [comment]
Thanks for the explanation, @jdmintz. We've just removed it from the README.md.
