### ISSUE TITLE
Sift Security seems to no longer exist

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#2113]
We have _Sift Security_ as a production user in our [README.md](https://www.netskope.com/blog/welcoming-sift-security-to-netskope), but the link to https://siftsecurity.com/ is dead and they seem to no longer exist as a company as [they have been acquired by a company, called Netskope](https://www.netskope.com/blog/welcoming-sift-security-to-netskope).

I unfortunately cannot find any information about whether Netskope is now using JanusGraph so I guess that we simply have to remove them from the list of production users.

**Comment by FlorianHockmann** [comment]
@rcanzanese Can you maybe clarify this?

**Comment by rcanzanese** [comment]
Confirmed @FlorianHockmann  -- Netskope is not currently using JanusGraph.  Please remove us from the list of production users.
