### ISSUE TITLE
Error at start gremlin.sh

### ISSUE THREAD

**Issue by djuwa4** [JanusGraph/janusgraph#2114]
Hello! I download version janusgraph 0.4.0. Unpack, run /app/janusgraph-0.4.1/janusgraph-dist/src/assembly/static/bin/gremlin.sh 
And getting an error: line 42: cd: /app/janusgraph-0.4.1/janusgraph-dist/src/assembly/static/bin/../lib: No such file or directory

I run the file from user "root"

My java
java -version:
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

echo $JAVA_HOME: (Displays the correct location)
/usr/lib/jvm/jdk1.8.0_251

Please help fix
### Stack Trace (if you have one)

```
paste stack trace here
```

**Comment by djuwa4** [comment]
I forgot to say that the OS version: Ubuntu 16.04.6

**Comment by farodin91** [comment]
It seems you downloaded the source directory not the distribution. https://github.com/JanusGraph/janusgraph/releases/tag/v0.5.2 (JanusGraph-0.5.2.zip)

Please ask such questions on our user mailing list or on Gitter. 

Further, we are no longer support JanusGraph 0.4 as you can see in our changelog. https://docs.janusgraph.org/changelog/

**Comment by djuwa4** [comment]
> Кажется, вы скачали исходный каталог, а не дистрибутив. https://github.com/JanusGraph/janusgraph/releases/tag/v0.5.2 (JanusGraph-0.5.2.zip)
> 
> Пожалуйста, задавайте такие вопросы в нашем списке рассылки или в Gitter.
> 
> Кроме того, мы больше не поддерживаем JanusGraph 0.4, как вы можете видеть в нашем списке изменений. https://docs.janusgraph.org/changelog/

Confusion (((
You are right, I downloaded something!
Thank you very much!

**Comment by djuwa4** [comment]
> Кажется, вы скачали исходный каталог, а не дистрибутив. https://github.com/JanusGraph/janusgraph/releases/tag/v0.5.2 (JanusGraph-0.5.2.zip)
> 
> Пожалуйста, задавайте такие вопросы в нашем списке рассылки или в Gitter.
> 
> Кроме того, мы больше не поддерживаем JanusGraph 0.4, как вы можете видеть в нашем списке изменений. https://docs.janusgraph.org/changelog/

Confusion (((
You are right, I downloaded incorrectly.
Thank you very much!
