### ISSUE TITLE
Port 8182 not available

### ISSUE THREAD

**Issue by djuwa4** [JanusGraph/janusgraph#2124]
Hello!
I had a problem, after starting gremlin-server.sh network port 8182 does not accept connections. 
Also, I transfer the file ./bin/gremlin-server.sh ./conf/gremlin-server/...yaml
I am testing this with Postman, I am sending post request: { "gremlin": "g.V().next()"}
Tell me, how can I diagnose this problem?

- Version: 
Release 0.4.0 JanusGraph (Unfortunately, this version is needed);
Ubuntu 18.4.4
- java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

- $JAVA_HOME
/opt/jdk1.8.0_251

**Comment by djuwa4** [comment]
After starting the file ./gremlin-server.sh, i see a error:  org.apache.tinkerpop.gremlin.server.GremlinServer.errors
firewall uwf disable

**Comment by djuwa4** [comment]
I also want to note that I am doing a standard installation, not in docker.

**Comment by djuwa4** [comment]
Here is a series of error messages that I get after starting the file gremlin-server.yaml:
5252 [main] INFO  com.datastax.driver.core.GuavaCompatibility  - Detected Guava                               
 < 19 in the classpath, using legacy compatibility layer
5725 [main] INFO  com.datastax.driver.core.Native  - Could not load JNR C Library, native system calls through this library will not be available (set this logger level to DEBUG to see the full stack trace).
Gremlin Server.  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implem                               entation [class org.janusgraph.core.JanusGraphFactory]
 /192.168.17.203:9042 (com.datastax.driver.core.exceptions.TransportException: [/192.168.17.203:9042] Cannot connect))
15655 [gremlin-server-exec-1] ERROR org.apache.tinkerpop.gremlin.jsr223.DefaultG                               remlinScriptEngineManager  - Could not create GremlinScriptEngine for gremlin-groovy
java.lang.IllegalStateException: javax.script.ScriptException: javax.script.Scri                               ptException: groovy.lang.MissingPropertyException: No such property: graph for class: Script1
Caused by: javax.script.ScriptException: javax.script.ScriptException: groovy.la                               ng.MissingPropertyException: No such property: graph for class: Script1
Caused by: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: graph for class: Script1
Caused by: groovy.lang.MissingPropertyException: No such property: graph for class: Script1
org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Could not initialize gremlin-groovy GremlinScriptEngine as init script could not be evaluated
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine

**Comment by farodin91** [comment]
hi @djuwa4 Please use the template if your are reporting issues, as we say in the template configuration would be helpful. Simple http request wont if you doesn't activated the http part. So did you activated the http. Normal communication happens via websocket. 

PS: We no longer support JanusGraph 0.4, as you can see in our doc: https://docs.janusgraph.org/changelog/. Please verify issue using a newer version.

**Comment by djuwa4** [comment]
Thank!
How to activate http ? Can I see the manual?

> Simple http request wont if you doesn't activated the http part. So did you activated the http.

**Comment by farodin91** [comment]
https://docs.janusgraph.org/basics/server/#janusgraph-server-as-a-http-endpoint

**Comment by djuwa4** [comment]
> https://docs.janusgraph.org/basics/server/#janusgraph-server-as-a-http-endpoint

Thank you very much!
To file gremlin-server.yaml, I needed to add this: 
channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer

**Comment by farodin91** [comment]
Seems to be solved so open if you're problem isn't resolved.
