### ISSUE TITLE
Documentation is missing link to API docs

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#213]
The [javadoc page](http://docs.janusgraph.org/0.1.0-SNAPSHOT/javadoc.html) should include a link to the API documentation (see corresponding [Titan page](http://s3.thinkaurelius.com/docs/titan/1.0.0/javadoc.html)).

**Comment by nelsonw2014** [comment]
It appears that the javadocs are not even being generated yet, so either a new issue should be created, or this issue should be updated to reflect that

**Comment by mbrukman** [comment]
The link should point to https://javadoc.io/doc/org.janusgraph/janusgraph-core which will automatically redirect to the latest version, but all versions are accessible there via the dropdown.
