### ISSUE TITLE
Spark batch mode getting failed

### ISSUE THREAD

**Issue by rafi12396** [JanusGraph/janusgraph#2130]
I am using Spark to load JanusGraph data in rdd.
 I am able to get the janusgraph vertices in rdd but face the following exception on using collect() on rdd.

[ org.apache.spark.SparkException: Job aborted due to stage failure: Exception while getting task result: org.apache.tinkerpop.shaded.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.janusgraph.core.attribute.Geoshape ]
I have the below rdd that contains **VertexWritable** objects , but when use **res16.collect()**, it fails with the above exception.
**res16**: org.apache.spark.rdd.RDD[org.apache.tinkerpop.gremlin.hadoop.structure.io.VertexWritable] = MapPartitionsRDD[1] at map at <console>:40

**Comment by rafi12396** [comment]
I am using the JanusGraphKryoRegistrator for serialization.

**Comment by farodin91** [comment]
It would be helpful, if you use the template for a bug. Could you reopen the bug using the template?
