### ISSUE TITLE
Milestone link in changelog should show closed issues

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#214]
Currently [the link](https://github.com/JanusGraph/janusgraph/blob/0.1/docs/changelog.txt#L41) is to https://github.com/JanusGraph/janusgraph/milestone/1. Should this instead be changed to https://github.com/JanusGraph/janusgraph/milestone/1?closed=1 so it shows all completed items in release?

**Comment by ptgoetz** [comment]
+1 Not too big a deal, but I noticed the same thing.

**Comment by sjudeng** [comment]
This is fixed in the 0.1.1 release.
