### ISSUE TITLE
Add support to AWS Keyspaces (or DynamoDB) as storage backend

### ISSUE THREAD

**Issue by nicolomarchicw** [JanusGraph/janusgraph#2154]
For discussion on internal implementation details of JanusGraph or proposing a [major new feature or subproject](https://docs.janusgraph.org/development/#development-decisions) use the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).

**Describe the feature:**
Add the possibility to use AWS Keyspaces as storage backend since it is a SaaS service and compatible with Cassandra. Or add the possibility to use AWS DynamoDB as storage backend using the old connector made by AWS Labs.
These could be good feature since developers could use managed services and avoid the difficulty in manage an "important storage like Cassandra"

**Describe a specific use case for the feature:**
In a completely SaaS architecture is common to have DBs and other technologies provided as a service. Have the possibility to connect Janus to an already existing (for other purposes) Keyspaces cluster or DynamoDB endpoint gives the possibility to have all data in a single service.

**Comment by farodin91** [comment]
Such questions should ask on the developer mailing list.

**Comment by nicolomarchicw** [comment]
Hi @farodin91 , asked on the mailing list. 
Thank you and sorry for the wrong place for the issue.

Cheers.
Nicolò
