### ISSUE TITLE
documentation packaging

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#216]
The documentation should be packaged as a convenience distribution. This could be done by including it with the binary distribution (similar to the javadoc). Alternatively, this could be a separate documentation distribution (perhaps include javadoc here, instead of with the binary). If it is a separate docs distribution, it should contain the LICENSE and NOTICE.

**Comment by chupman** [comment]
a zip of the docs is already available on the release page so I think this is already completed. @pluradj did you want to also have the docs in a pdf form? Or is this ok to close?
