### ISSUE TITLE
Failed to start on JDK 11

### ISSUE THREAD

**Issue by nnanda2016** [JanusGraph/janusgraph#2161]
My env:
- MacOS Catalina (v10.15.5)
- Java: OpenJDK 11.0.7
- Janusgraph: 0.5.2

Following the documentation at https://docs.janusgraph.org/getting-started/installation/ I tried to start a local instance. But it failed with following error.

```bash
java -version
openjdk version "11.0.7" 2020-04-14 LTS

./janusgraph.sh start -v
Forking Cassandra...
Running `nodetool statusthrift`.Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Is it a known bug? Could someone tell me what's the workaround?

**Comment by li-boxuan** [comment]
As the doc suggests,
> In order to run JanusGraph, Java 8 SE is required

Btw gitter and mailing list are more appropriate places to ask questions.

**Comment by porunov** [comment]
The PR to add support fir jdk 11 in Gremlin is just added: https://github.com/apache/tinkerpop/pull/1299 

TinkerPop will bring jdk 11 support in version 3.5.0 (not released yet). We are expecting to add jdk 11 support after the upgrade.

Current JanusGraph versions don't support jdk 11.

**Comment by i-davydov** [comment]
Any update?

**Comment by porunov** [comment]
@i-davydov TinkerPop added jdk 11 support for TinkerPop version 3.5.0 but that version isn't released yet.
You can search for available TinkerPop versions here: https://github.com/apache/tinkerpop/releases

**Comment by shyamremella** [comment]
@porunov - couple of questions 
1.  Is there a potential release date for Janusgraph 0.6 release?
2. what does experimental support for Java 11 stand for? should we not move our java infra to jdk 11 with 0.6 yet or any known issues with it? 
Thank you!

**Comment by porunov** [comment]
> Is there a potential release date for Janusgraph 0.6 release?

We are waiting on TinkerPop 3.5.1 right now. I created a topic for that release here: https://lists.apache.org/thread.html/r5c3e754750a2b20d4d06ba1cae1baaa3c6bd93fcd24f46ef20a5e55b%40%3Cdev.tinkerpop.apache.org%3E
I don't know when TinkerPop 3.5.1 will be released, so can't say for sure when JanusGraph 0.6.0 will be released.
You can follow discussion around JanusGraph 0.6.0 release here: https://github.com/JanusGraph/janusgraph/pull/2672

**Comment by porunov** [comment]
> what does experimental support for Java 11 stand for? should we not move our java infra to jdk 11 with 0.6 yet or any known issues with it?

We didn't test Java 11 support against all test cases as we do with Java 8. That said, JanusGraph 0.6.0 should be compatible with Java 11. If you are using CQL storage backend you are most likely to be fine as it is covered by Java 11 tests.

**Comment by shyamremella** [comment]
Thank you @porunov

**Comment by farodin91** [comment]
Everything is tested against java so we can close this issue.
