### ISSUE TITLE
Custom Keep-Alive strategy for ES client

### ISSUE THREAD

**Issue by debelyoo** [JanusGraph/janusgraph#2167]
**Describe the feature:**
Allow custom Keep-Alive strategy for ES rest client.

**Describe a specific use case for the feature:**
In our current network setup, there are strict FW rules that trigger every 30 minutes and close the open connections between the cluster nodes. We thus observe `Connection reset by peer` errors between JanusGraph and ES, similar to the errors described in this post: https://stackoverflow.com/questions/52997697/how-to-get-around-connection-reset-by-peer-when-using-elasticsearchs-restclie.
Using a custom Keep-Alive strategy (with a fairly short timeout) will prevent ES rest client to use a connection that has been idle for long and that may be broken due to the strict FW rules.

**Comment by lionelfleury** [comment]
Indeed. It looks like the ES nodes don't set any Keep-Alive header.

So setting it at HttpClient level might be reasonable IMO.

Refs.: 
- https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html
- https://hc.apache.org/httpcomponents-asyncclient-4.1.x/
