### ISSUE TITLE
How janusgraph0.5.2 runs on Hbase 1.x

### ISSUE THREAD

**Issue by MikuSugar** [JanusGraph/janusgraph#2179]
As in the question, I want janusgraph to run on Hbase 1.4.10, but an error is reported during startup.
After searching, I saw a similar problem at https://github.com/JanusGraph/janusgraph/issues/1723. The solution here is to build with the hbase1 configuration file. I tried to package with hbase1 configuration file. The maven command is as follows "mvn clean package -DskipTests -Drat.skip=true -Phbase1", but it cannot be packaged smoothly.
How can I change it to run on hbase 1.x

**Comment by MikuSugar** [comment]
Can you tell me the specific steps to build the distribution, thank you very much

**Comment by MikuSugar** [comment]
I found this command "mvn clean install -DskipTests -Drat.skip=true -Pjanusgraph-release -Dgpg.skip=true", but adding -Phbase1 to this command still uses the configuration of hbase2. Finally, I chose to manually modify all hbase2 configurations in the Pom file, and the problem is probably solved.

**Comment by wahahasssss** [comment]
can you tell me where are all all hbase2 configurations in the Pom file

**Comment by wahahasssss** [comment]
@MikuSugar can you tell me where are all the hbase2 configurations?

**Comment by godofwharf** [comment]
With this maven command we are able to build Janus Graph 0.6.1 for use with HBase 1 server, `mvn clean install -pl janusgraph-hbase -am -DskipTests -Denforcer.skip=true -Drat.skip=true -Dgpg.skip=true -Dhbase.profile -Pjanusgraph-release,hbase1`.
