### ISSUE TITLE
Check which GremlinServer is being used by JanusGraph container

### ISSUE THREAD

**Issue by winaterion** [JanusGraph/janusgraph#2180]
Hi,
I'm using the latest docker image under Kubernetes.
I tried to found out which gremlin server the current release is using but without any luck.
Accessing the container itself, and searching in the files did give me a good clue.

**Comment by mbrukman** [comment]
FWIW, you can see the `Dockerfile` source for each of the container versions in the https://github.com/JanusGraph/janusgraph-docker repo, which should help identify their contents, as they simply download the appropriate JanusGraph release and install them in the container.
