### ISSUE TITLE
what is the prefered scenario to back up and restore data when using Cassandra and ES embedded

### ISSUE THREAD

**Issue by ChenZhaobin** [JanusGraph/janusgraph#2183]
Hey, guys
What is the right way to back up and restore data  when using Cassandra + ES +ganusgraph?
Specificly,I need help to find a scenario to back up data automaticly and if some bad thing happened ,I can restore the whole system from back up data.
It will be very appreciate if someone help me out.

**Comment by FlorianHockmann** [comment]
Please ask usage questions like this in one of our [community channels](https://github.com/JanusGraph/janusgraph#community) as we're only using GitHub issues for feature requests or for confirmed bug reports.
Now to still give you a very brief answer: JanusGraph doesn't have its own backup mechanism so you can simply use the backup mechanism of your backends, in your case ES and Cassandra.

**Comment by ChenZhaobin** [comment]
@FlorianHockmann got it ,pretty rich info, helps a lot,thanks
