### ISSUE TITLE
Janusgraf + ScyllaDB

### ISSUE THREAD

**Issue by djuwa4** [JanusGraph/janusgraph#2191]
Good day!
1) I use JanusGraph in conjunction with ScyllaDB. I am planning to use  ScyllaDB in a clustered version. For this I need to not just create a keyspace: storage.cql.keyspace=janusgraph 
And create it with additional parameters: WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}

Is it real? If so, how can I do this?
2) Do I understand correctly that  JanusGraph creates a  keyspace  once and then works with it without deleting it? And he makes all further changes in this  keyspace?

If so, then it turns out I can just make the changes I need to the already created keyspace?

**Comment by mbrukman** [comment]
You deleted the issue template provided, which says that GitHub issues are only for specific feature requests or bug reports, not for open-ended questions or discussions.

You've also posted this question [on the mailing list](https://groups.google.com/g/janusgraph-users/c/4wBTo3tzGVc/m/15GcsBUOBQAJ), which was the correct forum, so closing this issue.
