### ISSUE TITLE
janusgraph + ElasticSearch + Hbase how to configure elasticsearch's kerberos configuration

### ISSUE THREAD

**Issue by Hok1** [JanusGraph/janusgraph#2199]
hello
now I want to use janusgraph with elasticsearch and hbase in my cluster.
In my cluster , elasticsearch support kerberos.
so when I use janusgraph with elasticsearch,I need to configure the configuration about elasticsearch'kerberos.
but I could not find any information about this, even in https://docs.janusgraph.org/

please help me how to configure the kerberos in janusgraph with elasticsearch.
Or tell me if janusgraph with elasticsearch support kerberos

**Comment by li-boxuan** [comment]
Hi, we're only using GitHub for feature requests or to report a bug. Please post questions in one of our community channels:
https://github.com/JanusGraph/janusgraph#community
