### ISSUE TITLE
Add fuzzy predicate on all mixed indexes backend

### ISSUE THREAD

**Issue by davidclement90** [JanusGraph/janusgraph#221]
This adds fuzzy predicate (similarity based on Levenshtein edit distance) for all mixed indexes backend.
For the method evaluateRaw of the predicate, I use the same degree of similarity as ES :

0 for strings of one or two characters
1 for strings of three, four or five characters
2 for strings of more than five characters

**Comment by sjudeng** [comment]
Closing after merge of #219
