### ISSUE TITLE
Allow to use custom analyser with ES 

### ISSUE THREAD

**Issue by davidclement90** [JanusGraph/janusgraph#222]
This feature allows to use custom analyser ES for String type instead of no analyser for mapping.STRING or default ES analyser (split on non-alphanumeric tokens then lowercase) for Mapping.TEXT.
Custom analyser allows to use specific indexing for special property.
For example, it could be good to use phonetic analyser to match more on a _last name_ property.

This feature will impact all String Predicates.
For _Equals_, _NotEquals_ and _Contains_ predicates, we should use ES query _match_ instead of _term_ because _match_ go through ES analyser.

For _Prefix_, _ContainsPrefix_, _Regex_ and _ContainsRegex_, I do not know because ES query _prefix_ and _regexp_  do not go through analyser.
The big issue is if we use _ContainsPrefix_ or _ContainsRegex_ on a property which have uppercase analyser, it will never match because JanusGraph convert value to lower case .
I propose to keep the actual code for  _Prefix_ or _Regex_ and to do for _ContainsPrefix_ or _ContainsRegex_ : 
- if the property use default analyser, we keep the actual code for backward compatibility.
- if not, we suppress the conversion to lowercase.

**Comment by sharpau** [comment]
I currently have (for Titan) a piece of code that uses ES' REST API directly to set a custom analyzer on a Titan index. It would be great to replace this workaround with some JanusGraph configuration to make it less brittle. However, considering it is a viable workaround, I think other features are higher priority.

**Comment by davidclement90** [comment]
I do the same but with the https://github.com/JanusGraph/janusgraph/pull/233 thus JanusGraph will check if the mapping is good instead of push it.
