### ISSUE TITLE
How to get the direction of the edge when using 'path()'

### ISSUE THREAD

**Issue by py463360578** [JanusGraph/janusgraph#2223]
When I search the paths from a vertex within 3 steps, I can get the paths, and know the edges and vertice traversaled of each path. But the edge objects don't show its directon, so I can't get the start vertex and end vertex of each edge. How can I deal with it ?
![image](https://user-images.githubusercontent.com/40166488/94130414-33bca180-fe8f-11ea-8fb3-14f3e3ff7b75.png)

**Comment by FlorianHockmann** [comment]
We're only using GitHub for feature requests or to report a bug. Please post questions like that in one of our community channels:
https://github.com/JanusGraph/janusgraph#community
