### ISSUE TITLE
Remove all hints of Ganglia from docs and config files.

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#2230]
**Describe the feature:**
We already dropped ganglia in version 0.6.0.

**Describe a specific use case for the feature:**
It be good to remove these changes, to prevent confusion.

**Comment by jiyoungsin** [comment]
Can you please explain where I could find this ganglia?

**Comment by jiyoungsin** [comment]
I see some comments and some key value pairs. Am I correct in saying you would like me to remove these lines of code?

**Comment by jiyoungsin** [comment]
May I please have this issue?
