### ISSUE TITLE
Docs on migration from Titan to JanusGraph

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#224]
Given the interest in migrating from Titan to JanusGraph, users need a clear documentation and guidance for how to migrate their databases and switch from Titan to JanusGraph, with as little work as possible, ideally without data migration.

Here's a [sample user question](https://groups.google.com/d/msg/janusgraph-users/BhNVNHvJD90/MxXDYbAcCQAJ) from the janusgraph-users@ mailing list which demonstrates the need for this.

This guide should:

- [ ] demonstrate how to migrate from Titan to JanusGraph using all storage systems that Titan 1.0 and 1.1 (unreleased) supported
- [ ] take into account that JanusGraph upgraded dependency versions, so any incompatibilities there should be also noted

**Comment by pluradj** [comment]
[Attribute serialization](http://docs.janusgraph.org/0.1.0/serializer.html) would need a code migration (package name update) since you're required to implement the [`AttributeSerializer`](https://github.com/JanusGraph/janusgraph/blob/0.1/janusgraph-core/src/main/java/org/janusgraph/core/attribute/AttributeSerializer.java) interface.

**Comment by pluradj** [comment]
- [ ] From the [mailing list](https://groups.google.com/d/msg/janusgraph-users/JtJ0JONIyck/vaB8DYDaAAAJ), `index.search.index-name` requires a GLOBAL_OFFLINE change via the management system.

**Comment by rytilahti** [comment]
In my simple setup it was not enough to change the keyspace as shown in that mailing list question but the cluster_name in conf/cassandra/cassandra.yaml had also be adapted.

**Comment by amcp** [comment]
- [ ] Also need to set the id store name

**Comment by FlorianHockmann** [comment]
Closing this one as I don't think it makes sense any more nowadays to document this given how long JanusGraph has been out already. If someone actually wants to put in the effort to document this, then of course feel free to do so and create a PR. We can then just reopen this.
