### ISSUE TITLE
The count query based on the vertex traversal edges is too slow!!!

### ISSUE THREAD

**Issue by wangweidonghb** [JanusGraph/janusgraph#2241]
` g.V().hasLabel("Instance").has("instanceId", P.within("12", "34")).bothE('Cause').has('enabled', true).as('e').bothV().has('instanceId', P.within('64', '123')).select('e').count();`

The above count query executes very slowly, what method can be used to speed up its query.

I have created mixedIndex for instanceId, enabled.

How should I convert this query to a direct index query!

**Comment by FlorianHockmann** [comment]
Please don't ask usage questions like this in GitHub issues as we use those only for bug reports or feature requests which is also stated in the template you deleted when creating this issue. But it looks like you already realized that and [asked in janusgraph-users](https://groups.google.com/g/janusgraph-users/c/P-4hF5r9WuU) which is the right place for such questions.
