### ISSUE TITLE
Use GitHub Actions instead of TravisCI

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#2260]
https://groups.google.com/g/janusgraph-dev/c/02rWKvC9LwU

- [x] Standard Tests
  - [x] most tests
  - [x]  solr
- [x] Full build
  - [x] cql tests
  - [x] flag
- [x] Release builds
- [x] Documentation 
- [x] TinkerPop tests
- [ ] Style and license enforcement 
- [ ] Find a solution for coverity scan

**Comment by porunov** [comment]
Related: #1987
