### ISSUE TITLE
How fix gremlin-server to a Database during initialisation

### ISSUE THREAD

**Issue by dineshZeo** [JanusGraph/janusgraph#2263]
For discussion on internal implementation details of JanusGraph or proposing a [major new feature or subproject](https://docs.janusgraph.org/development/#development-decisions) use the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).

**Describe the feature:**
TODO

**Describe a specific use case for the feature:**
TODO

**Comment by FlorianHockmann** [comment]
Please ask questions in one of [our community channels](https://github.com/JanusGraph/janusgraph#community). We are only using GitHub issues for confirmed bug reports or feature requests.
