### ISSUE TITLE
Relieve the pain caused by super-point problems

### ISSUE THREAD

**Issue by YYDreamer** [JanusGraph/janusgraph#2282]
**Describe the feature:**
Design a parameter to control the maximum return number of super nodes， just like `Nebula Graph ` param：`max_edge_returned_per_vertex`   

**Describe a specific use case for the feature:**
Users can choose whether to enable it and limit the number of nodes returned.
Reduce the probability of the under storage is blocked due to super point issues

thanks

**Comment by li-boxuan** [comment]
Have you tried `limit` step? e.g. `g.V().has('vid','vid000').inE().limit(1000).next()`
