### ISSUE TITLE
Indicate vertex-centric index used in profile step

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#2283]
Composite indexes and mixed indexes, if used, would show up in the profiler result. However, profile() step does not indicate if and which vertex-centric index is used.

See https://groups.google.com/g/janusgraph-users/c/SqjYfsEInrQ/m/RDWALyDMAgAJ

Related issue: https://github.com/JanusGraph/janusgraph/issues/898

**Comment by cmilowka** [comment]
Thank you for considering this enhancement. 
Datastax, which is sharing a lot of the code with JG, is having something of this kind, referring to:
https://docs.datastax.com/en/dse/6.0/dse-dev/datastax_enterprise/graph/using/useIndexes.html
quote: _"If an index was not used, index-query would be missing from the profile output_" where index-query look like: 
```
**index-query** :
    \_indexType=Materialized
   \_statement=SELECT "personId" FROM "dse60"."person_p_byName" 
      WHERE "name" = ? LIMIT ?; with params (java. lang.String) Emeril Lagasse, (java.lang.Integer) 50000
```

We already have a list of conditions considered for backend-query, sample:
` \_condition=(m_at >= 1589592639360 AND m_to <= 9223372036854775807 AND type[v_StartTime_t])`
what we are probably missing is to have a confirmation about the index that was used to support that
`\_index=MY_INDEX (m_at >= 1589592639360 AND type[v_StartTime_t])`
so conditions for m_to need to be filtered in-memory, and it is why isFitted=false.
Regards, Christopher

**Comment by li-boxuan** [comment]
@cmilowka Thanks for the info. How the new profile step will look like is in https://github.com/JanusGraph/janusgraph/pull/2289. You may take a look and see if it helps you.

I admit it is not as detailed & clear as the DSE Graph version. To achieve that there is more work to be done in the future.

**Comment by cmilowka** [comment]
### Thanks you so much for the effort,... desperate to try that asap. I have a feeling that more questions will pop up, like _why indexes are not used_ ;-) Christopher

**Comment by li-boxuan** [comment]
Fixed by https://github.com/JanusGraph/janusgraph/pull/2360
