### ISSUE TITLE
jhf

### ISSUE THREAD

**Issue by ISM2020** [JanusGraph/janusgraph#2288]
Please post all questions and issues on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)
before opening a GitHub issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Storage Backend: 
- Mixed Index Backend:
- Mailing list Thread URL:
- Steps to Reproduce: 

### Stack Trace (if you have one)

```
paste stack trace here
```

**Comment by porunov** [comment]
I believe this issue was create by mistake because it doesn't have any meaningful description. Closing this issue.
@ISM2020 you can edit the issue description and reopen it.
