### ISSUE TITLE
Unrecognized partitioner: com.amazonaws.cassandra.DefaultPartitioner

### ISSUE THREAD

**Issue by AjayChoudary** [JanusGraph/janusgraph#2291]
We are unable to configure Amazon Managed Cassandra as CQL backend

JanusGraph 0.5.2, Apache TinkerPop 3.4.6

Here are the storage/cassandra details configured in conf/gremlin-server/janusgraph-cql-es-server.properties

storage.backend=cql
storage.hostname=cassandra.us-east-1.amazonaws.com
storage.port=9142
storage.username=mycassandra1-at-598037xxx
storage.password=VV3AXXXX/Euw+3Mt1YyYyYyYTajaySpipRU=
storage.cql.keyspace=test_janusgraph
storage.cql.ssl.enabled=true
storage.cql.ssl.truststore.location=trust/truststore.p12
storage.cql.ssl.truststore.password=mypassword

Getting following error when initializing the graph

**Unrecognized partitioner: com.amazonaws.cassandra.DefaultPartitioner**
https://github.com/JanusGraph/janusgraph/blob/797d870a2e35303e212e6f474f22d832f4393587/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L233

Tried with settings by following [forum](https://forums.aws.amazon.com/thread.jspa?messageID=945795) but it has no effect.
storage.cql.schema.enabled=false
storage.cql.token-map.enabled=false

There is no info about managed cassandra in [docs](https://docs.janusgraph.org/storage-backend/cassandra/#deploying-on-amazon-ec2).

Is the aws managed cassandra supported as a storage backend for the janusGraph?

**Comment by farodin91** [comment]
We are currently don't support the aws cassandra default partitioner. 

Can you switch it?

**Comment by AjayChoudary** [comment]
As per AWS support team, currently it is not possible to change the partition type.
Below is their response for your reference.

> I found an internal ticket opened 1 month ago stating that Keyspace's partitioner can not be changed currently and the team recognized it as a valid feature request.
> 
> Unfortunately I'm afraid that currently it is not possible to change the partition type in the Keyspace service. I chatted with the software developer on the keyspace team about the issue and they confirmed the same. They were not able to provide any workarounds for the issue.

**Comment by li-boxuan** [comment]
I know this issue was created first but since there are more discussions in https://github.com/JanusGraph/janusgraph/issues/2370, closing this one.
