### ISSUE TITLE
Cardinality.SINGLE and others can be set different value?or can be configured?

### ISSUE THREAD

**Issue by wen313** [JanusGraph/janusgraph#2347]
https://github.com/JanusGraph/janusgraph/blob/d565c6353db9045644e51361ec758a09141efe5c/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java#L39:1

**Comment by farodin91** [comment]
Could you be a bit more expressive? You are referencing a non release java file. 
What do you want to change?

**Comment by li-boxuan** [comment]
I guess you are asking if we can make the way we calculate index score configurable.

At the moment, the answer is no. Do you find the current strategy selects a non-optimal index for you? If so, can you describe it? That can help us evaluate how we could improve it.

**Comment by wen313** [comment]
> I guess you are asking if we can make the way we calculate index score configurable.
> 
> At the moment, the answer is no. Do you find the current strategy selects a non-optimal index for you? If so, can you describe it? That can help us evaluate how we could improve it.

for example:g.V().has('tag','person').has('name','xxxx'),Both tag and name build indexes. if the `tag` property is Cardinality.SET,the `name` property is Cardinality.SINGLE。if CARDINALITY_SINGE_SCORE  is different with CARDINALITY_OTHER_SCORE,we can adjust the two indexes‘s priority,so we can Optimize the query speed.

**Comment by li-boxuan** [comment]
Starting from 0.6.0 (unreleased yet), the index select strategy will be made configurable. https://docs.janusgraph.org/master/configs/configuration-reference/#query `query.index-select-strategy`. You could write and use your custom index select strategy.

**Comment by wen313** [comment]
> Starting from 0.6.0 (unreleased yet), the index select strategy will be made configurable. https://docs.janusgraph.org/master/configs/configuration-reference/#query `query.index-select-strategy`. You could write and use your custom index select strategy.

When will version 0.6.0 be released?Very much looking forward to it.

**Comment by li-boxuan** [comment]
> When will version 0.6.0 be released?Very much looking forward to it.

The original target was somewhere near the end of January. Not sure if @porunov has a plan.
