### ISSUE TITLE
Docs should indicate non-root user required for release build and janusgraph.sh

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#238]
Because [Elasticsearch cannot run as root](https://github.com/elastic/elasticsearch/pull/18694) build steps that involve starting an ES instance (e.g. `mvn verify -pl janusgraph-es` and `mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true -pl :janusgraph-dist-hadoop-2`) cannot be run as root.

**Comment by jerryjch** [comment]
Is there a way we can get around the ES restriction when we do janus-graph build?
Can we avoid putting a restriction on janus-graph build because of this?
@sjudeng Thanks for looking into it

**Comment by sjudeng** [comment]
FYI for the same reason as above janusgraph.sh also cannot be run as root.

@jerryjch I don't think there's anyway around this for ES 5.x based on the link above. In ES 2.x there might be an escape hatch property that could be used to force it to run as root. But I think they had good cause for restricting ES to run as a non-root user and we should consider accepting this security control when running an embedded ES server (e.g. janusgraph-es tests, janusgraph-dist-hadoop-2 build and janusgraph.sh). If this is not acceptable maybe we could look at using another indexing backend (e.g. SOLR) in these cases where possible.

**Comment by robertdale** [comment]
There is no good reason to run as root anyway.

**Comment by jerryjch** [comment]
There is no problem requiring non-root in the case where ES is used as the backend. There is some argument on the ES ticket, but we can only comply nevertheless. 
Generally limiting the build process because of an ES restriction sounds like an issue. People may have different build tools or env. Jenkins, Docker that they may have to specially adapt in order to build JanusGraph then.

**Comment by sjudeng** [comment]
@jerryjch Maybe it would be possible to get around this at least for the case of the janusgraph-dist-hadoop-2 release build. The instance is started as part of the `generate-compat-test-files` step in building janusgraph-dist-hadoop-2. It's only run during release (`-Pjanusgraph-release`) builds. I'm not sure what its purpose is. Maybe it would be possible to skip/rework it to avoid starting the instance. One advantage of having it run though is it does exercise the same ES distribution that janusgraph.sh uses, so it provides some level of validation (#138 was created to extend this validation).

**Comment by jerryjch** [comment]
> It's only run during release (-Pjanusgraph-release) builds. I'm not sure what its purpose is. Maybe it would be possible to skip/rework it to avoid starting the instance
Agree. I am not very knowledgeable on what it tries to do here either. (Does not seem to be needed in the zip file?)
The ideal case would be:
1)  The release build can proceed without this blocker.
2)  The janusgraph.sh can be exercised in the test phase and the ES tests can fail with meaningful errors when running as root.

@sjudeng thanks for looking into this again.  Up to you.

**Comment by sjudeng** [comment]
@jerryjch Makes sense to me. I'll take a look at what if any options there are regarding skipping/handling this for the release build.
