### ISSUE TITLE
UniqueInstanceIdRetriever.getInstance() is not thread-safe

### ISSUE THREAD

**Issue by rouxiaomin** [JanusGraph/janusgraph#2400]
I use hbase as backend.JanusGraph properties is below：
        
        batch-loading = true
        schema.default=none

Both delete and add use the same config.Does anyone know the reason why when add,some data may get lost without exception?

- add operation：
`g.V().addV("xxx").property("uid","v1").next()`

- delete operation:
`g.V().has("uid","xxx").drop().iterate()`

The property "uid" has unique index.

I enable the debug log level.The log in "commit()" method:
`log.debug("Saving transaction. Added {}, removed {}", addedRelations.size(), deletedRelations.size());`
the size is the same in normal and abnormal case.

**Comment by li-boxuan** [comment]
Are you able to reproduce it using a minimal sample? If so, can you provide it?

**Comment by rouxiaomin** [comment]
> Are you able to reproduce it using a minimal sample? If so, can you provide it?

I've found out the reason.The vertex id conflict because two graph instances with the same instance id appear.It's thread-unsafe when call `UniqueInstanceIdRetriever.getInstance()`

**Comment by li-boxuan** [comment]
@rouxiaomin Thanks for reporting and investigating! This bug has been fixed by #2503 and will be released in 0.6.0.
