### ISSUE TITLE
Two artifacts at 0.1.0 in maven repository for each module

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#241]
https://mvnrepository.com/artifact/org.janusgraph/janusgraph-berkeleyje
https://mvnrepository.com/artifact/org.janusgraph/janusgraph-core
etc

each list 0.1.0 twice

**Comment by twilmes** [comment]
Created an [issue](https://issues.sonatype.org/browse/MVNCENTRAL-2216) to see what's up with this.

**Comment by twilmes** [comment]
@amcp I got word back from Sonatype. They do not have an association with MVN Repository so couldn't help there but confirmed things were good in MVN central so our publishing process was fine. I checked MVN Repository this morning and I'm no longer seeing duplicates. Not sure what happened but they appeared to clean it up.

**Comment by pluradj** [comment]
Everything looks ok over here too http://search.maven.org/#search%7Cga%7C1%7Cjanusgraph-core
