### ISSUE TITLE
Make Backend thread pool size configurable

### ISSUE THREAD

**Issue by haocornell-ms** [JanusGraph/janusgraph#2473]
**Describe the feature:**
Making Backend thread pool size configurable. Based on my understanding, when executing edgeStoreMultiQuery, this thread pool in Backend is used and each getSlice will occupy one thread. As there are only # core * 2 threads,  the overall execution parallelism is limited by this size of the pool. Should allow the size customizable.

**Describe a specific use case for the feature:**
[If possible add a description of the specific use case.]

**Comment by li-boxuan** [comment]
@haocornell-ms Would you like to work on this?
