### ISSUE TITLE
Multiple vertices generated for the same index value and vertex properties missing with RF3

### ISSUE THREAD

**Issue by sauverma** [JanusGraph/janusgraph#2515]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 0.5.0
- Storage Backend: scylla enterprise 2020.1.6-0.20210202.c6a70535c
- Mixed Index Backend: none
- Link to discussed bug: https://lists.lfaidata.foundation/g/janusgraph-dev/message/1495
- Expected Behavior: The vertex and edge meta should be correctly stamped without enabling ConsistenyModifier.LOCK
- Current Behavior: Observation is that for many vertices with the same index value, multiple vertex IDs are generated as seen below
- Steps to reproduce
- Create a keyspace in scylla with RF3
- Load the janusgraph schema, the schema needs to have an index as mentioned in https://lists.lfaidata.foundation/g/janusgraph-users/message/5706
- Insert a few vertices via using multiple clients (each client using Embedded JanusGraph), and check if the vertices got ingested with correct metadata via gremlin console

**Comment by li-boxuan** [comment]
Looks like this is caused by a race condition. As suggested by https://docs.janusgraph.org/advanced-topics/eventual-consistency/, if you want to keep uniqueness constraint, you need to enable locking.
