### ISSUE TITLE
Reindexig of vertex-centric index is unidirectional

### ISSUE THREAD

**Issue by supperslonic** [JanusGraph/janusgraph#2603]
Reindexing of a vertex-centric index doesn't work for Edges with `Direction.IN`.

I have created an edge label:
```
//Initialize the label for Relation edge
  if (!graphManagement.containsEdgeLabel("_relation")) {
    graphManagement.makeEdgeLabel("_relation").directed().make()
  }
```

I have added an edge between 2 vertexes:
```
val edge = fromVertex.addEdge("_relation", toVertex)
edge.property("_relation_tag", tag)
```

I'm able to find vertexes using both-way traversal.

```
dbContext.traversal.V(vertex)
      .toE(direction, "_relation")
      .has("_relation_tag", tagName)
     .toV(direction.opposite())
```

But when, later, I add a relation index and I reindex the data, I can't find edges for the `toVertex` which is using `Direction.IN`, it only works for `fromVertex`

`  graphManagement.buildEdgeIndex(edgeLabel, edgeIndexName, Direction.BOTH, tagProperty)`

**Comment by li-boxuan** [comment]
Likely fixed by https://github.com/JanusGraph/janusgraph/pull/2137 which will be released soon.

**Comment by supperslonic** [comment]
Thank you! I will retest this code after the release and update the issue with the results

**Comment by li-boxuan** [comment]
Sure, closing this issue for now. Feel free to reopen if you find the issue still exists in 0.6.0.
