### ISSUE TITLE
Duplicate addProperty calls in StandardJanusGraphTx:: makeSchemaVertex

### ISSUE THREAD

**Issue by Charele** [JanusGraph/janusgraph#2613]
Maybe this isn't a bug,Just my mistake(If so, sorry)

In StandardJanusGraphTx class
 makeSchemaVertex(JanusGraphSchemaCategory, String, TypeDefinitionMap) function
...
        updateSchemaVertex(schemaVertex);
        addProperty(schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()));
...

line 1 is: add a "SchemaUpdateTime" property for this schemaVertex,
but line 2 is also,
Must we add two same property for this vertex???

**Comment by li-boxuan** [comment]
Thanks for reporting! This is not a bug but I think it would be good to avoid doing the same call twice. Would you like to submit a PR to optimize this?

**Comment by Charele** [comment]
Hi, Mr Li,
Hmmm, I am not familiar with Github,
and I don't know how to do the "submit a PR" operation,
(I search it on Google, it likes so complex)
so can you handle it? Thanks.

**Comment by li-boxuan** [comment]
sure, no problem!
