### ISSUE TITLE
python example do not works

### ISSUE THREAD

**Issue by bioinfornatics** [JanusGraph/janusgraph#2714]
I followed instruction from [python.md](https://github.com/JanusGraph/janusgraph/blob/83c93fe717453ec31086ca1a208217a747ebd1a8/docs/interactions/connecting/python.md)

I got an error while trying to follow the code: 
```
GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server.

```

how to reproduce:

```
mkdir  janusgraph
# podamn or docker is same
podman run --rm -d --name janusgraph_server -v "${PWD}"/janusgraph:/var/lib/janusgraph -p 8182:8182 docker.io/janusgraph/janusgraph:0.5.3

sudo apt install python3.8-venv
python3 -m venv janusgraph_env
source janusgraph_env/bin/activate
pip3 install wheel
pip3 install gremlinpython==3.4.6
ipython3 # <<-- start here

```

**Comment by li-boxuan** [comment]
The link you provided is for the 0.6.0 version (which is not released yet), while you are pulling JanusGraph 0.5.3 version. You should follow the steps on https://docs.janusgraph.org/connecting/python/
