### ISSUE TITLE
0.1.0 JanusGraph Docs issues, typos and whatnot

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#272]
As reported on https://groups.google.com/d/msg/janusgraph-users/L3xA6xp3btI/iUxvyYE7BwAJ

> Hello, I read through the docs and found various flaws.  Some were key concepts not congruent with the codeblock and some were various typos. And since there is no link to report them, I thought I'd post them here.
> 
> 8.3
> Example uses battlesByRatingsAndTime but the description below the code block refers to battlesByLocationAndTime 
> 
> 26.3
> dicussed
> 
> 28.1
> peristence
> atomicly
> storge
> auhoritative
> 
>  
> 29.2.2
> Inedx

**Comment by robertdale** [comment]
Pull request #273

**Comment by robertdale** [comment]
Merged.

**Comment by mbrukman** [comment]
Fixed by #273 on the `0.1` branch and #274 on the `master` branch.
