### ISSUE TITLE
Add AstraDB Support

### ISSUE THREAD

**Issue by waleedzeb** [JanusGraph/janusgraph#2730]
AstraDB is a fully managed serverless Cassandra database. The service manages everything and provides a cost-effective serverless cost structure.

Has anyone tried this?

**Comment by vtslab** [comment]
AstraDB states that it works with Cassandra 3.11 clients ([https://docs.datastax.com/en/astra/docs/datastax-astra-faq.html](https://docs.datastax.com/en/astra/docs/datastax-astra-faq.html)). JanusGraph supports Cassandra 3.11 ([https://docs.janusgraph.org/changelog/#version-compatibility](https://docs.janusgraph.org/changelog/#version-compatibility)).
Although the [JanusGraph website ](https://janusgraph.org/) mentions ScyllaDB as a separate storage backend, there are many options for managed Cassandra services, so a list of these would not make things clearer and would be out of data soon.
