### ISSUE TITLE
Janusgraph could not deal with abnormal range queries for Predicate

### ISSUE THREAD

**Issue by zhengyingying** [JanusGraph/janusgraph#2751]
For confirmed bugs, please report:
- Version: 0.5.3
- Storage Backend: inmemory
- Mixed Index Backend: none
- Link to discussed bug: 
- Expected Behavior: 
When we execute the query `g.E().has('ep2', inside(0.8480583995943037, 0.5952456882067648))`, we want search edges in which the value of property 'ep2' is within the range of the twp specified values. 
- Current Behavior:
Now, an exception `java.lang.illegalArgumentException` was throw. 
- Steps to Reproduce: 

### Stack Trace (if you have one)

```
java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: java.lang.IllegalArgumentException
```

**Comment by porunov** [comment]
Hi @zhengyingying , could it be related to #2273 ?
If so, are you able to test your case with the upcoming 0.6.0 release? You can download release artifacts here: https://github.com/JanusGraph/janusgraph/releases/tag/v0.6.0
