### ISSUE TITLE
Link to obtain Hortonworks' winutils.exe has gone stale/died

### ISSUE THREAD

**Issue by bkmdev** [JanusGraph/janusgraph#2806]
Please include configurations and logs if available.

For confirmed bugs, please report:
- **Version**: 0.3.1 (+ 0.6)
- **Storage Backend**: CQL
- **Mixed Index Backend**: None
- **Link to discussed bug**: https://gitter.im/janusgraph/janusgraph?at=60f8229b3a178069da7b397b
> the HortonWorks URL as specified in https://github.com/JanusGraph/janusgraph/blob/v0.3.1/janusgraph-dist/src/assembly/static/bin/gremlin.bat#L43-L55 to obtain `winutils.exe` is now dead. I have done some Googling around and found https://github.com/steveloughran/winutils which in turn referenced https://github.com/cdarlint/winutils (ex: https://github.com/cdarlint/winutils/blob/master/hadoop-3.2.1/bin/winutils.exe) is this an appropriate replacement URL to obtain `winutils.exe` now?
- **Expected Behavior**:  Hortonworks URL to obtain `winutils.exe` is valid
- **Current Behavior**:  Hortonworks URL to obtain `winutils.exe` is invalid
- **Steps to Reproduce**:  Attempt to deploy & run JG on Windows OS w/o `winutils.exe`

**Comment by li-boxuan** [comment]
Yes that sounds like a good idea! @bkmdev Do you want to create a PR?
