### ISSUE TITLE
Could not instantiate implementation: org.janusgraph.diskstorage.solr.SolrIndex

### ISSUE THREAD

**Issue by buck-ross** [JanusGraph/janusgraph#2889]
## Description

When running JanuceGraph using Apache Cassandra & Apache Solr, JanusGraph spits out the following error:

> java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:84)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:72)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:106)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.addGraph(DefaultGraphManager.java:63)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:58)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:84)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:124)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:87)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.graphdb.server.JanusGraphServer.start(JanusGraphServer.java:85)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.graphdb.server.JanusGraphServer.main(JanusGraphServer.java:53)
Caused by: java.lang.reflect.InvocationTargetException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invoke(Method.java:498)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:80)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 14 more
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.solr.SolrIndex
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:79)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:525)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:509)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.diskstorage.Backend.<init>(Backend.java:239)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1355)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:184)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:176)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:147)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:127)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 19 more
Caused by: java.lang.reflect.InvocationTargetException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:73)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 27 more
Caused by: java.lang.NoSuchMethodError: org.noggit.ObjectBuilder.getValStrict()Ljava/lang/Object;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.common.util.Utils.fromJSON(Utils.java:319)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.common.util.Utils.fromJSON(Utils.java:305)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.common.cloud.ClusterState.load(ClusterState.java:245)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.common.cloud.ZkStateReader.refreshLegacyClusterState(ZkStateReader.java:637)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.common.cloud.ZkStateReader.createClusterStateWatchersAndUpdate(ZkStateReader.java:511)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.getZkStateReader(ZkClientClusterStateProvider.java:177)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.connect(ZkClientClusterStateProvider.java:161)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.connect(BaseCloudSolrClient.java:349)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.janusgraph.diskstorage.solr.SolrIndex.<init>(SolrIndex.java:296)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 32 more

The stack trace doesn't seem to yield too much useful information (at least from my perspective), but the line `java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.solr.SolrIndex` seems like a strong indicator that this id due to a failed connection to the Apache SolrCloud instance.

## Reproducing with Containers

Below is a script to reproduce the above error (I'm using [`podman`](https://podman.io)'s "pod" feature to make all of the containers share a common networking namespace. With docker, this can be accomplished with `--link`):

```sh
# Create fresh directories for the volume mounts:
mkdir -p ./volumes/{solr,cassandra,zk}
podman unshare chown -Rv 8983:8983 ./volumes/solr

# Provision the pod container:
podman pod create --name test -p 2181:2181 -p 8182:8182 -p 8983:8983 -p 9042:9042

# Deploy Zookeeper to support SolrCloud:
podman run -d --pod test --name zk -v ./volumes/zk:/data:Z zookeeper:latest

# Deploy SolrCloud:
podman run -d --pod test --name solr -e 'ZK_HOST=127.0.0.1:2181' -v ./volumes/solr:/var/solr:Z solr:8

# Deploy Cassandra:
podman run -d --pod test --name cassandra -v ./volumes/cassandra:/var/lib/cassandra:Z cassandra:3

# Deploy the JanusGraph instance:
podman run -d --pod test --name janusgraph \
    -e 'janusgraph.index.search.backend=solr' \
    -e 'janusgraph.index.search.solr.mode=cloud' \
    -e 'janusgraph.index.search.solr.zookeeper-url=localhost:2181' \
    -e 'janusgraph.storage.backend=cql' \
    -e 'janusgraph.cache.db-cache=true' \
    -e 'janusgraph.storage.hostname=127.0.0.1' \
    janusgraph/janusgraph:latest
```
NOTE: You will need to wait for Cassandra & Solr to become operational before deploying JanusGraph, otherwise it will fail to start.

Once the JanusGraph instance has finished starting up, checking it's logs with `podman logs janusgraph` will yield the above error message, along with a following message about being unable to `create GremlinScriptEngine for gremlin-groovy`, which I believe is directly caused by the failure to connect to Solr.

You can then cleanup all services / data from this reproduction with:
```sh
podman pod stop test
podman pod rm test
rm -rv ./volumes
```

Thank you for your time!

**Comment by buck-ross** [comment]
I have just confirmed that this error no longer occurs when the environment variable `janusgraph.index.search.backend` is set to `lucene`, which seems to confirm that this is an issue with connecting to SolrCloud.

**Comment by mad** [comment]
Fast fix just remove this jar `$JANUSGRAPH/lib/noggit-0.6.jar`

**Comment by buck-ross** [comment]
@mad Thanks for the quick response! That seems to have worked, and JanusGraph now outputs that it is able to connect to Zookeeper without any issue, but I'm a little concerned that I have no idea what I just did to my deployment. If it's not too much trouble, would you mind explaining to me what `noggit-0.8.jar` was doing, and why removing it has fixed this error?

**Comment by vtslab** [comment]
[https://github.com/JanusGraph/janusgraph/search?q=noggit](https://github.com/JanusGraph/janusgraph/search?q=noggit)
As you see, noggit is supposed to be excluded from janusgraph-solr, but it comes in again through janus-graph-driver.
So, there should be no impact as long as you do not use the client and server from the same lib/ folder.

**Comment by buck-ross** [comment]
Thanks so much to both of you for the help in figuring this issue out! Since there doesn't seem to be much immediate drive to fix this in the official docker image, I've gone ahead and created my own repository at [buckross/janusgraph-sin-noggit](https://hub.docker.com/r/buckross/janusgraph-sin-noggit), which excludes the noggit library.

I'm going to go ahead and close this issue for now. If anyone out there feels strongly that this needs to be further addressed, just @ me, and I'll re-open.

/close
