### ISSUE TITLE
Project with janusgraph-core dependency does not compile in Eclipse with Java 11

### ISSUE THREAD

**Issue by michalrrcc** [JanusGraph/janusgraph#2900]
- Version: 0.6.0
- Expected Behavior: Project with `janusgraph-core` dependency compiles in Eclipse with Java 11 without errors
- Current Behavior: Eclipse reports error: `The package java.util is accessible from more than one module: <unnamed>, java.base`
- Steps to Reproduce:
1. Create maven project with Java 11
2. Add dependency on `janusgraph-core` to `pom.xml`

The issue goes away when transitive dependency `high-scale-lib` of `janusgraph-core` is excluded in pom.xml. `high-scale-lib` contains package `java.util` which is causing the compilation error.
The error does not manifest when compiling with `javac` because of the bug [JDK-8215739](https://bugs.openjdk.java.net/browse/JDK-8215739).

**Comment by michalrrcc** [comment]
UPDATE:
Excluding `high-scale-lib` fixes Eclipse compilation error but some functionality does not work during runtime because for example class [StandardSchemaCache.java#L84](https://github.com/JanusGraph/janusgraph/blob/5e62b4006adb6f29e5a237036ae3a7aaa02bda7e/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/StandardSchemaCache.java#L84) needs class from it.

Potential fix could be to replace `high-scale-lib` with successor library [jctools-core](https://github.com/JCTools/JCTools) as suggested in [this mailing list discussion](https://lists.lfaidata.foundation/g/janusgraph-users/topic/87767003).

**Comment by farodin91** [comment]
@michalrrcc Would you like to replace high scale lib with JCTools? We would appreciate it.

**Comment by sergeymetallic** [comment]
As a temporary solution we excluded high-scale-lib, added jctools-core and "proxied" the class used in Janusgraph:
`package org.cliffc.high_scale_lib;

public class NonBlockingHashMapLong<TypeV> extends org.jctools.maps.NonBlockingHashMapLong<TypeV> {

    public NonBlockingHashMapLong() {
        super();
    }

    public NonBlockingHashMapLong(int initial_sz) {
        super(initial_sz);
    }

    public NonBlockingHashMapLong(boolean opt_for_space) {
        super(opt_for_space);
    }

    public NonBlockingHashMapLong(int initial_sz, boolean opt_for_space) {
        super(initial_sz, opt_for_space);
    }
}`

**Comment by michalrrcc** [comment]
> As a temporary solution we excluded high-scale-lib, added jctools-core and "proxied" the class used in Janusgraph:

@sergeymetallic thanks, that is useful

**Comment by michalrrcc** [comment]
Fixed by the PR.
