### ISSUE TITLE
storage.cql.netty.admin-size default value is 0 instead of 2

### ISSUE THREAD

**Issue by cdegroc** [JanusGraph/janusgraph#2936]
### Context:
- Version: 0.6.0
- Storage Backend: cql

### Description:
Cassandra's default size for Netty admin-group is 2 [doc](https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/performance/#thread-pooling), [code](https://github.com/datastax/java-driver/blob/4.13.0/core/src/main/resources/reference.conf#L2219)

JanusGraph 0.6.0 overrides it and sets it to 0 (`Runtime.getRuntime().availableProcessors() * 2`) by default [doc](https://docs.janusgraph.org/configs/configuration-reference/#storagecqlnetty), [code 1](https://github.com/JanusGraph/janusgraph/blob/v0.6.0/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java#L351), [code 2](https://github.com/JanusGraph/janusgraph/blob/v0.6.0/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java#L165).

We should probably leave `NETTY_IO_SIZE`/`NETTY_ADMIN_SIZE` unset by default and let Cassandra pick the defaults.
If that's not doable, we could set the default value to 2 in JanusGraph.

**Comment by FlorianHockmann** [comment]
Fixed in #2937
