### ISSUE TITLE
Fix the documentation for the key to the graph of gods ...

### ISSUE THREAD

**Issue by kedarmhaswade** [JanusGraph/janusgraph#296]
The index (see below) to the graph of gods should be fixed to use a 2-column table.
e.g. 
|bold key | graph indexed key|

![image](https://cloud.githubusercontent.com/assets/50923/26690324/b5e97414-46ad-11e7-91db-2473754e8bc9.png)

**Comment by jerryjch** [comment]
Fixed by the above two PRs.
