### ISSUE TITLE
Dist tests failing

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#3017]
It looks like `dist-tests (8)` started to fail suddenly. I assume we use some external calls to download some dependencies / artifacts / data from external sources in that test and something was changes (maybe a URL or something else). Now all PR's and a `master` branch fails because of this change.

Here is the link to the failed test: https://github.com/JanusGraph/janusgraph/runs/6128877287

As seen from #3025 (https://github.com/JanusGraph/janusgraph/runs/6194674118?check_suite_focus=true) previously this test was working but after trying it again it started to fail.

For confirmed bugs, please report:
- Version: master

### Stack Trace

```
Error:  Failures: 
Error:    JanusGraphScriptIT.testGraphOfTheGodsGraphSONFull:33->JanusGraphAssemblyBaseIT.unzipAndRunExpect:113->JanusGraphAssemblyBaseIT.unzipAndRunExpect:84->JanusGraphAssemblyBaseIT.parseTemplateAndRunExpect:106->JanusGraphAssemblyBaseIT.expect:128->JanusGraphAssemblyBaseIT.command:171 expected: <0> but was: <1>
```

**Comment by porunov** [comment]
Locally this test passes. Can't figure out why it fails in GitHub Actions

**Comment by porunov** [comment]
@farodin91 Do you have any thoughts why these dist tests started to fail?

My observations is that only dist (8) was failing at the beginning but later dist (11) started to fail as well. Thus, I think that Java versions might be updated and we started to use different Java version in our dist builds which somehow lead to this problem.
I guess we could try to force specific Java version for dist builds to see if that resolves the issue but I didn't check that yet.

**Comment by farodin91** [comment]
java 11 is broken with different reason. 
javadoc fails.
