### ISSUE TITLE
JanusGraph 0.6.1 is using Gremlin Version 1.21.0?

### ISSUE THREAD

**Issue by jgdervil** [JanusGraph/janusgraph#3027]
Gremlin.version()  command using JanusGraph 0.6.1 returns 1.21.0?
------------------------------------------------
- Version: 0.6.1
- Storage Backend: cql
- Mixed Index Backend: elasticsearch
- Link to discussed bug: https://github.com/JanusGraph/janusgraph/discussions/3004#discussioncomment-2655778
- Expected Behavior:  Gremlin.version() should return  3.4.6 or later
- Current Behavior: 1.21.0
- Steps to Reproduce:  Gremlin.version()

**Comment by li-boxuan** [comment]
Also created https://issues.apache.org/jira/browse/TINKERPOP-2761

**Comment by li-boxuan** [comment]
We will revert https://github.com/JanusGraph/janusgraph/pull/3088 once https://issues.apache.org/jira/browse/TINKERPOP-2761 is fixed.
