### ISSUE TITLE
Add requirements to Docs and README

### ISSUE THREAD

**Issue by MichaelMarkieta** [JanusGraph/janusgraph#304]
I don't think the requirements for development, or to be able to download a release and run `bin/janusgraph.sh` are explicitly listed anywhere.

**Comment by robertdale** [comment]
**Downloading and running:**
http://janusgraph.org/ -> Docs -> I. Introduction -> 3. Getting Started -> [3.1. Downloading JanusGraph and Running the Gremlin Shell](http://docs.janusgraph.org/latest/getting-started.html#_downloading_janusgraph_and_running_the_gremlin_shell)

```
JanusGraph requires Java 8 (Standard Edition). Oracle Java 8 is recommended.
JanusGraph’s shell scripts expect that the $JAVA_HOME environment variable points
to the directory where JRE or JDK is installed.
```

**Development:**
https://github.com/JanusGraph/janusgraph/blob/master/BUILDING.md
```
Required:
Java 8
Maven 3
```
