### ISSUE TITLE
Update to TinkerPop 3.6.x

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3069]
TinkerPop 3.6.0 is released in April. https://tinkerpop.apache.org/docs/current/upgrade/#_tinkerpop_3_6_0

**Comment by li-boxuan** [comment]
It seems GryoMessageSerializer support has been removed in TinkerPop 3.6.0. I am not quite familiar with it so hopefully, someone else could take this issue.

**Comment by porunov** [comment]
Also, Hadoop was upgraded from Hadoop 2 to Hadoop 3 in TinkerPop 3.6.0

**Comment by FlorianHockmann** [comment]
TinkerPop 3.6.0 also added a regex predicate: https://tinkerpop.apache.org/docs/current/upgrade/#_textp_regex
We probably want to convert that to our own regex predicate(s).

**Comment by a-magno98** [comment]
Hi,
I have found a mistake in the documentation of JanusGraph, in particular in connecting to JanusGraph using Java [https://docs.janusgraph.org/interactions/connecting/java/](url). You should update part 3, the remote-objects.yaml as follows:
`hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}`

**Comment by douglasawh** [comment]
Is there any chance this upgrade can be to 3.6.2? There are some CVEs in 3.6.2 we would like to address.

**Comment by porunov** [comment]
> Is there any chance this upgrade can be to 3.6.2? There are some CVEs in 3.6.2 we would like to address.

There is no 3.6.2 released TinkerPop version available. The release process isn't started for that version yet. The latest released version is TinkerPop 3.6.1 as of today. When 3.6.2 is available it shouldn't be a problem to bump that version in JanusGraph.
