### ISSUE TITLE
Cassandra 2.1.9 vs 2.1.17 vs 2.2.9

### ISSUE THREAD

**Issue by aie0** [JanusGraph/janusgraph#317]
Hi,

In release notes of 0.1.1 version stated that it was tested against Cassandra 2.1.9, which is neither the latest version of 2.1 nor part of 2.2 release.

Will it work with 2.2.9 or at least with 2.1.17?

**Comment by pluradj** [comment]
Go ahead and try it. You should see that it works. For the 2.2.x version, make sure you enable thrift.
