### ISSUE TITLE
Add support for Solr 6

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#320]
As stated in
https://github.com/JanusGraph/janusgraph/releases/

Janus supports: Apache Solr 5.2.1, which was released in June 2015.
The latest apache Solr version 6 was released in 2016.

Currently when trying to use Janus with Solr 6 the core config provided by janus causes schema errors that cannot be easily fixed, so bigger changes are required.

**Comment by aie0** [comment]
Should be fixed by [#311](https://github.com/JanusGraph/janusgraph/pull/311)
