### ISSUE TITLE
Add Solr mixed index support for properties with List and Set cardinality

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#327]
See
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L823
```

        if (information.getCardinality() != Cardinality.SINGLE) {
            return false;
        }
```

It is clear that properties with cardinality are NOT supported with solr index backend.

See also related issue #319

**Comment by holleyism** [comment]
While this is fixed, it will not work for fields defined as solr.UUIDField.  Jira opened here: https://issues.apache.org/jira/browse/SOLR-11264
