### ISSUE TITLE
Add Solr mixed index support for TEXTSTRING mapping

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#328]
See:

https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L865

https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L882

```
        if (Number.class.isAssignableFrom(dataType) || dataType == Date.class || dataType == Instant.class || dataType == Boolean.class || dataType == UUID.class) {
            if (mapping==Mapping.DEFAULT) return true;
        } else if (AttributeUtil.isString(dataType)) {
            if (mapping==Mapping.DEFAULT || mapping==Mapping.TEXT || mapping==Mapping.STRING) return true;
```

It is clear that TEXTSTRING mapping is not supported for Solr.

See also related issue #319

**Comment by porunov** [comment]
Fixed in #3179
