### ISSUE TITLE
Make mixed index updates behave in transactional way

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#329]
Configuration:
```
# storage backend
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=9.128.105.70
schema.default=none

# index backend
index.search.backend=solr
index.search.solr.mode=cloud
index.search.solr.zookeeper-url=9.128.105.70:2182
```

Mixed Index creation:
```
JanusGraphManagement mgmt = = graph.openManagement();
mgmt.buildIndex("indexByName", Vertex.class).addKey("name").buildMixedIndex("search");
```

When you try to do:

```
// add new data
Vertex v1 = graph.addVertex();
v.property("name", "abc")
...
graph.tx().commit();

// since the transaction has been committed, you expect new data to be readable from index
Iterable<Result<JanusGraphVertex>> it = graph.indexQuery("indexByName', "v.name=abc").vertices();
it.next()  // false!
```

In reality when solr server is over the network you will get empty results. 
To workaround this issue you need to add arbitrary sleep time to wait for the data to be propagated to the index.

```
// workaround
LOG.info("wait for full text index refresh");
TimeUnit.SECONDS.sleep(5);

// now if you set your sleep right, you will see the new data
Iterable<Result<JanusGraphVertex>> it = graph.indexQuery("indexByName', "v.name=abc").vertices();
it.next() // true
```

It seems that despite the fact:
1) Janus IS transactional by default and requires you to manually commit() the operations
2) Solr IS transactional by default and requires you to manually commit() the operations

the index updates happen in non-transactional asynchronous fashion.

Now if you look at:
https://github.com/JanusGraph/janusgraph/blob/ec441ac6d87f3359c9740075786ec6de3651745e/janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java#L78

The javadoc states:
_Note, that using indexQuery will may ignore modifications in the current transaction._

That is fine, but still if I have already committed the transaction I expect my changes to be visible as soon as the commit() call returns.

This either has to be changed or at least a new property should be introduced which would allow to set the desired behavior e.g. 
`index.XXX.transactionalUpdates=true/false`
to switch between sync/asnych modes.

This is especially problematic in JUnit testing, as you cannot reliably tell when your index is refreshed. Sleeping for x seconds is far from perfect as the tests take unnecessarily more time and still may fail if the network is slower than usual or the backend server is replaced with another one in a different location.

**Comment by holleyism** [comment]
This maybe a documentation update but when commit returns, I don't think the commit is actually complete because of the eventual consistency model.  You can use the addTransactionListener to know when the transaction is complete and trigger on that instead of using sleep.
```
Vertex v1 = graph.addVertex();
v1.property("name", "abc");
graph.tx().addTransactionListener(status -> {
   if (status == Transaction.Status.COMMIT) {
      Iterable<Result<JanusGraphVertex>> it = graph.indexQuery("indexByName", "v.name=abc").vertices();
      System.out.println(it.iterator().hasNext());  // prints "true"
      System.out.println("Committed");
   } else if (status == Transaction.Status.ROLLBACK) {
      System.out.println("Rolled back.");
   } else {
      throw new RuntimeException(String.format("The %s is not aware of this status: %s", EventQueue.class.getName(), status));
   }
});
graph.tx().commit();
```

**Comment by wojciechwojcik** [comment]
@holleyism  I've tried the above approach you suggested and unfortunately it does NOT work.
The commit event is fired and passed to the listener at exactly graph.tx().commit() time, thus there is no waiting effect.

**Comment by holleyism** [comment]
@wojciechwojcik Set index.[X].solr.wait-searcher to true for unit tests.  (http://docs.janusgraph.org/latest/config-ref.html)  This should make the commit wait for the index to be available.

**Comment by wojciechwojcik** [comment]
The option ``index.[X].solr.wait-searcher=true`` works as expected. Closing.
