### ISSUE TITLE
Elasticsearch should separate graphs by name when using ConfiguredGraphFactory

### ISSUE THREAD

**Issue by rngcntr** [JanusGraph/janusgraph#3338]
**Describe the feature:**
As stated in the [docs](https://docs.janusgraph.org/operations/configured-graph-factory/#important) JanusGraph's `ConfiguredGraphFactory.createTemplateConfiguration` is able to use the graph name as a storage directory, tablename or keyspace name for the storage backend. However, this is not the case for index backends. For example, when using elasticsearch, all indexed data ends up in one large index and therefore index queries from one graph also return matching vertices from other graphs.
Index backends should employ a mechanism similar to the one that is in use for storage backends.

**Describe a specific use case for the feature:**
Isolation of indices between multiple graphs.

**Comment by porunov** [comment]
We use `index.[X].index-name` to separate mixed indexes between multiple graphs (ElasticSearch).
To separate storage backend data for CQL we use `storage.cql.keyspace`.

I.e. graph1:
```
index.search.index-name=graph1
storage.cql.keyspace=graph1
```
graph2:
```
index.search.index-name=graph2
storage.cql.keyspace=graph2
```
By default `index-name` is used as a prefix for all created indices. Didn't check that for Solr and Lucene.

**Comment by rngcntr** [comment]
I understand your confusion because I forgot to point out that I am using [TemplateConfiguration](https://docs.janusgraph.org/operations/configured-graph-factory/#template-configuration) and therefore all graphs share the same config except for the graph name.
I will edit the original post to include that information.

**Comment by rngcntr** [comment]
We decided to fix this for Elasticsearch first, in order to keep the scope for a PR at a minimum.
In case there is interest in solving this problem for other index backends, please open a new issue.
