### ISSUE TITLE
Publish Docker Images in Post Build Step

### ISSUE THREAD

**Issue by chrislbs** [JanusGraph/janusgraph#337]
Now that a docker image build exists, it would be useful to publish them to docker hub. 

This will require the creation of a docker hub account and then either encrypting those credentials in the travis.yml file or adding those environment variables through the travis project itself. If that information can be updated, I can add the necessary changes to the travis.yml file and pom to handle the publishing.

**Comment by amcp** [comment]
I've squatted for janusgraph organization in my dockerhub account a while back. How to proceed

**Comment by chrislbs** [comment]
@amcp We'll need whoever has access to the travis ci build to add some environment variables that specify the docker hub account credentials. I'm working on a more thorough docker image that supports multiple persistence configurations. I can likely update the travis yml to support publishing but it will still require someone with access to the travis build to do some updates.

**Comment by FlorianHockmann** [comment]
Superseded by janusgraph/janusgraph-docker#9.
