### ISSUE TITLE
RelationIdentifierGraphBinarySerializer fails to serialize properties

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3454]
As reported by @gdotv on Discord, GraphBinarySerializer fails to serialize & deserialize properties. An example would be:

`conf/remote.yaml`:
```
hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
```

Insert some vertices:
```
g.addV('person').
  property(single, 'age', 29).
  property(single, 'name', "marko").
  addV('person').
  property(single, 'age', 27).
  property(single, 'name', "vadas").
  addV('software').
  property(single, 'lang', "java").
  property(single, 'name', "lop").
  addV('person').
  property(single, 'age', 32).
  property(single, 'name', "josh").
  addV('software').
  property(single, 'lang', "java").
  property(single, 'name', "ripple").
  addV('person').
  property(single, 'age', 35).
  property(single, 'name', "peter")
```

Query all properties:
```
gremlin> :> g.V().properties()
Server could not serialize the result requested. Server error - Error during serialization: java.lang.NullPointerException. Note that the class must be serializable by the client and server for proper operation.
```

I was able to reproduce it on 1.0-rc1. The bug is caused by `RelationIdentifierGraphBinarySerializer`, which does not consider properties would have `inVertexId` to be null.

**Comment by li-boxuan** [comment]
Need to check if this bug exists in v0.6 as well.

**Comment by farodin91** [comment]
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java#L40 this line has changed. Could this value be null.

**Comment by li-boxuan** [comment]
> Could this value be null?

Yes I forgot to do null check for `inVertexId`.

**Comment by farodin91** [comment]
Should we fix RelationIdentifier to be prepared for different types, as we already have a breaking change.

**Comment by li-boxuan** [comment]
> Should we fix RelationIdentifier to be prepared for different types, as we already have a breaking change.

Yes, in my #3418 PR, I introduce another breaking change to include markers and support different types of ids: https://github.com/JanusGraph/janusgraph/pull/3418/files#diff-2f173d6ce2e1e69cf3dd4d9b39b452e1a07ef9ca83857ce7e8126cfc8948dd7eR77 (which would also require a fix because I failed to consider properties serialization there too).
