### ISSUE TITLE
Hbase 1.2.0  guava  version conflict

### ISSUE THREAD

**Issue by hapuer** [JanusGraph/janusgraph#349]
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator

**Comment by sjudeng** [comment]
This is usually an issue with classpath order. Guava Stopwatch is overriden in [janusgraph-hbase](https://github.com/JanusGraph/janusgraph/blob/84ead7d907b62061e30c5d3210e5e8422fd4648c/janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/com/google/common/base/Stopwatch.java) but the janusgraph-hbase jar must be before guava in the classpath.
