### ISSUE TITLE
New Cassandra backend using CQL w/ prepared statements

### ISSUE THREAD

**Issue by rustyrazorblade** [JanusGraph/janusgraph#35]
Thrift is deprecated and will be removed in Cassandra 4.0.

For perf reasons, avoid IN() clauses for selects, prefer concurrent async queries.

**Comment by sharpau** [comment]
A request for any new Cassandra backend work: please consider better handling for vertices with large numbers of edges. In particular, although one can partition adjacency lists in Titan (http://s3.thinkaurelius.com/docs/titan/1.0.0/graph-partitioning.html), the results of traversals are still subject to hitting the Cassandra frame size limit, even though each individual partition should not.

Given how well the Tinkerpop API adheres to a lazy, streaming data model, it's frustrating when Titan's backend implementation does not.

**Comment by dylanht** [comment]
@sharpau thank you for the advice. I'm going to self-assign this one, and intend to deprecate thrift support.

**Comment by sjudeng** [comment]
The thread below mentions using thrift to enable support for ScyllaDB. Would this capability be affected by the proposed updates?

https://github.com/scylladb/scylla/issues/693
https://github.com/JanusGraph/janusgraph/issues/53

**Comment by rustyrazorblade** [comment]
@dylanht I can help with the data modeling on this.  I'm one of the first people to put titan + cassandra in production, and seen where it fails (miserably).

**Comment by dylanht** [comment]
@sjudeng I just had a look over ScyllaDB's docs on [Cassandra compatibility](http://docs.scylladb.com/cassandra-compatibility/) and it's my understanding that we can use [CQL Binary Protocol](https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol_v3.spec) with ScyllaDB just as well as Thrift (the REGISTER and AUTH_RESPONSE requests, and the AUTHENTICATE response are not supported by Scylla in case that alarms anyone), and reading through the comments in the issue you linked it seems Thrift support in ScyllaDB was actually the initial barrier to integration. Now that they have implemented support for Thrift https://github.com/scylladb/scylla/issues/399 and given the patches @duartan linked recently that apparently fix the OLAP queries @pluradj was running, my impression is that things are "working" on ScyllaDB master via Thrift. Correct me if I'm wrong, but it looks like support for CQL in Titan especially with @rustyrazorblade offering to help us out (thank you Jon!) might immediately provide a more stable/performant integration with ScyllaDB. 

I agree with the [assessment of Netflix on moving away from Astyanax/Thrift](http://techblog.netflix.com/2016/02/astyanax-retiring-old-friend.html), and I think deprecation or "maintenance mode" for the analogous components in JanusGraph is reasonable. To keep things clean for this work, I won't deprecate anything and we can just create a new backend configurable via `storage.backend=cassandracql` or just `cql`, and post a separate issue for deprecation of Astyanax/Thrift support. WDYT?

**Comment by rustyrazorblade** [comment]
+1 to backend = cql.

While I think it would be nice if ScyllaDB worked correctly, I don't know if that should be the main goal of a *CQL* implementation.  Fortunately I think a reasonable design for a graph doesn't really require a lot of CQL that ScyllaDB doesn't implement, so it should work out.

Generally, it's a good idea to avoid the following Cassandra featuers:

* Materialized Views.  They are still unstable.  Currently lead to issues with bootstrap & repair.  
* LWT (`IF NOT EXISTS`).  These rely on Paxos and perform extremely poorly under contention, resulting in node failure.
* Secondary indexes.  Performance wise, they're pretty terrible.  Implemented as hidden tables under the hood.

**Comment by sjudeng** [comment]
@dylanht Thanks for the great info! Sounds promising it might just work out. As a separate effort from this we should probably add some tests to validate ScyllaDB support in legacy cassandra and/or cql backend.

**Comment by dylanht** [comment]
@rustyrazorblade +1 that the goal here should be integration with Cassandra and not ScyllaDB if I'm reading into your statement correctly. While ScyllaDB's [blurb on licensing](http://www.scylladb.com/opensource/) is reassuring, as they say some entities will not approve AGPLv3.0 regardless. It seems the pragmatic thing to do is to focus on Apache 2.0 licensed Cassandra which likely (speculation on my part, but if I had to guess) accounts for the majority of deployments and expertise out there among teams interested in JanusGraph anyways. Thank you for the guidance on features to avoid up-front. I'm planning to push initial commits to this branch over the weekend https://github.com/dylanht/janusgraph/tree/cql-support

@sjudeng +1 on an issue for adding some tests to support ScyllaDB running under both Thrift and CQL, it looks like we have existing deployments and a lot of interest carried over from those involved in the issue you linked to above. ScyllaDB team seems to like the idea of a reliable integration point, so IMO there's a ton of value added here for little effort and we can work things out with them if it comes to it.

**Comment by rustyrazorblade** [comment]
> that the goal here should be integration with Cassandra and not ScyllaDB if I'm reading into your statement correctly.

Exactly.  If ScyllaDB claims they're a drop in replacement for Cassandra, it's on them to provide the compatibility.  I also haven't talked to a single person using it in production, so compromising on the data model of the graph would be a tradeoff with very little gain.

**Comment by fppt** [comment]
+1 on the general sentiments of dropping thrift regardless of ScyllaDB. The objective is to maintain the data model on a Cassandra backend. If Scylla claims to be a drop in replacement for Cassandra then it is up to them to provide the CQL interface.

**Comment by dylanht** [comment]
@fppt @rustyrazorblade agreed, I appropriated #53 for exploring/testing the "drop-in" of ScyllaDB, with the idea that we just test it according to what's existing for Cassandra and if it lives up to the claims great, we'll provide some basic documentation amounting to little more than changing the `storage.backend` value. If we hit snags and as we iterate on `janusgraph-cassandra`, at least we'll have it under test. I noted that #53 depends on this issue and will follow after, and I'm thinking we deal with Thrift/Astyanax backend deprecation/removal respectively in separate issues.

**Comment by penberg** [comment]
@dylanht ScyllaDB supports `REGISTER`, `AUTHENTICATE ` and `AUTH_RESPONSE` messages. The status page seems to be wildly out-of-date. The only limitation in ScyllaDB is that we don't support the newer role-based access control: https://github.com/scylladb/scylla/issues/1941

**Comment by psterk1** [comment]
+1 for supporting CQL backend

**Comment by clauds2x** [comment]
+1 for supporting CQL backend

**Comment by rsteppac** [comment]
+1 for supporting CQL backend

**Comment by pluradj** [comment]
Related dev mailing list discussion https://groups.google.com/d/msg/janusgraph-dev/MIsf4_pqGBc/hGyYtGyWBAAJ

**Comment by sharpau** [comment]
I'll add here another request due to a frustration with Titan: Titan 1.0's Cassandra thrift implementation has frame size issues not only with edges, but also with indices. So when a composite index (i.e. Titan-only, no external indexing backend) gets too large, exceptions like `org.apache.thrift.transport.TTransportException: Frame size (171114550) larger than max length (104857600)!` become very common.

So for a new CQL backend, both edge and index storage should be paged through when accessed instead of pulling a huge chunk into memory.

**Comment by sjudeng** [comment]
Merge of #166 resolves this issue.
