### ISSUE TITLE
How do decrypt and / or unzip the `janusgraph-0.1.1.zip.asc` file?

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [JanusGraph/janusgraph#359]
How do decrypt and / or unzip the `janusgraph-0.1.1.zip.asc` file?

What I did so far:

**Importing the keys**
`gpg --import KEYS`

**Decrypting** 
```zsh
> gpg --decrypt janusgraph-0.1.1.zip.asc

Please enter name of data file: janusgraph-0.1.1.zip.asc
gpg: Signature made Tue May 16 05:08:13 2017 CEST
gpg:                using RSA key <key>                                    
gpg: BAD signature from "Theodore Ratte Wilmes (CODE SIGNING KEY) <twilmes@apache.org>" [unknown]
```

Is this the correct procedure?
Does the `KEYS` file contain the correct keys?
If not, where to get them?

**Comment by robertdale** [comment]
I believe it's just for verifying the file.
`gpg --verify janusgraph-0.1.1-hadoop2.zip.asc janusgraph-0.1.1-hadoop2.zip`
