### ISSUE TITLE
Remove HBase 0.94 support

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#36]
HBase 0.94 is an old release.  Let's deprecate its support.

**Comment by jerryjch** [comment]
There are probably still a lot of 0.94 deployments. It is a long release with many patch releases.
Let's see if we want to remove its support completely.

**Comment by jerryjch** [comment]
Here is a recent survey on the HBase versions used in production from the hbase user list.
https://groups.google.com/forum/#!topic/nosql-databases/TSM63rkMCYc

**Comment by jerryjch** [comment]
This is also going to be tied with our hadoop support.  #39 

Currently in janusgraph-hbase-parent/janusgraph-hbase-094/pom.xml, 
   <properties>
        <hadoop.version>${hadoop1.version}</hadoop.version>
        <jruby.version>1.6.5</jruby.version>
        <hadoop.profile>1.0</hadoop.profile>

In the HBase doc, HBase 0.94 claims to only support hadoop 1.
https://hbase.apache.org/book.html#hadoop

If we only support hadoop2, it is going to be hard to have HBase 0.94.

**Comment by hsaputra** [comment]
I think we should just deprecate support for 0.94 while we can. Supporting more versions especially HBase 0.94 is a PITA.

Since we are "new" project it is making sense to start with latest dependencies as much as we can.

**Comment by jerryjch** [comment]
Resolved by Pull request #63
