### ISSUE TITLE
Trigger GitHub Actions on automatic PRs opened by GitHub Actions

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#3635]
Automatic backporting PRs which are opened by GitHub Actions are not triggering the GitHub Actions CI.
An example PR: https://github.com/JanusGraph/janusgraph/pull/3633
The issue and the solution is most likely defined here: https://github.com/orgs/community/discussions/25602

**Comment by FlorianHockmann** [comment]
I just found sqren/backport-github-action#79 where the same issue is discussed specifically for the backport action.
I think creating a new user for this and then using a personal access token from that user for the action as suggested [in this comment on that issue](https://github.com/sqren/backport-github-action/issues/79#issuecomment-1196622744) is the best workaround for us right now.
I'll try that out.

**Comment by porunov** [comment]
> I just found [sqren/backport-github-action#79](https://github.com/sqren/backport-github-action/issues/79) where the same issue is discussed specifically for the backport action. I think creating a new user for this and then using a personal access token from that user for the action as suggested [in this comment on that issue](https://github.com/sqren/backport-github-action/issues/79#issuecomment-1196622744) is the best workaround for us right now. I'll try that out.

Sounds good! That said, We have [janusgraph-bot](https://github.com/janusgraph-bot) and I believe @mbrukman should have access to that bot. Maybe we could reuse that bot for this purpose as well. I.e. create PAT for janusgraph-bot. Nevertheless, using another user is good as well.
