### ISSUE TITLE
Eliminate 3rd party stylesheet and font dependencies

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#368]
The Avada stylesheet is says its license is GPL. Avada also pulls in a jQuery plugin called Isotope, which has a several [license options](http://isotope.metafizzy.co/docs/license.html). Font Awesome uses [SIL OFL 1.1](http://fontawesome.io/license/).
- [avada-stub/style.css](https://github.com/JanusGraph/janusgraph/blob/v0.1.1/docs/static/avada-stub/style.css#L8)
- [avada-stub/js/main.js](https://github.com/JanusGraph/janusgraph/blob/v0.1.1/docs/static/avada-stub/js/main.js#L2167-L2170)
- [font-awesome-4.0.3/css/font-awesome.css](https://github.com/JanusGraph/janusgraph/blob/v0.1.1/docs/static/font-awesome-4.0.3/css/font-awesome.css#L3)

There's no reason other than good looks to use these artifacts. It would be cleaner for license scans of the JanusGraph source repository to remove these, and ultimately the docs won't look significantly different.

I have a pull request coming.

**Comment by mbrukman** [comment]
If you need to add fonts which are more interesting than the default system-installed fonts, [Google Fonts](https://fonts.google.com/) has a number of free web fonts that are trivial to embed via CSS.
