### ISSUE TITLE
Deprecate vertex-cut (vertex partitioning) feature

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3712]
https://docs.janusgraph.org/advanced-topics/partitioning/#vertex-cut suggests a way to overcome the super node problem: vertex-cut (vertex partitioning).

This feature has two important problems:
1) It is BUGGY. I have seen two companies struggling with this `partition()` feature and have to abandon it at the end (which is painful because they have to rebuild their graph). I cannot share the details but I am pretty sure we have one or more bugs around this feature.
2) It has a high overhead and some fundamental design issues. For more details, see this [discussion](https://github.com/JanusGraph/janusgraph/discussions/2717#discussion-3473622).

In the aforementioned discussion, we also discussed some alternative approaches to address the super node problem, but only prototypes have been built so far.

I propose that we add a notice to the user doc, warning that this feature is not production-ready and is discouraged to use.

**Comment by porunov** [comment]
+1 for adding notice to the user doc
