### ISSUE TITLE
Apply Repeat iteration result to multi-query Repeat beginning when possible

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#3733]
Currently only the first iteration of the `Repeat` step can leverage multi-query optimization from multiple results. Subsequent iterations will feed loops with traverse result of a result from the previous iteration. Meaning if `.in()` returns only 5 vertices per original vertex then only those 5 vertices will be fed into the next iteration.   
`graph.traversal().V().repeat(__.in())` - the first iteration will fetch `batchSize` vertices, other iterations will be fetching vertices one by one (assuming each vertex have only 1 incoming edge).
`graph.traversal().V().in().in().in()` - all 3 `in()` steps will execute queries for `batchSize` (i.e. this query is optimized, but the above query isn't).

**Comment by porunov** [comment]
I think if `start` step of `repeat`, `emit`, or `until` steps is any multi-query compatible step then we should include MultiQueryStep at the end of the `repeat` step and register all of those starts with the created MultiQueryStep.
Even if it's our last iteration it's still OK to register vertices for the next iteration (i.e. it's OK to register vertices for the next iteration even if that iteration won't happen).

**Comment by porunov** [comment]
After a small investigation I see that Repeat step is batched when `.emit` step is placed after `.repeat` step, but not batched when `.emit` step is batched before `.repeat` step.
A test to reproduce the issue (can be placed in `JanusGraphTest.java`):
```
@Test
public void testLimitBatchSizeForRepeatStep() {

    JanusGraphVertex a = graph.addVertex();
    addTestAdjacentVertices(a,  10,4);

    clopen(option(USE_MULTIQUERY), true, option(LIMIT_BATCH_SIZE), true);

    TraversalMetrics profile = graph.traversal().V(a).union(__.identity(), __.repeat(__.in("knows")).emit()).count().profile().next();
    assertTrue(profile.toString().contains("vertices=100000"));

    profile = graph.traversal().V(a).emit().repeat(__.in("knows")).count().profile().next();
    assertTrue(profile.toString().contains("vertices=100000"));
}

private void addTestAdjacentVertices(Vertex vertex, int levelVerticesAmount, int depth){
    for (int i = 0; i < levelVerticesAmount; ++i) {
        Vertex adjacentVertex = graph.addVertex();
        adjacentVertex.property("foo", "bar");
        adjacentVertex.addEdge("knows", vertex);
        if(depth>0){
            addTestAdjacentVertices(adjacentVertex, levelVerticesAmount, depth-1);
        }
    }
}
```

In the above step `graph.traversal().V(a).union(__.identity(), __.repeat(__.in("knows")).emit()).count().profile().next()` in this query `.repeat` step is using batching of vertices. That said, the `.barrier` step which is inserted has unlimited size which means that such batch retrieves 10 vertices, 100 vertices, 1000, vertices, 10000 vertices, 100000 vertices of different levels.
Profile:
```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[v[4128]])                                            1           1        1001.362    50.06
JanusGraphMultiQueryStep                                               1           1           0.138     0.01
NoOpBarrierStep(null)                                                  1           1           0.042     0.00
UnionStep([[IdentityStep, EndStep], [RepeatStep...                111111      111111         984.102    49.19
  IdentityStep                                                         1           1           0.067
  EndStep                                                              1           1           0.128
  RepeatStep([JanusGraphMultiQueryStep, NoOpBar...                111110      111110         945.578
    JanusGraphMultiQueryStep                                      111111      111111          31.547
    NoOpBarrierStep(null)                                         111111      111111          39.290
    JanusGraphVertexStep(IN,[knows],vertex)                       111110      111110         816.842
      \_condition=type[knows]
      \_orders=[]
      \_isFitted=true
      \_isOrdered=true
      \_query=knows:SliceQuery[0x70C1,0x70C2)
      \_multi=true
      \_vertices=100000
      optimization                                                                             0.025
      backend-query                                                   10                       3.456
        \_query=knows:SliceQuery[0x70C1,0x70C2)
      optimization                                                                             0.003
      backend-query                                                  100                       0.864
        \_query=knows:SliceQuery[0x70C1,0x70C2)
      optimization                                                                             0.003
      backend-query                                                 1000                       1.389
        \_query=knows:SliceQuery[0x70C1,0x70C2)
      optimization                                                                             0.005
      backend-query                                                10000                       8.603
        \_query=knows:SliceQuery[0x70C1,0x70C2)
      optimization                                                                             0.015
      backend-query                                                93340                      74.163
        \_query=knows:SliceQuery[0x70C1,0x70C2)
      optimization                                                                             0.016
      backend-query                                                    0                     517.730
        \_query=knows:SliceQuery[0x70C1,0x70C2)
    RepeatEndStep                                                 111110      111110          42.403
  EndStep                                                         111110      111110          19.672
CountGlobalStep                                                        1           1          14.791     0.74
                                            >TOTAL                     -           -        2000.438        -
```

The query after `graph.traversal().V(a).emit().repeat(__.in("knows")).count().profile().next()` fetches vertices one by one which is match slower then the query above.
Profile:
```
Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
GraphStep(vertex,[v[4128]])                                            1           1         999.363     4.18
JanusGraphMultiQueryStep                                               1           1           0.087     0.00
NoOpBarrierStep(null)                                                  1           1           0.040     0.00
RepeatStep(emit(true),[JanusGraphMultiQueryStep...                111111      111111       22901.337    95.73
  JanusGraphMultiQueryStep                                        111111      111111        3798.567
  NoOpBarrierStep(null)                                           111111      111111        1863.818
  JanusGraphVertexStep(IN,[knows],vertex)                         111110      111110       15808.372
    \_condition=type[knows]
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=knows:SliceQuery[0x70C1,0x70C2)
    \_multi=true
    \_vertices=1
    optimization                                                                               0.013
    backend-query                                                     10                       0.278
      \_query=knows:SliceQuery[0x70C1,0x70C2)
    optimization                                                                               0.003
    backend-query                                                     10                       0.196
      \_query=knows:SliceQuery[0x70C1,0x70C2)
...
...
...
  RepeatEndStep                                                                             1332.767
CountGlobalStep                                                        1           1          20.837     0.09
                                            >TOTAL                     -           -       23921.666        -
```

-----

@rngcntr I think we should either include barrier steps with the size of `2500` (maybe make it configurable) or update documentation to be more clear about those barrier steps. What do you think about it?

Currently documentation says:
> Although batch size does not necessarily need to be configured, it can provide an additional tuning parameter to improve the performance of a query. By default, the batch size of [TinkerPop's barrier step](https://tinkerpop.apache.org/docs/current/reference/#barrier-step) will be used, which is currently at 2500. The batch size of each vertex step can be individually configured by prepending a barrier(<size>) step. For example, in the query below, the first out() step would use the default batch size of 2500 and the second out() step would use a manually configured batch size of 1234:

I think this isn't fully true right because TinkerPop may insert some barrier steps using `LazyBarrierStrategy` with default size of `2500` in some places, but not to all places. After that in `JanusGraphMultiQueryStrategy` we may insert more `.barrier` steps with unlimited size to places where neither TinkerPop not user included `.barrier` step. Thus, it will mean that for such requests there will be unlimited batches. 
You can reproduce the issue by using the above query (`graph.traversal().V(a).emit().repeat(__.in("knows")).count().profile().next()` - this will insert unlimited `.barrier` step before `.in` step and before `.repeat` step).

**Comment by rngcntr** [comment]
Hi @porunov, thanks for your investigation!
I had a quick look at the inserted `.barrier` steps and I'm not quite sure for what reason they have no barrier. Wouldn't it be an easy solution to add the default limit to those barrier steps produced by the `JanusGraphMultiQueryStrategy`? If the user wants a different batch size, they can still just provide their own barrier steps.

**Comment by porunov** [comment]
> Hi @porunov, thanks for your investigation! I had a quick look at the inserted `.barrier` steps and I'm not quite sure for what reason they have no barrier. Wouldn't it be an easy solution to add the default limit to those barrier steps produced by the `JanusGraphMultiQueryStrategy`? If the user wants a different batch size, they can still just provide their own barrier steps.

Makes sense. I created a separate issue #3773 to track it. Will work on it soon.
