### ISSUE TITLE
Precision data type should be removed from the docs

### ISSUE THREAD

**Issue by disruptek** [JanusGraph/janusgraph#375]
This missing type was confusing to this newbie.

**Comment by pluradj** [comment]
Not clear what you're referring to here. Do you have specific documentation links?

**Comment by disruptek** [comment]
I tried to create a property key using Gremlin with the `Precision` type as per http://docs.janusgraph.org/latest/schema.html and http://docs.janusgraph.org/latest/search-predicates.html but received what appeared to be an essentially an "unrecognized symbol" error.

I found a list post https://goo.gl/U3MTz2 which seemed to suggest the deprecation of the Precision type.  Looking more closely, I found another list post https://goo.gl/rQUsDK which similarly suggests that `Double` is the new `Precision` and `FullDouble` is a "real" double.

It is, of course, entirely possible that I'm still confused.  :wink:

**Comment by pluradj** [comment]
Thanks for the links. You're right. `Precision` and `Decimal` should be removed.

It looks like they were in [Titan 0.5.4](https://github.com/thinkaurelius/titan/tree/0.5.4/titan-core/src/main/java/com/thinkaurelius/titan/core/attribute) then removed in [Titan 0.9.0-M2](https://github.com/thinkaurelius/titan/tree/0.9.0-M2/titan-core/src/main/java/com/thinkaurelius/titan/core/attribute).

**Comment by robertdale** [comment]
This was fixed in #170 .  The docs on the website don't get updated until a new release is made. So we'll have to wait until 0.2 is released.
