### ISSUE TITLE
Support HBase 1.2

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#38]
HBase's current stable release is 1.2.4.
https://archive.apache.org/dist/hbase/stable/

Let's add support for HBase 1.2.x line.

**Comment by jerryjch** [comment]
HBase 1.2 is API compatible and client/server compatible with 1.1 and 1.0.

Currently there are:
JanusGraph-HBase: 0.98 Compatibility Shim
JanusGraph-HBase: 1.0 Compatibility Shim

I don't think we need to create another Compatibility Shim for HBase 1.2.
The same 1.0 Compatibility Shim can be used for HBase 1.2.

So the plan is to support HBase 1.0, 1.1 and 1.2, but no extra sub-module/shim.
I am thinking we just bump up the dependency version in the existing janusgraph-hbase-parent/janusgraph-hbase-10 to hbase version 1.2.

The janusgraph-dist will bump up to hbase version 1.2 as well.

We will claim support for HBase 0.98, 1.0, 1.1 and 1.2.  The build release tarball contains the 0.98 shim, 1.x shim, and HBase 1.2 jars.

Hopefully the user can just drop in a different set and version of hbase jars if they want to use an older version. Need to test this binary compatibility.

**Comment by jerryjch** [comment]
Any thoughts?

**Comment by sjudeng** [comment]
From a testing perspective it might be a good idea to include regular test runs of at least the janusgraph-hbase-10 module with the supported versions (e.g. `mvn verify -pl :janusgraph-hbase-10 -Dhbase100.coreversion=1.1.x`, etc.). That's an easy step for a developer to forget is one issue. Other issue is time to run the test suite ... but 0.94 and 0.96 modules were just dropped so I guess easy come easy go.

If 1.2 is API and client/server compatible with 1.1 and 1.0 would the user actually have to change any jars if JanusGraph was bundled with 1.2 jars?

**Comment by jerryjch** [comment]
Right, it is not required to replace the bundled 1.2 jars in JanusGraph with a set of 1.0 or 1.1 jars to work with a 1.0 or 1.1 HBase cluster.   Replacing would work as well.
Using -Dhbase100.coreversion=1.x.x to run cycles with different versions is an option. That will increase the time.  We will need to judge the risk not running with the extra old versions, which is likely minimal.

**Comment by jerryjch** [comment]
Fixed by PR #94
