### ISSUE TITLE
Group keys by token ranges for CQL storage backend and execute a single SliceQuery for them via IN operator 

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#3863]
Right now CQL storage backend executes a separate CQL query per each partition key (vertex id) when executing `SliceQuery` queries.
This comes with additional network overhead, channels clogging, as well as potential overhead on the Cassandra storage side. 
Usually, usage of `IN` operator isn't a good choice due to potential touch of multiple nodes ([blog link](https://lostechies.com/ryansvihla/2014/09/22/cassandra-query-patterns-not-using-the-in-query-for-multiple-partitions/), [doc link](https://docs.datastax.com/en/dse/6.8/cql/cql/cql_reference/cql_commands/cqlSelect.html#cqlSelect__selectInNot)).
However, I suspect that touching multiple partition withing the same token range (i.e. same data shard) may have positive influence on performance due to less network overhead (**needs to be verified**).

As such, if we group keys by token ranges then it makes sense to execute all (or some amount) of grouped keys together.
For example, let's imagine we have 2 token ranges and we want to execute a query for 10 keys (4 from the first token range, and 6 from the second token range).
As such, after grouping we will have 2 CQL queries (instead of 10 CQL queries as it is right now). The first query will use keys 1-4, and the second query will use keys 5-10. 

However, if we execute a query touching multiple partition keys we will need to return a requested `key` back with a query (i.e. +8 bytes of data). 
I believe the overhead is quite small and it worth returning keys with such queries if grouped queries improve performance.

## How to implement it?

WIP PR can be found here: #3879

An example of grouping keys by same partition could be found in `CQLSliceQueryUtil` in this unfinished commit:
https://github.com/porunov/janusgraph/commit/f8efa3fe74adb6129e27186dab11e3fbc4d184a7

**Comment by porunov** [comment]
Also, in case someone uses Serverless deployments and pays pay read then by grouping keys together we may greatly decrease read cost in some scenarios.
For example, in AstraDB they charge per [read request unit](https://www.datastax.com/products/datastax-astra/pricing) based on the payload of each read query response. Where they describe “Read Request Unit” (RRU) as following:

> A read request that returns up to 4KB of data is considered one RRU. If the request returns more than 4KB of data, additional RRUs are required. If the read request involves an ALLOW FILTERING query the data is measured prior to in-memory filtering.

Typically JanusGraph sends many small CQL queries where each query returns very small amount of data. 
Let's say user reads properties for many vertices (batch reading. I.e. multi-query). JanusGraph will send at least 1 CQL query for each vertex (but may send more queries depending on the configuration and query itself). If we assume that each response is around 40 bytes (like column 8 bytes + 32 bytes of the property value) than the price user pays for such requests is **at least** 100 times higher than the price user would pay if we could group multiple keys together (to reduce the amount of CQL queries and optimize data retrieval). 

Thus, resolving this issue may give not only some potential performance improvements, but also huge price deduction for some Serverless CQL storage use-cases.

**Comment by li-boxuan** [comment]
This looks very interesting! I have a dumb question:

> Grouping keys by partition

What does it exactly mean? Isn't partition and key 1-to-1 mapping?

**Comment by porunov** [comment]
> This looks very interesting! I have a dumb question:
> 
> > Grouping keys by partition
> 
> What does it exactly mean? Isn't partition and key 1-to-1 mapping? i.e. a partition consists of multiple rows with the same partition id (vertex id).

I guess I’m not fully following the question 😅 
It could be we understand different things under “partition” word. I think I need to improve my wording, so that it could be more clear.

Here by “Partition” I mean a group of keys which are assigned to the same nodes. 
Partition is determined by partition key (i.e. vertex id). You are right that partition key is the vertex id. I.e. it means that vertex id decides to which partition should it belong (i.e. all columns of that vertex).
By partition I mean a chunk of keys (vertices) which belong to the same token range. I.e. those keys (vertex ids) belong to the same nodes because they use the same token ranges.
Thus, the idea is to send a group of keys together in a single CQL query which will touch a single partition only.

**Comment by li-boxuan** [comment]
> Here by “Partition” I mean a group of keys which are assigned to the same nodes.

I see, yeah that it indeed where my confusion was from, as a `partition` in Cassandra usually means a set of rows with the same `partition key`.

Grouping keys together might not lead to better performance. I could imagine scenarios where it leads to worse performance. For example, two queries with different keys could have gone to two different nodes (same shard, different replicas) in parallel. With the grouping logic, I imagine both lookups will happen on the same node. I am not Cassandra expert so this is just my thought experiment, but I am a bit concerned about the performance.

**Comment by porunov** [comment]
> Grouping keys together (if they belong to the same token range) might not lead to better performance. I could imagine scenarios where it leads to worse performance. For example, two queries with different keys could have gone to two different nodes (same shard, different replicas) in parallel. With the grouping logic, I imagine both lookups will happen on the same node. I am not Cassandra expert so this is just my thought experiment, but I am a bit concerned about the performance.

It's true. For situations when your query touches small amount of keys grouping might actually be worse than sending those queries in parallel because your query might be processed by several replicas (in case you use replication factor more than `1`). Also for deserialization we are using a thread pool with the size of `processors * 2`. With grouping the whole deserialization for several keys is executed in a single thread. Moreover, with groping we need to return `key` for each row which increases returned data size.
So, performance regression in scenarios when you query a small set of keys is totally possible. That said, the picture changes when you need to query big number of keys. With big number of keys (let's say thousands) your replicas  (which is usually `3` or `5`) will be spammed with many queries anyways. The question only if those queries are grouped or not. I.e. instead of 10000 queries you may group them by 100 keys and send 100 grouped queries instead - in this situations all your replicas and all your deserialization threads will be working on processing those 100 queries in parallel.
Most likely, due to a smaller network overhead your grouped queries will be returned faster. You channels won't be clogged with many small CQL requests. You won't suffer from reaching `storage.cql.max-requests-per-connection`.
Of course users need to decide if they want to make grouped queries or not, and if they want to group keys then what's the maximum amount of keys they want to group together.
I do expect some performance improvements for big queries (with thousands of keys), but I guess I expect more price reduction for Serverless deployments where you pay per each CQL query. I do expect small performance regression for queries with small amount of keys when the grouping feature is enabled.

**Comment by porunov** [comment]
> I see, yeah that it indeed where my confusion was from, as a partition in Cassandra usually means a set of rows with the same partition key.

I will change the wording above so that it clear that the grouping is per token ranges and not per partition. We already execute a single query per partition. I think I confused many people here when used `Partition` instead of `Shard`.

**Comment by li-boxuan** [comment]
> I do expect some performance improvements for big queries (with thousands of keys)

I see, that seems to make sense to me. Cannot wait to see the performance benchmarks.

**Comment by porunov** [comment]
> > I do expect some performance improvements for big queries (with thousands of keys)
> 
> I see, that seems to make sense to me. Cannot wait to see the performance benchmarks.

The PR is: #3879 
The PR is ready but I need to add tests to cover new configuration options with tests and properly benchmark it. 
Nevertheless, the functionality in the PR is ready (I don't expect any functionality changes there).

I only tested in locally (i.e. with the single-instance Cassandra running on the same node with replication factor = `1`).
I did see 10-20% performance improvements for most of the CQL benchmarks (and up to 45% improvement in some cases). However, the benchmarks which touch a small amount of keys (tests with less than 500 keys) didn't perform well as you expected. There were performance regression for such scenarios 10-20%. 
I don't have a distributed testing environment yet to properly benchmark the changes, but I will try to setup one later. 
In case you have a distributed Cassandra by any chance then it would be great if you could execute some CQL benchmark tests using that environment because the results might be different from what I'm getting locally right now.

@cdegroc @FlorianHockmann I have changed the description to emphasize grouping by token ranges instead of by partitions because I used `Partition` wording wrongly previously as @li-boxuan noticed. Thus, you might have been confused by the previous description.

In case anyone can check #3879 benchmarks in your environments then it would really help.
The grouping configuration options are enabled by default in #3879 , thus simply executing benchmarks would be good enough.
The behavior can be changed by using new config options:
```
storage.cql.grouping.keys-allowed
storage.cql.grouping.keys-limit
storage.cql.grouping.keys-min
storage.cql.grouping.slice-allowed
storage.cql.grouping.slice-limit
```
