### ISSUE TITLE
Remove hadoop 1 support

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#39]
Do we still need to keep the hadoop 1 profile/module?

**Comment by sjudeng** [comment]
Just noticed the TinkerPop 3.1.0 release notes for Hadoop Gremlin state "Hadoop1 is no longer supported". Based on this I'd agree the hadoop1 profile/module should just be removed from JanusGraph.

http://tinkerpop.apache.org/docs/3.1.1-incubating/upgrade/#_tinkerpop_3_1_0_2

**Comment by jerryjch** [comment]
Thanks for chiming in. Good info.

**Comment by jerryjch** [comment]
Resolved by Pull request #65
