### ISSUE TITLE
JanusGraph should support the ability to access graphs dynamically.

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#391]
With the addition of [this PR into TinkerPop](https://github.com/apache/tinkerpop/pull/569), implementations running the GremlinServer can customize their GraphManager for more customizability around creating/accessing/storing graph references. Since JanusGraph has adopted the version of TinkerPop that includes this code, let's get a good story around creating/accessing/storing graph references.

**Comment by pluradj** [comment]
Merged #392
