### ISSUE TITLE
Issue while creating Vertex Centric Index on edge property.

### ISSUE THREAD

**Issue by dxtr-1-0** [JanusGraph/janusgraph#3968]
### Discussed in https://github.com/JanusGraph/janusgraph/discussions/3965

<div type='discussions-op-text'>

<sup>Originally posted by **dxtr-1-0** September  8, 2023</sup>
Janusgraph version => 0.6.1
Tinkerpop version =>3.5.1
Usign Janusgraph in the embedded library mode and not in server mode. 

I am trying to create vertex centric index(es) on existing edge properties. 
To start with I followed the steps in the documentation. With that I was getting the infamous issue of index getting stuck in INSTALLED state while waiting for it to get available (REGISTERED). On debugging it seemed like it was happening because of already open transactions at the time of waiting for the index to become available. As mentioned in several answers to similar problems online, I followed the steps to close open transactions before calling the ManagementSystem,awaitRelationIndexStatus method. This solved for the issue of index getting stuck in INSTALLED and now i am able to build edge index and REINDEX it. But the probelm is that since its closing all open transactions whatever operations are going on at the time of this indexing, will be aborted and might result in data loss. Please find below the code that i am using currently:

```
public void registerVertexCentricIndexOnEdgeProperty(String edgeLabel, String propertyName, String userId) throws MinervaException {
    String indexName = autoCreatedRelationIndexName(edgeLabel, propertyName);
    StandardJanusGraph standardJanusGraph = (StandardJanusGraph) getGraphObjectByName();
    JanusGraphManagement management = getManagementForGraph();
    val propertyKey = management.getPropertyKey(propertyName);
    val label = management.getEdgeLabel(edgeLabel);
    val index = management.buildEdgeIndex(label, indexName, Direction.BOTH, propertyKey);
    log.info("Created Edge Index: {}. Now Going to wait for it to become REGISTERED", index.name());
    management.commit();

    //Close all open transactions
    standardJanusGraph.getOpenTransactions().forEach(JanusGraphTransaction::rollback);
    ManagementSystem
            .awaitRelationIndexStatus(
                    standardJanusGraph,
                    indexName,
                    edgeLabel
            ).call();
    management = getManagementForGraph();
    management.updateIndex(management.getRelationIndex(label, indexName), SchemaAction.REINDEX).get();
    management.commit();
}
```

Is there a cleaner and more graceful way to do this? I tried searching for similar issue but everywhere the solutions mention the closing of transactions as a mandatory step but if that is the case then this seems like a bug as the official documentation does not mention it explicitly anywhere. Moreover, it essentially means that you have to stop reads and writes on graph while doing reindexing which itself can take sometime to finish. Any help is appreciated. 

[UPDATE] : 
I am trying to debug this locally using test cases in Java. In my case there are no ghost management instances (checked using mgmt.getOpenInstances()). There is only 1 open management instance which has the (current) suffix. Although, i see 4 open transactions using standardJanusGraph.getOpenTransaction(), and on closing them (as in the code above), i am able to move the index from INSTALLED to REGISTERED. I am unable to figure out whether these transactions are management transactions or normal graph transactions. </div>

**Comment by FlorianHockmann** [comment]
I'm closing this as you have already started a discussion for this and we only use issues for (confirmed) bug reports or feature requests, but a discussion seems more suitable here. If the discussion leads to the conclusion that there is a bug or missing feature in JanusGraph, then you can still create an issue which should then have a clear description of the bug / feature request.
