### ISSUE TITLE
Snakeyaml warning in 1.0.0

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3979]
I've just noticed that I'm now getting a warning if I try to use this config file with our latest Docker images:

```java
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
Sep 13, 2023 2:23:59 PM org.yaml.snakeyaml.internal.Logger warn
WARNING: Failed to find field for org.apache.tinkerpop.gremlin.driver.Settings.serializers
```

Do you know what could be causing this, @li-boxuan?

It however continues to work afterwards. I haven't tested however whether the serializer config is actually used or not.

_Originally posted by @FlorianHockmann in https://github.com/JanusGraph/janusgraph/pull/3914#discussion_r1324628050_

**Comment by pdsway** [comment]
This message is from Tinkerpop 3.70

**Comment by ShahimEssaid** [comment]
The field name appears to be wrong here:
https://github.com/apache/tinkerpop/blob/d9bc32714b775d2c8be67abf104e0a6bcdf3faff/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java#L120

**Comment by pdsway** [comment]
interesting, gremlin-driver, "serializer" is the prop for gremlin client yaml (singular) and "serializers" is server side.
i did a quick test changing it to just "serializer".

It does indeed fix gremlin-console (client) which has yaml field "serializer" (singular) but breaks gremlin-server which uses (or used) field "serializers" (multi)

gremlin-server:
Sep 21, 2023 4:46:22 PM org.yaml.snakeyaml.internal.Logger warn
WARNING: Failed to find field for org.apache.tinkerpop.gremlin.server.Settings.plugins
[INFO] o.a.t.g.s.GremlinServer - Configuring Gremlin Server from conf/gremlin-server.yaml
[

**Comment by li-boxuan** [comment]
Yeah seems like it's just a warning. Weird though, I don't see this warning... I built JanusGraph from source code.

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
12:16:12 INFO  org.apache.tinkerpop.gremlin.driver.Connection.<init> - Created new connection for ws://localhost:8182/gremlin
12:16:12 INFO  org.apache.tinkerpop.gremlin.driver.ConnectionPool.<init> - Opening connection pool on Host{address=localhost/127.0.0.1:8182, hostUri=ws://localhost:8182/gremlin} with core size of 1
==>Configured localhost/127.0.0.1:8182-[706c2fc6-38e5-4436-a85b-682a7b4676b4]
gremlin>
```

**Comment by li-boxuan** [comment]
Thanks @FlorianHockmann, closing this issue.
