### ISSUE TITLE
Documentation versions menu doesn't recognize latest version as latest

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#4078]
As seen from the documentation https://docs.janusgraph.org/ versions menu doesn't respect latest version for some reason.

![Screenshot from 2023-10-25 17-03-00](https://github.com/JanusGraph/janusgraph/assets/17673243/b0526024-3ece-4cd1-ab0a-84350516f515)

It could potentially be related to this file: https://github.com/JanusGraph/janusgraph/blob/master/docs/theme/structor-menu.js.gotmpl
Which produces the following output: https://github.com/JanusGraph/docs.janusgraph.org/blob/606b5611bfc55a3bc12a78f8aa11b2a2d7dccc00/v1.0/theme/js/structor-menu.js

```
const versions = [
  {path: "master", text: "Upcoming version", selected: false },
  {path: "v1.0", text: "v1.0 RC", selected: true },
  {path: "", text: "v0.6 Latest", selected: false },
  {path: "v0.5", text: "v0.5", selected: false },
  {path: "v0.4", text: "v0.4", selected: false },
  {path: "v0.3", text: "v0.3", selected: false },
  {path: "v0.2", text: "v0.2", selected: false },
];
```

However, it seems that the output should be the following:
```
const versions = [
  {path: "master", text: "Upcoming version", selected: false },
  {path: "", text: "v1.0", selected: true },
  {path: "v0.6", text: "v0.6", selected: false },
  {path: "v0.5", text: "v0.5", selected: false },
  {path: "v0.4", text: "v0.4", selected: false },
  {path: "v0.3", text: "v0.3", selected: false },
  {path: "v0.2", text: "v0.2", selected: false },
];
```

**Comment by porunov** [comment]
Fixed it temporary by hardcoding versions in the menu. See this PR: #4079 
We should revert [this commit](https://github.com/JanusGraph/janusgraph/commit/5594f09ef1c99e4cd7373b5c43b2bf64994527d0) as soon as we fix this issue.

**Comment by farodin91** [comment]
at this point 1.0.0 wasn't marked as latest release yet.

**Comment by porunov** [comment]
Fixed by @farodin91 in https://github.com/JanusGraph/janusgraph/commit/a9549b5d7cd81897800addc1c01b2fc802c1ce58 and https://github.com/JanusGraph/janusgraph/commit/020642ad74b48b9f27bd7995d3666e766445afe9
