### ISSUE TITLE
GraphBinaryMessageSerializerV1 doesn't work for gremlin-python

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#4121]
```
serializers:
  - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
```
works if you are using a Java client, or gremlin console, but doesn't for gremlin-python 3.7.0, as reported by https://discord.com/channels/981533699378135051/1175217731553984552

Seems JanusGraph 1.0.0 has some incompatibility with gremlin-python package.

Workaround is to use GraphSONMessageSerializerV3.

**Comment by li-boxuan** [comment]
This incompatibility probably resides in other client libraries too. Our E2E tests, don't run for these third-party drivers, unfortunately.

**Comment by li-boxuan** [comment]
I am actually not sure if this is by design. Did `GraphBinary` serializer ever work for `gremlin-python`?

**Comment by cdegroc** [comment]
> I am actually not sure if this is by design. Did `GraphBinary` serializer ever work for `gremlin-python`?

It generally works, but maybe not for "custom" types such as JanusGraph's `RelationIdentifier`.

I've tried the following request:
```python
# return an Edge, i.e. RelationIdentifier for JanusGraph
g.V().limit(1).bothE().limit(1).next()
```
With a `GraphSONMessageSerializer`, this returns an edge with type `janusgraph:RelationIdentifier`.
With `GraphBinarySerializersV1`, it fails with
```
...
/usr/local/lib/python3.10/site-packages/gremlin_python/structure/io/graphbinaryV1.py in _read_edge(cls, b, r)
    536     @classmethod
    537     def _read_edge(cls, b, r):
--> 538         edgeid = r.readObject(b)
    539         edgelbl = r.toObject(b, DataType.string, False)
    540         inv = Vertex(r.readObject(b), r.toObject(b, DataType.string, False))

/usr/local/lib/python3.10/site-packages/gremlin_python/structure/io/graphbinaryV1.py in readObject(self, b)
    189             return self.toObject(io.BytesIO(b))
    190         elif isinstance(b, io.BufferedIOBase):
--> 191             return self.toObject(b)
    192
    193     def toObject(self, buff, data_type=None, nullable=True):

/usr/local/lib/python3.10/site-packages/gremlin_python/structure/io/graphbinaryV1.py in toObject(self, buff, data_type, nullable)
    198                     buff.read(1)
    199                 return None
--> 200             return self.deserializers[DataType(bt)].objectify(buff, self, nullable)
    201         else:
    202             return self.deserializers[data_type].objectify(buff, self, nullable)

KeyError: <DataType.custom: 0>
```

I'm not sure `gremlin-python` allows registering `IoRegistries` [as gremlin-driver does](https://tinkerpop.apache.org/docs/current/reference/#_serialization) today.

**Comment by li-boxuan** [comment]
So yeah I think this is by design. RelationIdentifier is JanusGraph-specific, and thus, only natively supported drivers could use GraphBinary serializer, that is, .Net and java drivers. Third-party drivers, like gremlin-python, could only use GraphSON serializer.

I also verified with JanusGraph 0.6.4 and the exactly same problem exists.

Repro script:
```python
from gremlin_python.process.anonymous_traversal import traversal
from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection
connection = DriverRemoteConnection("ws://localhost:8182/gremlin", "g")
g = traversal().withRemote(connection)
g.addV().next()
```
