### ISSUE TITLE
JanusGraph v1.0 unit tests failing when ran locally

### ISSUE THREAD

**Issue by cdegroc** [JanusGraph/janusgraph#4139]
# Description
Running unit tests from a fresh clone of JanusGraph v1.0 fails locally.

# Steps to reproduce
```
$ git clone https://github.com/janusgraph/janusgraph.git
$ cd janusgraph/
$ git checkout v1.0
$ jenv local zulu64-11.0.21
$ mvn clean test \
    -pl janusgraph-driver,janusgraph-core \
    -Dgpg.skip -Drat.skip
...
<janusgraph-driver tests pass>
<janusgraph-core CompletableFutureUtilTest fails - see stacktrace below>
<janusgraph-core MultiQueriableStepBatchFetcherTest fails - see stacktrace below>
<janusgraph-core other tests pass>
```

- [Stacktrace for CompletableFutureUtilTest](https://github.com/JanusGraph/janusgraph/files/13461093/CompletableFutureUtilTest.failure.txt)
- [Stacktrace for MultiQueriableStepBatchFetcherTest](https://github.com/JanusGraph/janusgraph/files/13461095/MultiQueriableStepBatchFetcherTest.failure.log)

**Comment by cdegroc** [comment]
I am rather puzzled by this issue. I'm not sure how it could have slipped through the net since unit tests are run in the CI.

**Comment by li-boxuan** [comment]
Similar to https://github.com/JanusGraph/janusgraph/issues/3445, we are missing `maven-surefire-plugin` definition in `janusgraph-core/pom.xml` thus the tests are not being picked up by CI.

**Comment by cdegroc** [comment]
Failures are visible from this CI test: https://github.com/JanusGraph/janusgraph/actions/runs/7048125623/job/19185888257
