### ISSUE TITLE
Benchmark Performance regression check failing regularly

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#4154]
I've noticed that this workflow is currently failing for some backporting PRs:
* #4143
* #4144
* #4145
* #4146

But it also failed for many recent commits on `master` and on `v1.0`.

Looks like there is some dependency missing:

```
12:55:57 ERROR com.datastax.oss.driver.api.testinfra.ccm.CcmBridge$2.processLine - ccmerr> Traceback (most recent call last):
12:55:57 ERROR com.datastax.oss.driver.api.testinfra.ccm.CcmBridge$2.processLine - ccmerr>   File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/ccm", line 7, in <module>
12:55:57 ERROR com.datastax.oss.driver.api.testinfra.ccm.CcmBridge$2.processLine - ccmerr>     import pkg_resources
12:55:57 ERROR com.datastax.oss.driver.api.testinfra.ccm.CcmBridge$2.processLine - ccmerr> ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by FlorianHockmann** [comment]
This is failing on `master` now for every commit (excluding doc only commits where this isn't executed).

@li-boxuan Do you maybe have an idea what could lead to these sudden failures? I've noticed that you added this logic to benchmark Cassandra [2 years ago](https://github.com/JanusGraph/janusgraph/commit/15a00b7938052274fe15cf26025168299a311224).

The only results I can find online related to this error message [talk about needing to install Python `setuptools`](https://stackoverflow.com/a/10538412/6753576), but I would expect the `CcmBridge` to handle stuff like that for us since we're only using it from Java.
If we can't get it to work again with this `CcmBridge`, then I think we should remove these benchmarks for now to at least have a green build again.

**Comment by li-boxuan** [comment]
Sorry I missed this earlier. I'll experiment with this.

**Comment by li-boxuan** [comment]
python 3.12 was released on 2 October 2023. I suspect that might be the curse.

**Comment by li-boxuan** [comment]
I found some other victims of python 3.12: https://github.com/googleapis/python-aiplatform/issues/2834 I'll fix this by explicitly installing that package.
