### ISSUE TITLE
hello  why this can not insert to Graph

### ISSUE THREAD

**Issue by lazyfighter** [JanusGraph/janusgraph#419]
![image](https://user-images.githubusercontent.com/17143488/28361189-9d90c2b4-6caa-11e7-92b0-2fbcd958fd73.png)

I

**Comment by mbrukman** [comment]
@lazyfighter — could you please post code snippets as text, instead of screenshots? That makes it easier for others to quote parts of your code to suggest changes.

Also, did you not finish your message? There seems to be some trailing text at the end of it.

**Comment by FlorianHockmann** [comment]
This was already answered on the Gremlin users mailing list where also more information was provided:
https://groups.google.com/forum/#!topic/gremlin-users/Ee_dy-HIl58

The solution was to simply iterate the traversal.

**Comment by pluradj** [comment]
Thanks @FlorianHockmann. @lazyfighter please use the mailing lists for usage question and answers. The issues tracker is for bug reporting. Closing.
