### ISSUE TITLE
Data gets lost when i restart my backend (DynamoDB Local)

### ISSUE THREAD

**Issue by MainaWycliffe** [JanusGraph/janusgraph#425]
I have installed Janus Graph and configured it to use the DynamoDb as the backend (local in my case). I have been trying to learn gremlin using the gremlin console. The issue i have is that when i have executed and committed all queries and then restart the server, all the data is lost and i have to start everything again.

**Comment by pluradj** [comment]
The DynamoDB backend isn't tracked in this repository. It looks like you've already [opened an issue](https://github.com/awslabs/dynamodb-janusgraph-storage-backend/issues/230) in the appropriate spot. FYI @amcp

**Comment by MainaWycliffe** [comment]
So, its not an issue with Janus Graph but with the janus graph but the backend?

**Comment by pluradj** [comment]
Based on the info you provided, it sounds like the graph data is not persisted in the storage backend after a commit. You are using the DynamoDB storage backend for JanusGraph, and its source code is currently in a different repository than this one.

The storage adapters for Cassandra, HBase, and BerkeleyJE are supported by this repository.

**Comment by MainaWycliffe** [comment]
Thanks, i just received confirmation, it uses in memory storage and hence data cannot persists. Thank you very much.
