### ISSUE TITLE
How to load data into JanusGraph (Hbase and Caching)?

### ISSUE THREAD

**Issue by archurcode** [JanusGraph/janusgraph#428]
How to  load data into Hbase?  Not use GraphOfTheGodsFactory.load(graph)

**Comment by pluradj** [comment]
In the future, please use the [janusgraph-users](https://github.com/JanusGraph/janusgraph/blob/master/README.md#community) list for usage questions like this. The issues tracker is used for bug tracking.

[HBase](http://docs.janusgraph.org/latest/hbase.html#_hbase_setup) is just a configuration setting. You can find more of the [configuration settings](http://docs.janusgraph.org/latest/config-ref.html) in the documentation.

```
Graph graph = JanusGraphFactory.build().set("storage.backend", "hbase").set("storage.hostname", "127.0.0.1").set("storage.hbase.table", "mygraph").open();
```

You load the data in the same way regardless of your chosen backend: either call on the graph APIs or traversal APIs to create a graph. By default, a transaction is automatically started for you, so just make sure you commit the transaction when you're done adding the graph elements.

Graph API:
```
Vertex v0 = graph.addVertex(T.label, "person", "username", "archurcode");
Vertex v1 = graph.addVertex(T.label, "person", "username", "pluradj");
Edge e0 = v0.addEdge("connected", v1, "issue", 428);
graph.tx().commit();
```

Traversal API:
```
GraphTraversalSource g = graph.traversal();
g.addV("person").property("username", "archurcode").as("A").addV("person").property("username", "pluradj").as("P").addE("connected").property("issue", 428).from("A").to("P").iterate();
g.tx().commit();
```
