### ISSUE TITLE
Fix JanusGraphIndexTest to use transactionlistener instead of Thread.sleep

### ISSUE THREAD

**Issue by holleyism** [JanusGraph/janusgraph#429]
The use of Thread.sleep() in the unit tests is to give the index and store time to commit the changes since tx().commit() return does not mean the commit has completed.  As documented in response to #329, where applicable, the use of Thread.sleep() in the unit tests should be replaced with tx().addTransactionListener().  Also switch other tests as appropriate.

**Comment by mbrukman** [comment]
Closing issue per [this comment](https://github.com/JanusGraph/janusgraph/pull/423#issuecomment-317487496) which says the PR fixes this issue.

**Comment by sjudeng** [comment]
@mbrukman I think this issue was created to address feedback during review of #423 (see [this comment](https://github.com/JanusGraph/janusgraph/pull/423/files#r130005253)) and isn't yet resolved.

**Comment by holleyism** [comment]
@mbrukman Can you please reopen this as it is not fixed.  Thanks.

**Comment by mbrukman** [comment]
Apologies for the misunderstanding.
