### ISSUE TITLE
Node created failed when adding a label "L"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [JanusGraph/janusgraph#4334]
I execute 2 queries on my empty JanusGraph database ,and an error occurs.

JanusGraph version: 1.0.0
operating system: windows 10

first query: 
g.addV('L').as('n0').has('id', eq(1)).property(single, 'id', 1).V().as('  GENERATED1').where(__.select('  GENERATED1').where(eq('n0'))).hasLabel('L').path().from('  GENERATED1').addV('L').as('n1').V().as('  GENERATED2').where(__.select('  GENERATED2').where(eq('n1'))).hasLabel('L').path().from('  GENERATED2').project('a').by(__.constant(1))

second query: 
g.addV().as('n0').property(single, 'id', 1).V().as('  GENERATED1').where(__.select('  GENERATED1').where(eq('n0'))).where(__.select('n0').values('id').is(eq(1))).path().from('  GENERATED1').addV('L').as('n1').V().as('  GENERATED2').where(__.select('  GENERATED2').where(eq('n1'))).hasLabel('L').path().from('  GENERATED2').project('a').by(__.constant(1))

The first query creates 1 node but the second creates 2.
And they are translated from "CREATE p0=(n0:L{id:1}),p1=(n1:L) RETURN 1 AS a" and "CREATE p0=(n0{id:1}),p1=(n1:L) RETURN 1 AS a" respectively. So I think they should both create 2 nodes.

I use the plugin named [cypher-for-gremlin](https://github.com/opencypher/cypher-for-gremlin) to translate Cypher query to Gremlin query.

**Comment by FlorianHockmann** [comment]
Closed as this is most likely not an issue with JanusGraph, but with _cypher-for-gremlin_. See my [comment in a different similar issue](https://github.com/JanusGraph/janusgraph/issues/4336#issuecomment-2023009469) for more information.
