### ISSUE TITLE
Creating node failed when removing CASE WHEN

### ISSUE THREAD

**Issue by ljhhuxiaoba** [JanusGraph/janusgraph#4338]
I execute 2 queries on my empty JanusGraph database ,and an error occurs.

JanusGraph version: 1.0.0
operating system: windows 10

first query:
g.addV().addV().as('n2').addV().as('n3').addE('T').from('n2').to('n3').as('r').property('id', __.choose(__.constant(true).is(eq(true)), __.constant(1), __.constant('  cypher.null'))).V().as('  GENERATED1').where(__.select('  GENERATED1').where(eq('n2'))).outE('T').as('r').where(__.choose(__.constant(true).is(eq(true)), __.constant(1), __.constant('  cypher.null')).is(neq('  cypher.null')).as('  GENERATED2').select('r').values('id').where(eq('  GENERATED2'))).aggregate('  cypher.path.edge.p0').inV().as('  GENERATED3').where(__.select('  GENERATED3').where(eq('n3'))).path().from('  GENERATED1').addV().project('a1').by(__.constant(1))

second query:
g.addV().addV().as('n2').addV().as('n3').addE('T').from('n2').to('n3').has('id', eq(1)).property('id', 1).V().as('  GENERATED1').where(__.select('  GENERATED1').where(eq('n2'))).outE('T').has('id', eq(1)).aggregate('  cypher.path.edge.p0').inV().as('  GENERATED2').where(__.select('  GENERATED2').where(eq('n3'))).path().from('  GENERATED1').addV().project('a1').by(__.constant(1))

The first query creates 4 nodes but the second creates 3 nodes.
And they are translated from "CREATE (n1), p0 = (n2)-[r:T{id:CASE WHEN TRUE THEN 1 END}]->(n3) CREATE () RETURN 1 AS a1" and "CREATE (n1), p0 = (n2)-[r:T{id:1}]->(n3) CREATE () RETURN 1 AS a1" respectively. The two Cypher queries are equivalent so I think they should both create 4 nodes.

I use the plugin named [cypher-for-gremlin](https://github.com/opencypher/cypher-for-gremlin) to translate Cypher query to Gremlin query.

**Comment by FlorianHockmann** [comment]
Closed as this is most likely not an issue with JanusGraph, but with _cypher-for-gremlin_. See my [comment in a different similar issue](https://github.com/JanusGraph/janusgraph/issues/4336#issuecomment-2023009469) for more information.
