### ISSUE TITLE
Creating node failed when adding "WITH *"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [JanusGraph/janusgraph#4339]
I execute 2 queries on my empty JanusGraph database ,and an error occurs.

JanusGraph version: 1.0.0
operating system: windows 10

first query:
g.inject('  cypher.start').choose(__.V().V(), __.V().V(), __.constant('  cypher.null')).addV().project('a1').by(__.constant(1))

second query:
g.inject('  cypher.start').choose(__.V().as('n0').V().as('n1'), __.V().as('n0').V().as('n1'), __.constant('  cypher.null').as('n0')).select('n0', 'n1').project('n0', 'n1').by(__.select('n0')).by(__.select('n1')).as('  GENERATED1').select('n0').as('n0').select('  GENERATED1').select('n1').as('n1').addV().project('a1').by(__.constant(1))

The first query creates 1 node but the second creates 0 node.
And they are translated from "OPTIONAL MATCH (n0),(n1) CREATE () RETURN 1 AS a1" and "OPTIONAL MATCH (n0),(n1) WITH * CREATE () RETURN 1 AS a1" respectively. The two Cypher queries are equivalent so I think they should both create 1 node.

I use the plugin named [cypher-for-gremlin](https://github.com/opencypher/cypher-for-gremlin) to translate Cypher query to Gremlin query.

**Comment by FlorianHockmann** [comment]
Closed as this is most likely not an issue with JanusGraph, but with _cypher-for-gremlin_. See my [comment in a different similar issue](https://github.com/JanusGraph/janusgraph/issues/4336#issuecomment-2023009469) for more information.
