### ISSUE TITLE
Cannot create vertex-centric-index on edgeLabel with SIMPLE multiplicity

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#442]
This issue existed in Titan: https://github.com/thinkaurelius/titan/issues/1275 and still exists here.

In the issue listed above, someone alluded to a possible solution being to update the `isContrained` function [here](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/core/Multiplicity.java#L67-L72) however I an edgeLabel is technically `constrained` if it is `SIMPLE`-- the constraint being that it can only have one edge between any two vertices. 

Rather than updating that code, I think it makes more sense and will upkeep system integrity by instead changing the caller to open up vertex-centric-index creation to work with SIMPLE by checking [the isUnique function](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/core/Multiplicity.java#L81-L91) instead-- which should correlate to the proper constraints for a vertex-centric-index in relation to an edgeLabel.

**Comment by pluradj** [comment]
#443 merged
