### ISSUE TITLE
Update Bigtable client to 1.0.0 prior to the JanusGraph 0.2.0 release

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#447]
The Bigtable client currently in JanusGraph is 0.9.5.1; the 1.0.0 is currently in a pre-release stage (1.0.0-pre2 is the latest version).

Bigtable client 1.0.0 will bring with it a number of improvements, so rather than upgrading JanusGraph to use an intermediate Bigtable client release such as 0.9.7.x, we should aim to launch the next version of JanusGraph (0.2.0) with Bigtable client 1.0.0 once it is available, which should be in the near future.

**Comment by sjudeng** [comment]
Fixed by #454
