### ISSUE TITLE
Cannot use vertex TTL on Hbase

### ISSUE THREAD

**Issue by yefengzhishu** [JanusGraph/janusgraph#448]
I saw the document on the JanusGraph website and it said Hbase support vertex TTL setting. I am using JanusGraph 0.2.0-SNAPSHOT and Hbase 1.1.4. When I call the function mgmt.setTTL(), an error showed up saying "The storage engine does not support TTL". Could anyone help me?

**Comment by jerryjch** [comment]
I wonder if PR #369 is in the 0.2.0-SNAPSHOT you are  using.

**Comment by jerryjch** [comment]
@yefengzhishu 
JanusGraph 0.2.0 will be released soon.  Please report any issue against JanusGraph 0.2.0.
