### ISSUE TITLE
Fix CI Release commit (and possibly official?) artifacts workflow

### ISSUE THREAD

**Issue by criminosis** [JanusGraph/janusgraph#4531]
**Describe the feature:**
Looks like the `CI Release commit artifacts` workflow has been broken for [at least a couple weeks](https://github.com/JanusGraph/janusgraph/actions/workflows/ci-publish-commit.yml).

>Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project janusgraph-scylla: Remote staging failed: Failed to deploy artifacts: Could not transfer artifact org.janusgraph:janusgraph-berkeleyje:jar:1.1.0-20240624-072117.55880ea from/to ossrh ([https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/orgjanusgraph-1711](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgjanusgraph-1711)): authentication failed for [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/orgjanusgraph-1711/org/janusgraph/janusgraph-berkeleyje/1.1.0-20240624-072117.55880ea/janusgraph-berkeleyje-1.1.0-20240624-072117.55880ea.jar,](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgjanusgraph-1711/org/janusgraph/janusgraph-berkeleyje/1.1.0-20240624-072117.55880ea/janusgraph-berkeleyje-1.1.0-20240624-072117.55880ea.jar,) status: 401 Content access is protected by token -> [Help 1]

It appears [Sonatype has made changes](https://community.sonatype.com/t/401-content-access-is-protected-by-token-authentication-failure-while-performing-maven-release/12741/3) with regards to publisher accounts, presumably JanusGraph commit publications are blocked until the changes are adopted.

**Describe a specific use case for the feature:**
Usage of any libraries published to Maven Central.

**Comment by porunov** [comment]
Thank you @criminosis for noticing it and pointing on the solution! I confirm that after generating User Access token and replacing old password and username with the generated token the workflow is now back to healthy state.
The latest commit release should be indexed by Sonatype OSSRH in 2-4 hours (as usual).

**Comment by criminosis** [comment]
Awesome. Thank you @porunov !
