### ISSUE TITLE
0.5.0 upgrade instructions do not mention removal of inmemory backend from janusgraph-core

### ISSUE THREAD

**Issue by FieteO** [JanusGraph/janusgraph#4532]
While upgrading from Janusgraph 0.4.1 to 0.5.0 I noticed that my test cases that use the inmemory backend started to fail with a ClassNotFoundException for the `InMemoryStoreManager`.
I then looked at the [Upgrade Instructions for 0.5.0](https://docs.janusgraph.org/changelog/#upgrade-instructions_7) and couldn't find any mention of the inmemory backend.
Upon investigating in the code, I saw that the class was moved into a newly created `janusgraph-inmemory` module.

I am sure other users can do that too, but I think this change should be mentioned in the upgrade instructions. In particular,
that for users that use the inmemory backend, it's necessary to add the `janusgraph-inmemory` dependency:
```xml
<dependency>
    <groupId>org.janusgraph</groupId>
    <artifactId>janusgraph-inmemory</artifactId>
    <scope>test</scope>
    <version>0.5.0</version>
</dependency>
```

**Comment by FlorianHockmann** [comment]
Looks like that was forgotten. Do you want to submit a PR to add this?

**Comment by FieteO** [comment]
Sure, I'll do that at the weekend if I find some time 👍
