### ISSUE TITLE
JanusGraphFactory.Builder.open() took 1-2 seconds to complete

### ISSUE THREAD

**Issue by lolski** [JanusGraph/janusgraph#458]
I have noticed that the function `JanusGraphFactory.Builder.open()` takes some time to execute. In my case, it is approximately 2.5 seconds on an empty Cassandra, and 1.7 seconds for the subsequent calls.

Here's my configuration:
1. janusgraph version 0.2.0-SNAPSHOT https://maven.grakn.ai/content/repositories/snapshots/org/janusgraph/
2. Tested primarily on Mac OS X, however this behavior has been observed in Ubuntu 16.04 64bit as well

The following code should be enough to demonstrate it.
```
public static void main(String[] args) {
    JanusGraphFactory.Builder builder = JanusGraphFactory.build().
            set("storage.hostname", "localhost").
            set("storage.cassandra.keyspace", "test").
            set("storage.batch-loading", true); // both true and false have been tested with no effect to the execution time
    builder.open(); // will take approximately 2.5 seconds on an empty Cassandra, and 1.7 seconds for the subsequent calls.
}
```

**Comment by pluradj** [comment]
FWIW, results on my Mac are significantly faster. This issue seems mostly environmental, not a specific bug. The initial `open()` creates the keyspace and 9 tables, so 1-2 seconds doesn't seem out of line. Thoughts?

```
gremlin> ts = System.currentTimeMillis(); graph = JanusGraphFactory.build().set('storage.backend', 'cassandra').set('storage.cassandra.keyspace', 'test').set('storage.batch-loading', true).open(); System.currentTimeMillis()-ts
==>1482
gremlin> graph.close()
==>null
gremlin> ts = System.currentTimeMillis(); graph = JanusGraphFactory.build().set('storage.backend', 'cassandra').set('storage.cassandra.keyspace', 'test').set('storage.batch-loading', true).open(); System.currentTimeMillis()-ts
==>28
gremlin> graph.close()
==>null
```

**Comment by lolski** [comment]
I got the same number on a standard `t2.medium` Amazon machine running on Ubuntu.

There, we used:
1. janusgraph version 0.2.0-SNAPSHOT https://maven.grakn.ai/content/repositories/snapshots/org/janusgraph/
2. Apache Cassandra 2.2.10
3. Ubuntu on t2.medium Amazon instance

And this is the code I'm using: https://github.com/lolski/slow-janusgraph-builder-open/blob/master/src/main/java/ai/grakn/SlowJanusGraphBuilderOpen.java

Can you perhaps describe your environment where you get such result?

**Comment by pluradj** [comment]
My results posted above were on my MacBook Pro (Retina, 15-inch, Mid 2015), 2.8 GHz Intel Core i7, 16 GB 1600 MHz DDR3, 1 TB SSD

* Cloned the latest JanusGraph `master` from the _official repository_ `git clone git@github.com:JanusGraph/janusgraph.git`
* Created a distribution `cd janusgraph; mvn clean install -DskipTests=true -Dgpg.skip=true -Pjanusgraph-release`
* Unzipped the distribution `unzip janusgraph-dist/janusgraph-dist-hadoop-2/target/janusgraph-0.2.0-SNAPSHOT-hadoop2.zip`
* Started the pre-packaged server (C* 2.1.9, ES 5.4.2) with `cd janusgraph-0.2.0-SNAPSHOT-hadoop2/; bin/janusgraph.sh start`
* Ran the console `bin/gremlin.sh`
* Ran the commands shown in my first comment (1482 ms first open, 28 ms second open)

I'd imagine that the `t2.medium` isn't configured with a local SSD, and that would make a big difference for C* performance.

**Comment by robertdale** [comment]
@lolski I'm not sure why you believe it should be so much faster.  As @pluradj describes, it's essentially 'creating the database' on first open. In your second comment, since you are running `bin/janusgraph.sh start`, the gremlin server will incur the cost of creating the database for the first time which is why your console connection was slightly faster.  In any case, connecting to the graph is a one-time cost. It should be shared throughout the application afterwards thus making its startup time negligible.

**Comment by lolski** [comment]
@robertdale Ok, I am starting to understand it. However I have one more question.

If I do the following:
1. Start the application which calls `open()` for the first time
2. Stop the application
3. Restart the application, which will again calls `open()`

Can you help me understand why step #3 still take 1-2 seconds as I have observed (per my first comment)? As far as I understood from your response, the time taken to execute step #3 should have been negligible, as the database has already been created during step #1.

The fact that the application is stopped in step #2 should not matter in my opinion (unless of course this is not how it works)

Excuse me for being extra curious about it :)

**Comment by robertdale** [comment]
@lolski I couldn't tell you what it does when the tables exist. Minimally, it must checking that the tables exist, perhaps reading some other metadata.  But I think you're thinking of this is in far too simple terms.  This is not merely a client to a database like jdbc. This is the graph database engine!  Liken it to starting cassandra or elastic search.  It's an expensive operation that should be done once on startup.  If you require faster startup times, then consider running JanusGraph Server.  Then the server incurs the one-time expense of 2 seconds but stays running. Meanwhile your clients can connect and disconnect quickly.

**Comment by lolski** [comment]
Your explanation makes complete sense. This ticket can be closed. Thanks!
