### ISSUE TITLE
Improve Index Documentation

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#460]
- explain different states
- explain that there are states on each key of an index and the index as a whole
- explain state transitions (how to get from one to the next)
- explain index requirements
- troubleshooting

**Comment by dpitera** [comment]
For troubleshooting, ensure to look at [this SO post](https://stackoverflow.com/questions/40585417/titan-db-ignoring-index/40591478#40591478) where I've made notes of all potential issues I've run into for having indexes get stuck in the `installed` or `registered` states.

**Comment by robertdale** [comment]
**States:**
- INSTALLED - The index is installed in the system but not yet registered with all instances in the cluster
- REGISTERED - The index is registered with all instances in the cluster but not (yet) enabled
- ENABLED - The index is enabled and in use
- DISABLED - The index is disabled and no longer in use

**Actions:**
- REGISTER_INDEX - Registers the index with all instances in the graph cluster. After an index is installed, it must be registered with all graph instances
- REINDEX - Re-builds the index from the graph
- ENABLE_INDEX - Enables the index so that it can be used by the query processing engine. An index must be registered before it can be enabled.
- DISABLE_INDEX - Disables the index in the graph so that it is no longer used.
- REMOVE_INDEX - Removes the index from the graph (optional operation). Only on composite index.

**Comment by dpitera** [comment]
Also note that a REINDEX automatically ENABLES an index.

**Comment by robertdale** [comment]
I made a diagram. Not sure where to put it.

**Comment by sjudeng** [comment]
Wiki? https://github.com/JanusGraph/janusgraph/wiki

**Comment by robertdale** [comment]
I still had to upload the image to somewhere other than here.  Anyway, you can see it here - https://github.com/JanusGraph/janusgraph/wiki/Indexes

**Comment by pluradj** [comment]
I came looking for this issue because of the nice writeup from @robertdale on [janusgraph-users](https://groups.google.com/d/msg/janusgraph-users/KOn6hso1hJM/pQV5xzYxBAAJ), which would be a nice addition to the indexing docs.

I didn't know some docs were going up on a wiki. Why not add that image to the [asciidoc](https://github.com/JanusGraph/janusgraph/blob/v0.1.1/docs/basics.txt#L738)?

**Comment by farodin91** [comment]
Link #1780
