### ISSUE TITLE
Upgrade ScyllaDB version

### ISSUE THREAD

**Issue by mykaul** [JanusGraph/janusgraph#4641]
Version used currently is a bit outdated (end-of-life actually):
https://github.com/JanusGraph/janusgraph/blob/94c55f04a3153285b0803c7e575d4653782e7840/pom.xml#L107

Should use 6.1.0 or above, for latest version.
See https://forum.scylladb.com/t/relase-scylladb-6-1/2486

**Comment by mykaul** [comment]
CC @FlorianHockmann

**Comment by FlorianHockmann** [comment]
Just to be clear: This is only the version we are testing against. Users have to set up their own Scylla cluster and are therefore not bound by this. But nevertheless we should of course update this so we test against a version that is still supported.
