### ISSUE TITLE
Json Write

### ISSUE THREAD

**Issue by Sankitha** [JanusGraph/janusgraph#472]
Hi I am a new bee to Janus . Can any one tell me , How to load Json document into janus database with cassandra as backend. Adding to this is there any library tool kit available for Janus in Python?

Thank You

**Comment by mbrukman** [comment]
Hi @Sankitha, the GitHub issue tracker is for reporting specific feature requests or bugs with JanusGraph, not for open-ended discussion.

Please visit https://github.com/JanusGraph/janusgraph#community and use either the Gitter chat or the `janusgraph-users@` mailing list for open-ended questions. You can also search the mailing list archives via the link provided; similar questions have been asked in the past and already answered on the mailing list.

**Comment by Sankitha** [comment]
Thank You :) . Is there Any useful URL's regarding Janus implementation with real time transaction data.Adding to this how Do I use gremlin python with janus ?
