### ISSUE TITLE
Update CSS to make docs links green

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#486]
Previously, in Titan, the CSS specified that links were red on mouseover, as were the table borders. This made sense, because the Titan logo was primarily red, and this went along with the overall theme.

After the removal of third-party CSS in PR #370, we lost the red color, and now the links are bright blue, which slightly detracts from the readability as it is a sharp, bright blue. A nicer version, which would also match the JanusGraph logo, would be to make the links green on mouseover in the table of contents, and green everywhere else.

It looks like the links in the heading are already using the green color, so we just need to also make this change in the body of the docs to match it.

/cc: @pluradj in case he has a good idea of how to fix this, since he's updated CSS recently

**Comment by pluradj** [comment]
I went with the bright blue because JanusGraph green didn't provide enough [contrast for accessibility](http://webaim.org/blog/wcag-2-0-and-link-colors/) compared with regular black text.

**Comment by mbrukman** [comment]
Sounds good, @pluradj, thanks for the clarification!
