### ISSUE TITLE
The jar version is  too old

### ISSUE THREAD

**Issue by Chendamai** [JanusGraph/janusgraph#494]
Why not update new version about elasticsearch ,solr and hbase?

**Comment by sjudeng** [comment]
The versions are all already updated in the master branch and we're working towards a 0.2.0 release which will include these updates.

**Comment by mbrukman** [comment]
@Chendamai — as @sjudeng mentioned, it will be fixed in the next release. If you don't want to wait, you can build JanusGraph from source right now — please see the directions in [`BUILDING.md`](https://github.com/JanusGraph/janusgraph/blob/master/BUILDING.md).

**Comment by pluradj** [comment]
@Chendamai if you'd like to discuss your issue further, please take it up first on the [mailing list or Gitter](https://github.com/JanusGraph/janusgraph/blob/master/README.md#community). Thanks.
