### ISSUE TITLE
GuavaVertexCache onRemoval Bug

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#503]
Since the Guava cache [processes its removals
asynchronously](https://github.com/google/guava):

"""
Caches built with CacheBuilder do not perform cleanup and evict values
"automatically," or instantly after a value expires, or anything of the
sort. Instead, it performs small amounts of maintenance during write
operations, or during occasional read operations if writes are rare.
The reason for this is as follows: if we wanted to perform Cache
maintenance continuously, we would need to create a thread, and its
operations would be competing with user operations for shared locks.
Additionally, some environments restrict the creation of threads, which
would make CacheBuilder unusable in that environment.
"""

there is a chance that we reach the onRemoval code _after_ the vertex
being removed due to cache eviction asynchronous processing has indeed
_already been removed and processed_ by user interaction. In this
scenario, the transaction is not open, and more importantly, this
denotes that the vertex processing is done and we do not need to add the
vertex to the volatileVertices map.

**Comment by robertdale** [comment]
See also thinkaurelius/titan#893

**Comment by robertdale** [comment]
Somewhat related #500

**Comment by dpitera** [comment]
> See also thinkaurelius/titan#893

That issue was closed, and I _quickly_ read the comments about the cause. I am not convinced the cache access patterns inside the GuavaVertexCache are correct; for example, should we be locking on a singular lock [here](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/GuavaVertexCache.java#L75-L83)? My gut reaction is _yes_, as we are modifying 3 different java objects.

**Comment by robertdale** [comment]
With this change, do you think we can backout thinkaurelius/titan#893 ?

**Comment by dpitera** [comment]
No I think my change has nothing to do with the issue you've linked.
