### ISSUE TITLE
Use hbase shaded client and server

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#512]
We should start using hbase shaded client to avoid dependency conflicts.
See https://issues.apache.org/jira/browse/HBASE-18800
and #488

**Comment by jerryjch** [comment]
The hbase shaded client is only available in version 1.x +
Since we have 0.98 client too, it may not be a complete clean-up.
We also depend on hbase-server because the TableInputFormat that JanusGraph Hadoop uses is in the hbase-server jar.  Therefore to do a complete clean-up, we need to use the hbase shaded server module as well.

**Comment by KevinGong** [comment]
### when I started  the janusGraph ,  the  RegionServer  will go down.

## janusGraph:
`bin/gremlin-server.sh  conf/gremlin-server/http-gremlin-server.yaml `

`1332 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:java.io.tmpdir=/tmp
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:java.compiler=<NA>
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:os.name=Linux
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:os.arch=amd64
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:os.version=2.6.32-642.6.2.el6.x86_64
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:user.name=root
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:user.home=/root
1335 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Client environment:user.dir=/usr/local/janusgraph-0.2.0-hadoop2
1339 [main] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper  - Initiating client connection, connectString=hadoop01:2181,hadoop02:2181,hadoop03:2181 sessionTimeout=90000 watcher=hconnection-0x4bd310640x0, quorum=hadoop01:2181,hadoop02:2181,hadoop03:2181, baseZNode=/hbase
1356 [main-SendThread(hadoop01:2181)] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn  - Opening socket connection to server hadoop01/10.163.47.171:2181. Will not attempt to authenticate using SASL (unknown error)
1363 [main-SendThread(hadoop01:2181)] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn  - Socket connection established to hadoop01/10.163.47.171:2181, initiating session
1371 [main-SendThread(hadoop01:2181)] INFO  org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn  - Session establishment complete on server hadoop01/10.163.47.171:2181, sessionid = 0x15f4dd42f23001d, negotiated timeout = 60000`

## the conf：
`[root@bbs janusgraph-0.2.0-hadoop2]# cat conf/gremlin-server/http-gremlin-server.yaml |head -20
host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
#channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
graphs: {
  #graph: conf/gremlin-server/janusgraph-cassandra-es-server.properties
  graph: conf/gremlin-server/http-janusgraph-hbase-server.properties
}
plugins:
  - janusgraph.imports
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
    scripts: [scripts/empty-sample.groovy]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}`
`[root@bbs janusgraph-0.2.0-hadoop2]# cat conf/gremlin-server/http-janusgraph-hbase-server.properties 
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=hbase
storage.hostname=hadoop01,hadoop02,hadoop03
storage.hbase.ext.zookeeper.znode.parent=/hbase`

**Comment by jerryjch** [comment]
I don't think the bin/gremlin-server.sh will start any backend servers.   It will only start the gremlin server, not the backend hbase or es or solr server.
The bin/janusgraph.sh on the other hand, is s bundled script that will start an embedded Cassandra and ES together with the gremlin server.  But it is hard-coded with Cassandra and ES only.

**Comment by pluradj** [comment]
@KevinGong Please don't add your usage questions with HBase on a closed GitHub issue. We use issue tracker for working on bugs and features. If you need to report a bug or feature request, it should be done as a new issue, not as a comment on a closed issue.

It seems you have a question on usage, so please use the [`janusgraph-users`](https://groups.google.com/forum/#!forum/janusgraph-users) mailing list. Please see the project [README](https://github.com/JanusGraph/janusgraph/blob/master/README.md#community) for more details.
