### ISSUE TITLE
SLF4j binding issue resulted in no internal logging

### ISSUE THREAD

**Issue by ankurgoelmb** [JanusGraph/janusgraph#517]
Problem:
I am using JanusGraph 0.1.1. And using logback:

       <logger name="org.janusgraph" level="DEBUG" additivity="false">

<appender-ref ref="CONSOLE" />

</logger>

<logger name="org.apache" level="DEBUG" additivity="false">

<appender-ref ref="CONSOLE" />

</logger>

        <root level="debug">

<appender-ref ref="CONSOLE" />

</root>

This result in following output only:
```
15:28:23,108  INFO ReflectiveConfigOptionLoader:173 - Loaded and initialized config classes: 9 OK out of 12 attempts in PT0.018S
15:28:23,171  INFO Reflections:224 - Reflections took 38 ms to scan 1 urls, producing 12 keys and 25 values 
15:28:23,244  INFO CassandraThriftStoreManager:628 - Closed Thrift connection pooler.
15:28:23,251  INFO GraphDatabaseConfiguration:1563 - Generated unique-instance-id=0a96cb391964-MacBook-Pro-3-local1
15:28:23,263  INFO Backend:463 - Configuring index [search]
15:28:23,355  INFO plugins:151 - [Solarr] loaded [], sites []
15:28:23,875  INFO ElasticSearchIndex:368 - Configured remote host: 127.0.0.1 : 9300
15:28:24,043  INFO Backend:178 - Initiated backend operations thread pool of size 8
15:28:24,165  INFO KCVSLog:744 - Loaded unidentified ReadMarker start time 2017-09-13T09:58:24.152Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@7fcff1b9
15:28:25,409  INFO CassandraThriftStoreManager:628 - Closed Thrift connection pooler.
```

Solution:
As per SLF4j:
Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

Request to exclude following dependency 

```
<groupId>org.slf4j</groupId>
<artifactId>slf4j-log4j12</artifactId>
```

from JanusGraph.

```
<groupId>org.janusgraph</groupId>
<artifactId>janusgraph-es</artifactId>
<artifactId>janusgraph-cassandra</artifactId>
<artifactId>gremlin-driver</artifactId>
```

Logging will start working.

**Comment by pluradj** [comment]
`gremlin-driver` is part of Apache TinkerPop, so that would need to be addressed in that project. However its `slf4j-log4j12` [dependency](https://github.com/apache/tinkerpop/blob/3.2.6/gremlin-driver/pom.xml#L61-L65) is marked as optional, so no work may be required for `gremlin-driver`.
