### ISSUE TITLE
Is profile dev-install-hadoop2 useful?

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#519]
There is a profile called `dev-install-hadoop2` defined in `janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml` that is activated by the absence of property `dev.hadoop`.   Let's call it **activated by default**. This property is undocumented.

When this profile is activated, it activates an assembly called `install-dev-dirs-hadoop` defined in `janusgraph-dist/pom.xml`.  The assembly defined by `janusgraph-dist/src/assembly/descriptor/filesystem.xml` simply copies the distribution stuff into the root janusgraph dir.  I guess it's so one can quickly test the janusgraph distribution without unzipping the zip file and having to `cd`.

But does anyone actually use this?  If you are just now learning about it, do you think it would be useful ?

It pollutes the root dir with:
```
bin
conf
data
elasticsearch
ext
lib
log
scripts
```

This is why they are in `.gitignore`.  `mvn clean` will remove them.

1. Is this feature useful and worth keeping?
2. Should it be enabled by default (current) or should users request it `-Ddev.hadoop=true`?
3. If it's kept, it should be documented in `BUILDING.md`

I would like to see it disabled by default and I wouldn't be against removing it altogether.

Thoughts?

**Comment by sjudeng** [comment]
Not sure how this would be used. Maybe at some point in Titan for running/debugging SparkGraphComputer or earlier MapReduce implementation in the IDE. I'd be okay with removing it now, or else disable it for now and remove it in 0.3.0. This was definitely an annoyance so thanks for looking into it.
