### ISSUE TITLE
Force push master to coverity_scan

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#528]
The `coverity_scan` branch contains two commits (the second undoing the first) not in `master`. To resolve the issue `master` should be forced pushed to `coverity_scan`.

@mbrukman I pushed the commits previously during coverity debugging.

**Comment by mbrukman** [comment]
Temporary lifted the force-push protection for `coverity_scan`, force-pushed `master` to it, and re-enabled forced-push protection.
