### ISSUE TITLE
SpatialContextFactory in schema.xml depends on Solr version

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#533]
This line in [`schema.xml`](https://github.com/JanusGraph/janusgraph/blob/92b85eeb76ddb6a7c10407bda29b8f148914382f/janusgraph-dist/src/assembly/static/conf/solr/schema.xml#L536) works with Solr 6 (JTS jar not required): `org.locationtech.spatial4j.context.SpatialContextFactory`

Solr 5 uses an older version of spatial4j (and requires JTS jar), so it should use the former package name: `com.spatial4j.core.context.SpatialContextFactory`

A comment in the `schema.xml` file would be helpful in addition to updating the [Solr docs](http://docs.janusgraph.org/latest/solr.html#_troubleshooting_2).

**Comment by sjudeng** [comment]
I think it can be set to `com.spatial4j.core.context.SpatialContextFactory` in the schema and Solr 6 will "upgrade" it automatically. I thought that had been addressed prevously. That's what's done in testing (see [here](https://github.com/JanusGraph/janusgraph/blob/352ae52b360c28ede8537fff5e10b8cc10995ea4/janusgraph-solr/src/test/resources/solr/core-template/schema.xml#L543)) to support both Solr 6 and Solr 5.
