### ISSUE TITLE
Mitigate recent Coverity findings

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#535]
Latest Coverity scan report (see [here](https://scan.coverity.com/projects/janusgraph-janusgraph)) showed a number of new findings. Issues should be addressed or dismissed as false positives as appropriate.

**Comment by chupman** [comment]
@sjudeng were there any outstanding issues to resolve from this scan or can this issue be closed out?

**Comment by sjudeng** [comment]
@chupman It can be closed. Looks like the coverity service might be offline or experiencing issues currently but in any case we can open future new issues for specific findings if needed.
