### ISSUE TITLE
Roadmap/timeline to support Spark 2.x

### ISSUE THREAD

**Issue by kuncle** [JanusGraph/janusgraph#543]
Can you tell me about the release date of support spark 2.x ?

**Comment by davidclement90** [comment]
Spark 2.x will be supported when Tinkerpop 3.3.x will be supported (https://github.com/JanusGraph/janusgraph/pull/435).

This discussion (https://groups.google.com/forum/#!searchin/janusgraph-dev/tinkerpop%7Csort:relevance/janusgraph-dev/kQX9aSdCJME/cnVUJ5QLBQAJ) decide that JanusGraph 0.2.0 will support Tinkerpop 3.2.x. Then JanusGraph 0.3.x will support Tinkerpop 3.3.x.

**Comment by mbrukman** [comment]
Now that PR #435 has been merged, you can build JanusGraph from `master` branch to get Spark 2.x support. As @davidclement90 said, the next release of JanusGraph (0.3.0) will include this change.
