### ISSUE TITLE
Allow one to run Cassandra tests against a remote backend

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#558]

**Comment by sjudeng** [comment]
This is currently supported by passing `-Dstorage.hosts=0.0.0.0` (or other host). It's leveraged for testing cassandra (and cql) against scylladb (see [here](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cassandra/pom.xml#L433-L434)).

**Comment by sjudeng** [comment]
Regarding running with ScyllaDB, see #53 and [TESTING.md](https://github.com/JanusGraph/janusgraph/blob/master/TESTING.md#running-thriftcql-tests-with-scylladb-requires-docker). Previously we decided not to push too hard on Thrift test compliance given it's on the deprecation path, though it'd be great if you want to run that down. Any issues should be raised and addressed on the ScyllaDB side.

The ScyllaDB team addressed a TTL consistency issue that was failing some JanusGraph CQL/Thrift tests and that fix should be in the upcoming 2.0 release. Once that's released we can add Travis jobs to automate running the CQL tests against ScyllaDB. Also ScyllaDB is actually running some of the JanusGraph CQL tests as part of their test suite (see https://github.com/scylladb/scylla-cluster-tests/pull/351). It's currently just CQLGraphTest that's being run.

**Comment by dpitera** [comment]
> This is currently supported by passing -Dstorage.hostname=0.0.0.0 (or other host).

Thanks. Closing.
