### ISSUE TITLE
ClassNotFoundException org.apache.tinkerpop.gremlin.server.GraphManager when trying to open graph using JanusGraphFactory

### ISSUE THREAD

**Issue by prismofeverything** [JanusGraph/janusgraph#569]
Just pulled the latest snapshot, now I cannot connect to a graph using the `org.janusgraph.core.JanusGraphFactory.open(config)` I have been using forever. I get the following exception:

    ClassNotFoundException org.apache.tinkerpop.gremlin.server.GraphManager

Looks like you went up to tinkerpop 3.2.6? I have verified that I have all the new 3.2.6 jars from tinkerpop are loaded. What could have changed here that would break this?

Any tips for triage? Thanks!

**Comment by prismofeverything** [comment]
If it helps, I am using JanusGraph in embedded mode and still following the docs here to connect: http://docs.janusgraph.org/latest/configuration.html

And actually, this has worked for a long time before the latest snapshots were released (yesterday I believe?)

**Comment by sjudeng** [comment]
Thanks for the report. I think this will be fixed by #566.

**Comment by sjudeng** [comment]
The fix was just merged into master.

**Comment by prismofeverything** [comment]
Ah awesome! Thanks for the quick response.

How long does it take the snapshots to release? Basically I have fixed this locally by pinning to a particular snapshot, which I might do going forward.

**Comment by sjudeng** [comment]
The release process for 0.2.0 is about to begin. It'll include this fix. You can follow progress at https://groups.google.com/forum/#!topic/janusgraph-dev/PJF8qdoe_Zo.

**Comment by robertdale** [comment]
Fixed.
