### ISSUE TITLE
Update Cassandra supported versions

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#585]
Cassandra should work with versions 2.2.z, 3.0.z, and 3.z. Recent Travis attempts by @sjudeng (https://travis-ci.org/sjudeng/janusgraph/builds/282098716) have shown a few errors

> The current build does still show a small number of CQL test failures. In 3.11.0 and 3.0.14 there are three failures in CQLStoreTest (testDefaultCFCompressor, testCustomCFCompressor and testDisableCFCompressor). In 2.2.10 there is one failure in CQLLogTest (testFuzzMessagesSerial). @pkendall64, @samant-orionhealth Have you observed these issues/failures before with newer C*, or any ideas how they might be resolved?

With 3.11.0 and 3.0.14 there are three failures in CQLStoreTest: testDefaultCFCompressor, testCustomCFCompressor and testDisableCFCompressor.
```
Tests run: 33, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 648.132 sec <<< FAILURE! - in org.janusgraph.diskstorage.cql.CQLStoreTest
testDefaultCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.22 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor, chunk_length_kb=64}> but was:<{chunk_length_in_kb=64, class=org.apache.cassandra.io.compress.LZ4Compressor}>
...

testCustomCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.223 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{sstable_compression=org.apache.cassandra.io.compress.DeflateCompressor, chunk_length_kb=128}> but was:<{chunk_length_in_kb=128, class=org.apache.cassandra.io.compress.DeflateCompressor}>
...

testDisableCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.249 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{}> but was:<{enabled=false}>
...
```

With 2.10.14 there is an error in CQLLogTest: testFuzzMessagesSerial.
```
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 80.187 sec <<< FAILURE! - in org.janusgraph.diskstorage.cql.CQLLogTest
testFuzzMessagesSerial(org.janusgraph.diskstorage.cql.CQLLogTest)  Time elapsed: 31.813 sec  <<< FAILURE!
java.lang.AssertionError: Did not read expected number of messages before timeout was reached (latch count is 32)
	at org.janusgraph.diskstorage.log.LogTest$LatchMessageReader.await(LogTest.java:325)
	at org.janusgraph.diskstorage.log.LogTest.testFuzzMessagesSerial(LogTest.java:212)
...
```

**Comment by sjudeng** [comment]
In addition to fixing the above issues do SSL tests need to be run to claim support for 3.11.x, etc.?

**Comment by pluradj** [comment]
I'd think we can claim support for 2.2.x, 3.0.x, 3.11.x without it, but it would be nice to know the results of those tests so it can be documented if it doesn't work. The SSL tests run and pass against 2.1.x?

**Comment by sjudeng** [comment]
They run without issue using default 2.1.18 when the test Cassandra instance is managed by JanusGraph. Tests with the other versions use Docker to manage the test server externally but some more work (e.g. Docker/Travis configuration) would be needed to get this approach to work for SSL tests.

**Comment by sjudeng** [comment]
The other thing to note with the current approach is that only the default patitioner (`Murmur3Partitioner`) is being tested, whereas default tests would also include `ByteOrderedPartitioner`.

**Comment by pluradj** [comment]
@sjudeng what do you think we should do here? I noticed that you have a [fix](https://github.com/sjudeng/janusgraph/tree/travis-cassandra-only) for those failing test cases and [Travis](https://travis-ci.org/sjudeng/janusgraph/builds/282733620) built it successfully.

**Comment by sjudeng** [comment]
Yes the above errors are fixed. I was going to submit a PR and also update the version compatibility matrix when these questions occurred to me. Ideally we'd test SSL and both partitioners to have a clean claim but that might take some time. The other option is to add a caveat that these aspects are currently untested with the newer C* versions. One is cleaner but the other gets to a release quicker. Not sure which is preferable.

**Comment by pluradj** [comment]
How much time do those tests take?

**Comment by sjudeng** [comment]
Issue is the time it will take to make the update to support running the tests. Once that's done it just takes as long as a normal build (about an hour total when parallelized in Travis). The required updates are to support enabling SSL and changing partitioner as part of the Docker run, conditionally based on Travis job parameters.

**Comment by pluradj** [comment]
I think it's fine to wait to get the testing done thoroughly. I'd think the community would appreciate that. I sent out a [note](https://groups.google.com/d/msg/janusgraph-dev/PJF8qdoe_Zo/qooLCkTcCAAJ) on the dev list, in case there's a consensus that we should just push it out without waiting.

**Comment by pluradj** [comment]
@sjudeng do you have cycles to take the lead on this? happy to help out wherever I can.

**Comment by sjudeng** [comment]
Yep I took a good crack at it last night. I got it working on the Docker side with configurable SSL and partitioner. The last piece is to update Travis. Hopefully I can wrap it up tonight or worst case this weekend.

Other thing that occurred to me is we should probably run the TinkerPop tests as well, which we don't do through Travis. Once things are wired up properly I might ask for a couple volunteers to run the TinkerPop tests for the different versions locally.

**Comment by sjudeng** [comment]
Ran through all tests for 3.11.0 including SSL and ByteOrderedPartitioner (see https://travis-ci.org/sjudeng/janusgraph/builds/284205063). There are a few remaining issues. Once resolved we can re-run against the other versions. I'll take a look at the issues this weekend but summarizing below in case @pluradj (or anyone else) have insight or can investigate in the meantime.
* With ByteOrderedPartitioner the `ThriftDistributedStoreManagerTest#testGetDeployment` test is failing (expected REMOTE but was LOCAL). The update to expect `REMOTE` was added for when testing against Docker-based C*. The test passed previously so I think the only difference is the partitioner. Any reason why result here would be different by partitioner?
* Also with ByteOrderedPartitioner the `ThriftDistributedStoreManagerTest#testGetLocalKeyPartition` failed (expected <1> but was <0>). This one is unfamiliar to me so will have to dig in unless it's obvious to anyone.
* The Astyanax tests with ByteOrderedPartitioner are timing out. Will also need to check on this. If it's really just a timeout and not a symptom of a bigger issue then it's no problem as we'll run tests locally.

**Comment by sjudeng** [comment]
Regarding the timeout in Astyanax tests there was a missing configuration (`initial_token: 0000000000000000000000000000000000`) in cassandra.yaml when using ByteOrderedPartitioner. Once the configuration was updated the issue appears to be resolved.

**Comment by sjudeng** [comment]
The other two issues are because of differences in identifying whether connection is local (e.g. provided storage.hostname of 0.0.0.0/127.0.0.1 is identified as local but Docker container IP is not).
