### ISSUE TITLE
Update Solr supported versions

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#588]
On PR #311 we missed this small detail before... the testing went back to Solr 5.3.2, but JanusGraph 0.1.1 supports Solr 5.2.1.

Does Solr 5.2.1 still pass all tests after this change?

* If so, 5.2.z should be included on the [version compatibility matrix](https://github.com/JanusGraph/janusgraph/blob/master/docs/versions.txt).
* If not, we need to add a [upgrade instructions](https://github.com/JanusGraph/janusgraph/blob/master/docs/upgrade.txt) for people upgrading from JanusGraph 0.1.1 to 0.2.0.

cc @sjudeng

**Comment by sjudeng** [comment]
I tested without issue with version 5.2.1. There are no Docker images available for the version so it's more difficult to test, which is why it wasn't included during testing in #311 (or #551).
