### ISSUE TITLE
Creating edges without loading vertices

### ISSUE THREAD

**Issue by scottrpatterson** [JanusGraph/janusgraph#593]
Working with a 0.2.0 build. When I am adding an edge between two existings nodes, I must fetch each node and then call the Vertex method:

public Edge addEdge(final String label, final Vertex inVertex, final Object... keyValues);

In the case where one of the nodes is expensive to load, because it's a super node or has lot of properties, this approach is not scaling for me when I am modifying large graphs. 

It would be more efficient if JanusGraph had an API that lets you create an edge using the in/out vertex ids. Maybe something in the JanusGraph object like:

public Edge addEdge(Object outVertexId, final String label, final Object inVertexId, final Object... keyValues);

**Comment by robertdale** [comment]
Do you have `query.fast-property` set to false?  http://docs.janusgraph.org/latest/config-ref.html#_query

**Comment by scottrpatterson** [comment]
I did not set that property, so it should be defaulting to false.

**Comment by robertdale** [comment]
It's true in 0.2.0-SNAPSHOT.

**Comment by robertdale** [comment]
https://robertdale.github.io/docs.janusgraph.org/0.2.0-SNAPSHOT/config-ref.html#_query

**Comment by scottrpatterson** [comment]
I've turned off query.fast-property but I'm still seeing that I spend about 1/5 of every minute doing vertex fetching. While that should be helping to avoid loading properties, what about edges? Are a vertex's edges front loaded?

**Comment by twilmes** [comment]
@scottrpatterson can you provide a snippet of code showing how you look up the two vertices and add the edge?

**Comment by scottrpatterson** [comment]
I've attached a full code example. The basic logic is:
`
/**
	 * This method is called millions of times, once for each data entity, and
	 * may results in tens of thousands of graph elements being created per
	 * method call.
	 * 
	 * @param uniqueName
	 *            a unique name for the entity
	 * @param properties
	 *            key is a common name for the entity, which is not unique.
	 *            value is a map of property key/value pairs.
	 * @param relationships
	 *            key is a common name for the entity, which is not unique.
	 *            value is a map of edges labels to other common names.
	 * @throws Exception
	 */
	public void create(String uniqueName, Map<String, Map<String, Object>> properties,
			Map<String, Map<String, Collection<String>>> relationships) throws Exception {
		try {
			JanusGraph tg = g;
			int max = 10000;
			int count = 0;

			// create nodes and properties
			for (String commonName : properties.keySet()) {

				Vertex v = tg.addVertex(T.label, "commonLabel", "commonName", commonName, "uniqueName", uniqueName);
				List<Vertex> instances = getOrCreateSharedVertices(tg, commonName);
				for (Vertex i : instances) {
					v.addEdge("sharedWith", i);
				}
				List<Vertex> owners = getOrCreateSharedVertices(tg, uniqueName);
				for (Vertex o : owners) {
					v.addEdge("ownedBy", o);
				}

				Map<String, Object> propMap = properties.get(commonName);
				for (Entry<String, Object> e : propMap.entrySet()) {
					VertexProperty<Object> property = v.property(e.getKey(), e.getValue());
				}

				count += 3;
				if (count > max) {
					commit();
					count = 0;
				}
			}
			commit();
			count = 0;

			// create in nodes if they don't exist
			for (Map<String, Collection<String>> edgeData : relationships.values()) {
				for (Collection<String> targetNames : edgeData.values()) {
					for (String targetName : targetNames) {
						List<Vertex> targets = getOrCreateSharedVertices(tg, targetName);
						count += targets.size();
						if (count > max) {
							commit();
							count = 0;
						}
					}
				}
			}
			commit();
			count = 0;

			// create edges
			for (String commonName : relationships.keySet()) {
				List<Vertex> outVertices = new LinkedList<Vertex>();
				GraphTraversal<Vertex, Vertex> results = tg.traversal().V().has("commonName", commonName)
						.has("uniqueName", uniqueName).hasLabel("commonLabel");
				while (results.hasNext()) {
					outVertices.add(results.next());
				}

				boolean refetch = false;
				for (Vertex v : outVertices) {
					if (refetch) {
						final Vertex f1 = v;
						v = tg.traversal().V(f1).next();
					}

					Map<String, Collection<String>> edges = relationships.get(commonName);
					for (Entry<String, Collection<String>> e : edges.entrySet()) {
						String edgeLabel = e.getKey();
						Collection<String> targetNamess = e.getValue();
						for (String targetName : targetNamess) {
							List<Vertex> targets = getOrCreateSharedVertices(tg, targetName);
							count += targets.size();

							for (Vertex t : targets) {
								final Vertex f2 = v;
								f2.addEdge(edgeLabel, t);
								count++;
								if (count > max) {
									commit();
									count = 0;
									final Vertex f3 = v;
									v = tg.traversal().V(f3).next();
									refetch = true;
								}
							}
						}
					}
				}
				count++;
				if (count > max) {
					commit();
					count = 0;
				}
			}
			commit();
		} catch (Exception e) {
			rollback();
			throw e;
		}
	}

	private List<Vertex> getOrCreateSharedVertices(JanusGraph tg, String commonName) throws Exception {
		final Object[] ids = cache.get(commonName);
		Object[] newIds = null;
		final List<Vertex> nodes = new LinkedList<Vertex>();
		if (ids == null) {
			GraphTraversal<Vertex, Vertex> results = tg.traversal().V().has("commonName", commonName)
					.hasLabel("sharedLabel");
			while (results.hasNext()) {
				nodes.add(results.next());
			}

			if (!nodes.isEmpty()) {
				newIds = new Object[nodes.size()];
				int index = 0;
				for (Vertex v : nodes) {
					newIds[index] = v.id();
					index++;
				}
			}
		} else {
			Iterator<Vertex> i = tg.vertices(ids);
			while (i.hasNext()) {
				nodes.add(i.next());
			}
			newIds = ids;
		}
		if (nodes.isEmpty()) {
			Vertex c = tg.addVertex(T.label, "sharedLabel", "commonName", commonName);
			cache.put(commonName, new Object[] { c.id() });
			return Collections.singletonList(c);
		} else {
			cache.put(commonName, newIds);
			return nodes;
		}
	}
`

[CreationTest.java.txt](https://github.com/JanusGraph/janusgraph/files/1372416/CreationTest.java.txt)

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
