### ISSUE TITLE
DynamoDB support?

### ISSUE THREAD

**Issue by zolaemil** [JanusGraph/janusgraph#601]
After a quick search through the existing issues it looks like that some people has successfully set up JanusGraph with DynamoDB (see https://github.com/JanusGraph/janusgraph/issues/425), but its support as storage backend is not documented. (Titan used to list DynamoDB as a storage solution besides others, but this is no longer the case in JanisGraph docs. 

Is DynamoDB supported by JanusGraph in any way, or its support has been dropped, and it's merely coincidental that the legacy of Titan means it's still working?

**Comment by mbrukman** [comment]
DynamoDB driver for JanusGraph is in a separate repo: https://github.com/awslabs/dynamodb-janusgraph-storage-backend and is documented and supported there.

**Comment by krish7919** [comment]
That seems to be an old one; is it still supported and work with the latest JanusGraph releases?

**Comment by mbrukman** [comment]
DynamoDB backend for JanusGraph is maintained by AWS in a separate repo:
https://github.com/awslabs/dynamodb-janusgraph-storage-backend

Please raise an issue on that repo to find out the status of JanusGraph version support and what their plans are; JanusGraph community does not maintain that backend driver.

**Comment by krish7919** [comment]
@mbrukman  I did just that with https://github.com/awslabs/dynamodb-janusgraph-storage-backend/issues/301 :)

But I was wondering if the community here would know.

**Comment by mbrukman** [comment]
It may be better to ask on janusgraph-users@ to see if anyone in the community is using it and what their experience is.
