### ISSUE TITLE
Bulk loading JanuGraph-Hbase

### ISSUE THREAD

**Issue by mpolonioli** [JanusGraph/janusgraph#602]
I have JanusGraph using Hbase as backend storage on an Hadoop cluster.

I need to load a very large quantity of data that represents a social network graph mapped in csv files.
By now I created a java program that creates the schema and load verticies and edges using gremlin.

The problem is that this method is very slow. Is there a way to perform bulk loading into Hbase in order to significantly reduce the loading times?

**Comment by mbrukman** [comment]
Please only use GitHub issues for specific feature requests or bug reports.

This is an open-ended howto question, which is more suited to being discussed on a mailing list, specifically `janusgraph-users@`. In fact, there have been several threads on this topic in the past; please search the archives: https://groups.google.com/group/janusgraph-users and if it's not quite answered there, either post a follow-up to one of those threads, or start a new thread if you feel it's sufficiently different from the rest.
