### ISSUE TITLE
Janusgraph vs TinkerPop query results 

### ISSUE THREAD

**Issue by monali01** [JanusGraph/janusgraph#604]
Using the same query in gremlin.sh from TinkerPop package vs gremlin.sh from Janusgraph package yields different results. TinkerPop results looks right as expected according to documentation so it seems like something is wrong when using Janusgraph? 

The sample data and query can be found [on StackOverflow](https://stackoverflow.com/questions/46572827/gremlin-repeat-query-takes-really-long-time/46573753#46573753)
`g.V(4208).repeat(out("link").group("x").by(loops()).by(groupCount().by(values("memberType")))).times(3).cap("x")`

Is there an alternative to achieve the same results? I also have problem with performance using the same queries, it is really slow - so any feedback is appreciated.

**Comment by robertdale** [comment]
Which versions of each are you using?

**Comment by monali01** [comment]
JanusGraph 0.1.1 and TinkerPop 3.2.5

**Comment by monali01** [comment]
I am using JanusGraph for the Janusgraph test by
 `graph = JanusGraphFactory.build().set('storage.backend', 'inmemory').open()`
and TinkerGraph for TinkerPop as showed in the SO.

Where do I find JanusGraph 0.2-SNAPSHOT release for download, I didn't see it in release page.

I have to use JanusGraph with 0.1.1 since I am using https://github.com/awslabs/dynamodb-janusgraph-storage-backend and they don't support higher version - they are at JanusGraph 0.1.1 and TinkerPop 3.2.3 .

**Comment by robertdale** [comment]
Ok, so can you test on the official TinkerPop 3.2.3 distribution and compare that to JanusGraph 0.1.1?

**Comment by monali01** [comment]
I tested with TinkerPop 3.2.3, it produced same results as Janusgraph 0.1.1. 
So it looks like they added that support (or fixed a bug) after TinkerPop 3.2.3.

**Comment by robertdale** [comment]
Can we close this or do you want to leave this open until you can test on JanusGraph 0.2.0 and TinkerPop 3.2.6?

**Comment by monali01** [comment]
I think we can close this - any idea when JanusGraph 0.2.0 will be available?

**Comment by robertdale** [comment]
@monali01 it's in code freeze right now. So, "soon" ;-)
