### ISSUE TITLE
Update Elasticsearch 1.x-2.x compatible versions

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#608]
Version compatibility table currently shows support for Elasticsearch 1.z and 2.z but full support is limited to 1.4-1.7z and 2.3-2.4.z.

**Comment by pluradj** [comment]
Dropping ES 1.5.z? That was the supported level in JanusGraph 0.1.1.

**Comment by sjudeng** [comment]
@pluradj Just updated to claim 1.4-1.7.z. On further investigation the errors under 1.4.z/1.5.z were just because of a difference in required syntax to enable dynamic scripting. Once corrected the tests ran fine.
