### ISSUE TITLE
JanusGraph with ElasticSearch authentication/SSL

### ISSUE THREAD

**Issue by techpanga** [JanusGraph/janusgraph#612]
Hi 

Our ElasticSearch has Shield Protected. So Janusgraph configuration to be supplied with ElasticSearch userid and password. 

what are the configuration keys to be supplied.

Please advise.

**Comment by sjudeng** [comment]
It's not currently supported but it shouldn't be too hard to add this support in the future. Would also need to add support for HTTPS connections to Elasticsearch to ensure credentials are encrypted.

**Comment by davidclement90** [comment]
I think is not that easy.
We will have to support shield syntax for ES 1 and 2 and X-pack syntax for ES 5 and 6.

For the test, shield plugin can be found in maven central. X-pack is not published in maven central. But X-pack is in official elasticsearch docker image. So we have to find a properly way to get X-pack for testing.

And the initialisation of shield and X-pack are completely different.

**Comment by sjudeng** [comment]
@davidclement90 It's a good point testing will be the hardest part. Maybe we can live with Docker for the tests. For the implementation I was thinking basic auth and SSL support could be added at the HttpClient level when we're building the RestClient and we wouldn't have to get into Elasticsearch specifics (yet another benefit of dropping the Transport client).

**Comment by davidclement90** [comment]
Ok the implementation is not that hard with HttpClient.
If docker is ok and works on Travis I do not know any alternative.

**Comment by SatyaNarayan1** [comment]
@ngrigoriev thanks for working on it. Auth was working for us earlier ( 0.1.1) with transport client and shield with below setting

# Management System to read or modify this value after bootstrapping.
index.search.elasticsearch.client-only=true
index.search.elasticsearch.interface=TRANSPORT_CLIENT
index.search.elasticsearch.ext.shield.user=elastic:changeme

**Comment by ngrigoriev** [comment]
@SatyaNarayan1 

Most recent version of JG requires the migration to REST_CLIENT, e.g. it does not support TRANSPORT_CLIENT anymore.

Ref: https://groups.google.com/forum/#!topic/janusgraph-dev/F-zfIsuiIoQ

https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients

**Comment by SatyaNarayan1** [comment]
@ngrigoriev correct and due to that we are currently not able to upgrade JG. 
Thanks for this , it will help us to migrate.

**Comment by sjudeng** [comment]
Fixed in #671
