### ISSUE TITLE
JanusGraph specific authentication for gremlin server

### ISSUE THREAD

**Issue by krlohnes** [JanusGraph/janusgraph#623]
TinkerPop authentication can't be set up to use a JanusGraph graph for storing credentials. It would be nice to be able to do that.

**Comment by robertdale** [comment]
Would you explain why authentication can’t use JanusGraph?

**Comment by krlohnes** [comment]
Sorry, this isn't entirely correct, I misunderstood a few things about the auth in TinkerPop (as I mentioned in the PR related to this). The concerns are really 3 fold

1. Configure a credential graph that automatically creates the appropriate JanusGraph specific indexes.

2. TinkerPop now supports (as of 3.2.6 and 3.3.0) a combined channelizer
for enabling port unification for WebSockets and HTTP. This adds the
necessary classes to enable authentication for one, the other, or both
using JanusGraph specific authentication.

3. HTTP Basic Auth is (and should be) slow. This adds an HMAC token
authentication mechanism to allow for fast authentication over HTTP.
