### ISSUE TITLE
documentation cleanup items

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#626]
@robertdale noted these issues (https://github.com/JanusGraph/docs.janusgraph.org/pull/24#issuecomment-336233345) while checking preview documentation. Ultimately the doc is written in Asciidoc and stored in the [source code repo](https://github.com/JanusGraph/janusgraph/tree/master/docs), so the cleanup should be tracked here.

-------

Does github ignore files starting with `_`?
404:  https://pluradj.github.io/janusgraph.org/latest/_field_mapping.html
but it's there..  https://github.com/pluradj/docs.janusgraph.org/blob/0.2.0-docs/0.2.0/_field_mapping.html

- [x] https://pluradj.github.io/janusgraph.org/latest/cassandra.html
  - 404: `DataStax AMI Docs`
- [x] https://pluradj.github.io/janusgraph.org/latest/config-ref.html
  - 404: http://sourceforge.net/apps/trac/ganglia/wiki/gmetric_spoofing
    - Correct:  https://github.com/ganglia/monitor-core/wiki/Gmetric-Spoofing
- [x] https://pluradj.github.io/janusgraph.org/latest/elasticsearch.html
  - `dynamic scripting documentation`: remove missing anchor
  - 404: `processors documentation`
- [x] https://pluradj.github.io/janusgraph.org/latest/monitoring.html
  - DNS not found for link `Metrics` pointing to http://metrics.codahale.com/
    - Correct: http://www.dropwizard.io
  - 404: `Override IP:hostname reported to Ganglia`
    - Correct:  https://github.com/ganglia/monitor-core/wiki/Gmetric-Spoofing

- [x] Apply this patch and `Field Mapping` will not start with `_` hence will appear!

```
diff --git a/docs/textsearch.txt b/docs/textsearch.txt
index 48fa61df7..a1618faa8 100644
--- a/docs/textsearch.txt
+++ b/docs/textsearch.txt
@@ -106,6 +106,7 @@ mgmt.commit()
 
 Note that some indexing backends (e.g. Solr) may require additional external schema configuration to support and tune indexing non-point properties.
 
+[[field-mapping]]
 == Field Mapping
 
 [[index-local-field-mapping]]
```

**Comment by mbrukman** [comment]
I am fixing all of the issues reported above. Thanks for the thorough investigation, @robertdale!

Note that per [DataStax docs][1]:

> DataStax no longer provides the DataStax Community version of Apache Cassandra™ or the DataStax Distribution of Apache Cassandra.

The only thing we can do here is remove the link to "DataStax AMI docs", as I don't see what the replacement might be.

[1] http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/install/installPriorVersions.html
