### ISSUE TITLE
How can I store nested object to property?

### ISSUE THREAD

**Issue by HackingJ** [JanusGraph/janusgraph#628]
My data spec is below

```
{
  "key1" : "mykey",
  "key2" :  {
     "nestedKey1" : {
        "nestedNestedKey1" : "value"
     },...
  }
}

```
If I want to store key2 into property, How?

Thanks

**Comment by HackingJ** [comment]
Do I implement AttributeSerializer?

**Comment by robertdale** [comment]
Please only use GitHub issues for specific feature requests or bug reports.

This is an open-ended howto question, which is more suited to being discussed on a mailing list, specifically [janusgraph-users](https://groups.google.com/group/janusgraph-users). Please search the [archives](https://groups.google.com/group/janusgraph-users) and if it's not quite answered there, either post a follow-up to one of those threads, or start a new thread if you feel it's sufficiently different from the rest.
