### ISSUE TITLE
Potentially conflicting versions of asm included

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#631]
asm-3.1.jar
asm-5.0.3.jar

**Comment by amcp** [comment]
does this affect our 0.2.0 candidate?

**Comment by pluradj** [comment]
Not a new behavior. In JanusGraph 0.1.1, these are packaged:

- asm-3.1.jar
- asm-4.1.jar

**Comment by robertdale** [comment]
It's not my intention to hold up this release. I have found no actual
issues by the presence of these libraries.  The release is already in its
own process, tests are passing, etc.  I do think that these need to be
addressed prior to the next release.

Robert Dale

**Comment by pluradj** [comment]
Understood and agreed. I think most of these conflicts come down to all the dependencies getting dumped into the `lib` directory, regardless of what backend your server is running with. For example, if you wanted to run a server with just BerkeleyDB, you could probably don't need 100+ of the jars in there.

#371 is related.
