### ISSUE TITLE
Potentially conflicting versions of high-scale-lib included

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#634]
high-scale-lib-1.0.6.jar
high-scale-lib-1.1.4.jar

**Comment by mad** [comment]
high-scale-lib-1.0.6.jar from cassandra
high-scale-lib-1.1.4.jar from janusgraph-core

Version 1.0.6. has some fixes, like this https://github.com/boundary/high-scale-lib/commit/5ed79c93b66825c159965f60fe679188efcb36a4 and has replace for `java.util.concurrent.ConcurrentHashMap`

**Comment by mad** [comment]
fixed in #1698
