### ISSUE TITLE
Uncomment janusgraph-solr in janusgraph-all

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#640]
[`janusgraph-all/pom.xml`][1] says:

```xml
        <!--
        Commented since it requires Hadoop 2 and TP3 requires Hadoop 1.
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-solr</artifactId>
            <version>${project.version}</version>
        </dependency>
        -->
```

[JanusGraph currently depends on TinkerPop 3.2.6][2]; per the [TinkerPop docs][3]:

> Hadoop1 is no longer supported. Hadoop2 is now the only supported Hadoop version in TinkerPop.

Are there any concerns with uncommenting `janusgraph-solr` in `janusgraph-all`?

[1]: https://github.com/JanusGraph/janusgraph/blob/6a04d5c793343af6ce3226adc20bbd77ef466731/janusgraph-all/pom.xml#L76-L83
[2]: https://github.com/JanusGraph/janusgraph/blob/6a04d5c793343af6ce3226adc20bbd77ef466731/pom.xml#L68
[3]: http://tinkerpop.apache.org/docs/3.2.6/upgrade/

**Comment by jerryjch** [comment]
Solr should be added back there, I think.
I will get a PR.

**Comment by mbrukman** [comment]
@jerryjch — no need, I already have one ready, just wanted to confirm this is OK and there are no concerns.
