### ISSUE TITLE
Excessive of array resizing in MultiKeySliceQuery.java

### ISSUE THREAD

**Issue by pencal** [JanusGraph/janusgraph#648]
Result place holder is set to size of 4 in MultiKeySliceQuery.java:56. For a query with large number of results being returned, i.e. tx.query().has("customId", Contain.IN, customIds10000), it will incur an excessive amount of array resizing. Proposing to fix it by switching it to a LinkedList or an ArrayList with initial size of Math.min(getLimit(), queries.size())

**Comment by robertdale** [comment]
I think we should stick with ArrayList unless we're absolutely certain that no downstream usage requires positional index. e.g. range(x,y)

**Comment by pencal** [comment]
submitted PR: https://github.com/JanusGraph/janusgraph/pull/668
trying to figure out why I get the cla:no at the moment.

**Comment by robertdale** [comment]
@pencal Please stop creating new PRs. You can `git push -f` on an existing one.   Looks like you're not listed as a contributor - https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTORS.txt - or you are not using the email address that is listed.
