### ISSUE TITLE
Index always not used

### ISSUE THREAD

**Issue by HackingJ** [JanusGraph/janusgraph#655]
In my case, The property named 'category' is indexed like below.

```
JanusGraphManagement mgmt = graph.openManagement();
PropertyKey cate = mgmt.makePropertyKey("category").dataType(String.class).make();
mgmt.buildIndex("my_category", Vertex.class).addKey(cate).buildMixedIndex("search");
mgmt.commit();

//below is insert data example
String label = "myLabel";
Transaction tx = graph.tx();

JanusGraphVertex v = graph.addVertex(label); 
v.property("data", json); //json is serialized object(java.util.HashMap)
v.property("category", "myCategoryName");

tx.commit();

//below is warned : Query requires iterating over all vertices [(category = myCategory)]. For better performance, use indexes
graph.traversal().V().has("category", "myCategoryName").count().next();
```

I use JanusGraph 0.1.1 in java(embedded janusgraph), ElasticSearch, Cassandra

I checked index status like below and It is enabled 
`mgmt.getGraphIndex("my_category").getIndexStatus(mgmt.getPropertyKey("category")) //ENABLED`

also I checked "category" property is indexed field like below.
`mgmt.getGraphIndex("my_category").getFieldKeys()//[category]`

**Comment by pluradj** [comment]
You created a mixed index which defaults to [full-text searching](http://docs.janusgraph.org/latest/index-parameters.html#_full_text_search). If you want to utilize this mixed index, you need to use a full-text predicate. For example:

```
graph.traversal().V().has("category", Text.textContains("myCategoryName")).count().next();
```

If you're looking for exact matches only, you should use a [composite index](http://docs.janusgraph.org/latest/indexes.html#_composite_versus_mixed_indexes) as it will be faster than a mixed index. Alternately, you could use a mixed index configured for  [string search](http://docs.janusgraph.org/latest/index-parameters.html#_string_search), which allows for the `eq()` predicate.

**Comment by pluradj** [comment]
Also, please use [`janusgraph-users`](https://groups.google.com/forum/#!forum/janusgraph-users) in the future for usage questions like this.
