### ISSUE TITLE
running janusgraph on java9

### ISSUE THREAD

**Issue by kontact-chan** [JanusGraph/janusgraph#657]
Hi Committers,

Shall we support JanusGraph on java9, please?

As you guys know, Java9 did lot of bug fixes and enhancements. Particularly core enhancements like collection literals, stream API's, private interface methods, HTTP/2, etc.

This would help us write clean client side code.

Thanks,
Chandran.

**Comment by pluradj** [comment]
JanusGraph should be able to run with Java 9 without any issues. If you have encountered specific problems running JanusGraph with Java 9, please go ahead and report them.

Java 8 will not go end of life until September 2018, so I'd expect to see support for Java 8 to continue for a while. We can consider Java 9 enhancements, but they would need to be able to co-exist with Java 8. Another consideration is that many of the core client APIs that JanusGraph developers call on are actually defined in Apache TinkerPop, so any Java 9 specific enhancements would need to be driven into an Apache TinkerPop release first, then we can roll it into a JanusGraph release.

That being said, JanusGraph and Apache TinkerPop are community driven projects. Are there specific graph APIs that you think would benefit from Java 9 features? Did you have some ideas on how that would look @kontact-chan?

**Comment by The-Don-Himself** [comment]
I've also faced issues running JanusGraph with Java 9, digging further, it seems a lot of incompatibilities with some (optional) dependencies still exists like groovy and even cassandra. For me specifically, I was looking forward to using Java 9's new Map.of feature to create inline object properties i.e 

````
gremlin > ...property('product_name', 'leather shoe').property('images', Map.of("id", "1", "version", "2", "id", "2", "version", "2")).property('price', 20.12).....
```` 

I tried using HashMap and double brace initialization but that dint work. I haven't found a way to inline Arrays/Objects/Maps. I need to be able to inline them for a gremlin-ogm library I'm working on.

**Comment by robertdale** [comment]
@The-Don-Himself This is not a Java 9 issue.  See [supported data types](http://docs.janusgraph.org/latest/schema.html#_property_key_data_type).  You can create your own [serializer](http://docs.janusgraph.org/latest/serializer.html) for your types.

**Comment by The-Don-Himself** [comment]
Thanks for the response @robertdale but perhaps we're not on the same page yet?

Perhaps a better example with the Twitter API, which has a "entities" field which is an array. 

````
  ....
  "entities": {
    "url": {
      "urls": [
        {
          "url": "https://t.co/66w26cua1O",
          "expanded_url": "https://dev.twitter.com/",
          "display_url": "dev.twitter.com",
          "indices": [
            0,
            23
          ]
        }
      ]
    },
    "description": {
      "urls": []
    }
  },
  ....
````

I can create a property type of with Object.class.

````
mgmt.makePropertyKey('entities').cardinality(Cardinality.SINGLE).dataType(Object.class).make()
````

With Java 8, I can put data in it by doing this in Gremlin console

````
gremlin > urls = new HashMap();
gremlin > urls.put("url", "https://t.co/66w26cua1O");
gremlin > urls.put("expanded_url", "https://dev.twitter.com/");

gremlin > url = new HashMap();
gremlin > url.put("urls", urls);

gremlin > description = new HashMap();
gremlin > description.put("urls", new HashMap());

gremlin > entities = new HashMap();
gremlin > entities.put("url", url);
gremlin > entities.put("description", description);

gremlin > g.V().hasLabel('tweets').has('tweets_id', 123).property('entities', entities);
gremlin > g.tx().commit();

````


With Java 9, I can inline this all in one step by doing this in Gremlin console

````

gremlin > g.V().hasLabel('tweets').has('tweets_id', 123).property('entities', Map.of("url", Map.of("urls", Map.of("url", "https://t.co/66w26cua1O", "expanded_url", "https://dev.twitter.com/")), "description", Map.of("urls", Map.of())));
gremlin > g.tx().commit();

````

It might look less pretty but the fact that it is one line allows me to easily serialize an array into a graph element property.

I'll look into the creating a Serializer as you mentioned, maybe it can solve this headache but I was looking for a native Java solution that can work with JanusGraph out of the box because I'm creating a [PHP graph-ogm library](https://github.com/the-don-himself/gremlin-ogm) that can should ideally work also out of the box with any data (it has a Twitter sample though without the entities)

**Comment by robertdale** [comment]
@The-Don-Himself I see now.  Although `HashMap` is not a supported user-facing data type, it does have a serializer for internal usage.  That is why it is apparently permitted in JanusGraph.  However, Java 9 `Map.of()` does not use `HashMap` for the implementation. It has its own implementation.  I don't forsee JanusGraph supporting that data type even for internal usage.  Thus, you are back to implementing a serializer for the Java 9 `Map.of()` implementation.

I still don't understand your requirement, but you actually can "inline" `HashMap`...
```
new HashMap<String, String>() { { put("url", "https://t.co/66w26cua1O"); put("expanded_url", "https://dev.twitter.com/"); } }
```

**Comment by The-Don-Himself** [comment]
Thanks @robertdale, I dint know of the internals and that Java 9's Map.of won't work, thanks for pointing that out. 
With regards to the double brace initialization HashMap(){{ }}, I already tried this and it does not work inline, i.e.

````
gremlin> map = new HashMap(); map.getClass()
==>class java.util.HashMap

gremlin> map = new HashMap<String, String>() { { put("url", "https://t.co/66w26cua1O"); put("expanded_url", "https://dev.twitter.com/"); } }; map.getClass()
==>class groovysh_evaluate$1
````

The requirement I seek, is for the gremlin-ogm library I'm working on, to create a way serialize PHP arrays, even deep multidimensional one's into a graph element property. So if you had 50 tweets each with an 'entities' field, I'd generate 50 gremlin commands to run and create 'tweets' vertexes from them.

That said, I'm beginning to realise that I may have overlooked groovy's capabilities of [Collection-Lists](http://groovy-lang.org/groovy-dev-kit.html#Collections-Lists) and [Collection-Maps](http://groovy-lang.org/groovy-dev-kit.html#Collections-Maps) and went straight into seeing how to do this in Java.

**Comment by sjudeng** [comment]
You could use Guava's ImmutableMap, though you'd still have to convert to HashMap if you don't want to add a custom serializer.

```
gremlin> import com.google.common.collect.ImmutableMap
gremlin> map = new HashMap(ImmutableMap.of("url", "https://t.co/66w26cua1O", "expanded_url", "https://dev.twitter.com/"))
gremlin> map.getClass()
==>class java.util.HashMap
```

**Comment by The-Don-Himself** [comment]
Thanks a bunch @sjudeng that actually works, recursively as well, just tested with
````
gremlin> new HashMap(ImmutableMap.of("url", ImmutableMap.of("urls", ImmutableMap.of("url", "https://t.co/66w26cua1O", "expanded_url", "https://dev.twitter.com/")), "description", ImmutableMap.of("urls", ImmutableMap.of())))
==>description={urls={}}
==>url={urls={url=https://t.co/66w26cua1O, expanded_url=https://dev.twitter.com/}}
````

Guess Java 9 wasn't really necessary after all.
Cheers.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
