### ISSUE TITLE
Update properties files to add `gremlin.graph` setting

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#662]
As mentioned in https://github.com/JanusGraph/janusgraph/issues/659#issuecomment-339353527 by @pluradj, we should:

> add `gremlin.graph=org.janusgraph.core.JanusGraphFactory` to all the properties files shipped with the distribution.

**Comment by pluradj** [comment]
I was thinking we'd use #659 for it

**Comment by chupman** [comment]
This would be a good first issue for someone to work on. Here's a little extra direction to fix this.

For all of the properties files under `janusgraph-dist/src/assembly/cfilter/conf/` not for `ConfiguredGraphFactory`, that the following line should be added.

```
#JANUSGRAPHCFG{gremlin.graph=org.janusgraph.core.JanusGraphFactory}
```

One way to tell if it's a `ConfiguredGraphFactory` properties file is the presence of this line `gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory` within the properties file.

**Comment by li-boxuan** [comment]
Hi, I would like to take this issue. I will send out a patch soon.
