### ISSUE TITLE
Update ElasticSearch dependency

### ISSUE THREAD

**Issue by sharpau** [JanusGraph/janusgraph#67]
JanusGraph officially is only compatible with ElasticSearch 1.5.x, a release from late 2014 that is no longer supported (EOL was September 2016 https://www.elastic.co/support/eol).

http://docs.janusgraph.org/0.1.0-SNAPSHOT/version-compat.html

I am running Titan in production with ES 1.7.5 with no issues, but that just hit EOL as well. The 2.0 branch is still maintained, and ES recently jumped to 5.x releases. There are security concerns with the older, unmaintained branches. 

Related: Titan requires the dynamic scripting feature of ES, which is off by default in newer versions. I do not know how strict of a requirement this is, but it would be nice to not rely on it if possible.
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html

**Comment by sjudeng** [comment]
The branch below updates JanusGraph to Elasticsearch 2.4.4. I hope to be able to sumit a PR off this shortly. But note this breaks support for Elasticsearch 1.x. Not sure if that'll be acceptable to the community.

https://github.com/ngageoint/janusgraph/tree/elasticsearch-geoshape-upgrade

I do plan to update to support Elasticsearch 5.x unless someone else is already on it. Question is whether we'd want to maintain backwards compatiblity with 2.x.

**Comment by MichaelMarkieta** [comment]
I am interested in the support for ElasticSearch 5.x. Let me know if there is anything I can help with.

**Comment by sjudeng** [comment]
@MichaelMarkieta There's related discussion on the list below. It would be useful if you're interested in chiming in there on your opinion on whether to maintain support for ES 1.x, or just go forward with 2.x/5.x compatibility, and whether to support node/transport clients or just the HTTP client (ES RestClient or Jest client).

https://groups.google.com/forum/#!topic/janusgraph-dev/F-zfIsuiIoQ

Current status is #79 pending merge adds support for 2.x and there are at least a couple of efforts underway to get to ES 5.x support. I have updates to add support for 5.x with backwards compatibility with 2.x using ES 5.x REST client. @krlohnes has updates to use the Jest high level HTTP ES client. Hopefully some combination of these will get JanusGraph to full 2.x/5.x compatibility in the near term.

**Comment by sjudeng** [comment]
Closing after merge of #79 which adds support for ES 2.x and 5.x.
