### ISSUE TITLE
SET and LIST cardinality support for lucene indexes

### ISSUE THREAD

**Issue by Lakedaemon** [JanusGraph/janusgraph#670]
Would it be possible to support SET and LIST cardinality for Lucene indexes ? or does something prevent this ?
In cas it is possible, how hard would it be to support it ? 
What would be the required steps or methods to implement ?

Best regards,
Olivier

**Comment by davidclement90** [comment]
I do not know if it's possible, I'm not a Lucene user. But if you want to try, you should :
1) update static attribute LUCENE_FEATURES
2) update addToDocument method

**Comment by robertdale** [comment]
It's definitely possible.  Both Elasticsearch and Solr are built on top of Lucene. My guess is you would iterate the list and treat each element as its own document.

**Comment by Lakedaemon** [comment]
thanks, I'll probably have a go at this (an easy but dirty workaroud now would probably be to set the property as a string with spaces separating the different elements)

**Comment by davidclement90** [comment]
It's can not work because you can update or delete one property among all or you could have spaces in property value.

**Comment by Lakedaemon** [comment]
I have just started looking at adding Cardinality.Set and cardinality.LIST for a lucene index backend. 

I have also only been playing with janusGraph recently so I only have a partial understanding of it's inner workings (so please be kind with me If I ask silly questions).

My guess is that lucene's Document is used to store and index a single Vertex (with it's properties) or Edge (right ?). But Lucene's Document can't have multiple values with the same key (an IndexableField has a single value). Yet, that single value can be a BytesRef (binary value) a ReaderValue (accessible through a Reader) and have a TokenStream.

So, I guess that the set or list should be serialized in an indexableField in a binary blob (or Json or whatever) and deserialized later through a Reader or a ByteRef and we should provide a special Analyzer that will first split the values of the IndexableField value into the values of the LIST/SET and then delegate tokenizing to the janusGraph Analyzer to provide tokens for this particular LIST/SET value

That way, spaces can be used in property values. Is there a janusGraph Way to serialize things into bytes ? (I guess there is...Serializers probably)

To mutate a LIST/SET value, you have to delete it and add it again, 

I'll try doing it this way (except if someone tells me this is wrong and should be done another way (please also try to tell why))

**Comment by Lakedaemon** [comment]
Mmmmh, I don't need to store the values, that's the job of the store backend (not lucene's). I should just index the values

**Comment by Lakedaemon** [comment]
mmmh, actually Lucene's Document can handle multiple values for the same field...

**Comment by Lakedaemon** [comment]
LIST and SET cardinality will prevent using NumericDocValues for numbers (only 1 value per field)

I'll probably get something working decently soon. But to make a decent job, I'll need to know :  

Are the stored values used to restore the old document (before mutation) ? 
If no, why are indexed values stored in the lucene index ? what purpose do those stored values serve ?

**Comment by Lakedaemon** [comment]
Yes, old document is restored thanks to the stored fields (which means that the index duplicates the indexed data of the graph)... 
Now, I guess mutation adds some value to a field and deletes some value (for CARDINALITY LIST and SET)... how to handle that...mmh... (how do you delete a value from a list, with it's index ? what happens if the list has multiple occurences of the same value ? )

**Comment by Lakedaemon** [comment]
Ok.. deletions remove fields by (String) key and additions add a value to a field. 
Now, il the user adds a value to a list for a janusgraph property, how is it handled at the index side ? 
delete the whole list and add each value of the new list OR 
take the old list an only add the added value ?

What about sets ? are the check made at the janusgraph end or should I make the unicity check (also) at the index end ?

What about single value, should I throw if I catch a value added to a SINGLE field that already has one value (and no deletion ?)

**Comment by Lakedaemon** [comment]
for numeric fields, this happens : 
doc.add(field);
doc.add(sortField);
where field is not stored... which means that the only possible way to mutate a list with numbers is to delete it first and then add all elements again (or there will be missing fields in the recreated Document) with this code

**Comment by Lakedaemon** [comment]
Something is weird though IMO. As I know it, lucene mostly updates documents (appart from docValues that can be updated, it may depend from the lucene version, I'm mostly knowledgeable about lucene 4.7) by deleting them and reindexing them (so trying to mutate them is like recreating them from scratch anyway)...
Also, in my experience, clearing Document was slower than creating a new Document, so I'm a bit surprised by this strategy of storing values, recreating an old Document through an IndexReader, mutating it and adding it to the index especially since some fields cannot be stored and restored (LongPoint for whole numbers, I'm looking at you).

I would expect JanusGraph to send Lucene an id (the DOCID string) and a list of Pair(field, value) for all indexable property of a Vertex/Edge, each time it is mutated.

But maybee I'm mistaken and I don't understand the whole picture.
Could anybody knowing how janusgraph works  internally regarding indexing (or the person who contributed LuceneIndex) care to explain the indexing process (or point me to a doc where the inner mechanism of Janusgraph regarding indexing is explained) ? 

Anyway, I'll keep on experimenting with my own implementation of LuceneIndex, the next weeks.
Please send my regards to the dev who made it so easy to plug a custom third party indexing backend to a Janusgraph (I love you).

**Comment by Lakedaemon** [comment]
Ok, after experimenting a bit with Gremlin : 
Each time a value is deleted from (say) a key with LIST cardinality, a deletion is emitted (with key and value) and each time a value is added, an addition (with key and value) is emitted.

As the whole vertex/edge properties aren't emitted, this means that the index must work incrementally (and so it must store the previous emitted values).
a value that is tokenized into a list of tokens is lost if it is not stored, as Lucene update documents by deleting them and addind them again (reindexing them). 

So, for incremental indexing to succeed with Lucene, with the data passes in an IndexMutation.
Either lucene gets the old values of the index (which is doable but may take time) and it only needs to index things

Or lucene stores the indexed values and uses them to reindex when an incremental update is sent  

I think that the second option is the one that was used for Cardinality.SINGLE.

**Comment by Lakedaemon** [comment]
This issue isn't so bad for Cardinality.SINGLE : 
on addition, you have the only value that you need to index, on deletion, you remove it.

Yet, for Cardinality.LIST and cardinality.SET this is a big issue.
Also, as an addition can have an Object value, you have to be able to store arbitrary objects (serializers/deserializers...) AGAIN (because they are stored in the index too).
This is really annoying.

Mutation should pack the old values (for better Cardinality Set/List support).
This is going to be a pain to implement

**Comment by Lakedaemon** [comment]
looks like the solr guys go with the first way and 
https://lucene.apache.org/solr/guide/6_6/updating-parts-of-documents.html

Then, I'll try to do it this way too :/

**Comment by Lakedaemon** [comment]
I have started working on a pr for that. Hopefully, my attempt will be successful

**Comment by porunov** [comment]
Fixed in #1686
