### ISSUE TITLE
Custom analyzer for lucene

### ISSUE THREAD

**Issue by Lakedaemon** [JanusGraph/janusgraph#672]
Is there a way to use custom analyzer with a lucene index ?
I have properties that might be in 30 different languages (chinese, japanese, russian, french, urdu, lots of fancy languages that won't work best with the StandardAnalyzer shipped with lucene) and that need specific analyzers

I have been using lucene extensively for the last 5 years in some multi-lingual android app and I would like to know if I can use the full might of Lucene with JanusGraph or if I should start looking for a property graph replacement. 

If it is theoretically possible to make lucene work with custom analyzers and if It is in my capacity to implement it, I would also like to help (might take less time to implement the lucene features I need in JanusGraph than looking for better alternatives or getting burned reimplementing one)

Best regards,
Olivier

**Comment by robertdale** [comment]
You could check or add support similar to ES, Solr - http://docs.janusgraph.org/latest/field-mapping.html#_custom_analyser

**Comment by Lakedaemon** [comment]
Before posting, I  had a (fast) look at the code for Solr and gor the feeling it might be feasible (but I needed a confirmation before trying it)

I'll probably have a go at it (not immediately though). If I manage to make things work and to put it in a decent shape, I'll create a pr. Thanks

**Comment by Lakedaemon** [comment]
It looks like I just managed to implement custom analyzer support for lucene and JanusGraph
I'll now take some time to test if it really works (it was relatively easy) and if it does I'll clean my stuff and make a pr

**Comment by Lakedaemon** [comment]
It looks like my code produces an index with a custom analyzer (for french, chinese, english...)
I looked in the lucene index and all the terms are there
But when I'm doing a simple gremlin query on a field indexed with the custom analyzer, it warns that 

> Query requires iterating over all vertices [(fraG = livre)]. For better performance, use indexes

pondering now.... what am I doing wrong ?

**Comment by robertdale** [comment]
@Lakedaemon  Where's your repo? I didn't see a fork of JanusGraph.

**Comment by Lakedaemon** [comment]
I just forked janusgraph and sent a pr
How may I sign the CLA ?

**Comment by robertdale** [comment]
@Lakedaemon  https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

**Comment by Lakedaemon** [comment]
thanks, I'm sending the email with the scans and the cla right now.

**Comment by Lakedaemon** [comment]
figured out what was wrong with my test.
I was using operator has with a Mapping.Text field instead of Mapping.textContains
I have started testing custom analyzers for Lucene with my own code, (now it pass the lucene tests)...
