### ISSUE TITLE
JanusGraph 0.2.0 Spark failed to connect to master

### ISSUE THREAD

**Issue by fromnowon66** [JanusGraph/janusgraph#685]
When I use the example in Chapter 35 of JanusGraph 0.2.0 documentation, it is OK. But when I change spark.master in conf/hadoop-graph/hadoop-load.properties from local[*] to spark://192.168.63.105:7077, I get some warn infos.

There is a note in Chapter 35 of JanusGraph 0.2.0 documentation: The example in this chapter are based on running Spark in local mode. Additional configuration is required when using Spark in standalone mode or when running Spark on Yarn or Mesos. What is additional configuration?

The warn info:
> WARN org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer - class org.apache.hadoop.mapreduce.lib.output.NullOutputFormat does not implement PersistRequestGraphAware and thus, persistence options are unknown -- assuming all options are possible

> WARN org.apache.spark.deploy.client.AppClient$ClientEndpoint - Failed to connect to master 192.168.63.105:7077

> java.lang.RuntimeException: java.io.EOFException
> at java.io.DataInputStream.readFully(DataInputStream.java:197)
> at java.io.DataInputStream.readUTF(DataInputStream.java:609) 
> at java.io.DataInputStream.readFully(DataInputStream.java:564) 
> at org.apache.spark.rpc.netty.RequestMessage$.readRpcAddress(NettyRpcEnv.scala:582)
> at org.apache.spark.rpc.netty.RequestMessage$.apply(NettyRpcEnv.scala:592)
> at org.apache.spark.rpc.netty.NettyRpcHandler.internalReceive(NettyRpcEnv.scala:651)
> at org.apache.spark.rpc.netty.NettyRpcHandler.receive(NettyRpcEnv.scala:636)
> at org.apache.spark.network.server.TransportRequestHandler.processRpcRequest(TransportRequestHandler.java:157)
> at org.apache.spark.network.server.TransportRequestHandler.handle(TransportRequestHandler.java:105)
> at org.apache.spark.network.server.TransportChannelHandler.channelRead(TransportChannelHandler.java:118)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
> at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
> at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
> at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:85)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
> at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
> at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
> at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> at io.netty.channel.nio.NioEventLoop.processSelectedkey(NioEventLoop.java:643) 
> at io.netty.channel.nio.NioEventLoop.processSelectedkeyOptimized(NioEventLoop.java:566)
> at io.netty.channel.nio.NioEventLoop.processSelectedkey(NioEventLoop.java:480)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
> at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
> at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
> at java.lang.Thread.run(Thread.java:745)

> at org.apache.spark.network.client.TransportResponseHandler.handle(TransportResponseHandler.java:186)
> at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:106)
> at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:51)
> at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
> at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
> at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
> at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:86)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
> at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
> at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> at io.netty.channel.nio.NioEventLoop.processSelectedkey(NioEventLoop.java:646)
> at io.netty.channel.nio.NioEventLoop.processSelectedkeyOptimized(NioEventLoop.java:581)
> at io.netty.channel.nio.NioEventLoop.processSelectedkey(NioEventLoop.java:498)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
> at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
> at java.lang.Thread.run(Thread.java:745)

My configuration file is conf/janusgraph-hbase-es-test-spark.properties whose content is following:

storage.backend=hbase
storage.hostname=192.168.63.105,192.168.63.107,192.168.63.109
storage.hbase.ext.hbase.zookeeper.property.clientPort=2181
storage.hbase.table=janus_test_spark_7077
gremlin.graph=org.janusgraph.core.JanusGraphFactory
cache.db-cache=true
cache.db-cache-clean-wait=20
cache.db-cache-time=18000
cache.db-cache-size=0.5
index.search.backend=elasticsearch
index.search.hostname=192.168.63.105,192.168.63.107,192.168.63.109
index.search.elasticsearch.client-only=true

The spark version which I use is spark-2.2.0-bin-hadoop2.7. 

I also try spark-1.6.0-bin-hadoop2.6, the warn info is following:

>WARN org.apache.spark.scheduler.TaskSetManager - Lost task 0.0 in stage 0.0 (TID 0, SparkWorker109): java.io.InvalidClassException: org.apache.spark.rdd.MapPartitionsRDD; local class incompatible: stream classdesc serialVersionUID=6732270565076291202, local class SerialVersionUID=-1059539896677275380
>at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616) 
>at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630) 
>at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) 
>at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781) 
>at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353) 
>at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018) 
>at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942) 
>at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808) 
>at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353) 
>at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373) 
>at org.apache.spark.serializer:JavaDeserializationStream.readObject(JavaSerializer.scala:76)
>at org.apache.spark.serializer:JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
>at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:64)
>at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
>at org.apache.spark.scheduler.Task.run(Task.scala:89)
>at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>at java.lang.Thread.run(Thread.java:745)

Thanks for your attention and help.

**Comment by pluradj** [comment]
JanusGraph 0.2.0 is compatible with Spark 1.6.1. Agreed that the docs need updating. Please refer to this issue https://github.com/JanusGraph/janusgraph/issues/253. There is a good blog post mentioned there that covers YARN in depth.

**Comment by fromnowon66** [comment]
Thanks. I try spark-1.6.1-bin-hadoop2.6, but I get following warn info:
 >warn org.apache.spark.scheduler.TaskSchedulerImpl - Initial job has not accepted any resource; check your cluster UI to ensure that workers are registered and have sufficient resources. 
In spark's log, I can see that workers are registered. And free memory is sufficient, cpu cores are enough.  
Is there some specific configuration for spark standalone mode ?

**Comment by fromnowon66** [comment]
Sorry, It's my problem. I removed ”spark.serializer=org.apache.spark.serializer.KryoSerializer“ in conf/hadoopgraph/hadoop-load.properties.  SparkGraphComputer does work with Spark-1.6.1-bin-hadoop2.6's standalone mode. Thanks. How well if spark-2.2.0 were also OK.

**Comment by pluradj** [comment]
sounds like you've solved your problem. closing.
