### ISSUE TITLE
Create ES ConfigOption MAX_RETRIES_IN_MILLIS

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#688]
The ES RestClient does [not
support](https://github.com/elastic/elasticsearch/issues/21789#issuecomment-263243530)
a per request timeout configuration, however it does at least support a
timeout configuration option `maxRetriesInMillis` that will timeout the
overall request, including retries. It can be useful for others to
configure this timeout, especially given the fact that users can
configure their gremlin-script-execution timeout.

**Comment by davidclement90** [comment]
Merge in 0.2
