### ISSUE TITLE
Looks like we are missing modes-rexster.png file?

### ISSUE THREAD

**Issue by hsaputra** [JanusGraph/janusgraph#69]
In the document page for HBase:

http://docs.janusgraph.org/0.1.0-SNAPSHOT/hbase.html

There is a missing link to an image:

http://docs.janusgraph.org/0.1.0-SNAPSHOT/images/modes-rexster.png

**Comment by mbrukman** [comment]
Looks like my fault (filename misspelled), I'll fix it.

**Comment by jerryjch** [comment]
Cassandra section 'Remote Server Mode with Gremlin Server' does not have the link to the modes-rexster.png.  Do you want to add it?
http://docs.janusgraph.org/0.1.0-SNAPSHOT/cassandra.html
Or do it separately?

**Comment by mbrukman** [comment]
@jerryjch – I added another commit to my PR to include the image in the Cassandra docs as well.

**Comment by hsaputra** [comment]
Since it is merged, will close this issue

**Comment by mbrukman** [comment]
Pushed changes to http://docs.janusgraph.org; both URLs from [initial report](https://github.com/JanusGraph/janusgraph/issues/69#issue-203760482) now work.
