### ISSUE TITLE
Licensing Issue with lgpl license on transitive dependency

### ISSUE THREAD

**Issue by sebastiantb** [JanusGraph/janusgraph#691]
Greetings :
 
I’m Sebastian a Software Engineer for GE Digital.
 
We are currently using your graph engine,  which uses the following library as a transitive dependency.
 
https://mvnrepository.com/artifact/org.acplt/oncrpc/1.0.7

This dependency is being used by metrics-ganglia --> gmetric4j and it's being imported on your janusgraph-core maven dependency

https://mvnrepository.com/artifact/org.janusgraph/janusgraph-core/0.2.0
 
We are currently working with the eclipse foundation on making a project contribution and the intellectual property scans detected the library is licensed under LGPL and therefore it cannot be used.
 
Is there any possibility this library can be replaced?

Also, if we remove it from our pom file, will it affect stability?

info on the project

https://projects.eclipse.org/projects/iot.keti
 
Best Regards
 
Sebastian Torres Brown

**Comment by pluradj** [comment]
@sebastiantb We use pull request for code updates. Please see the responses on thread you started on [`janusgraph-dev`](https://groups.google.com/d/msg/janusgraph-dev/WVvQEi2g1zA/UM1CU21BAQAJ) an continue the conversation there. Thanks.
