### ISSUE TITLE
hasId() with multiple IDs fails unless IDs are strings

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [JanusGraph/janusgraph#706]
Hi! On JanusGraph 0.2.0, using a StandardJanusGraph instance, I've been unable to reproduce various examples from the TinkerPop documentation where `hasId()` (or `has(id, ...)`) is used with multiple IDs.

None of the forms `hasId(1, 2, 3)`, `has(id, within(1, 2, 3))` and `hasId(within(1, 2, 3))` work. 

However the form `hasId("1", "2", "3")`, with the integer IDs used as strings does work. Is this intended behavior? Using a TinkerGraph instance instead, I _am_ able to use `hasId(...)` with multiple numeric vertex IDs.

Here's a quick example. Three vertices, with one edge between each unique pair:

```
gremlin> g
==>graphtraversalsource[standardjanusgraph[cassandra:[cassandra]], standard]
gremlin> g.V().drop()
gremlin> g.inject(1, 2, 3).addV('artist')
==>v[4216]
==>v[4224]
==>v[8320]
gremlin> g.V(4216).addE('alias_of').to(V(4224))
==>e[173-394-t1-39c][4216-alias_of->4224]
gremlin> g.V(4216).addE('alias_of').to(V(8320))
==>e[1lb-394-t1-6f4][4216-alias_of->8320]
gremlin> g.V(4224).addE('alias_of').to(V(8320))
==>e[1zk-39c-t1-6f4][4224-alias_of->8320]
```

Checking for edges between vertices `(4216 or 4224)` and `4216` returns the expected edge:

```
gremlin> g.V(4216, 4224).bothE().dedup().where(otherV().hasId(4216))
==>e[173-394-t1-39c][4216-alias_of->4224]
```

Checking for edges between `(4216 or 4224)` and `(4216 or 4224)` returns nothing:

```
gremlin> g.V(4216, 4224).bothE().dedup().where(otherV().hasId(4216, 4224))
```

Treating the vertex IDs as strings, and checking for edges between `(4216 or 4224)` and `("4216" or "4224")` returns the expected edge:

```
gremlin> g.V(4216, 4224).bothE().dedup().where(otherV().hasId("4216", "4224"))
==>e[173-394-t1-39c][4216-alias_of->4224]
```

`within(...)` shows the same behavior:

```
gremlin> g.V(4216, 4224).bothE().dedup().where(otherV().has(id, within(4216, 4224)))
gremlin> g.V(4216, 4224).bothE().dedup().where(otherV().has(id, within("4216", "4224")))
==>e[173-394-t1-39c][4216-alias_of->4224]
```

**Comment by robertdale** [comment]
JanusGraph IDs are Java Long.  Numbers in Gremlin console (Groovy) are Integer by default.  I believe you are experiencing the rather odd behavior of Gremlin where Strings are auto-converted to the proper type but Numbers are otherwise left to strict typing.  Thus, in Java, an Integer will never equal a Long. I.e. 1 != 1L.  Yes, perplexing.  However, should you try your query again using `4216L`, `4224L`, you will find it produces the correct results.  In conclusion, be sure to use the correct type of the values to be compared.

**Comment by josiah-wolf-oberholtzer** [comment]
Thanks for the explanation. That certainly is perplexing, but I can work with it. Cheers!

**Comment by josiah-wolf-oberholtzer** [comment]
Actually though, I'm curious why `g.V(1)`, `g.V(1, 2, 3)` and `hasId(1)` don't require the `L` suffix when `hasId(1, 2, 3)` does (as `hasId(1L, 2L, 3L)`. Is this inconsistency a quirk of Gremlin?
