### ISSUE TITLE
JanusGraphCleanup.clear() failed with java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by EugeneChung** [JanusGraph/janusgraph#710]
```
import org.janusgraph.core.JanusGraphFactory
import org.janusgraph.core.util.JanusGraphCleanup

graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
graph.close()
JanusGraphCleanup.clear(graph)
```

My groovy script to call JanusGraphCleanup.clear() well worked for 0.1.1 with ElasticSearch 1.5.x.
But for 0.2.0 and ElasticSearch 5.6.x, the script shows an error like below.

    [exec] org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
     [exec] 	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup.clear(JanusGraphCleanup.java:55)
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup$clear.call(Unknown Source)
     [exec] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
     [exec] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
     [exec] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
     [exec] 	at groovysh_evaluate.run(groovysh_evaluate:3)
     [exec] 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
     [exec] 	at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:70)
     [exec] 	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:191)
     [exec] 	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.super$3$execute(GremlinGroovysh.groovy)
     [exec] 	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
     [exec] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
     [exec] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
     [exec] 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
     [exec] 	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:72)
     [exec] 	at org.apache.tinkerpop.gremlin.console.Console$_executeInShell_closure20.doCall(Console.groovy:391)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
     [exec] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
     [exec] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
     [exec] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
     [exec] 	at groovy.lang.Closure.call(Closure.java:414)
     [exec] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1956)
     [exec] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1936)
     [exec] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1986)
     [exec] 	at org.codehaus.groovy.runtime.dgm$174.doMethodInvoke(Unknown Source)
     [exec] 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
     [exec] 	at org.apache.tinkerpop.gremlin.console.Console.executeInShell(Console.groovy:368)
     [exec] 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
     [exec] 	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:161)
     [exec] 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
     [exec] 	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:478)
     [exec] Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation ClearBackend
     [exec] 	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:82)
     [exec] 	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
     [exec] 	... 38 more
     [exec] Caused by: java.lang.RuntimeException: org.janusgraph.diskstorage.PermanentBackendException: Could not delete index janusgraph
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup$1.lambda$call$0(JanusGraphCleanup.java:68)
     [exec] 	at java.util.Map.forEach(Map.java:630)
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup$1.call(JanusGraphCleanup.java:64)
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup$1.call(JanusGraphCleanup.java:55)
     [exec] 	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
     [exec] 	... 39 more
     [exec] Caused by: org.janusgraph.diskstorage.PermanentBackendException: Could not delete index janusgraph
     [exec] 	at org.janusgraph.diskstorage.es.ElasticSearchIndex.clearStorage(ElasticSearchIndex.java:1081)
     [exec] 	at org.janusgraph.core.util.JanusGraphCleanup$1.lambda$call$0(JanusGraphCleanup.java:66)
     [exec] 	... 43 more
     [exec] Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
     [exec] 	at org.apache.http.util.Asserts.check(Asserts.java:46)
     [exec] 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
     [exec] 	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
     [exec] 	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:343)
     [exec] 	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:325)
     [exec] 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
     [exec] 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
     [exec] 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:153)
     [exec] 	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.indexExists(RestElasticSearchClient.java:139)
     [exec] 	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.deleteIndex(RestElasticSearchClient.java:209)
     [exec] 	at org.janusgraph.diskstorage.es.ElasticSearchIndex.clearStorage(ElasticSearchIndex.java:1079)
     [exec] 	... 44 more
     [exec] Result: 1

**Comment by CJSoldier** [comment]
The clear method is deprecated in 0.2.0.
I found a new way, Try this `JanusGraphFactory.drop(graph);`. 
It will drop janusgraph keyspace in cassandra and delete index in elasticsearch completely.

**Comment by EugeneChung** [comment]
Thank you. It works.
