### ISSUE TITLE
Cassandra 3 Support

### ISSUE THREAD

**Issue by neeleshsambhajiche** [JanusGraph/janusgraph#72]
I am interesting in using JanusGraph with Cassandra 3.x. Is there any step that I need to perform to make JanusGraph work with Cassandra 3.x? Are there any special build instructions?

**Comment by fppt** [comment]
We are currently discussing upgrading the Cassandra backend here: https://github.com/JanusGraph/janusgraph/issues/35

**Comment by pluradj** [comment]
In the short term though, you should be able to run JanusGraph against a Cassandra 3.x backend without any special build changes to JanusGraph itself -- just make sure you enable thrift for Cassandra.
