### ISSUE TITLE
When will JanusGraph 0.2.1 be released?

### ISSUE THREAD

**Issue by CJSoldier** [JanusGraph/janusgraph#778]
Please, I really need this version.

**Comment by The-Don-Himself** [comment]
I'm curious, what features exactly do you need? You can always [build](https://github.com/JanusGraph/janusgraph/blob/master/BUILDING.md) from the master version, thats actually what I use in production ever since I needed elasticsearch 5.x support.

**Comment by robertdale** [comment]
TinkerPop 3.2.7 should be released this month. I would like to see JanusGraph 0.2.1 include that and released shortly after.

**Comment by CJSoldier** [comment]
I'm waiting for a bug being fixed.  You're right,@The-Don-Himself.
