### ISSUE TITLE
Add missing code formatting for file and directory paths

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#803]
The [current version of `docs/basics.adoc`][1] does not consistently use code formatting to separate file and directory paths inline with text using the code font, e.g., here's an example:

> Once a local configuration is tested and you have a working properties file, copy the properties file from the ./conf directory to the ./conf/gremlin-server directory.

which should be formatted as:

> Once a local configuration is tested and you have a working properties file, copy the properties file from the `./conf` directory to the `./conf/gremlin-server` directory.

[1]: https://github.com/JanusGraph/janusgraph/blob/2053aec6decca64fa209b390c07388f4d483d195/docs/basics.adoc

**Comment by chupman** [comment]
@mbrukman I'll take this one. I'm already reading through the basics section to help myself get up to speed.
