### ISSUE TITLE
Consider updating Travis CI config to use newer image versions

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#811]
According to [this Travis CI blog post][travis-blog]:

> Starting December 11, we start supporting a new set of group attributes for selecting build images, and the existing ones will be deprecated. By default, the value will be `travis_lts` which means that you won’t see any drastic changes to your current projects. If you’re looking for more frequent, regular updates, `travis_latest` will be available.

So my understanding is that instead of using:

```yaml
dist: trusty
```

we can use:

```yaml
group: travis_lts  # also the default, and equivalent to what we have today
```

or

```yaml
group: travis_latest  # to get newer image versions
```

@sjudeng, what are your thoughts on using newer images? Seems like Trusty is quite old (even though [it's not EOL until 2019][ubuntu-releases]), and we're likely not testing with what many of our users are running themselves. On the other hand, some folks may be rather content to use LTS images, but I don't think we can double the size of our build/test matrix with both.

[travis-blog]: https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
[ubuntu-releases]: https://wiki.ubuntu.com/Releases

**Comment by sjudeng** [comment]
I think at the time this was used to get an image supporting running Docker. As long as all jobs pass with the newer image I'd say definitely go for it. I agree we don't want to double the build matrix by testing against multiple images.
