### ISSUE TITLE
JanusGraph should have a preferred Cassandra driver

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#834]
The docs prefer `cassandra` which is `astyanax`.
Contrary to the docs, the property files are configured for `cassandrathrift`.
There is also the new `cql` driver which does not have **any** documentation. See also #385 

There may be a reason to not use the `cassandra` driver - http://docs.janusgraph.org/latest/common-questions.html#_cassandra_connection_problem

In any case, the documentation and configuration should be clear and consistent.

**Comment by takaomag** [comment]
I guess many people use cassandrathrift because it is default in example property file.
Which cassandra driver is recommended in case of current  master?
cql ?

**Comment by menggudaoke** [comment]
How to update a disabled mixed index to enabled?
@robertdale

**Comment by FlorianHockmann** [comment]
Isn't this ticket already implemented by PR #1135? @pluradj changed the property files to use `cql` and also updated the docs accordingly in that PR. They now list `cql` first like this:

> cql - CQL based driver. This is the recommended driver.

and repeat this recommendation again:

> JanusGraph users are recommended to use the cql storage backend.

----

@menggudaoke Please ask usage questions on the [JanusGraph users Google group](https://groups.google.com/forum/#!forum/janusgraph-users). There more people willl see your question and can possibly help you.

**Comment by pluradj** [comment]
closing as fixed https://docs.janusgraph.org/latest/cassandra.html#cassandra-storage-backend
