### ISSUE TITLE
how to delete a mixed index ? or how to update a disabled mixed index to enabled?

### ISSUE THREAD

**Issue by menggudaoke** [JanusGraph/janusgraph#840]
now i have a mixed index, it's status is DISABLED, like this:
`gremlin> m.getGraphIndex('singleProperty_mixedIndex').getIndexStatus(m.getPropertyKey('prop1'))
==>DISABLED
`
now i want to delete it ,but the gremlin server report this exception: 
`gremlin> m = graph.openManagement();
==>org.janusgraph.graphdb.database.management.ManagementSystem@233a3493
gremlin> i = m.getGraphIndex('singleProperty-5_20171213034756cec8a1b4-3535-489c-aae9-28bc23057ba2');
==>singleProperty-5_20171213034756cec8a1b4-3535-489c-aae9-28bc23057ba2
gremlin> m.updateIndex(i, SchemaAction.REMOVE_INDEX)
External mixed indexes must be removed in the indexing system directly.
`

or how to update a DISABLED index to ENABLED?
THANKS FOR HELP!

**Comment by robertdale** [comment]
The github issue tracker is for bug reports, feature requests. Please use the user list for questions - https://groups.google.com/forum/#!forum/janusgraph-users
