### ISSUE TITLE
Update to Spatial4J 0.7 / JTS 1.15

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#846]
Spatial4J 0.7 will contain JTS 1.15.

[See discussion](https://groups.google.com/d/msg/janusgraph-dev/JOQBE_0DNok/wkbDcl7JCgAJ)

- [x] Release date 12/22

Without much fanfare, [JTS](https://www.locationtech.org/projects/technology.jts) 1.15 was released.  This release uses the less restrictive EPL license which should enable JanusGraph to include it by default - IANAL.

- [Annoucement](https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00215.html)
- [Release Notes](https://www.locationtech.org/projects/technology.jts/releases/1.15/plan)
- [License FAQ](https://github.com/locationtech/jts/blob/master/FAQ-LICENSING.md)
- [Upgrade Guide](https://github.com/locationtech/jts/blob/master/MIGRATION.md)
- [GitHub Release Page](https://github.com/locationtech/jts/releases/tag/jts-1.15.0)
- [Deployed to maven](http://search.maven.org/#artifactdetails%7Corg.locationtech.jts%7Cjts-core%7C1.15.0%7Cbundle)

Remove `optional` from pom(s).

**Comment by chupman** [comment]
Work was completed in PR #907
