### ISSUE TITLE
Support standalone HTTP HMAC authentication

### ISSUE THREAD

**Issue by krlohnes** [JanusGraph/janusgraph#859]
This issue arose from discussion around a regression issue in TinkerPop in [this PR](https://github.com/JanusGraph/janusgraph/pull/624#discussion_r158963481). I've created a PR fixing the issue in the [TinkerPop repo](https://github.com/apache/tinkerpop/pull/767). It's just a matter of that PR being merged and updating TinkerPop accordingly.

**Comment by chupman** [comment]
Hi @krlohnes can this be considered resolved with 0.3.1 using tinkerpop 3.3.3?

**Comment by krlohnes** [comment]
@chupman I believe it can.
