### ISSUE TITLE
Cassandra driver 3.1.4 is out of date

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#864]
Hello,

Is it possible to update Cassandra driver to 3.2.0+ (The newest version right now is 3.3.2)? The problem with Cassandra drivers below 3.2.0 is that they are using Guava 19.0 dependency which is out of date. Most libraries which use Guava use Guava 20+. With fixes in the newest versions of Cassandra driver it will be possible to use newer versions of other libraries. I would suggest to update Cassandra driver dependency from 3.1.4 to 3.3.2. 

Best regards,
Alexandr

**Comment by pluradj** [comment]
FWIW, I think HBase still uses a Guava version even older than 19 (cc: @jerryjch).

I'm not saying that we can't update the Cassandra driver, but I want to highlight that updating the driver might not be as simple as bumping the version in the pom.xml.

**Comment by porunov** [comment]
@pluradj , I know that Cassandra 3.3.2 can switch between Guava <= 19 and Guava > 19 depends on the Guava provided in the application. I don't know what changes can happen if the Cassandra driver is updated, but at least newer versions of Cassandra have a Guava workaround.

**Comment by fbalicchia** [comment]
Hi, 
in my own branch I've upgrade Cassandra driver from  3.1.4 to 3.3.2. For build JanusGraph I had to exclude from  cassandra-driver-core io.dropwizard.metrics:metrics-core cause was in conflict with  version 3.1.2  imported from  3.1.2 org.apache.tinkerpop:spark-gremlin:jar:3.3.0.

Unit test continue to works, in this moment I'm trying this with my app to check if something fails. As soon as I'll send my pr  for review
