### ISSUE TITLE
Remove all uses of and references to Apache Whirr, as it has been retired

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#866]
Per [Apache Whirr website](https://whirr.apache.org/):

> 2015/03/18 - Apache Whirr has been retired.

We should cleanup the documentation referring to Apache Whirr and all configs using Apache Whirr, as it only serves to confuse users, since no one has likely been using it for over 2 years now.

**Comment by chupman** [comment]
Hi @mbrukman I can take this one.

**Comment by mbrukman** [comment]
Thanks, @chupman!

**Comment by mbrukman** [comment]
This is clearly a duplicate of my own issue #83; I should've searched before filing this but forgot that I filed the other issue a year ago.
