### ISSUE TITLE
IncompatibleClassChangeError opening in-memory graph under Java 9

### ISSUE THREAD

**Issue by dmolesUC3** [JanusGraph/janusgraph#867]
## Steps to reproduce:

1. Create a project with dependency `org.janusgraph:janusgraph-core:0.2.0`
    - demo project: [janus-icce](https://github.com/dmolesUC3/janus-icce)
2. Under Java 9, run the following code:

```
    JanusGraph graph = JanusGraphFactory.build().set("storage.backend", "inmemory").open();
```

## Expected:

In-memory `JanusGraph` instance is a drop-in replacement for in-memory TinkerGraph (`TinkerGraph.open()`).

## Actual:

```
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception

	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)

...

Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation getConfiguration
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:82)

...

Caused by: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/janusgraph/diskstorage/StaticBuffer. Method lambda$static$0([BII)[B at index 105 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.janusgraph.diskstorage.StaticBuffer.<clinit>(StaticBuffer.java:79)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:105)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:100)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148)
```

(Full stack trace in a [gist here](https://gist.github.com/dmolesUC3/e6cdcbf0bcbcb1ba60678886e2c7f6d6).)

## Environment

OS: mac OS Sierra 10.12.6 (16G1114)

Java: 9.0.1+11

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by robertdale** [comment]
JanusGraph (and TinkerPop) is tested on only Java 8.  Try that version and see if your issues are resolved.

**Comment by dmolesUC3** [comment]
Rebuilding and rerunning the project with Java 8 does fix the problem.

I cloned the janusgraph repository and was able to get the same error running the Maven build under Java 9 but, annoyingly, wasn't able to get it to happen in my IDE. I also tried copying StaticBuffer and related classes and interfaces into a new project and building/testing that under Java 9, and that also ran with no problems. Whatever's triggering the problem must be somewhere deeper in the Maven build/packaging process.

Is there any timeline on Java 9 support? For our application we might be able to get by with keeping the server at arm's length using [JanusGraph Server](http://docs.janusgraph.org/latest/server.html) and [`DriverRemoteConnection`](http://tinkerpop.apache.org/javadocs/3.2.5/full/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.html) (I think—I'm still pretty new to TinkerPop), but it would be nice to have access to the full API.

**Comment by dmolesUC3** [comment]
The [JDK bug report](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8145148) that apparently led to this JVM “feature” claims “javac has never generated inconsistent constant pool entries, but some bytecode generating software may.” I'm not sure what bytecode shenanigans there are in the JanusGraph build, if any, but that might be a place to look.

Googling around, I also found some references to this error connected with the Maven Shade Plugin, which I do see go by in the JanusGraph build, although that might be a red herring. At any rate if I have time tomorrow I'll see if updating that plugin helps.

**Comment by dmolesUC3** [comment]
I updated to maven-shade-plugin 3.1.0 and that seems to fix the problem. See PR #868.

**Comment by dmolesUC3** [comment]
OK, pretty sure it’s not worth the hassle of trying to get the University of California to sign off on the CLA just for this, but the fix is beyond trivial, and somebody who has should do it.

(While you're at it, update the asciidoctor plugin to a version that supports the `skip` property, too.)

**Comment by mbrukman** [comment]
Note: unfortunately, we had to revert @dmolesUC3's PR due to a lack of CLA. Please do not re-commit it; it has to be reimplemented, from scratch, by someone who has not seen the commit, which means both @jerryjch and I are ineligible, since we reviewed the PR.

The changes you need to make are [described above](https://github.com/JanusGraph/janusgraph/issues/867#issuecomment-355618744) by @dmolesUC3: update `maven-shade-plugin` to 3.1.0; `maven-shared-plugin` is currently used in two modules:

* `janusgraph-codepipelines-ci`
* `janusgraph-core`

Then, please test it with both OpenJDK 8 and OpenJDK 9 to verify the fix. Our current Travis CI config will only test with OpenJDK 8, so please test with OpenJDK 9 locally.

@sjudeng, @amcp, @pluradj — are any of you up for making this simple change to close out this issue?

**Comment by pluradj** [comment]
@chupman you up for this one?

**Comment by chupman** [comment]
@pluradj I'm happy to work on this one. Feel free to assign me.

**Comment by mbrukman** [comment]
@chupman, thanks for working on this! We can't assign this to you because you're not a committer on this project; feel free to take ownership and work on the bug.
