### ISSUE TITLE
TinyLFU cache (vs LRU)

### ISSUE THREAD

**Issue by ben-manes** [JanusGraph/janusgraph#871]
There are a number of LRU caches, such as Guava's and the custom `ConcurrentLRUCache`. Guava's amortizes the locking required by LRU, whereas `ConcurrentLRUCache` uses a dedicated thread per instance to perform a full sweep after a threshold size is crossed. Both use LRU, which is a simple algorithm but underperforms in db / search / analytical workloads due to scans and one-hit wonders polluting the cache. In most cases frequency is a better indicator, due to caches following a Zipf-like distribution, but traditionally was not O(1) and difficult to implement well.

TinyLFU is a modern policy that has [near optimal hit rates](https://github.com/ben-manes/caffeine/wiki/Efficiency) while also being O(1) and has a low memory footprint. [Caffeine](https://github.com/ben-manes/caffeine) is an implementation that has [superior performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks) compared to Guava and scales linearly with the cpu count. It implements Guava's API, is feature compatibility, and is used by other databases like Cassandra, Druid, and Neo4J. It is also recommended by the Guava team when closing their issues as won't fix, probably because I coauthored Guava's cache with them.

I think the eviction policy and concurrency would be a good fit for Janus, as well be trivial to migrate to. We can easily run a trace against a production workload if you'd like to see the hit rate curve.

**Comment by robertdale** [comment]
Yes, if you can provide a test plan and the before/after metrics, that would be great.

**Comment by ben-manes** [comment]
Since I do not have a production deployment, you're best bet is to add tracing to the most critical cache (e.g. a node/vertex cache). This could simply be a logger that appends to its own file, capturing the key's hash code, and canary'd for an hour or so. We can then run it through a simulator to see the hit rate curve across many sizes and policies. That would have minimal impact and provide useful data to understand your access patterns.
