### ISSUE TITLE
Put  support ElementValueComparator back

### ISSUE THREAD

**Issue by davidclement90** [JanusGraph/janusgraph#872]
After PR : https://github.com/JanusGraph/janusgraph/pull/842, `g.V().hasLabel("Person").has("lang", "java").order().by(new ElementValueComparator("name", org.apache.tinkerpop.gremlin.process.traversal.Order.incr))` is no longer be supported  by mixed index

**Comment by twilmes** [comment]
@davidclement90 interesting, is there a difference between that and a `order().by("name", incr)`? Reason I ask is the TinkerPop code, though `ElementValueComparator` is still defined, it's no longer used anywhere from what I can tell.

**Comment by robertdale** [comment]
FWIW.. TinkerPop 3.0:  Added `ElementValueComparator` and `ElementFunctionComparator` in support of vendor introspection on `ComparatorHolder`-steps.

**Comment by twilmes** [comment]
Yeah, it looks like it was used internally and then removed at some point but the class was left. I can see the benefit of allowing a user to provide a custom comparator implementation that extends this, but `by` will already take a vanilla extension of `Comparator` and in that case, we can't push the custom comparator down to the indexing backend anyway so we couldn't fold the ordering in. I guess the other issue is I don't think that `ElementValueComparator` will be serialized in such a way where it'll work with a `GLV` at the moment.

**Comment by davidclement90** [comment]
@twilmes  The are no difference but for backwards compatibility we can not remove it on a bug fix version. 
As in 0.2.0 is the only way to use order by of mixed index, current code as mine should use it.
We may remove it after but not in a big fix.

**Comment by twilmes** [comment]
Got it,makes sense @davidclement90. I'll review the PR.

**Comment by pluradj** [comment]
@davidclement90 I believe this needs to be merged into `master` https://github.com/JanusGraph/janusgraph/pull/873#issuecomment-373381045

**Comment by twilmes** [comment]
I think I took care of this one with my last merge of `0.2.1` to `master` but please reopen if I'm wrong @davidclement90.
