### ISSUE TITLE
Add strategy that will optimize mixed index lookup followed by a count

### ISSUE THREAD

**Issue by twilmes** [JanusGraph/janusgraph#874]
I think we can make use of the work accomplished in #318 to optimize queries with the following structure `g.V().has("text", textFuzzy("foo")).count()`. The strategy should be able to replace the default counting behavior with one that uses the count retrieved from the index provider.

**Comment by iceriver2000** [comment]
this is very important optimize for big number return

**Comment by Eric-Bourry** [comment]
Hi team,

Can we expect a fix on this one? Is there a known workaround?

Thanks

**Comment by li-boxuan** [comment]
@Eric-Bourry Yes, I have a PR for this issue, but there is no guarantee it will appear in the next release (0.6.0).

A workaround would be https://docs.janusgraph.org/index-backend/direct-index-query/
