### ISSUE TITLE
Add property to element label mapping constraints to Janus schema system

### ISSUE THREAD

**Issue by twilmes** [JanusGraph/janusgraph#880]
This issue proposes we add property key to element label mapping constraints so that mutations containing properties that are not mapped to the element label they are being executed on, will fail.

# Proposed additions to the management API
Pre-requisites: Vertex/edge label exists and PropertyKeys have been created.
```
mgmt.addProperties(vertexLabel, propertyKey1, propertyKey2, ...)
mgmt.addProperties(edgeLabel, propertyKey1, propertyKey2, ...)

mgmt.addConnection(edgeLabel, outVLabel, inVLabel)
```

method sigs:

```
VertexLabel addProperties(VertexLabel vertexLabel, PropertyKey... propertyKeys)
EdgeLabel addProperties(EdgeLabel edgeLabel, PropertyKey... propertyKeys)
EdgeLabel addConnection(EdgeLabel edgeLabel, VertexLabel outVLabel, VertexLabe inVLabel)
```

# JanusGraphDefaultSchemaMaker Behavior
If `schema.default=default`:
* New or existing property is added to a vertex or edge label that wasn't previously mapped, the schema will be updated via an automatic `mgmt.addProperties` transparent to the user. If the property is new & unmapped, it'll be created automatically and the type inferred before the mapping, same as the current behavior.

* Edge added between two vertex labels that previously did not have a "connection" defined, `mgmt.addConection(edgeLabel, vertexLabel1, vertexLabel2)` is executed prior to commit of mutation.

If `schema.default=none`, exceptions will be thrown if a mutation containing an unmapped property or edge label connection is attempted.

**Comment by jerryjch** [comment]
The proposal looks good!
One question on the default behavior.   Will the 'schema.default == true' allow the new version of JanusGraph with this feature work with previous version of graphs without this feature?

**Comment by robertdale** [comment]
I'm confused by 'schema.default' being a boolean.  Currently, it accepts a
string that is mapped to a SchemaMaker.
none = DisableDefaultSchemaMaker
default = JanusGraphDefaultSchemaMaker
tp3 = Tp3DefaultSchemaMaker


Robert Dale

**Comment by robertdale** [comment]
I'm confused by `schema.default` being a `boolean`.  Currently, it accepts a
string that is mapped to a `SchemaMaker`.
- `none` = `DisableDefaultSchemaMaker`
- `default` = `JanusGraphDefaultSchemaMaker`
- `tp3` = `Tp3DefaultSchemaMaker`

Are you proposing to replace `SchemaMaker` with either on or off?

**Comment by twilmes** [comment]
That was some confusing wording on my part. I'm not proposing we change that and have updated the description.

**Comment by pluradj** [comment]
Which interface would these new methods go on?

**Comment by twilmes** [comment]
My thinking was `org.janusgraph.core.schema.SchemaManager` and you'd ultimately interact with them through the `ManagementSystem`.

**Comment by FlorianHockmann** [comment]
Is anyone already working on this? Otherwise, my colleagues and I would give it a shot.

**Comment by farodin91** [comment]
I started with the implementation of this feature, but I'm not done with the behavior part.
