### ISSUE TITLE
Better OR support for mixed indexes

### ISSUE THREAD

**Issue by davidclement90** [JanusGraph/janusgraph#888]
Currently these traversals do not match indexes
```
g.V().has('age', outside(20, 50))
g.V().has('age', lt(50).or(gte(60)))
g.V().or(__.has('name', textContains('hercules')), __.has('age', inside(20, 50)))
```
Is-it not the problem of mixed index backends which can handle OR but of the Strategy which do not root theses traversals to mixed indexes.

**Comment by pluradj** [comment]
@davidclement90 is this a duplicate of #163?

**Comment by davidclement90** [comment]
Yes I did not find it when I search.
I close this and I change the PR description.
