### ISSUE TITLE
Remove TTL support for Elasticsearch in documentation

### ISSUE THREAD

**Issue by davidclement90** [JanusGraph/janusgraph#892]
Since 0.2.0 (https://github.com/JanusGraph/janusgraph/pull/79) , ttl is no longer support by Elasticsearch but the doc says that janusgraph-es support it : http://docs.janusgraph.org/latest/elasticsearch.html

**Comment by jerryjch** [comment]
Ok. This will make JanusGraph's TTL story less complete. We have to think about other ways to support it.
