### ISSUE TITLE
min() and max() work only in the range of Integer values

### ISSUE THREAD

**Issue by rkozmer** [JanusGraph/janusgraph#895]
Following examples show the problem. The Min and Max steps are seeded with Integer.MIN_VALUE and Integer.MAX_VALUE. This is not high/low enough for long and double values.

`g.V(0).values().inject(9999999999).min()`

returns 2147483647 instead of 9999999999.

`g.V(0).values().inject(-9999999999).max()`

returns -2147483648 instead of -9999999999.

Extremes like -Double.MAX_VALUE and Double.MAX_VALUE should solve the problem, but I see some casting issues in the MinGlobalStep, MaxGlobalStep, MinLocalStep, MaxLocalStep.

Can anybody help with this?

**Comment by twilmes** [comment]
@rkozmer can you confirm this still happens with a plain old in-memory TinkerGraph? If it does, the best thing to do would be to close this issue and open a TinkerPop issue [here](https://issues.apache.org/jira/projects/TINKERPOP/).

You can graph a TinkerGraph traversal source from the Gremlin console like this: `g = TinkerGraph.open().traversal()`.

**Comment by rkozmer** [comment]
Same problem with traversal `g = TinkerGraph.open().traversal()`. I'll create new TinkerPop issue.
Thanks.

[https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-1873](https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-1873)
