### ISSUE TITLE
Add 'delayed index availability' notice to direct index query documentation

### ISSUE THREAD

**Issue by m-manseer** [JanusGraph/janusgraph#896]
I recently spent multiple hours trying to figure out why my [direct index queries](http://docs.janusgraph.org/latest/direct-index-query.html) would fail. At the end they worked all along, however the index queried did either not yet include the nodes added or was not available when the query was executed.

Adding a delay of 1s after defining the index and inserting test nodes before performing a query resolved the issue. To make this circumstance more apparent, I'd like to suggest adding another 'gotcha' to the documentation of direct index queries:

http://docs.janusgraph.org/latest/direct-index-query.html

**Comment by pluradj** [comment]
You're right, see also https://groups.google.com/d/msg/janusgraph-users/q00v-5I6We8/OisdZB_pAAAJ

@m-manseer would you like to [contribute](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) the documentation update? The source file for that document is located at [directindex.adoc](https://github.com/JanusGraph/janusgraph/blob/master/docs/directindex.adoc)

**Comment by m-manseer** [comment]
@pluradj I'm happy to contribute to the documentation, however I would not like to go through the CLA paperwork at this time. I edited the documentation and prepared a pastebin for you below. Feel free to use it as you wish.

https://pastebin.com/0mxciwM6

**Comment by chupman** [comment]
I'll work on the documentation update and try to get a PR in today.
