### ISSUE TITLE
about error with hbase 

### ISSUE THREAD

**Issue by ganhb** [JanusGraph/janusgraph#914]
Dear developer:
   hi~ 
   I was running the official website of  [the loading of the Graph of the Gods](http://docs.janusgraph.org/latest/getting-started.html) JanusGraph, there were some exceptions.
   step:
 - 1. janusgraph-hbase-solr.properties file content is:
     >> storage.backend=hbase
     >>storage.hostname=HSlave02,HSlave01,HMaster
     >>storage.port=2181
     >>storage.hbase.ext.hbase.zookeeper.property.clientPort = 2181
     >>cache.db-cache = true
     >>cache.db-cache-clean-wait = 20
     >>cache.db-cache-time = 180000
     >>cache.db-cache-size = 0.5
     >>index.search.backend=solr
     >>index.search.solr.mode=http
     >>index.search.solr.http-urls=http://localhost:7574/solr
`
 - 2. graph = JanusGraphFactory.open('conf/janusgraph-hbase-solr.properties')
 - 3. error:
     >> Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage 
     >> backend
     >> org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations

ps : hbase and zk can work properly

**Comment by Delostik** [comment]
Hi, I've met same problem.
Use   "hbase master start" to start hbase server manually, you may find more infomations.

And BTW, do you deploy your hbase server on mac? with latest update 10.13.3? There's some bugs I think

**Comment by msalihkarakasli** [comment]
Hi all, 
I have also faced same problem.
Is there any solution to handle this problem? Please let us know.

**Comment by CPorrot** [comment]
We encountered a _TemporaryBackendException_ error when installing Janus on our project. It was related to Kerberos. If your HBase is secured by a Kerberos authentication, ensure that it is configured properly and that the user executing Gremlin has a valid TGT, which allows him to use HBase.

Check also if the HBase table you try to use exists (`exists 'tableName'`), that your user has the correct permissions (RWCA) on this table, and that you point on this table in your properties file, with the `storage.hbase.table` setting.

**Comment by msalihkarakasli** [comment]
Actually I use below docker-compose for HBASE;
https://github.com/big-data-europe/docker-hbase

I think there is not any security or authentication default. Or **am I wrong?**

I am sure table is exist. This is also my sample properties file.

**Pom XML**
      ```
<dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-core</artifactId>
            <version>0.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-hbase</artifactId>
            <version>0.2.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-shaded-client</artifactId>
            <version>1.2.6</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-solr</artifactId>
            <version>0.2.0</version>
            <scope>runtime</scope>
        </dependency>
```
```
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=hbase
storage.hostname=10.122.216.235
storage.hbase.ext.hbase.zookeeper.property.clientPort=2181
storage.hbase.table=graph3
```

`JanusGraph graph = JanusGraphFactory.open("conf/janusgraph.properties");`

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
