### ISSUE TITLE
migrate es to HTTP client and not TransportClient (on deprecation path)

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#92]
At some point in the future, support for the [Transport Client (native Java client) will be removed](https://www.elastic.co/blog/elasticsearch-the-server).
To mitigate, we need to use the HTTP API.

**Comment by sjudeng** [comment]
The current Java REST client in Elasticsearch 5.x is very low level. I'd recommend waiting until they release a higher level Java REST client before working on migration to avoid unnecessary work.

**Comment by amcp** [comment]
I agree it is extremely low level and would require major refactoring. We should wait for a higher level REST client. I just wanted to get ES lack of commitment to the transport client on our radar (so that we know to plan for it).

**Comment by pluradj** [comment]
Related dev mailing list discussion https://groups.google.com/d/msg/janusgraph-dev/F-zfIsuiIoQ/q_R-kkhHDgAJ

**Comment by sjudeng** [comment]
With merge of #79 JanusGraph now supports the low-level ES REST HTTP client. But keeping this issue open to track work on migrating to higher level HTTP client for ES (e.g. Jest or maybe eventually ES 6.x REST).

**Comment by sjudeng** [comment]
With merge of #289 JanusGraph now only supports the ES REST HTTP client and the Transport client is no longer support.
