### ISSUE TITLE
Issues in query with Text.textContains

### ISSUE THREAD

**Issue by huxiaoqing0704** [JanusGraph/janusgraph#922]
When I query all the vertices with gremlin 
        **_g.V().has("rdfs:label",Text.textContains("杨"))_**  
There are many vertices with label person in the result.  

But, When I query with label constraints, there are no vertices in the result.
**_g.V().hasLabel("person").has("rdfs:label",Text.textContains("杨"))_**

![](https://images2017.cnblogs.com/blog/775861/201802/775861-20180209174323920-1285229149.png)

When I query like the following script, there  are also no vertices in the result.  But, In fact, there are many vertices meet the constraints.
_**g.V(45133848).both("case.xyr").has("rdfs:label",Text.textContains("梁")).valueMap(true)**_

Is it a bug?  Anyone can help me?

**Comment by davidclement90** [comment]
Can you profile (with _.profile_) your queries ? 
Which janusgraph version do you use ?
Which backend do you use ?
Do you put index ?

**Comment by huxiaoqing0704** [comment]
Thanks very much for your reply  @davidclement90 .

**The janusgraph version is 0.2.0 released  on 12 Oct 2017.
The storage backend is HBase with version 1.1.2.
The index backend is Elasticsearch with version 5.5.1 .**

I put mixed index with property key rdfs:label.
![2](https://user-images.githubusercontent.com/15335756/36068483-d7ced146-0f11-11e8-9368-2811eeffccf6.png)

My first query
 **_g.V().hasLabel("person").has("rdfs:label",Text.textContains("杨"))_**
 profile is as followings.
![](https://images2017.cnblogs.com/blog/775861/201802/775861-20180211091733310-930280771.png)

My second query
_**g.V(45133848).both("case.xyr").has("rdfs:label",Text.textContains("梁")).valueMap(true)**_
profile is as followings.
![1](https://user-images.githubusercontent.com/15335756/36068421-2bfd8bce-0f10-11e8-9f32-c1456678ea25.png)

**Comment by davidclement90** [comment]
Ok,
Can you profile this one too : _g.V().has("rdfs:label",Text.textContains("杨"))_ ? 
Do you use a custome ES mapping or the normal one ?
Can you check directely on ES (or with Kibana) if the doc are indexed ?

**Comment by huxiaoqing0704** [comment]
Thanks very much.

 _**g.V().has("rdfs:label",Text.textContains("杨"))**_ profile as followings.
![1](https://user-images.githubusercontent.com/15335756/36080974-8821c546-0fd3-11e8-92a3-f2437714bda3.png)

Docs are indexed on ES.

![2](https://user-images.githubusercontent.com/15335756/36081016-2f18e0a0-0fd4-11e8-8921-638087b1d5ea.png)
![3](https://user-images.githubusercontent.com/15335756/36081017-38cf98f0-0fd4-11e8-861a-54d6641a298b.png)

My index backend configuration in janusgraph properties  file.

![4](https://user-images.githubusercontent.com/15335756/36081056-c283855c-0fd4-11e8-98ac-fb3ae5487558.png)

**Comment by davidclement90** [comment]
Ok so you index is not an index

Can you try to turning off smart-limit (query.smart-limit=false) ?

Can you do an explain on both queries ?

**Comment by huxiaoqing0704** [comment]
Thanks very much.
I have turning off smart-limit. 
But ,execute the query **_g.V().hasLabel("person").has("rdfs:label",Text.textContains("杨"))_** there is also no vertices.

![3](https://user-images.githubusercontent.com/15335756/36086211-d92b3738-1005-11e8-8e90-da22bb526b0b.png)
![1](https://user-images.githubusercontent.com/15335756/36086217-e41df14e-1005-11e8-8a1a-6494f36bc564.png)
![2](https://user-images.githubusercontent.com/15335756/36086222-ea61041a-1005-11e8-9a96-721f0870a32a.png)

**Comment by davidclement90** [comment]
It's really strange.
And this one ?
g.V().has("rdfs:label",Text.textContains("杨")).local(__.hasLabel("person")).profile()

**Comment by huxiaoqing0704** [comment]
Thanks very much.

**_g.V().has("rdfs:label",Text.textContains("杨")).local(__.hasLabel("person")).profile()_** as followings.
![1](https://user-images.githubusercontent.com/15335756/36153546-92073488-1109-11e8-9eb7-2492d5c9a999.png)

I think this is very strange too. I do not  know if it is a bug or not.

I've tried a lot of ways to solve this problem， but I didn't find the reason and the solution.

**Comment by davidclement90** [comment]
Do you declare your label on the management system and do you use strict schema ?

**Comment by huxiaoqing0704** [comment]
Thanks very much.
Before import data into janusgraph, I have created property key _**rdfs:label**_ , build composite index and mixed index for **_rdfs:label_** property key through JanusGraphManagement. 

**_mgmt.makePropertyKey("rdfs:label").dataType(String.class).make();
mgmt.buildIndex("labelIndex",Vertex.class).addKey(mgmt.getPropertyKey("rdfs:label")).buildCompositeIndex();
mgmt.buildIndex("vLabel",Vertex.class).addKey(mgmt.getPropertyKey("rdfs:label"),Mapping.TEXTSTRING.asParameter()).buildMixedIndex(MIXED_INDEX_CONFIG_NAME);_**

**Comment by davidclement90** [comment]
Ok so your schema is not strict ? And you do not declared the label vertex _Person_ ?

**Comment by huxiaoqing0704** [comment]
Thanks very much.

In addition to creating property key _**rdfs:label**_ , I have created VertexLabels and EdgeLabels through JanusGraphManagement. In the last reply，I forgot to explain.

_**mgmt.makePropertyKey("rdfs:label").dataType(String.class).make();
mgmt.makeVertexLabel("person").make();
mgmt.makeEdgeLabel("case.xyr").make();
mgmt.buildIndex("labelIndex",Vertex.class).addKey(mgmt.getPropertyKey("rdfs:label")).buildCompositeIndex();
mgmt.buildIndex("vLabel",Vertex.class).addKey(mgmt.getPropertyKey("rdfs:label"),Mapping.TEXTSTRING.asParameter()).buildMixedIndex(MIXED_INDEX_CONFIG_NAME);**_

The above is all my schema.

**Comment by pluradj** [comment]
The [docs](http://docs.janusgraph.org/latest/index-parameters.html#_full_text_search) call out a particular behavior:

> JanusGraph’s default tokenization splits the string on non-alphanumeric characters and removes any tokens with less than 2 characters.

Are you trying to match on words that are _exactly_ the single character? If this is your requirement, the [`Text.tokenize()`](https://github.com/JanusGraph/janusgraph/blob/0.2/janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java#L297) behavior described in the doc would need to be changed.

If you are looking for words that _contain_ the single character, you should use one of the other predicates instead (`textContainsPrefix`, `textContainsRegex`, `textContainsFuzzy`) and you can find usage examples in the link above.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by ChenZhaobin** [comment]
@huxiaoqing0704  Hey buddy,how did you solve this ,I met with the same issue
