### ISSUE TITLE
Janusgraph indexing on edge attributes

### ISSUE THREAD

**Issue by ketan582** [JanusGraph/janusgraph#928]
````
gr1 = JanusGraphFactory.open("/Downloads/janusgraph-cassandra.properties")

var mgmt = gr1.openManagement()

var prop1 = mgmt.makePropertyKey("prop1").dataType(classOf[String]).make()

mgmt.buildIndex("byprop1", classOf[Edge]).addKey(prop1).buildCompositeIndex()

mgmt.commit()
````

The above code runs without any errors and in gremlin when I do a
`mgmt.getGraphIndex("byprop1")`, I get this index and not null, but still while running queries like,
`tr.E().has("prop1", value)`, I get a `Query requires iterating over all vertices` warning. Is the indexing not working?

**Comment by davidclement90** [comment]
Do you respect phases of http://docs.janusgraph.org/latest/index-admin.html ?
INSTALLED to REGISTERED to REINDEX to ENABLED

**Comment by ketan582** [comment]
I am creating multiple indexes at once before committing and close the management object. Some indexes are working(strangely, only those whose corresponding properties are of String type) and the others are not.

**Comment by pluradj** [comment]
Example data and code reproducing the problem would be useful. Also, questions like this are better suited for the [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) group than a GitHub issue. We use the issue tracker for bug tracking, not for usage q&a.

**Comment by pluradj** [comment]
Here's the thread on [janusgraph-users](https://groups.google.com/d/msg/janusgraph-users/gIR4yPgSVAE/SRwfh4lgAgAJ).
