### ISSUE TITLE
exisiting hbase table

### ISSUE THREAD

**Issue by msure4** [JanusGraph/janusgraph#935]
Hello,

Is it possible to create a janusgraph on existing hbase table? I have a table already on Hbase with CF. I want create a janus Graph on that table/s. Is there any exisiting sample example to refer.

Thank you in Advacne!!

**Comment by jerryjch** [comment]
Yes, you can use an existing table by specifying the table name in the graph properties.
The question is what is in the table already.  If it has unrelated CFs and data, it is ok, but generally it is not a recommended approach.  If the table is a graph table, then you are basically adding to the graph.

PS. Please ask questions on the janusgraph mailing list:
janusgraph-users@googlegroups.com  or
janusgraph-dev@googlegroups.com

**Comment by msure4** [comment]
@jerryjch thank you for quick response. Here are my table descrption
"COLUMN FAMILIES DESCRIPTION                                                                                                                                                                                                                  
{NAME => 'cf1', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '
65536', REPLICATION_SCOPE => '0'}   "

And data:
ROW                                                          COLUMN+CELL                                                                                                                                                                     
 row1                                                        column=cf1:1, timestamp=1518483833280, value=value1                                                                                                                             
 row2                                                        column=cf1:2, timestamp=1518483845104, value=value2                                                                                                                             
2 row(s) in 0.0800 seconds

So now how to create a graph on my table? And is there any sample code or example is available on google?

Thank you in Adaavace!!

**Comment by msure4** [comment]
@jerryjch thank you for quick response. Here are my table descrption
"COLUMN FAMILIES DESCRIPTION                                                                                                                                                                                                                  
{NAME => 'cf1', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '
65536', REPLICATION_SCOPE => '0'}   "

And data:
ROW                                                          COLUMN+CELL                                                                                                                                                                     
 row1                                                        column=cf1:1, timestamp=1518483833280, value=value1                                                                                                                             
 row2                                                        column=cf1:2, timestamp=1518483845104, value=value2                                                                                                                             
2 row(s) in 0.0800 seconds

So now how to create a graph on my table? And is there any sample code or example is available on google?

Thank you in Adaavace!!

**Comment by msure4** [comment]
@jerryjch thank you for quick response. Here are my table descrption
"COLUMN FAMILIES DESCRIPTION                                                                                                                                                                                                                  
{NAME => 'cf1', BLOOMFILTER => 'ROW', VERSIONS => '1', IN_MEMORY => 'false', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '
65536', REPLICATION_SCOPE => '0'}   "

And data:
ROW                                                          COLUMN+CELL                                                                                                                                                                     
 row1                                                        column=cf1:1, timestamp=1518483833280, value=value1                                                                                                                             
 row2                                                        column=cf1:2, timestamp=1518483845104, value=value2                                                                                                                             
2 row(s) in 0.0800 seconds

So now how to create a graph on my table? And is there any sample code or example is available on google?

Thank you in Adaavace!!

**Comment by jerryjch** [comment]
Please take a look at the Getting Started section in the doc:
http://docs.janusgraph.org/latest/getting-started.html
You will specify your existing table as the property value for 'storage.hbase.table'.  JanusGraph will create additional cfs to store the graph.  Your existing cf1 will not be touched.

**Comment by pluradj** [comment]
@msure4 Please refer to JanusGraph's [HBase docs](http://docs.janusgraph.org/latest/hbase.html). 

The issue tracker is for bug tracking. Please direct usage questions like this to `janusgraph-users`. Read [this]((https://github.com/JanusGraph/janusgraph#community)) to learn more about it.
