### ISSUE TITLE
Authentication for Webscoket Connection

### ISSUE THREAD

**Issue by martingg88** [JanusGraph/janusgraph#957]
What/How can I configure the username and password for websocket connection and so any connection sending to Janusgraph server requires username and password?

**Comment by martingg88** [comment]
any update about this question?

**Comment by robertdale** [comment]
This is for tracking issues. General questions should go to the user list - https://groups.google.com/forum/#!forum/janusgraph-users

You may want to read up on JanusGraph/Gremlin Server -
http://docs.janusgraph.org/latest/server.html#_janusgraph_server_as_a_websocket_endpoint
http://tinkerpop.apache.org/docs/3.2.7/reference/#_security_and_execution

**Comment by sjudeng** [comment]
Note some related updates on this are in https://github.com/JanusGraph/janusgraph/pull/624, which is not in the documentation yet. It'll be included in the upcoming 0.3.x release or you can build locally.
