### ISSUE TITLE
Unable to create csv file in CSV File Reporter while configuring Janusgaph Metrics

### ISSUE THREAD

**Issue by shubham190892** [JanusGraph/janusgraph#962]
I was trying to configure the csv file reporter in the janusgraph metrics But there was no file getting created and No Exceptions were visible in the logs. I debugged the stats code I found the below issue.

There was discrepancy between property name in documentation and codebase. Document page suggest the **metrics.csv.dir** property while codebase searching for **metrics.csv.directory**.

In the Documentation ([metrics-csv-doc](http://docs.janusgraph.org/latest/monitoring.html#metrics-csv)).
metrics.enabled = true
metrics.csv.interval = 60000
_**metrics.csv.dir = foo/bar**_

In codebase the configuration call searching for the property **_metrics.csv.directory_**.  The second parameter in the below constructor.
```
public static final ConfigOption<String> METRICS_CSV_DIR = new ConfigOption<String>(METRICS_CSV_NS, "directory",
            "Metrics CSV output directory",
            ConfigOption.Type.MASKABLE, String.class);
```

Please update the doc to avoid problems for the new upcoming users.

**Comment by chupman** [comment]
Issue has been resolved via PR #964
