### ISSUE TITLE
[COMMITTERS] Register with Sonatype

### ISSUE THREAD

**Issue by ptgoetz** [JanusGraph/janusgraph#97]
In order for committers to push artifacts to maven central as part of the release process, each must have a Sonatype Nexus account with permissions for the "org.janusgraph" group ID.

I have a Nexus account and can set this up,  but it would be best if I can setup the "org.janusgraph" users in bulk.

Anyone who is interested in acting as a release manager for JanusGraph should register for a JIRA account at the following URL:

https://issues.sonatype.org/secure/Dashboard.jspa

Once you have registered, respond to this issue with your JIRA ID. Once we have a list of IDs, I will proceed with setting up the Nexus account.

**Comment by twilmes** [comment]
Thanks for coordinating @ptgoetz.  My id is `twilmes`.

**Comment by pluradj** [comment]
I have `pluradj`

**Comment by amcp** [comment]
I have amcp

**Comment by jerryjch** [comment]
My id is 'jerryjch'. Thanks!

**Comment by ptgoetz** [comment]
Thanks for the updates. I'll wait 24 hours to give others a chance to sign up, then submit the request to Sonatype.

**Comment by mbrukman** [comment]
My id is `mbrukman`.

**Comment by ptgoetz** [comment]
JIRA ticket has been submitted: https://issues.sonatype.org/browse/OSSRH-28274

I will close this issue when the ticket is resolved. Turnaround time is typically 24 hrs.

**Comment by amcp** [comment]
@ptgoetz Ticket at sonatype is resolved but not closed. Keep this issue open until we release or close now?

**Comment by sjudeng** [comment]
Referenced ticket is closed.
